Aptoide/aptoide-client-v8

- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/app/AppViewFragment.java
https://aptoide.atlassian.net/browse/AN-1695
> AN-1695 - NPE for no rating

- v8engine/src/main/java/cm/aptoide/pt/v8engine/AutoUpdate.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/InstallManager.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/V8Engine.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/notification/PullingContentService.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/presenter/DownloadsPresenter.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AppUpdateDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/app/AppViewFragment.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/app/widget/AppViewInstallWidget.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/downloads/active/ActiveDownloadDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/downloads/active/ActiveDownloadsHeaderDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/downloads/completed/CompletedDownloadDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/downloads/scheduled/ScheduledDownloadsFragment.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/updates/UpdateDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/updates/UpdatesHeaderDisplayable.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/updates/UpdatesHeaderWidget.java
This pull-request removes all context parameters from Install Manager method calls. The context is injected in the install manager instantiation in v8Engine (with getApplicationContext() )
Install an app.
Tickets related to this pull-request: [AN-1715](https://aptoide.atlassian.net/browse/AN-1715).
N/A
Questions:
> [AN-1715] Install manager context dependency injection.

- v8engine/src/main/java/cm/aptoide/pt/v8engine/InstallService.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/V8Engine.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/analytics/events/FabricEvent.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/install/InstallFabricEvents.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/install/InstallerAnalytics.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/install/InstallerFactory.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/install/installer/DefaultInstaller.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/install/installer/RootCommandOnSubscribe.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/updates/rollback/RollbackFragment.java
Analytic events are now sent when a root install is made informing if there was an error or the installation was successful
> [Analytics/AN-1690] - Root install analytics

- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/CardType.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/presenter/TimelinePresenter.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/TimelineAnalytics.java
Small Timeline refactoring to remove static method calls in CardType enum.
> [AN-1818] Refactoring CardType method static calls.

- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/AggregatedMediaViewHolder.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/AggregatedRecommendationViewHolder.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/AggregatedStoreViewHolder.java
https://aptoide.atlassian.net/browse/AN-1830
> AN-1830- aggreagted cards - validation

- aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/Account.java
- aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/AptoideAccount.java
- aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/LocalAccount.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/account/FacebookAccount.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/account/GoogleAccount.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/SharePreviewFactory.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/presenter/TimelinePresenter.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/CardWidget.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/dialog/SharePreviewDialog.java
https://aptoide.atlassian.net/browse/AN-1846
> AN-1846 - add new methods to account: has store and isPublicUser

- v8engine/src/main/AndroidManifest.xml
- v8engine/src/main/java/cm/aptoide/pt/v8engine/DeepLinkIntentReceiver.java
https://aptoide.atlassian.net/browse/AN-1729
Try: the two use cases and check:
https://aptoide.atlassian.net/wiki/spaces/AN/pages/1749903/Deeplinks
> AN-1729 - listen: https for market.android.com; and listen search

- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/RatedRecommendation.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/SocialMedia.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/SocialStore.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/TimelineResponseCardMapper.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/SocialMediaViewHolder.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/SocialRecommendationViewHolder.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/viewholder/SocialStoreViewHolder.java
This pull-request adds shared by to the social cards (social recommendation/social install/social article/social video/social latest apps (store))
Open Aptoide v8 > Timeline > share a share > check own user timeline > should be shared by you.
Tickets related to this pull-request: [AN-1852](https://aptoide.atlassian.net/browse/AN-1852)
N/A
Questions:
> [AN-1852] added shared by to social posts.

- v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/SocialFragment.java
- v8engine/src/main/java/cm/aptoide/pt/v8engine/view/settings/SettingsFragment.java
> [AN-1900] Fabric Settings/onBackPressed

- app/src/main/java/cm/aptoide/pt/analytics/Analytics.java
Send an event that was to flurry to facebook as well:
https://aptoide.atlassian.net/browse/AN-1950
Event name for facebook was changed
> AN-1950 add Home_Page_Editors_Choice event to facebook

- app/src/main/java/cm/aptoide/pt/timeline/post/UrlValidator.java
"Check if edittext is not focus and search for url, even if there is no space"
> [AN-1908] Timeline: post minor changes

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/InstallService.java
- app/src/main/java/cm/aptoide/pt/analytics/events/FabricEvent.java
- app/src/main/java/cm/aptoide/pt/install/InstallFabricEvents.java
- app/src/main/java/cm/aptoide/pt/install/InstallerAnalytics.java
- app/src/main/java/cm/aptoide/pt/install/installer/RootCommandOnSubscribe.java
- app/src/main/java/cm/aptoide/pt/view/updates/rollback/RollbackFragment.java
root install has now an event that is logged when install is started
> feature/AN-1971-FC-log-root-events-facebook 

- app/src/main/java/cm/aptoide/pt/social/data/TimelineResponseCardMapper.java
- app/src/main/java/cm/aptoide/pt/social/view/PostAdapter.java
This PR fixes the adapter post sorting. 
It also fixes the aggregated social install/app card type, which was always AGGREGATED_SOCIAL_APP
> Bugfix/AN-1972 Timeline AD first in list

- app/src/main/java/cm/aptoide/pt/account/view/store/ManageStorePresenter.java
- app/src/main/java/cm/aptoide/pt/account/view/store/StoreManager.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v3/CheckUserCredentialsRequest.java
What does this pull request do?
> Fixes a bug associated with the creation of a store.
> Create a user and then a store. It should create the store as expected.
> Bugfix for ticket AN-1992 where a user cannot create a store

- app/src/main/java/cm/aptoide/pt/view/app/AppViewNavigator.java
- app/src/main/java/cm/aptoide/pt/view/app/widget/AppViewInstallWidget.java
What does this pull request do?
> Solves the issue related with the ticket by attaching the click handler to the component lifecycle using RxJava
> Bugfix for AN-1990: Illegal state navigation in install widget

- app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialMediaViewHolder.java
This PR fixes the fact that number of comments text in the social media (articles/videos) cards were not clickable.
> [AN-2009] fixing click on comments text in articles and videos (social)

- app/src/main/java/cm/aptoide/pt/analytics/AptoideNavigationTracker.java
- app/src/main/java/cm/aptoide/pt/view/custom/AptoideViewPager.java
- app/src/main/java/cm/aptoide/pt/view/store/GetStoreWidgetsFragment.java
https://aptoide.atlassian.net/browse/AN-2014?src=confmacro
> AN-2014 - bug fix: screens history

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
https://aptoide.atlassian.net/browse/AN-2033
> an-2033 search when there's no app with given keyword

- app/src/main/java/cm/aptoide/pt/view/app/screenshots/ScreenshotsViewerFragment.java
- app/src/main/java/cm/aptoide/pt/view/store/StoreFragment.java
- app/src/main/res/layout-land/fragment_wizard.xml
- app/src/main/res/layout/fragment_screenshots_viewer.xml
- app/src/vanilla/java/cm/aptoide/pt/view/wizard/WizardFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/wizard/WizardPresenter.java
This PR fixes the issue https://aptoide.atlassian.net/browse/AN-2035
> AN-2035 fixed crash when wizard was changing in landscape and portrait

- app/src/main/res/layout/fragment_manage_user.xml
- app/src/main/res/layout/fragment_profile_step_one.xml
- app/src/main/res/layout/fragment_profile_step_two.xml
Fix for issue https://aptoide.atlassian.net/browse/AN-2026
> AN-2026 fixed buttons layout not being aligned in layout bottom

- app/src/main/java/cm/aptoide/pt/search/view/SearchBuilder.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchView.java
"If you type over the search keywords, you can edit you keyword" as requested in https://aptoide.atlassian.net/browse/AN-1969
> AN-1969 click on search result title will allow to continue searching

- app/src/main/java/cm/aptoide/pt/view/store/StoreFragment.java
- app/src/main/java/cm/aptoide/pt/view/store/my/MyStoresSubscribedFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/app/AppViewFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/app/AppViewModel.java
- app/src/vanilla/java/cm/aptoide/pt/view/store/home/HomeFragment.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/store/GetHomeMeta.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/WSWidgetsUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/store/GetStoreWidgetsRequest.java
Fix for issue https://aptoide.atlassian.net/browse/AN-2046
> AN-2046 pull to refresh does not use local cache

- app/src/vanilla/java/cm/aptoide/pt/view/app/AppViewFragment.java
PR to fix https://aptoide.atlassian.net/browse/AN-2061
> AN-2061 App view is broken

- app/src/main/java/cm/aptoide/pt/search/view/SearchBuilder.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/view/store/StoreFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/app/AppViewFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/store/home/HomeFragment.java
What does this pull request do?
> This pull request should fix the two tickets related to the creation of the options menu in different views. 
> Bugfix for AN-2064 and AN-2065 options menu bug

- app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpFragment.java
- app/src/main/java/cm/aptoide/pt/billing/view/login/PaymentLoginFragment.java
- app/src/main/java/cm/aptoide/pt/crashreports/IssuesAnalytics.java
- app/src/main/java/cm/aptoide/pt/notification/view/InboxFragment.java
- app/src/main/java/cm/aptoide/pt/search/SearchAnalytics.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchBuilder.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/spotandshare/view/SpotSharePreviewFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/post/PostFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/view/SocialFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowFragment.java
- app/src/main/java/cm/aptoide/pt/view/app/OtherVersionsFragment.java
- app/src/main/java/cm/aptoide/pt/view/comments/CommentListFragment.java
- app/src/main/java/cm/aptoide/pt/view/downloads/scheduled/ScheduledDownloadsFragment.java
- app/src/main/java/cm/aptoide/pt/view/feedback/SendFeedbackFragment.java
- app/src/main/java/cm/aptoide/pt/view/fragment/DescriptionFragment.java
- app/src/main/java/cm/aptoide/pt/view/reviews/LatestReviewsFragment.java
- app/src/main/java/cm/aptoide/pt/view/reviews/RateAndReviewsFragment.java
- app/src/main/java/cm/aptoide/pt/view/store/FragmentTopStores.java
- app/src/main/java/cm/aptoide/pt/view/store/StoreFragment.java
- app/src/main/java/cm/aptoide/pt/view/store/StoreTabGridRecyclerFragment.java
- app/src/main/java/cm/aptoide/pt/view/updates/excluded/ExcludedUpdatesFragment.java
- app/src/main/java/cm/aptoide/pt/view/updates/rollback/RollbackFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/app/AppViewFragment.java
- app/src/vanilla/java/cm/aptoide/pt/view/store/home/HomeFragment.java
Attempt to solve issue https://www.fabric.io/aptoide2/android/apps/cm.aptoide.pt/issues/59ea1bb261b02d480de8078a?time=last-seven-days
> Bugfix for attach search method throwing null pointer

- app/src/main/java/cm/aptoide/pt/notification/AptoideNotification.java
- app/src/main/java/cm/aptoide/pt/notification/NotificationCenter.java
- app/src/main/java/cm/aptoide/pt/notification/NotificationIdsMapper.java
- app/src/main/java/cm/aptoide/pt/notification/NotificationPolicyFactory.java
- app/src/main/java/cm/aptoide/pt/social/AccountNotificationManagerUserProvider.java
Fixed bug related to the new notifications consumption.
Also added the correct policies to the new notification types.
> [AN-2099] Added new notifications logic (new share + new activity)

- app/src/main/java/cm/aptoide/pt/account/view/store/ManageStoreFragment.java
- app/src/main/java/cm/aptoide/pt/account/view/store/ManageStorePresenter.java
- app/src/main/java/cm/aptoide/pt/account/view/store/ManageStoreViewModel.java
- app/src/main/java/cm/aptoide/pt/account/view/store/StoreManager.java
- app/src/main/res/layout/fragment_manage_store.xml
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/SetStoreImageRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/SimpleSetStoreRequest.java
In order to test this make sure that your store has at least one channel added, afterwards delete your channels text and press save. (Deleted channels might take some time to get reflected on the UI)
> [AN-2103] - Now allowing for social channels to be deleted.

- app/src/main/java/cm/aptoide/pt/notification/NotificationAnalytics.java
Check:
https://aptoide.atlassian.net/browse/AN-2145
> AN-2145 - facebook event type is wrong

- aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/SignUpAdapterRegistry.java
Checking if the account adapter (faceb…ook, aptoide, google) is enabled
> Logging out user with proper validation 

- app/src/main/java/cm/aptoide/pt/account/view/store/ManageStoreFragment.java
- app/src/main/res/layout/fragment_manage_store.xml
Non existent User/Channel doesn't trigger an explicit/visual error
> fix for AN-2163

- app/build.gradle
- app/src/androidTest/java/cm/aptoide/pt/MockApplicationModule.java
- app/src/androidTest/java/cm/aptoide/pt/SignInSignUpUITests.java
1. Id from UI Tests for the search didn't match new search id
2. Changed mocked aptoideAccountManager dagger signature to match new application implementation
3. Added test dependencies needed for point 3
> [AN-2225] Tests: search id changed

- app/src/main/res/values/strings.xml
- app/src/vanilla/java/cm/aptoide/pt/store/view/home/HomeFragment.java
- app/src/vanilla/res/menu/menu_drawer.xml
This pull request aims to remove the links to Facebook and Twitter from the drawer.
**Where to start**:
HomeFragment;
**Testing**:
Open aptoide -> Check drawer
**Tickets**:
ASV-106
> [ASV-106] Remove Social Links

- app/src/main/java/cm/aptoide/pt/download/view/DownloadsFragment.java
- app/src/main/java/cm/aptoide/pt/presenter/DownloadsPresenter.java
- app/src/test/java/cm/aptoide/pt/downloads/DownloadsPresenterTest.java
Tests for the DownloadsPresenter.
This presenter is associated with the view where it the list of downloads is shown.
The developed tests verify all of possible download states and how they are shown on the view (as active, completed or standby).
No
DownloadsPresenterTest
DownloadsPresenter
QA Tickets related to this use-case: [ASV-XXXX](<Jira url>)
Tickets related to this pull-request: [ASV-152](https://aptoide.atlassian.net/browse/ASV-152)
**Questions:**
No.
> [ASV-152] Testing DownloadPresenter on both error and success cases

- app/src/main/java/cm/aptoide/pt/view/app/AppCenterRepository.java
- app/src/main/java/cm/aptoide/pt/view/app/AppService.java
- app/src/test/java/cm/aptoide/pt/apps/AppCenterRepositoryTest.java
Create AppCentereRepositoryTestss
No
AppCenterRepositoryTest.java
Check if all tests pass except the TODO test, due not being able to find a case where AppsLeft == 0
[ASV-158] https://aptoide.atlassian.net/browse/ASV-158
> [ASV-158] task/app center repository tests

- app/src/main/java/cm/aptoide/pt/home/BottomNavigationFragmentView.java
Adds "HomeView" when application is opened
> [ASV-177] HomeView now shows at the start

- app/src/main/java/cm/aptoide/pt/home/AptoideBottomNavigator.java
- app/src/main/java/cm/aptoide/pt/home/BottomNavigationItem.java
- app/src/main/java/cm/aptoide/pt/home/BottomNavigationMapper.java
- app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
- app/src/main/res/drawable/nav_item_color_state.xml
- app/src/main/res/layout/action_bar.xml
- app/src/main/res/values/colors_deprecated.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/cm/aptoide/pt/navigation/BottomNavigationPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/presenter/MainPresenter.java
Corrected some issues from previous R
No
MainPresenter.java
BottomNavigationPresenterTest.java
- [] Database changed?
> [ASV-171] feature/bottom_navigation

- app/src/main/java/cm/aptoide/pt/home/BottomHomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/HomeView.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresFragment.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresNavigator.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresPresenter.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresView.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/res/drawable/ic_account_circle.xml
- app/src/main/res/layout/action_bar.xml
- app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
- app/src/test/java/cm/aptoide/pt/navigation/MyStoresPresenterTest.java
Note: userAvatar on BottomHomeFragment needs to be set to null onDestroy
This PR shows a default user icon if user is not logged in, displays the image of the user if user is logged in and has image and shows a default image if user is logged in and has no image.
When clicked the user should navigate to the new AccountFragment (currently goes to the SettingsFragment)
Currently it's only implemented ono Home and MyStores Fragment, it should also be implemented later on AppsFragment
No
HomePresenter.java
MyStoresPresenter.java
160, 172, 188 (later i'll put the links)
> [ASV-188] Icon on Action Bar is now displayed

- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/vanilla/res/menu/fragment_appview.xml
This PR aims to remove the search functionality from the appview
No
Check the appview, search should always be gone;
Tickets related to this pull-request: [ASV-250](<https://aptoide.atlassian.net/browse/ASV-250>
> [ASV-250] Removed search from the appview;

- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
- app/src/vanilla/java/cm/aptoide/pt/view/ActivityModule.java
- app/src/vanillaDev/res/xml-v25/shortcuts.xml
- app/src/vanillaFairy/res/xml-v25/shortcuts.xml
- app/src/vanillaInternal/res/xml-v25/shortcuts.xml
- app/src/vanillaLeak/res/xml-v25/shortcuts.xml
- app/src/vanillaProd/res/xml-v25/shortcuts.xml
This PR aims to remove the shortcut to timeline;
No
(removed the timeline shortcut from an xml for each build flavor)
Verify that the shortcut does not exist anymore
Tickets related to this pull-request: [ASV-248](<https://aptoide.atlassian.net/browse/ASV-248>)
> [ASV-248] Successfully removed shortcut to timeline;

- app/src/main/java/cm/aptoide/pt/home/AptoideBottomNavigator.java
- app/src/main/java/cm/aptoide/pt/home/BottomHomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/BottomNavigationActivity.java
- app/src/main/java/cm/aptoide/pt/home/BottomNavigationMapper.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresFragment.java
Note: Merge from dev messed up and some of the things that are said to be removed but they are just moved to another place.
Every fragment that is present in the BottomNavigation now requests that the icon of that fragment gets focus every time the user is on that fragment
No
BottomNavigationActivity.java
Navigate quickly between a view to another (both from bottomNavigation)
Rotate screen
Press back
https://aptoide.atlassian.net/browse/ASV-241
> [ASV-241] BN correct button focus

- app/src/main/AndroidManifest.xml
Fixes the incorrect behaviour where the keyboard would cover the EditTexts
The solution isn't the best, as it push the action bar up. It should be better investigated in the future.
No
AndroidManifest.xml
Check on views that use the keyboard
Seen views (LoginSignUp, ManageUser/EditUser, Search, In a store search)
Not seen views(EditStore, others that may exist...)
https://aptoide.atlassian.net/browse/ASV-242
> [ASV-242] keyboard adjustment

- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragmentView.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
- app/src/main/java/cm/aptoide/pt/home/apps/UpdatesManager.java
- app/src/main/res/layout/fragment_apps.xml
This PR is the implementation of the pull to refresh on the Apps view. If the user swipes the Apps view, it will refresh and sync the available updates.
No
- AppsFragment contains the view where the progress bar will apear.
- AppsPresenter which is where the click is being listened.
Open Apps section from the Bottom Navigation and perform a pull to refresh action.
Tickets related to this pull-request: [ASV-263](<https://aptoide.atlassian.net/browse/ASV-263>)
**Questions:**
No
> [ASV-263] feature/ASV-263-SwipeToRefreshUpdates

- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
This PR aims to fix a bug with the searchView on the search fragment not filling the whole view in landscape mode.
No
Check the ticket
Tickets related to this pull-request: [ASV-288](<https://aptoide.atlassian.net/browse/ASV-288>)
> [ASV-288] Bug with searchView 

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/home/RemoteBundleDataSource.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/WSWidgetsUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/GetHomeBundlesRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/GetSocialRecommendsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/store/GetStoreWidgetsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/store/GetUserRequest.java
This Pull request adds new information for the card/get request that was implemented in the alternative social flow.
The new information is a list of package names, which is a merge of two different lists: One is the list of the latest 10 installed package names and the other a list of 10 random package names.
No
charles, pull to refresh home and check timeline/card/get request body.
Tickets related to this pull-request: [ASV-323](https://aptoide.atlassian.net/browse/ASV-323)
> [ASV-323] feature: get card request now takes in a list of package names

- app/src/main/java/cm/aptoide/pt/analytics/analytics/AnalyticsManager.java
- app/src/main/java/cm/aptoide/pt/home/AdsBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AppHomeClick.java
- app/src/main/java/cm/aptoide/pt/home/AppHomeEvent.java
- app/src/main/java/cm/aptoide/pt/home/AppInBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AppsBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AppsInBundleAdapter.java
- app/src/main/java/cm/aptoide/pt/home/BottomHomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
- app/src/main/java/cm/aptoide/pt/home/EditorsAppsAdapter.java
- app/src/main/java/cm/aptoide/pt/home/EditorsBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/FeatureGraphicInBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/HomeClick.java
- app/src/main/java/cm/aptoide/pt/home/HomeEvent.java
- app/src/main/java/cm/aptoide/pt/home/HomeMoreClick.java
- app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/HomeView.java
- app/src/main/java/cm/aptoide/pt/home/SocialBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/app/AppLoadingViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/app/AppViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/app/ApplicationViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/app/ListStoreAppViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/app/ListStoreAppsAdapter.java
- app/src/test/java/cm/aptoide/pt/home/HomeAnalyticsTest.java
- app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
Home Fragment now has new metrics defined in [ASV-244](https://aptoide.atlassian.net/browse/ASV-244)
No
Either debug FacebookEventLogger with breakpoints, use facebook developers dashboard or check log's in logcat regarding Analytics Manager and FacebookEventLogger.
Tickets related to this pull-request: [ASV-292](https://aptoide.atlassian.net/browse/ASV-292) [ASV-244](https://aptoide.atlassian.net/browse/ASV-244)
> [Feature/ASV-292] Home Fragment Metrics

- app/src/main/res/values/colors_deprecated.xml
Changes default window background colour of the whole app
No
Tickets related to this pull-request: [ASV-258](https://aptoide.atlassian.net/browse/ASV-358)
> [ASV-258] task: change default window background colour

- app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
- app/src/main/java/cm/aptoide/pt/home/SocialBundleViewHolder.java
- app/src/main/res/layout/social_recommends_bundle_item.xml
Shows "- -" instead of 0 in the app rating
Ellipsize's the app name when it reaches the install button and limits it to 1 single line.
No
Tickets related to this pull-request: [ASV-334](https://aptoide.atlassian.net/browse/ASV-334)
Tickets related to this pull-request: [ASV-347](https://aptoide.atlassian.net/browse/ASV-347)
> [ASV-347/ASV-334] Social Home Bundle layout fixes

- app/src/main/java/cm/aptoide/pt/store/StoreAnalytics.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoreWidget.java
new events: Stores_Tab_Interact with Open Followers and with Open Following
No
Tickets related to this pull-request: [ASV-382](https://aptoide.atlassian.net/browse/ASV-382)
> [ASV-382] feature: new analytics event: click on followers/following with specific action.

- app/src/main/java/cm/aptoide/pt/home/apps/AppsAdapter.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
The update apps are ordered by alphabetical order
No
Open the Apps section of the app and check if the updates are correctly sorted.
Tickets related to this pull-request: [ASV-391](https://aptoide.atlassian.net/browse/ASV-391)
**Questions:**
> [ASV-391] Order updates by alphabetic order

- app/src/main/java/cm/aptoide/pt/view/app/ApplicationViewHolder.java
This is happening because the layouts that are being used in other view were updated and the view binds would fail. view ids were updated.
No
Tickets related to this pull-request: [ASV-395](https://aptoide.atlassian.net/browse/ASV-395)
> [ASV-395] fix: npe in apps in store view.

- app/src/main/java/cm/aptoide/pt/store/StoreTheme.java
- app/src/main/res/values/themes.xml
Changed notification bar color (not final, talk to luis about it)
No
StoreTheme.java
themes.xml
Possible Inconsistency across app
393
**Questions:**
> [ASV-393] Changed Notification Bar to gradient end color

- app/src/main/res/layout/partial_app_view_collapsing_toolbar.xml
App view toolbar is transparent again
No
Tickets related to this pull-request: [ASV-394](https://aptoide.atlassian.net/browse/ASV-394)
> [Hotfix/ASV-394] App View toolbar not transparent

- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewFragment.java
Svg now being shown correctly in the appview, which would not load correctly in specific Android versions like api 22 (lollipop).
No
Tickets related to this pull-request: [ASV-397](https://aptoide.atlassian.net/browse/ASV-397)
> [Hotfix/ASV-397] Trusted badge showing up correctly

- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewFragment.java
Fixes the lifecycle of the AppViewFragment which in turn makes the menu items clickable as they should
No
- AppViewFragment.java
-  Open the AppView, and click a youtube video from the gallery. Cancel the "Open With" prompt. Click the menu items.
- Run a youtube video from the AppView gallery and immediately cancel it and return to AppView. Click the menu items.
Tickets related to this pull-request: [ASV-404](https://aptoide.atlassian.net/browse/ASV-404)
> [ASV-404] Fixed menu items stop responding to clicks in AppView

- app/src/main/java/cm/aptoide/pt/home/BottomHomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/HomeView.java
Guarantee that the interactions with the Get Rewarded with AppCoins bundle correctly log events for Scroll Right, tap on more button and click on app.
No
Verify that all the aforementioned events are logged.
Tickets related to this pull-request: [ASV-400](https://aptoide.atlassian.net/browse/ASV-400)
**Questions:**
> [ASV-400] Metrics for AppCoins

- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresFragment.java
Changes the icon of the placeholder on the user icon
No
-MyStoresFragment.java
-AppsFragment.java
Check if the default icon shows up
https://aptoide.atlassian.net/browse/ASV-431
**Questions:**
> [ASV-431] Changed placeholder image on user icon

- app/src/main/res/layout/action_bar.xml
Adds a Ripple effect to the user image on the toolbar
No
action_bar.xml
Click on the user image and check if the ripple effect appears
https://aptoide.atlassian.net/browse/ASV-278
> [ASV-278] Added ripple effect to user icon image

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/home/GetRewardAppCoinsAppsFragment.java
- app/src/main/java/cm/aptoide/pt/repository/request/RewardAppCoinsAppsRepository.java
If you press the more button on the Get Rewarded With AppCoins bundle, you shouldn't see that are or were ever installed on your device.
No
Press the more button on the Get Rewarded with AppCoins bundle.
Tickets related to this pull-request: [ASV-407](https://aptoide.atlassian.net/browse/ASV-407)
**Questions:**
> [ASV-407] Installed apps on more button of Get Rewarded with AppCoins bundle

- app/src/main/java/cm/aptoide/pt/search/analytics/SearchAnalytics.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchAdResultWrapper.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchAppResultWrapper.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultAdapter.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
- app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultAdViewHolder.java
- app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultItemView.java
- app/src/test/java/cm/aptoide/pt/search/SearchResultPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.java
This PR aims to add a new field to the search result clicked event: card postion;
No
Do a search on the app -> upon clicking on a result, verify the event is being sent with the position field added;
Tickets related to this pull-request: [ASV-450](<https://aptoide.atlassian.net/browse/ASV-450>)
> [ASV-450] Added card position to searchResultClicked event;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/home/apps/UpdatesManager.java
- app/src/main/java/cm/aptoide/pt/presenter/MainView.java
- app/src/main/java/cm/aptoide/pt/view/MainActivity.java
- app/src/main/res/drawable/updates_badge_circle.xml
- app/src/main/res/layout/updates_badge.xml
- app/src/test/java/cm/aptoide/pt/navigation/BottomNavigationPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/presenter/MainPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/view/ActivityModule.java
Created a badge to display above the Apps section on the bottom navigation. 
No
Open the app and check if the number of updates is correct inside the badge.
Tickets related to this pull-request: [ASV-443](https://aptoide.atlassian.net/browse/ASV-443)
**Questions:**
> [ASV-443] Updates badge

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/install/PackageRepository.java
This Pull Request filters already installed apps in the Social Recommendation bundle in the Home Fragment.
No
Home > Make sure to have the social recommends app installed > confirm that it doesn't show up visually, but it is on the https://ws75.aptoide.com/api/7/user/timeline/card/get/ response.
Tickets related to this pull-request: [ASV-344](https://aptoide.atlassian.net/browse/ASV-344)
> [Bugfix/ASV-344] Recommends bundle filter already installed apps

- app/src/main/java/cm/aptoide/pt/search/SearchNavigator.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchViewModel.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
- app/src/main/java/cm/aptoide/pt/store/StoreTheme.java
- app/src/main/java/cm/aptoide/pt/store/view/StoreFragment.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/res/drawable/amber_search_button_background.xml
- app/src/main/res/drawable/black_search_button_background.xml
- app/src/main/res/drawable/blue_grey_search_button_background.xml
- app/src/main/res/drawable/brown_search_button_background.xml
- app/src/main/res/drawable/deep_purple_search_button_background.xml
- app/src/main/res/drawable/green_search_button_background.xml
- app/src/main/res/drawable/grey_search_button_background.xml
- app/src/main/res/drawable/indigo_search_button_background.xml
- app/src/main/res/drawable/light_blue_search_button_background.xml
- app/src/main/res/drawable/light_green_search_button_background.xml
- app/src/main/res/drawable/lime_search_button_background.xml
- app/src/main/res/drawable/orange_search_button_background.xml
- app/src/main/res/drawable/pink_search_button_background.xml
- app/src/main/res/drawable/red_search_button_background.xml
- app/src/main/res/drawable/teal_search_button_background.xml
- app/src/test/java/cm/aptoide/pt/search/SearchResultPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
This PR aims to keep the store themes in the search result when the user searches in his/her store.
No
SearchResultFragment.java
Do a search in a store with a theme and check if the search keeps the theme.
Navigate to home and confirm that the theme isn't propagated anymore.
https://aptoide.atlassian.net/browse/ASV-458
> [ASV-458] Store theme persistence in Search

- app/src/main/java/cm/aptoide/pt/account/AccountAnalytics.java
- app/src/vanilla/java/cm/aptoide/pt/FlavourApplicationModule.java
- app/src/vanilla/java/cm/aptoide/pt/view/settings/NewAccountPresenter.java
Everytime a user clicks on an aptoide product card in my profile screen, it records the event to FB analytics
No
In FacebookEventLogger.java, use a breakpoint in log function to make sure everytime a product card is clicked, the right parameters are being sent.
Tickets related to this pull-request: [ASV-513](https://aptoide.atlassian.net/browse/ASV-513)
> [ASV-513] now sending metrics for aptoide products

- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
Fixes the open app. When you go to the appview of an app that you already have installed, the main button should be "Open". After you press open it should open the installed app.
Yes 
Open appview of an installed app, check if it opens the app after pressing the main button.
Tickets related to this pull-request: [ASV-536](https://aptoide.atlassian.net/browse/ASV-536)
**Questions:**
> [ASV-536] fix open app

- app/src/main/res/layout/fragment_new_app_view.xml
App View collapsing toolbar state was being reset on orientation changed, which would leave the view inconsistent if you scroll down and rotate phone. State is being saved thanks to the set in the coordinator layout. See here for details: https://issuetracker.google.com/issues/37055789#c8
No
Tickets related to this pull-request: [ASV-539](https://aptoide.atlassian.net/browse/ASV-539)
> [ASV-539] fix: save collapsing toolbar state on orientation change.

- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/vanilla/java/cm/aptoide/pt/app/DownloadStateParser.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
This PR adds the Install analytics events when the user downloads/upgrades/downgrades an app
This PR also ended up changing the empty packageName and the wrong appId to the correct ones.
AppViewManager.java (line 237, setupDownloadEvents)
Put a breakpoint on logEvent on AnalyticsManager or filter the logs on the logcat by "logEvent" and see if an event with eventName = [INSTALL] appears (the eventName is one of the last attributes)
https://aptoide.atlassian.net/browse/ASV-532
> [ASV-532] InstallAnalytics event 

- app/src/main/res/layout/appview_uploaded_by_layout.xml
- app/src/main/res/layout/fragment_new_app_view.xml
- app/src/main/res/layout/install_app_view.xml
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
This PR aims to fix the downloads layout as well as displaying the correct similar apps bundle
No
Try to install something and check the layouts
Tickets related to this pull-request: [ASV-538](<https://aptoide.atlassian.net/browse/ASV-538>)
> [ASV-538] Fixed download view layout;

- app/src/vanilla/java/cm/aptoide/pt/app/DownloadAppViewModel.java
- app/src/vanilla/java/cm/aptoide/pt/app/DownloadStateParser.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
Handles download errors, showing a dialog explaining the problem.
No
There are two types of errors, the general and the no space error.
For the first one, the general error, you can test it by turning off the wifi in the middle of a download.
For the second one, i recommend creating a setter method for the downloadState, and with the debugger set the download state to NOT_ENOUGH_SPACE_ERROR in order to simulate that you have no space on your device.
Tickets related to this pull-request: [ASV-540](https://aptoide.atlassian.net/browse/ASV-540)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new libs, new …
> [ASV-540] Handle error downloads

- app/src/main/java/cm/aptoide/pt/view/app/AppService.java
- app/src/main/res/layout/fragment_new_app_view.xml
- app/src/main/res/values/strings.xml
- app/src/vanilla/java/cm/aptoide/pt/app/SimilarAppsViewModel.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
fix to the similar apps without ads error
No
Tickets related to this pull-request: [ASV-420](<Jira url>)
> [Task/ASV-420] fix similar apps without adds

- app/src/main/java/cm/aptoide/pt/view/fragment/DescriptionFragment.java
Changes the toolbar color from the read more fragment to solid orange to gradient
DescriptionFragment.java
Navigate to readMore fragment trough the read more button below the description. Check if it has the gradient.
https://aptoide.atlassian.net/browse/ASV-543
> [ASV-543] Changed toolbar color on ReadMore view in AppView

- app/src/main/java/cm/aptoide/pt/store/StoreTheme.java
This PR aims to put the correct theme colors on the search result tabs. This was done before but was lost due to merge problems 
No
StoreTheme.java
Search in a store with a non-default theme (red or green for example) and see if the search tabs are with the same theme as the selected store
https://aptoide.atlassian.net/browse/ASV-571
> [ASV-571] Changed default search tabs colors to the correct ones

- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/view/app/AppCenter.java
- app/src/main/java/cm/aptoide/pt/view/app/AppCenterRepository.java
- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
Adds tests to the AppViewManager.
NOTE: Who accepts this ticket should put it to close and not in testing
No
- AppViewManagerTest.java
https://aptoide.atlassian.net/browse/ASV-551
**Questions:**
> [ASV-551] AppViewManager tests

- app/build.gradle
- app/src/main/java/cm/aptoide/pt/app/view/widget/AppViewRateAndReviewsWidget.java
- app/src/main/java/cm/aptoide/pt/billing/view/payment/PaymentFragment.java
- app/src/main/java/cm/aptoide/pt/networking/image/CircleTransform.java
- app/src/main/java/cm/aptoide/pt/networking/image/GlideModifications.java
- app/src/main/java/cm/aptoide/pt/networking/image/ImageLoader.java
- app/src/main/java/cm/aptoide/pt/networking/image/RoundedCornersTransform.java
- app/src/main/java/cm/aptoide/pt/networking/image/ShadowCircleTransformation.java
- app/src/main/java/cm/aptoide/pt/notification/SystemNotificationShower.java
- app/src/main/java/cm/aptoide/pt/share/ShareDialogs.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/MiniTopReviewViewHolder.java
- build.gradle
updated glide to 4.7.1
No
Test images loaded with glide all over the app
Tickets related to this pull-request: [ASV-490](https://aptoide.atlassian.net/browse/ASV-490)
> [ASV-490] Updated glide to 4.7.1

- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/appview/PreferencesManager.java
- app/src/main/java/cm/aptoide/pt/download/DownloadFactory.java
- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
Fixed some of the proposed changes from the appview pull request. They were mostly renames and one change of signature on the DownloadFactory create method.
No
Tickets related to this pull-request: [ASV-566](https://aptoide.atlassian.net/browse/ASV-566)
**Questions:**
> [ASV-566] App view pull request re review

- app/src/main/java/cm/aptoide/pt/download/DownloadFactory.java
As requested by the web team, every time we download an app, we should pass an action saying if the app is an install, an update or an downgrade.
The action was being passed on all the downloads except for the auto update case.
Unfortunately we can not test the auto update as it is not working ( bug : ASV-617 https://aptoide.atlassian.net/browse/ASV-617 ) 
No
Check on charles the downloads requests. To test the autoupdate you will have to override the autoupdate request response in order to put a bigger vercode so that the auto update is requested. …
> [ASV-581] Setting udpate action for the auto updates

- app/src/main/java/cm/aptoide/pt/comments/view/CommentListFragment.java
- app/src/main/java/cm/aptoide/pt/reviews/LatestReviewsFragment.java
- app/src/main/java/cm/aptoide/pt/store/view/StoreFragment.java
- app/src/main/java/cm/aptoide/pt/store/view/StoreTabGridRecyclerFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowFragment.java
Fixes NPE when clicking followers in the my meta store inside my stores BN menu item.
No
Open Aptoide > Stores > (need to be logged in) > click on followers #.
Tickets related to this pull-request: [ASV-652](https://aptoide.atlassian.net/browse/ASV-652)
> [ASV-652] bugfix: fix possible NPE when storeContext is null.

- app/src/main/java/cm/aptoide/pt/account/view/AccountNavigator.java
- app/src/main/res/values/strings.xml
- app/src/vanilla/java/cm/aptoide/pt/view/settings/SettingsFragment.java
Removes URL from java files to xml files
No
No
No
**Questions:**
No
> url should be in xml files

- app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
- app/src/main/java/cm/aptoide/pt/install/AutoUpdate.java
- app/src/vanilla/java/cm/aptoide/pt/view/ActivityModule.java
The reason was the download analytics startDownload event was not being called before the updateDownload one.
No
Tickets related to this pull-request: [ASV-617](https://aptoide.atlassian.net/browse/ASV-617)
> [ASV-617] fix: npe that was causing auto-update not to work. 

- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowFragment.java
- app/src/main/res/layout-v21/my_store_displayable_layout.xml
- app/src/main/res/layout/layout_dialog_badge.xml
- app/src/main/res/layout/my_store_displayable_layout.xml
- app/src/main/res/layout/timeline_follow_user.xml
- app/src/main/res/values/styles.xml
Fixes some of the RTL support issues that were reported by the localisation team.
No
QA Tickets related to this use-case: [ASV-590](https://aptoide.atlassian.net/browse/ASV-590)
Tickets related to this pull-request: [ASV-590](https://aptoide.atlassian.net/browse/ASV-590)
> [Bugfix/ASV-590] Arabic issues

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/app/view/MoreBundlePresenter.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresFragment.java
- app/src/main/res/layout/list_store_apps_fragment_layout.xml
- app/src/main/res/layout/my_stores.xml
- app/src/main/res/layout/post_comments_fragment.xml
- app/src/main/res/layout/recycler_swipe_fragment_with_toolbar.xml
- app/src/main/res/layout/store_activity.xml
Errors layouts were overlapping the toolbar
When Retry button is pressed in HomeFragment with no net it now shows the retry button again
Small bugfixes regarding possible NPE on MyStoresFragment and wrong context being passed on ApplicationModule while creating IdRepository
Database changed?
Yes | No
HomePresenter.java
Test some fragments with no network and check if the image is not overlapping the toolbar
In homeFragment press retry with no network and check if it doesn't show an empty screen.
https://aptoide.atlassian.net/browse/ASV-624
> [bugfix/ASV-624] Retry button fixes

- app/src/main/java/cm/aptoide/pt/networking/image/ImageLoader.java
This PR fixes some images not being shown on android 8.0 in AppsFragment
No
ImageLoader.java
Check if the images now shows up and if there's a case missed that other images couldn't load because of the change
https://aptoide.atlassian.net/browse/ASV-412
**Questions:**
> [ASV-412] Some apps have no icon in AppsFragment

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/util/ApkFy.java
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
- app/src/main/res/layout/apkfy_onboard_message.xml
- app/src/main/res/values/strings.xml
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
- utils/src/main/java/cm/aptoide/pt/utils/GenericDialogs.java
Adds a new dialog specifically for the apkfy flow.
No
Tickets related to this pull-request: [ASV-644](https://aptoide.atlassian.net/browse/ASV-644)
> [ASV-644] feature: new dialog for apkfy flow.

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
Fix crash that would happen on first launch because fetching aptoide id was happening in the main thread.
No
Clear data and restart.
Tickets related to this pull-request: [ASV-674](https://aptoide.atlassian.net/browse/ASV-674) 
> [ASV-674] fix: first launch analytics is trying to get AptoideId in the main thread. Now it isnt.

- app/src/main/res/layout/fragment_new_app_view.xml
App view: trust badge. Centred and bigger
No
open app view for trust, unknown badge. 
https://aptoide.atlassian.net/browse/ASV-605
**Questions:**
No
> ASV-605 - app view - badge is centred and bigger.

- app/src/test/java/cm/aptoide/pt/home/BundlesRepositoryTest.java
Tests added for the BundleRepository
No
BundlesRepositoryTest.java
https://aptoide.atlassian.net/browse/ASV-689
> [ASV-689] Tests for the BundlesRepository

- app/src/vanilla/java/cm/aptoide/pt/view/wizard/WizardFragment.java
Fixes bug in previous transition colour PR
No
WizardFragment.java
Go trough wizard logged in
> [ASV-641] Transition colours bug fix

- app/src/vanilla/java/cm/aptoide/pt/view/settings/NewAccountFragment.java
Replaces the aptoide tv promotion url by the right one.
No
Tickets related to this pull-request: [ASV-730](https://aptoide.atlassian.net/browse/ASV-730)
> [ASV-730] fix: replace aptoide tv promotion url to the right one.

- app/src/main/AndroidManifest.xml
Removes app permissions related to Spot & Share.
No
- AndroidManifest.xml (main)
Go to possible places where the removed permission could be used 
https://aptoide.atlassian.net/browse/ASV-676
> [ASV-676] Review App Permissions

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
- app/src/main/java/cm/aptoide/pt/appview/InstallAppView.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
Created some tests for appview presenter. Due to time restrictions didn't do too many, but this will be iterative and new tests will be added.
Made some refactor on appview analytics, by removing the billing and store analytics from appview presenter, putting them inside the AppViewAnalytics class.
Removed some unused code.
No
Run the tests
Tickets related to this pull-request: [ASV-706](https://aptoide.atlassian.net/browse/ASV-706)
**Questions:**
> [ASV-706] Test app view presenter

- app/src/main/res/layout/toolbar.xml
This PR aims to fix the spacing between the logo and titles of bundle after pressing more;
No
Check the ticket and confirm those cases are correctly displaying now;
Tickets related to this pull-request: [ASV-603](<https://aptoide.atlassian.net/browse/ASV-603>)
> [ASV-603] Fixed title spacing;

- app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/home/FakeBundleDataSource.java
- app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/SocialBundle.java
- app/src/test/java/cm/aptoide/pt/home/HomeAnalyticsTest.java
Adds a parameter in the TapRecommendations analytic in HomeAnalytics saying if it was a social recommendation or an Aptoide recommendation
No
SocialBundle.java
See in the logs if when there's an aptoide recommends it sends the analytic with "aptoide recommends" and when there's a social recommendation see if it sends the analytic with "social recommendations"
https://aptoide.atlassian.net/browse/ASV-739
Architecture
Documentation on public interfaces
Database changed?
If yes - Database migration?
Remove comments & unused code & forgotten testing Logs
Codestyle
Partners build
Unit tests pass
Functional QA …
> [ASV-739] new parameters for recommendation event

- app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/MoreBundlePresenter.java
- app/src/main/java/cm/aptoide/pt/home/AdHomeEvent.java
- app/src/main/java/cm/aptoide/pt/home/AdInBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AdsBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AdsInBundleAdapter.java
- app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
- app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/apps/BundleView.java
- app/src/test/java/cm/aptoide/pt/app/view/MoreBundlePresenterTest.java
- app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
This PR aims to fix a problem where clicking on highlighted apps in home wouldn't send the corresponding analytics event;
No
Click on a highlighted app and verify the event is being sent (this is a facebook event so you won't see it in charles);
Tickets related to this pull-request: [ASV-345](<https://aptoide.atlassian.net/browse/ASV-345>)
> [ASV-345] Highlighted apps in home now sending click event;

- aptoide-analytics-core/build.gradle
- aptoide-analytics-default-implementation/build.gradle
- build.gradle
Upgrades the version of the facebook sdk to 4.28.0 
No
build.gradle
See if you can login with a facebook account
Useful links:
https://developers.facebook.com/docs/android/upgrading-4x
https://developers.facebook.com/docs/android/change-log-4x
https://aptoide.atlassian.net/browse/ASV-800
> [ASV/800] Facebook sdk update

- app/src/dev/java/cm/aptoide/pt/home/AppSecondaryInfoViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AppInBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchAppResult.java
- app/src/main/java/cm/aptoide/pt/view/app/Application.java
- app/src/main/res/layout/search_app_row.xml
- app/src/prod/java/cm/aptoide/pt/home/AppSecondaryInfoViewHolder.java
- app/src/vanilla/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/listapp/App.java
Shows GET/SPEND Appc label in the search results. 
No
Go to search: Search for 2048 ASF. Check if the result is the version 0.0.3 and has the label GET/SPEND APPC on it.
Tickets related to this pull-request: [ASV-786](https://aptoide.atlassian.net/browse/ASV-786)
> [Feature/ASV-786] Appc in search

- aptoide-analytics-default-implementation/build.gradle
title.
No
Tickets related to this pull-request: [ASV-861](https://aptoide.atlassian.net/browse/ASV-861)
> [ASV-861] fix: make retrofit rx-adapter open to aptoide anayltics lib users.

- app/src/vanilla/java/cm/aptoide/pt/view/wizard/WizardFragment.java
Possibly solves the NPE bug in fabric
No
WizardFragment.java 
Could not reproduce the bug.
https://aptoide.atlassian.net/browse/ASV-866  
> [bugfix/ASV-866] WizardFragment NPE

- app/src/fairy/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/fairy/java/cm/aptoide/pt/home/AppSecondaryInfoViewHolder.java
- app/src/internal/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/internal/java/cm/aptoide/pt/home/AppSecondaryInfoViewHolder.java
- app/src/leak/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/leak/java/cm/aptoide/pt/home/AppSecondaryInfoViewHolder.java
- app/src/prod/java/cm/aptoide/pt/app/view/AppViewPresenter.java
Changes method signature so that leak, fairy and internal flavours compile
No
AppSecondaryInfoViewHolder.java
Build leak, fairy and internal debug
https://aptoide.atlassian.net/browse/ASV-935
> [ASV-935] Leak, fairy, internal not compiling

- app/src/dev/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/app/view/widget/AppViewInstallWidget.java
- app/src/main/java/cm/aptoide/pt/appview/InstallAppView.java
- app/src/main/java/cm/aptoide/pt/share/ShareAppHelper.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/res/layout/logged_in_share.xml
- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
- app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
This PR aims to remove the AB test experiment regarding the recommends dialog from the appview and replacing the "continue" text we previously had with "recommends";
No
Log in to Aptoide -> go to an appview -> start download -> recommends dialog should appear with the word recommend -> press the different options to confirm that nothing's broken
Tickets related to this pull-request: [ASV-929](<https://aptoide.atlassian.net/browse/ASV-929>)
> [ASV-929] Remove recommends AB test experiment

- app/src/main/java/cm/aptoide/pt/home/InfoBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/view/Translator.java
- app/src/main/res/layout-v21/info_action_item.xml
- app/src/main/res/layout/info_action_item.xml
- app/src/main/res/values/strings.xml
AppCoins on-boarding card is now temporarily being translated in the client until we have translations in the API. 
No
Check if AppCoins onboarding card doesn't break.
Tickets related to this pull-request: [ASV-949](https://aptoide.atlassian.net/browse/ASV-949)
> [ASV-949] task: AppCoins on boarding card translations.

- app/src/main/res/drawable/nav_item_color_state.xml
- app/src/main/res/layout-v21/my_store_displayable_layout.xml
- app/src/main/res/layout/social_recommends_bundle_item.xml
- app/src/main/res/values/styles.xml
Fix 3 UI related problems:
Rating not showing up in the Aptoide Recommends card in home.
Bottom navigation item colour should be the orange_gradient_end and not the Aptoide orange.
(API 21+) In stores tab, the user’s store description meta margins are wrong (too much padding)
No
- [ ] social_recommends_bundle_item.xml
- [ ] my_store_displayable_layout.xml
- [ ] styles.xml
QA Tickets related to this use-case: [ASV-XXXX](<Jira url>)
Tickets related to this pull-request: [ASV-XXXX](<Jira url>)
**Questions:**
> [Bugfix/ASV-976] fix to UI issues

- app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
Change layout type, because it was changed in the BE.
No
To test this, simply check if the onBoarding card is showing up. Have it in mind that the card can be blacklisted if you seen him more than ?5 times.
Tickets related to this pull-request: [ASV-977](https://aptoide.atlassian.net/browse/ASV-977)
> [Task/ASV-977] AppCoins onboarding card layout type change

- app/src/main/res/layout/fragment_profile_step_one.xml
- app/src/main/res/layout/fragment_profile_step_two.xml
Fixes some issues with gradient background on some toolbars title (FragmentProfileStepOne and FragmentProfileStepTwo).
No
Checking if the toolbars described don't present background on their title.
https://aptoide.atlassian.net/browse/ASV-945
> ASV 945  - wrong theme on toolbar

- app/src/main/res/values/strings.xml
- app/src/vanilla/java/cm/aptoide/pt/view/wizard/WizardFragment.java
Fix to a crash that would happen if you press skip while changing page in the viewpager at the same time.
Also has a fix that was done in dev to a string that must go corrected to the release version.
No
Clear data > Scroll wizard at the same time you press skip > should not crash.
Tickets related to this pull-request: [ASV-979](https://aptoide.atlassian.net/browse/ASV-979)
> [Hotfix/ASV-979] Wizard Fragment Crash

- app/src/main/res/layout/fragment_manage_store.xml
- app/src/main/res/layout/fragment_manage_user.xml
Changed the buttons layout size on fragment_manage_store.xml and fragment_manage_user.xml. This is a temporary solution, since this screen will change in the near future.
No
Run the app and checking the button sizes when you enter the 'edit user', and 'create a store' screens.
https://aptoide.atlassian.net/browse/ASV-952
> [ASV-952] Fixed different sized buttons by changing the layouts size.

- app/src/main/res/layout/media_layout.xml
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialItemsViewHolder.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/MediaBundleAdapter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/MediaViewHolder.java
This PR fixes a bug where media lists weren't supporting videos;
No
Using charles, for the request:
`https://ws75.aptoide.com/api/7/user/action/item/card/get/card_id=72635teguyegr`
rewrite the response with:
`{"info":{"status":"OK","time":{"seconds":0.043149948120117,"human":"43 milliseconds"}},"data":{"card_id":"72635teguyegr","layout":"curation_1_card","type":"Game of the Week","title":"Z Day: Hearts of Her","background_image":"http://pool.img.aptoide.com/img/cd58a8b03e67fa40b3f2c6815ad34576_image.jpg","app":{"id":40212042,"name":"WhatsApp Messenger","package":"com.whatsapp","uname":"whatsapp","size":40696495,"icon":"http://pool.img.aptoide.com/appstv/461638042f630 …
> [ASV-1013] Now supports videos in media list;

- app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java
- app/src/main/res/layout/credentials_edit_texts.xml
- app/src/main/res/layout/fragment_login_sign_up.xml
- app/src/main/res/layout/fragment_login_sign_up_credentials.xml
Shows the error message by shifting the bottomsheet up and down. Checkbox turns red when the error message is displayed.
No
Go to signup view. Click signup without accepting TC and PP. Checkbox should turn red and the bottomsheet should shift up to accomodate the error message, and then shift down.
https://aptoide.atlassian.net/browse/ASV-983
> Bugfix/ASV-983 - fix TC and PP snackbar

- app/src/main/res/layout/editorial_layout.xml
- app/src/main/res/values/themes.xml
This was the result of the spike (link down below), which was decided that to avoid the orange background detected, to change it to another color (grey_700)
No
- themes.xml
Check if there’s an orange background in the status bar when you enter the Editorial Fragment
spike: https://aptoide.atlassian.net/browse/ASV-1028
https://aptoide.atlassian.net/browse/ASV-1061
**Questions:**
> [ASV-1061] change color of status bar background

- app/src/main/res/layout/editorial_item_layout.xml
- app/src/main/res/layout/editorial_layout.xml
- app/src/main/res/layout/media_layout.xml
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialContent.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialEvent.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialFragment.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialItemsAdapter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialItemsViewHolder.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialView.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/MediaBundleAdapter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/MediaViewHolder.java
Adds transition to the descriptions, fixes small layout changes related to the media and refactored code requested in a previous PR
No
EditorialItemsViewHolder.java
To add description to the media, you got to mock charles response where it has an array of media and replace the description for any string
Try to break the animations
https://aptoide.atlassian.net/browse/ASV-1051
> [feature/ASV-1051] AotW description transition

- app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialFragment.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialView.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialViewModel.java
Unit testing to the editorial presenter
No
-EditorialPresenterTest.java
https://aptoide.atlassian.net/browse/ASV-1083
> [testing/ASV-1083] Editorial presenter unit testing

- app/src/main/java/cm/aptoide/pt/install/DownloadsNotification.java
- app/src/main/java/cm/aptoide/pt/install/DownloadsNotificationsPresenter.java
- app/src/main/java/cm/aptoide/pt/install/InstallService.java
Refactored the notifications handling on InstallService to be according to the rest of the app MVP.
No
Check if the notification flow on the updates tab works as the release.
https://aptoide.atlassian.net/browse/ASV-858
> [ASV-858] Refactored notifications handling on installService.

- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
Adds a delay to progress update in the Apps View
No
AppsManager.java
-Update an app and see if the app doesn’t update every second. Maybe change the timer to 1 second on the code to better notice that  
https://aptoide.atlassian.net/browse/ASV-1088
> [ASV-1088] Added view update delay to the Apps View

- app/src/main/java/cm/aptoide/pt/abtesting/experiments/SimilarAdExperiment.java
- app/src/main/java/cm/aptoide/pt/ads/AppNextAdRepository.java
- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/vanilla/java/cm/aptoide/pt/ads/AdsRepository.java
- app/src/vanilla/java/cm/aptoide/pt/app/AdsManager.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
This fixes the problem where if a user were to open appview and install without scrolling, ad impression would not register.
No
[ASV-1119](https://aptoide.atlassian.net/browse/ASV-1119)
[ASV-1119](https://aptoide.atlassian.net/browse/ASV-1119)
> [Bugfix/ASV-1119] - Similar apps impressions are now registered on install click

- build.gradle
Fix project build error : Could not find play-services-basement.aar
No
Try to build the project
Tickets related to this pull-request: [ASV-1126](https://aptoide.atlassian.net/browse/ASV-1126)
**Questions:**
> [ASV-1126] Fix project build

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/file/CacheHelper.java
- app/src/main/java/cm/aptoide/pt/install/InstallService.java
Adds the cache manager logic of cleaning cache in the install service. 
No
InstallService.java
After the install popup ticket is accepted, download a file to 100% and install it, if you have files in cache that weren’t modified for more than 1 day and the cache limit has been reached it should remove those files.
As this didn’t change the cleanCache logic I would suggest to just put a log at the beginning of the cleanCache to know if it’s called when it’s supposed to be
https://aptoide.atlassian.net/browse/ASV-1086
> [ASV-1086] Cache manager

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/AptoideApplicationAnalytics.java
Adds new user property: version code, so we can track changes between vercodes.
No
See if the user property "version code" is being sent to analytics.
[ASV-1139](https://aptoide.atlassian.net/browse/ASV-1139)
> [ASV-1139] - Added version code user property

- app/src/main/java/cm/aptoide/pt/ads/data/AppNextNativeAd.java
- app/src/main/java/cm/aptoide/pt/ads/data/ApplicationAd.java
- app/src/main/java/cm/aptoide/pt/ads/data/AptoideNativeAd.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppViewHolder.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppsAdapter.java
- app/src/main/java/cm/aptoide/pt/home/AdInBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/AdsInBundleAdapter.java
- app/src/main/res/layout/displayable_grid_ad_appnext.xml
- app/src/vanilla/java/cm/aptoide/pt/app/AppViewSimilarApp.java
Please see [this](https://github.com/Aptoide/aptoide-client-v8/pull/761) pull request. It is exactly the same but for the dev branch instead of the monetization branch.
> [bugfix/ASV-1141] Encapsulated appnext ad views with NativeAdView

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/res/layout/large_banner_item.xml
- app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java
Adds a delay for interstitial ad load. Only loads 1 second after the progress of a download is bigger than 0%. Also changed banner size to medium.
No
Just test if it works as described above.
Specification: [ASV-1145](https://aptoide.atlassian.net/browse/ASV-1145)
> [Monetization/ASV-1145] Interstitial delay

- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
This PR aims to fix the Apps loading forever bug.
No
Download an app that is not an update, install it and then open the Apps section in the bottom navigation.
Tickets related to this pull-request: [ASV-1161](https://aptoide.atlassian.net/browse/ASV-1161)
**Questions:**
> [ASV-1161] Forever Loading Apps

- app/src/main/res/xml/settings.xml
This PR switches from setting the beta versions from true to false by default.
No
Start the app, go to settings menu and check that beta versions is off by default.
https://aptoide.atlassian.net/browse/ASV-1179
> ASV-1179 - Swapped the default value of beta versions to false.

- app/src/vanilla/java/cm/aptoide/pt/view/recycler/DisplayableWidgetMapping.java
Fix to the crash trying to resolve the LatestReviews tab.
No
Open LatestReviews tab in rmota's store. Shouldn't crash.
Tickets related to this pull-request: [ASV-1184](https://aptoide.atlassian.net/browse/ASV-1184)
> [ASV-1184] Fix crash in Latest Reviews fragment.

- app/src/main/java/cm/aptoide/pt/home/ActionItem.java
- app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/home/EditorialBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/InfoBundleViewHolder.java
- app/src/main/res/layout/app_install_cardview_with_rating.xml
- app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java
- app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialContent.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialFragment.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialRequest.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialService.java
- app/src/vanilla/java/cm/aptoide/pt/app/view/EditorialViewModel.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/EditorialCard.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/MarkAsReadRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/ActionItemData.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/GetActionItemRequest.java
Changes the necessary fields in the requests and the responses related to the editorial e appc cards
No
-EditorialFragment.java
-EditorialService.java
-Check if APPC card appears (change the aptoide_uid in the layout=appc_card_info request) and if the know more and mark as read works correctly through the 7.20181019 endpoint.
Check if the EditorialCard appears in home (change the vercode in the getStoreWidgets request to 9400) and check if after pressing the editorial card in home it shows the editorial view and everything is working fine
https://aptoide.atlassian.net/browse/ASV-1162
https://aptoide.atlassian.net/browse/ASV-1177 …
> [ASV-1162] [ASV-1177] Adapt curation api

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/AndroidManifest.xml
- app/src/main/java/cm/aptoide/pt/ads/IronSourceAdRepository.java
- build.gradle
Implements mediation for the IronSource interstitial ad. This means that other ads from other ad networks can be loaded if their SDK decides that it is appropriate.
This is all handled by their SDK, only the adapters need to be included and everything else should be automatic.
No
Check if both AppLovin network and Vungle network are integrated. This can be manually checked to see if there's interstitials that come from their networks and also verify integration by following the documentation below:
https://developers.ironsrc.com/ironsource-mobile/android/integration-helper-android/ …
> [monetisation/ASV-1193] IronSource mediation

- app/src/cobrand/java/cm/aptoide/pt/LoginSignupManager.java
- app/src/cobrand/java/cm/aptoide/pt/MyAccountManager.java
- app/src/cobrand/java/cm/aptoide/pt/MyStoreManager.java
- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepOneFragment.java
- app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepOnePresenter.java
- app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepTwoFragment.java
- app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepTwoPresenter.java
- app/src/main/java/cm/aptoide/pt/view/recycler/displayable/DisplayablesFactory.java
- app/src/main/java/cm/aptoide/pt/view/settings/MyAccountFragment.java
- app/src/vanilla/java/cm/aptoide/pt/LoginSignupManager.java
- app/src/vanilla/java/cm/aptoide/pt/MyAccountManager.java
- app/src/vanilla/java/cm/aptoide/pt/MyStoreManager.java
This PR removes the create store flow from the cobrand flavor. This was done by creating managers for each flavor and checking if it should show the flow or not. 
No
Compiling cobrand should hide the create store flows from the user signup, store menu, and my account menu. When compiling in vanilla, everything regarding create store should be shown. 
https://aptoide.atlassian.net/browse/ASV-1170
> [ASV-1170] Remove create store from cobrand flavor.

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/networking/UserAgentInterceptorV8.java
This PR adds the missing fields to the UserAgentInterceptorV8. The fields missing were aptoidePackageName, aptoideVersionCode and aptoideMd5.
No
Test the request in Charles to see if the required fields are being appended.
https://aptoide.atlassian.net/browse/ASV-1194
> Asv 1194 new user agent for v8

- app/src/main/java/cm/aptoide/pt/app/view/EditorialContent.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialEvent.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialItemsViewHolder.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialService.java
- app/src/main/java/cm/aptoide/pt/app/view/EditorialView.java
- app/src/main/res/layout/editorial_item_layout.xml
- app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/EditorialCard.java
Adds action button logic
No
EditorialItemViewHolder.java
Add the request in charles as in the ticket
https://aptoide.atlassian.net/browse/ASV-1249
**Questions:**
> [ASV-1249] Added action button logic

- app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
This PR aims to implement metrics for promotions in home;
No
Check that the analytics for promotions in home layed out in the ticket are being correctly sent
Tickets related to this pull-request: [ASV-1239](<https://aptoide.atlassian.net/browse/ASV-1239>)
> [ASV-1239] Implemented home analytics regarding promotions;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsAnalytics.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
Implements analytics for the promotions first view.
The events to be logged are both related to the promotions interact with the following actions: open view, install, update and claim.
**PS:**
This PR can not be accepted before the feature/ASV-1219_UserIncentivesView PR is accepted.
No
Press the install, update and claim button.
Tickets related to this pull-request: [ASV-1239](https://aptoide.atlassian.net/browse/ASV-1239)
**Questions:**
> [ASV-1239] First promotions view analytics

- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
There was a bug where if you pressed the install button and refused the permissions, the clicks for that button would never be handled anymore. This should be fixed in this PR.
No
Press the install button don't accept the permissions. Try pressing the install button again and check if it is still being handled.
Tickets related to this pull-request: [ASV-1261](https://aptoide.atlassian.net/browse/ASV-1261)
**Questions:**
> [ASV-1261] Promotions install not working

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
This PR aims to add a deeplink to the promotions fragment;
No
Test that the deeplink is being correctly handled by sending this command through your android studio terminal:
adb shell am start -a "android.intent.action.VIEW" -d "aptoide://cm.aptoide.pt/deeplink?name=promotions"
This should prompt a launch to the promotions fragment;
Tickets related to this pull-request: [ASV-1250](<https://aptoide.atlassian.net/browse/ASV-1250>)
> [ASV-1250] Deeplink for promotions created and tested;

- app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsAnalytics.java
The download complete event was not working for the promotions analytics. This should be fixed on this pull request
No
Download a promotion and check if the event is sent
Tickets related to this pull-request: [ASV-1262](https://aptoide.atlassian.net/browse/ASV-1262)
**Questions:**
> [ASV-1262] Fix download complete

- app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
When the user is only with mobile data and tries to download an app it is asked to go to the settings to enable that setting. When coming back the app was crashing.
No
Disable wifi, enable mobile data, try to download an app, go to settings and come back.
Tickets related to this pull-request: [ASV-1272](https://aptoide.atlassian.net/browse/ASV-1272)
**Questions:**
> [ASV-1272] Crash when back from settings

- app/src/main/java/cm/aptoide/pt/account/view/user/ManageUserFragment.java
Android starts counting months on 0 to better count time. e.g 22 jan is 0 months and 22 days, for that reason the month was appearing as less 1 of what was expected. This PR aims to show the correct month number
No
ManageUserFragment.java
Check if the month number is the correct one
https://aptoide.atlassian.net/browse/ASV-1291
**Questions:**
> [ASV-1291] Wrong month in date picker 

- app/src/main/java/cm/aptoide/pt/promotions/PromotionsHomeDialog.java
Dismisses the dialog when navigating to other fragments
No
PromotionsHomeDialog.java
Check if it’s still possible to replicate the ticket (check ticket in JIRA)
https://aptoide.atlassian.net/browse/ASV-1289
**Questions:**
> [ASV-1289] Promotion Dialog not working on other fragments

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/networking/UserAgentInterceptorV8.java
This PR aims to include the api level of the device on the V8 user agent interceptor.
No
Check in Charles if the api level (int) is being added to the requests.
https://aptoide.atlassian.net/browse/ASV-1277
> [ASV-1277] Add android api level to v8 user agent.

- app/build.gradle
It changes the cobrand packageName
No
build.gradle(app)
Run through both flavours and check if the packageName is correct
https://aptoide.atlassian.net/browse/ASV-1301
**Questions:**
> [ASV-1301] Change packageName for the cobrand flavour

- app/src/cobrand/java/cm/aptoide/pt/FlavourActivityModule.java
- app/src/cobrand/java/cm/aptoide/pt/FlavourFragmentModule.java
- app/src/cobrand/java/cm/aptoide/pt/abtesting/experiments/IronSourceInterstitialAdExperiment.java
- app/src/main/java/cm/aptoide/pt/ApplicationComponent.java
- app/src/main/java/cm/aptoide/pt/view/ActivityComponent.java
- app/src/main/java/cm/aptoide/pt/view/BaseActivity.java
- app/src/main/java/cm/aptoide/pt/view/BaseFragment.java
- app/src/main/java/cm/aptoide/pt/view/FragmentComponent.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/vanilla/java/cm/aptoide/pt/FlavourActivityModule.java
- app/src/vanilla/java/cm/aptoide/pt/FlavourFragmentModule.java
Adds flavour modules for the activity and fragment scopes. Added InterstitialAd class to flavour fragment module. 
No
BaseFragment.java
BaseActivity.java
ActivityComponent.java
FragmentComponent.java
Run the app in both flavours and go to the app view and check if it runs.
https://aptoide.atlassian.net/browse/ASV-1257
**Questions:**
> [ASV-1257] Created flavour modules for activity and fragment scopes

- app/src/cobrand/res/drawable/ic_stat_aptoide_notification.xml
This PR aims at changing the updates notification small icon only for cobrand.
Note this also changes the icon on other views (since they were using the same icon, but that will be fixed on another ticket, where those views will be reviewed).
No
Uninstall and install the app, look at the aptoide notification
Tickets related to this pull-request: [ASV-1292](https://aptoide.atlassian.net/browse/ASV-1292)
**Questions:**
> [ASV-1292] Set partner icon updates notification

- app/src/main/java/cm/aptoide/pt/home/GetRewardAppCoinsAppsFragment.java
- app/src/main/java/cm/aptoide/pt/repository/request/RewardAppCoinsAppsRepository.java
The tag used for apps in this fragment was an empty string. It now uses the tag that is sent in the request
No
GetRewardAppCoinsFragment.java
RewardAppCoinsAppsRepository.java
Use logs or breakpoints to see if the tag is being passed correctly, it should say “appcoins-ads”
https://aptoide.atlassian.net/browse/ASV-1364
**Questions:**
> [ASV-1364] Added tag to apps created in the getRewardedWithAppCoinsFragment (more button)

- app/src/cobrand/java/cm/aptoide/pt/FlavourApplicationModule.java
- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/vanilla/java/cm/aptoide/pt/FlavourApplicationModule.java
Adds missing oemid for cobrand v7 interceptor
No
FlavourApplicationModule.java
https://aptoide.atlassian.net/browse/ASV-1375
https://aptoide.atlassian.net/browse/ASV-1375
**Questions:**
> [ASV-1375] Added missing oemid in cobrand v7 interceptor

- app/build.gradle
This PR aims to fix the error when login in on cobrand versions. The way this was achieved was to match the applicationId on cobrand to the authenticator.
No
Check if the login is successful on cobrand versions.
https://aptoide.atlassian.net/browse/ASV-1334
> [ASV-1334] Error when login in on cobrand.

- app/src/cobrand/java/cm/aptoide/pt/FlavourFragmentModule.java
- app/src/cobrand/java/cm/aptoide/pt/abtesting/experiments/MoPubInterstitialAdExperiment.java
This PR aims at fixing cobrand build by fixing missed imports and two unimplemented methods.
No
Run both cobrand and vanilla flavours
No ticket.
**Questions:**
> [Hotfix] Fix cobrand build

- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
This PR aims at fixing a NPE that was discovered in Fabric. We were not able to reproduce it, so we just added the null verification.
No
Search for an app, check if you have a banner, try to do another search or rotate the screen to see if you can reproduce the problem. (Me and QA couldn't).
Tickets related to this pull-request: [ASV-1421](https://aptoide.atlassian.net/browse/ASV-1421)
**Questions:**
> [ASV-1421] SearchResult NPE

- app/src/main/java/cm/aptoide/pt/view/wizard/WizardFragment.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/WebService.java
Uniformizes the release of the ViewPager and related dependencies like the adapter and the callbacks in the same android lifecycle call. 
Reduced ViewPager variable scope.
No
Cannot reproduce this crash. This is an attempt to fix the issue.
Tickets related to this pull-request: [ASV-1418](https://aptoide.atlassian.net/browse/ASV-1418)
**Questions:**
> [Bugfix/ASV-1423] fix wizard npe

- app/src/main/java/cm/aptoide/pt/promotions/PromotionAppViewHolder.java
- app/src/main/res/drawable/card_border_rounded_green.xml
- app/src/main/res/drawable/card_border_rounded_orange.xml
This fixes a minor visual bug where the claim button in promotions was not rounded as it should be.
No
Just check if the claim button is now rounded.
[ASV-1432](https://aptoide.atlassian.net/browse/ASV-1432)
> [bugfix/ASV-1432] Claim button not rounded

- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListSearchAppsRequest.java
This PR aims to fix ab testing for search keys with wrong names;
No
Check the request to see if the fields are being well sent;
Tickets related to this pull-request: [ASV-1460](https://aptoide.atlassian.net/browse/ASV-1460)
> [ASV-1460] Fixed wrong keys related to search ab testing

- app/src/main/java/cm/aptoide/pt/bottomNavigation/BottomNavigationMapper.java
- app/src/main/java/cm/aptoide/pt/view/MainActivity.java
Adds the first version of a dot in the BN icon (it will later be slightly change when the icon design is made
No
MainActivity.java
See if it appears
https://aptoide.atlassian.net/browse/AS-105
**Questions:**
> [AS-105] Added dot to the new Bottom navigation item

- app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsPresenter.java
Fixes TC and PP removal from cobrand,
No
Try signing up on cobrand and vanilla.
https://aptoide.atlassian.net/browse/ASV-1350
> [ASV-1350] TC and PP for cobrand

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
Recently while trying to enhance appc apps appviews, we removed the ads from those appviews in order to highlight the appc information. While trying to remove the banner ads, a bug was introduced where no banners would be shown due to a filter condition on the chain where the appview information is loaded. This PR aims at fixing this problem and showing banner ads on the appviews where it should be shown.
No
The bug caused no banner ads to be shown on any appview. Confirm that appviews from non appc apps show banners (or at least make the request by reading the logcat and checking if there is a log saying "banner ads error", which means that the network couldn't …
> [ASV-1474] Fix banner ads on appview

- app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
This fixes the missing rounded corners on appc promotions buttons
No
[ASV-1432](https://aptoide.atlassian.net/browse/ASV-1432)
> [bugfix/ASV-1432] Fix rounded corners

- app/src/main/java/cm/aptoide/pt/promotions/ClaimPromotionDialogPresenter.java
- app/src/main/res/drawable/card_border_rounded_green.xml
- app/src/main/res/values/strings.xml
This changes the get wallet address flow according to the specification in the ticket linked below. Basically changes the order of the trigger so instead of happening when the dialog opens, it happens on button click. 
No
Check if it follows the flow described on the ticket correctly.
[ASV-1476](https://aptoide.atlassian.net/browse/ASV-1476)
> [bugfix/ASV-1476] Get wallet address flow 

- app/build.gradle
- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
Implemented analytics on launch to check if the app is flagged by Play Protect using Google's SafetyNet API.
No
Check if the analytics are being sent for the 'Google_Play_Protect' event and verify different scenarios, e.g.: if play protect is not active, if aptoide is flagged and if aptoide is not flagged.
[ASV-1408](https://aptoide.atlassian.net/browse/ASV-1408)
> [feature/ASV-1408] Play Protect Flag Analytics

- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListAdapter.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListFragment.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListManager.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListPresenter.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListRepository.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListView.java
- app/src/main/res/layout/fragment_editorial_list.xml
- app/src/test/java/cm/aptoide/pt/editorialList/EditorialListPresenterTest.java
Adds Pull to refresh to the editorial list view 
No
EditorialListFragment.java
Pull to refresh and check if the view refresh with new cards
https://aptoide.atlassian.net/browse/AS-111
> [AS-111] Added Pull to refresh to editorial list view

- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListRepository.java
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-<Jira ticket number>)
Tickets related to this pull-request: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-<Jira ticket number>)
**Questions:**
> [ASV-109] Cache is now working properly

- app/src/main/java/cm/aptoide/pt/view/wizard/WizardPageTwoFragment.java
Fixes a crash in first launch due to missing injection method call.
No
Check if first launch doesn't crash
[ASV-1528](https://aptoide.atlassian.net/browse/ASV-1528)
> [bugfix/ASV-1528] Crash First Launch

- app/src/main/java/cm/aptoide/pt/editorial/ViewsFormatter.java
- app/src/main/java/cm/aptoide/pt/home/EditorialBundleViewHolder.java
- app/src/test/java/cm/aptoide/pt/editorial/ViewsFormatterTest.java
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-<Jira ticket number>)
Tickets related to this pull-request: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-<Jira ticket number>)
**Questions:**
> [AS-121] Views on editorial card now have a max of 3 digits

- app/src/main/java/cm/aptoide/pt/bottomNavigation/BottomNavigationNavigator.java
Changed BottomNavigation on back pressed home fragment
Yes | No
BottomNavigationActivity
Navigate to other BN fragment, press back, container should be there
Tickets related to this pull-request: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-<Jira ticket number>)
**Questions:**
> [Hotfix] Changed BottomNavigation on back pressed home fragment

- app/build.gradle
- aptoide-analytics-default-implementation/build.gradle
- build.gradle
Updates facebook android sdk version from 4.28 to 4.41 in both app and analytics modules.
Also swapped the whole Facebook Android SDK for the specific modules that we need for analytics and login.
No
Test Facebook services that we use.
Tickets related to this pull-request: [ASV-1566](https://aptoide.atlassian.net/browse/ASV-1566)
> [Task/ASV-1566] update facebook sdk to 4.41

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppViewHolder.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppsAdapter.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/main/java/cm/aptoide/pt/app/view/similar/SimilarAppClickEvent.java
- app/src/main/java/cm/aptoide/pt/app/view/similar/bundles/SimilarAppcAppsViewHolder.java
- app/src/main/java/cm/aptoide/pt/app/view/similar/bundles/SimilarAppsViewHolder.java
This PR aims at fixing the metrics for the similar apps bundles. 
No
Open appviews and check if the events reported in the ticket are being correctly logged (impression and clicks on similar apps bundle apps).
Tickets related to this pull-request: [ASV-1496](https://aptoide.atlassian.net/browse/ASV-1496)
**Questions:**
> [ASV-1496] Metrics for similar appc bundle

- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/res/values/strings.xml
Use the correct string id so Carlos knows which one is being used.
No
- [ ] AppViewFragment.java
Open AppView on an app to be migrated.
Tickets related to this pull-request: [ASV-1587](https://aptoide.atlassian.net/browse/ASV-1587)
> [Task/ASV-1587] update to appc button use correct string id

- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListAdapter.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListRepository.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListService.java
Fixes the load more loading 2 of the same editorial content after a pull to refresh
No
-EditorialListAdapter
Check ticket
https://aptoide.atlassian.net/browse/ASV-1612
> [AS-1612] Fix Load more on editorial view loading 2 of the same editorial content

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListNavigator.java
- app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
Adds deeplink that navigates to the Editorial View
No
DeepLinkManager.java
DeepLinkIntentReceiver.java
Link for confluence in the ticket
https://aptoide.atlassian.net/browse/ASV-1451
> [ASV-1451] Deeplinks for curation

- app/proguard-rules.pro
This PR aims at fixing the pro guard rules for the release candidate build. The IronSource pro guard rules were not updated, which was also not reported in the MoPub documentation.
No
Build project in release variant and see if it compiles. Also try to simulate the base flows of the app to make sure everything is correct.
Tickets related to this pull-request: [ASV-1631](https://aptoide.atlassian.net/browse/ASV-1631)
**Questions:**
> [ASV-1631] Fix network proguard rules

- app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
This ticket aimed at investigating possible too many calls to the same ad unit. The problem could not be reproduced but there was a leak of native ads in search. This PR fixes that. Also removed unused code in home.
No
Since the only changes were in search, open the app, go to the search view and check if there is anything wrong.
Tickets related to this pull-request: [ASV-1593](https://aptoide.atlassian.net/browse/ASV-1593)
**Questions:**
> [ASV-1593] Fixed native ads leaks in search

- app/proguard-rules.pro
This fixes release build that had some problems with proguard warnings related to Flurry SDK.
No
Check if the release flavour builds succesfully
Tickets related to this pull-request: [ASV-1662](https://aptoide.atlassian.net/browse/ASV-1662)
> [bugfix/ASV-1662] Fix release build

- app/src/main/res/layout/displayable_grid_ad.xml
fix: attempt to fix fabric bug that appeared last version v9.9.0.0. Since InMobi was implemented in latest release, it looks like this is the problem: InMobi sets our adview's LayoutParameters with a RelativeLayout.LayoutParams (you can see this in the createAdView method inside InMobiNativeAdRenderer class) and our adview is a relativeLayout but with a FrameLayout parent (in case of displayable_grid_ad). For the LayoutParams to be used successfuly, the PARENT of the view must be the same type of object as the X.LayoutParams that we set in the setLayoutParams method, which in our case it isn't (adview parent: FrameLayout), potentially causing a ClassCastException. InMobiNativeAdRenderer verification before setLayoutParams is verifying - primaryAdLayout instanceof …
> [ASV-1674] fix: Crash in FrameLayout - ClassCastException - Fabric bug

- app/build.gradle
- aptoide-analytics-default-implementation/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This PR aims to increase gradle version to 3.4
No
Anything could break here for any reason and so this is hard to test for specifically. Ran the major app flows and everything looks okay but do check whatever comes to mind
Tickets related to this pull-request: [ASV-1632](https://aptoide.atlassian.net/browse/ASV-1632)
> [ASV-1632] Updated gradle to 3.4;

- app/src/main/java/cm/aptoide/pt/reactions/network/ReactionsResponse.java
This PR aims to implement the new error code for V8 service on the reactions.
No
Check on charles the requests for setting reactions (first and second) and rewrite the response code to one of https://aptoide.atlassian.net/wiki/spaces/IA/pages/1286242331/Echo+V8+Error+Codes
Check if the view shows: <em>An Error Ocurred Please Try Again</em> or Shows the Login error if it reached the 5 reactions limit.
https://aptoide.atlassian.net/browse/ASV-1669
> [ASV-1669] Implement new error structure for Reactions

- app/src/main/java/cm/aptoide/pt/AptoideApplicationAnalytics.java
- app/src/main/java/cm/aptoide/pt/ads/MoPubAnalytics.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
This PR aims to send session parameters to flurry.
No
See the flurry requests and flurry dashboard. 
(NOTE: This does not seem to be working, charles requests are inconsistent, recent documentation doesn't mention the method used and I can't seem to see anything in the flurry dashboard. We decided to go ahead and test it in production anyway);
Tickets related to this pull-request: [ASV-1649](https://aptoide.atlassian.net/browse/ASV-1649)
> [ASV-1649] Sending facebook session parameters to flurry;

- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallActivity.kt
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallView.kt
- app/src/main/res/drawable/ic_check_orange_gradient_start.xml
- app/src/main/res/drawable/ic_white_circle.xml
- app/src/main/res/layout/wallet_install_activity.xml
This PR aims to implement a success screen for the wallet install flow;
No
This newly created view isn't linked to the main flow in anyway so you'll have to force it to appear in the code;
Tickets related to this pull-request: [ASV-1739](https://aptoide.atlassian.net/browse/ASV-1739)
> [ASV-1739] Added success view to the wallet install flow;

- utils/src/main/java/cm/aptoide/pt/utils/q/QManager.java
This PR aims to add leanback value to our q;
No
Toggle the leanback value between 0 and 1; Search for twitch app. Leanback version is 4.5, otherwise 7.10. Make sure the value you try returns the correct version;
Tickets related to this pull-request: [ASV-1712](https://aptoide.atlassian.net/browse/ASV-1712)
> [ASV-1712] Added leanback value to q;

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppcAppsAdapter.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragmentView.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
- app/src/main/java/cm/aptoide/pt/home/apps/UpdatesManager.java
- app/src/main/java/cm/aptoide/pt/install/InstallManager.java
- app/src/main/java/cm/aptoide/pt/install/InstallService.java
- app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
- downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java
Refactored getInstalledDownloads that was doing redundant work when there are methods that already do it.
Added debug logs so we can debug downloads more efficiently in Apps.
Fix Active Downloads Section not showing up.
Replaced toBlocking operations in observable streams.
Only observe downloads in Apps after initial load.
Avoiding file missing downloads to be returned in the DownloadManager. 
While it is still not visible that this fixes improve loading time in Apps, this optimisations were done while benchmarking the problem - which might be related to Realm - deeper inside. 
No
Test downloads in App View and Apps.
Tickets …
> [Improvement/ASV-1733] Apps optimizations

- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
- app/src/main/res/layout/search_ad_loading_list_item.xml
This PR aims to fix a bug where load more wouldn't show at the end of the search RV;
No
Check the ticket and make sure it's not happening anymore;
Tickets related to this pull-request: [ASV-1719](https://aptoide.atlassian.net/browse/ASV-1719)
> [ASV-1719] Fixed bug with loading more in search;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- utils/src/main/java/cm/aptoide/pt/utils/q/QManager.java
This PR aims to fix a bug with leanback value on TV.
No
Check if the leanback value is 0 on phone and 1 on tv;
Tickets related to this pull-request: [ASV-1712](https://aptoide.atlassian.net/browse/ASV-1712)
> [ASV-1712] Fixed bug with leanback value for tv;

- app/src/main/java/cm/aptoide/pt/abtesting/Experiment.java
- app/src/test/java/cm/aptoide/pt/abtesting/AbTestCacheValidatorTest.java
Increases Ab testing experiement cache time (expiration) from 24h to 1 month
No
?
Tickets related to this pull-request: [ASV-1745](https://aptoide.atlassian.net/browse/ASV-1745)
> [Feature/ASV-1745] Increase ab-testing experiment cache time

- app/src/main/java/cm/aptoide/pt/install/InstalledIntentService.java
- app/src/main/java/cm/aptoide/pt/util/ReferrerUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ads/AdNetworkUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/util/referrer/ReferrerUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v2/aptwords/GetAdsRequest.java
disable referrer extraction for installations.
removed commented code, todos and translated comments in local language to english
No
Talk with @jdandrade 
Tickets related to this pull-request: [ASV-1751](https://aptoide.atlassian.net/browse/ASV-1751)
> [Task/ASV-1751] disable referrer extraction for installations

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/install/InstallEvents.java
- app/src/main/java/cm/aptoide/pt/install/InstallerAnalytics.java
- app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
- packageinstaller/src/main/java/cm/aptoide/pt/packageinstaller/AppInstaller.java
- packageinstaller/src/main/java/cm/aptoide/pt/packageinstaller/InstallResultReceiver.java
- packageinstaller/src/main/java/cm/aptoide/pt/packageinstaller/InstallStatus.java
- utils/src/main/java/cm/aptoide/pt/utils/AptoideUtils.java
Fallbacks Installation failures through PackageInstaller to the default installer in MIUI devices.
No
Install apps with appcoins in MIUI device above 21 with and without MIUI Optimisations on.
Tickets related to this pull-request: [ASV-1671](https://aptoide.atlassian.net/browse/ASV-1671)
> [Bugfix/ASV-1671] attribution miui

- build.gradle
This bumps Facebook Analytics lib to v5.0.1.
No
Check if all facebook analytics still work as expected.
[ASV-1779](https://aptoide.atlassian.net/browse/ASV-1779)
> [task/ASV-1779] Facebook V5

- app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
This PR aims at fixing the events regarding the downloads in AppView. During this sprint, we broke the events, and the download events were not being setup. This means that when the download would start and the download interceptor would try to update the event, there would be no event to update and the download would return an error.
No
AppViewAnalytics.java
Open AppView of different types of installations (Downgrade, update, Install) and check that everything is working fine.
Tickets related to this pull-request: ASV-1802
**Questions:**
**Code Review …
> [HOTFIX-1802] fix updates app view

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
- app/src/main/java/cm/aptoide/pt/install/InstallAnalytics.java
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallConfiguration.kt
- aptoide-analytics-core/src/main/java/cm/aptoide/analytics/AnalyticsManager.java
This PR aims at fixing the metrics. Some events were not being correctly sent as detected by QA. Download Complete was being sent eventhough there was no download (or the download was already previously done) and the Application install event was not being sent if there was no download.
Also changed requests order.
Also, now we are verifying the wallet package name in the deeplink and we are also allowing the deeplink to be sent without app source.
`adb shell am start -a "android.intent.action.VIEW" -d "market://details?id=com.appcoins.wallet\&utm_source=myappcoins"`
No
Open the deeplink and perform the download and check that all metrics are being correctly sent as …
> [ASV-1757] Fix metrics

- app/src/main/res/drawable-land/ic_wallet_install_header_background.xml
- app/src/main/res/drawable/ic_wallet_install_header_background.xml
This PR aims at adding the landscape svg to the helping appcoins wallet installation dialog.
No
Send the deeplink in lancscape.
Tickets related to this pull-request: [ASV-1805](https://aptoide.atlassian.net/browse/ASV-1805)
**Questions:**
> [ASV-1805] Fix Landscape

- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
This PR fixes a bug where if an user would scroll in donations list in appview, the action bar would not collapse correctly.
No
Go to an app with appcoins and without screenshots (e.g. Red runner) and scroll down touching the Top donations list. Before, the action bar would not collapse correctly, and it would overlap the view. Now it should collapse correctly.
[ASV-1465](https://aptoide.atlassian.net/browse/ASV-1465)
> [bugfix/ASV-1465] - Fixed appview action bar collapse bug 

- app/src/main/java/cm/aptoide/pt/promotions/PromotionsManager.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsModel.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
passes the correct promotion id to the claim service instead of promotion type.
No
Try to claim the wallet app (charles rewrites in the ticket) and check promotion id in the claim request.
Tickets related to this pull-request: [ASV-1746](https://aptoide.atlassian.net/browse/ASV-1746)
> [ASV-1746] fix: pass the correct promotion id to the claim service

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/com/mopub/nativeads/InneractiveAdapterConfiguration.java
This PR aims at fixing the problems related with Fyber. We also took the chance to fix the way we are starting InMobi and admob (withAdditionalNetwork call was missing).
No
Open the app and check that the sdks were all correcty started. You can check this by looking into the logcat with the filter Init or Inneractive.
There is still a configuration missing on the dashboard but we do not depend on it.
Tickets related to this pull-request: [ASV-1794](https://aptoide.atlassian.net/browse/ASV-1794)
**Questions:**
> [ASV-1794] Fyber problems

- app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsAnalytics.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsManager.java
This fixes 'Download Complete' and 'DOWNLOAD' events according to the document specification linked in the ticket.
No
Go to the linked ticket, check the document specification and verify that all problems specified in the 'Download Complete' and 'DOWLOAD' column are fixed. You can either check this with Charles or debug logcat. 
[ASV-1817](https://aptoide.atlassian.net/browse/ASV-1817)
> [feature/ASV-1817] Download Complete Events

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/util/ReferrerUtils.java
This fixes a flow handle ads flow that was broken during donations development. 
When we open an app view coming from a native legacy ad, we pass a parcelable ad object to the appview for the ads logic to be handled: cpc, cpd, cpi calls are handled with this object, but handleAdsLogic was not being called on this flow. 
No
Steps to reproduce: [ASV-1837](https://aptoide.atlassian.net/browse/ASV-1837)
Tickets related to this pull-request: [ASV-1837](https://aptoide.atlassian.net/browse/ASV-1837)
> [Bugfix/ASV-1837] cpc cpd cpi fix

- app/build.gradle
- app/proguard-rules.pro
This PR aims at fixing Smaato ad network issues.
Now it is being correctly initialized and it is well configured on MoPub's dashboard.
No
Run the app and check in the logcat that we are making calls to Smaato. You can do this by adding the "Soma" tag.
Tickets related to this pull-request: [ASV-1793](https://aptoide.atlassian.net/browse/ASV-1793)
**Questions:**
> [ASV-1793] Smaato problems

- app/build.gradle
- app/proguard-rules.pro
> Fix smaato implementation

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/appview/PreferencesPersister.java
- app/src/main/java/cm/aptoide/pt/preferences/AptoideMd5Manager.java
- app/src/main/res/values/strings.xml
- aptoidepreferences/src/main/java/cm/aptoide/pt/preferences/managed/ManagedKeys.java
This PR persists the md5 calculation on memory and on shared preferences, so it doesn't have to recalculate on every launch, improving startup times.
No
Check if first launch times are bigger than subsequent launch times (filter with the text 'Displayed' on logcat). Also check if the launch time for an update is comparable to a first launch, since the caches should be invalidated. Testing the validation of the implementation probably can only be done with debugging. You can also check if the every request has the correct md5 being sent.
[ASV-1863](https://aptoide.atlassian.net/browse/ASV-1863)
> task/ASV-1863 - Persist aptoide md5

- app/src/main/res/layout/fragment_promotions.xml
This PR aims at fixing the loading inside the promotions view
No
Open promotions fragment and check that there is no error and that the view opens successfully.
Tickets related to this pull-request: [ASV-1884](https://aptoide.atlassian.net/browse/ASV-1884)
**Questions:**
> [ASV-1884] Fix loading

- app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
- app/src/main/java/cm/aptoide/pt/install/InstallAnalytics.java
This PR aims to fix events related to migration apps in apps fragment;
No
Check the ticket and make sure the events are being correctly sent.
Note that the action is still as Action (spoke to ana about this) because all events with it are being sent the same;
Tickets related to this pull-request: [ASV-1808](https://aptoide.atlassian.net/browse/ASV-1808)
> [ASV-1808] Fixed migration events in apps fragment;

- app/build.gradle
- build.gradle
- gradle.properties
This PR aims at optimizing build times by adding the following:
- build parallellization 
- build cache
- removed dex count depependency
No
Run the app from dev (try clean build and a build with no changes).
Run the app in this branch (try clean build and a build with no changes).
No ticket as this came from the codelabs
**Questions:**
> [CODELABS] Build optimizations

- app/src/main/java/cm/aptoide/pt/home/AppBundle.java
- app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/home/FakeBundleDataSource.java
- app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
- app/src/test/java/cm/aptoide/pt/home/BundlesRepositoryTest.java
This PR aims at fixing the problems related with the tag of the "more section" bundles, which was being sent wrong in the events
No
Open appview from the editors choice and then open the appview through the more section. Check that the tags are correct.
Tickets related to this pull-request: [ASV-1859](https://aptoide.atlassian.net/browse/ASV-1859)
**Questions:**
> [feature/ASV-1859] Fixed tag for actions in bundles

- app/src/main/java/cm/aptoide/pt/app/AppCoinsAdvertisingModel.kt
- app/src/main/java/cm/aptoide/pt/app/AppCoinsService.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/res/layout-v21/appview_poa_layout.xml
- app/src/main/res/layout/appview_poa_layout.xml
- app/src/main/res/values/strings.xml
- aptoide-views/src/main/res/drawable/appview_countdown_rounded_corners_black_background.xml
- aptoide-views/src/main/res/layout/appview_poa_countdown_element.xml
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/AppCoinsCampaign.java
This PR aims to implement the countdown fomo element on appview regarding PoAs
No
You'll need to rewrite the new api call for appview promotions and add the end_date field to see this. While in production this should never come along with the budget element, I made this so it takes precedence over it and as such there's not need for you to remove it. You can find this json in the confluence page regarding poa
Tickets related to this pull-request: [ASV-1914](https://aptoide.atlassian.net/browse/ASV-1914)
> [ASV-1914] Implemented countdown element for PoA in appview;

- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListFragment.kt
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
This PR aims to implement navigation for the new appcoins ads deeplink;
No
Send the deeplink in the ticket and make sure it works as intended;
Tickets related to this pull-request: [ASV-1924](https://aptoide.atlassian.net/browse/ASV-1924)
> [ASV-1924] Created deeplink navigation for appcoins ads;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
This PR aims at fixing root install for android devices above android O
No
With a rooted device both above android O and bellow, check that we are able to root install apps correctly 
Tickets related to this pull-request: [ASV-1963](https://aptoide.atlassian.net/browse/ASV-1963)
**Questions:**
>  Fixed root install on devices above android O

- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/main/java/cm/aptoide/pt/app/view/googleplayservices/PlayServicesBottomSheetFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/googleplayservices/PlayServicesView.java
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-XXXX)
Tickets related to this pull-request: [ASV-XXXX](https://aptoide.atlassian.net/browse/ASV-XXXX)
**Questions:**
> Fixed install start

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/install/installer/RootCommandPermissionOnSubscribe.java
- app/src/main/java/cm/aptoide/pt/install/installer/RootPermissionGranter.java
This PR grants permissions to all packages.
No
Open the app and it will give permissions to all google apps needed
Tickets related to this pull-request: [ASV-1964](https://aptoide.atlassian.net/browse/ASV-1964)
**Questions:**
> [ASV-1964] Grant permissions to 3rd party

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/app/view/OtherVersionsFragment.java
- app/src/main/java/cm/aptoide/pt/home/bundles/RemoteBundleDataSource.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsService.java
- app/src/main/java/cm/aptoide/pt/repository/RepositoryFactory.java
- app/src/main/java/cm/aptoide/pt/repository/request/GetStoreWidgetsRequestFactory.java
- app/src/main/java/cm/aptoide/pt/repository/request/GetUserRequestFactory.java
- app/src/main/java/cm/aptoide/pt/repository/request/ListAppsRequestFactory.java
- app/src/main/java/cm/aptoide/pt/repository/request/RequestFactory.java
- app/src/main/java/cm/aptoide/pt/reviews/RateAndReviewsFragment.java
- app/src/main/java/cm/aptoide/pt/search/SearchManager.java
- app/src/main/java/cm/aptoide/pt/search/suggestions/TrendingService.java
- app/src/main/java/cm/aptoide/pt/updates/UpdateRepository.java
- app/src/main/java/cm/aptoide/pt/view/app/AppService.java
- app/src/main/java/cm/aptoide/pt/view/fragment/DescriptionFragment.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppMetaRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListAppsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListSearchAppsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/WSWidgetsUtils.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/GetHomeBundlesRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/listapps/ListAppVersionsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/listapps/ListAppsUpdatesRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/promotions/GetPromotionAppsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/store/GetStoreWidgetsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/store/GetUserRequest.java
To prevent the situation where the installation will fail due to the MIUI Optimization option in Xiaomi devices, App bundles are disabled in MIUI ROM's.
No
Test App Bundle installs in Xiaomi and Non-Xiaomi devices.
Tickets related to this pull-request: [ASV-1992](https://aptoide.atlassian.net/browse/ASV-1992)
> [ASV-1992] task: disable app bundles requests

- app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
This PR fixes root install and system install for API >= 28. For root install, it uses a variant command of pm, and for system install we simply use split install which handles everything automatically for us.
No
Ideally, 4 different cases should be tested:
-> Root install in devices API < 28
-> Root install in devices API >= 28
-> System install in devices API < 28
-> System install in devices API >= 28
[ASV-1974](https://aptoide.atlassian.net/browse/ASV-1974)
> [task/ASV-1974] Fixes for system install and root install for API >= 28

- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListAdapter.java
- app/src/main/java/cm/aptoide/pt/editorialList/LoadingViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/bundles/editorial/EditorialBundleViewHolder.java
- app/src/main/java/cm/aptoide/pt/home/bundles/editorial/EditorialViewHolder.java
This PR fixes a bug that was making editorial crash on scroll;
No
Make sure the described bug is no longer happening
Tickets related to this pull-request: [ASV-2039](https://aptoide.atlassian.net/browse/ASV-2039)
> [ASV-2039] Fixed crash on editorial scroll;

- app/src/main/java/cm/aptoide/pt/home/bundles/top/TopBundleAdapter.java
- app/src/main/java/cm/aptoide/pt/store/view/StoreTabFragmentChooser.java
- app/src/main/java/cm/aptoide/pt/store/view/StoreTabGridRecyclerFragment.java
Fixed top games showing grid instead of list;
No
Make sure top games in the games chip now shows a list view instead of grid;
> Fixed top games showing grid instead of list;

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/ads/MoPubAnalytics.java
This PR aims at setting the a super property to Rakam, so that all the following events are sent with this super property. 
Super properties are a feature from Rakam that does not have any type of documentation.
No
Open the app, it will load the super property. Since currently we do not have any events from Rakam, it is not possible to see it. From what I tested, looking into _session_start_ tables, it is possible to see the atribute ads. 
Tickets related to this pull-request: [ASV-2054](https://aptoide.atlassian.net/browse/ASV-2054)
**Questions:**
**Code …
> [ASV-2054] Rakam retention

- app/src/main/java/cm/aptoide/pt/install/InstallManager.java
This PR aims at improving the efficiency of the getCurrentInstallation method. This method returns the current download to show the notification, but before, we were loading all downloads and filtering afterwards. This would lead to unnecessary processing.
No
Open the app, perform a download and check if everything is ok with the notification.
Tickets related to this pull-request: [ASV-2077](https://aptoide.atlassian.net/browse/ASV-2077)
**Questions:**
> [ASV-2077] Improve efficiency of current installation check

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/home/bundles/ads/AdMapper.java
- app/src/main/java/cm/aptoide/pt/search/SearchNavigator.java
- app/src/main/java/cm/aptoide/pt/search/analytics/SearchAnalytics.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchAdResult.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchAppResult.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchQueryModel.kt
- app/src/main/java/cm/aptoide/pt/search/model/SearchViewModel.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchSuggestionsPresenter.java
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
- app/src/test/java/cm/aptoide/pt/search/SearchResultPresenterTest.java
This PR implements Rakam search events (see ticket for specification).
No
Check on logcats if both events are as specified in the ticket.
[ASV-2092](https://aptoide.atlassian.net/browse/ASV-2092)
> [feature/ASV-2092] Implemented Rakam search event

- app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoView.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
- app/src/main/java/cm/aptoide/pt/navigator/ExternalNavigator.kt
- app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoPresenter.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/res/drawable/ic_arrow_right_catappult.xml
- app/src/main/res/layout/appview_catappult_card.xml
- app/src/main/res/layout/fragment_app_view.xml
- app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java
- app/src/test/java/cm/aptoide/pt/app/view/AppCoinsInfoPresenterTest.java
This PR adds the new "Are you a developer" element to appview;
No
Make sure the element shows up on appviews and navigates to catappult.io
Tickets related to this pull-request: [ASV-2037](https://aptoide.atlassian.net/browse/ASV-2037)
> [ASV-2037] Added "Are you a developer" element to appview;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- dataprovider/build.gradle
- gradle.properties
Delegates rakam base host creation to Dagger.
Follow the same http/https scheme selection (internal/prod)
Extracts rakam base host to the configuration (gradle.properties)
Changes the base host to the new one.
No
Check if rakam is sending events (200 OK)
Tickets related to this pull-request: [ASV-2123](https://aptoide.atlassian.net/browse/ASV-2123)
**Questions:**
Does this add new dependencies which need to be added?
New RAKAM key.
> [Task/ASV-2123] rakam new base host

- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
User clicks in-app billing label, goes to appcoins info view.
No
Test clicks in in-app billing label that should go to the appcoins information view. 
Tickets related to this pull-request: [ASV-2030](https://aptoide.atlassian.net/browse/ASV-2030)
> [Feature/ASV-2030] app view hook to appc detail view

- app/src/main/java/cm/aptoide/pt/search/analytics/SearchAnalytics.java
- app/src/main/java/cm/aptoide/pt/search/model/SearchQueryModel.kt
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
Search event added new Source=deeplink
No
Flow on how to test this or QA Tickets related to this use-case: [ASV-2155](https://aptoide.atlassian.net/browse/ASV-2155)
Tickets related to this pull-request: [ASV-2155](https://aptoide.atlassian.net/browse/ASV-2155)
> [Task/ASV-2155] Search event deeplink source

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/permission/PermissionServiceActivity.java
- app/src/main/java/cm/aptoide/pt/permission/PermissionServiceFragment.java
- app/src/main/res/values/strings_settings.xml
- utils/src/main/java/cm/aptoide/pt/actions/PermissionManager.java
- utils/src/main/java/cm/aptoide/pt/actions/PermissionService.java
- utils/src/main/java/cm/aptoide/pt/actions/RequestDownloadAccessOnSubscribe.java
- utils/src/main/java/cm/aptoide/pt/utils/GenericDialogs.java
This PR implements a new flow for downloading in appview when a user is on mobile data and has set downloads to wifi only
No
While on mobile data and with the option to only download on wifi, go to any appview and try to download an app. You should see the new dialog. Make sure everything is working as intended;
Tickets related to this pull-request: [ASV-2113](https://aptoide.atlassian.net/browse/ASV-2113)
> [ASV-2113] Implemented new wifi/3g appview flow;

- app/src/main/java/cm/aptoide/pt/ads/data/AptoideNativeAd.java
- app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultAdViewHolder.java
- app/src/main/res/values/strings.xml
This PR fixes an issue where certain ads would display -1 fiat value, especially in Search.
No
[ASV-2183](https://aptoide.atlassian.net/browse/ASV-2183)
> [bugfix/ASV-2183] PoA ad fix

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/AptoideApplicationAnalytics.java
This PR implements an event to check whether a user is on tv or not
No
Make sure the event described in the ticket is being sent to facebook on application start;
Tickets related to this pull-request: [ASV-2116](https://aptoide.atlassian.net/browse/ASV-2116)
> [ASV-2113] Implemented tv check analytic to facebook;

- app/src/main/java/cm/aptoide/pt/ads/MoPubAnalytics.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
This PR aims at adding first session super property to rakam. 
No
Open app, do any of the rakam events and check that the user property is being correctly sent.
Tickets related to this pull-request: [ASV-2195](https://aptoide.atlassian.net/browse/ASV-2195)
**Questions:**
> [ASV-2195] First interaction super property

- app/src/main/java/cm/aptoide/pt/install/InstallManager.java
This PR aims at fixing the install method which is a completable. This method was not completing as it was always returning an error because we were applying a first() on it and, so it was returning an error and not completing.
This means that the things that were being done in case this method completes, are now happening again, as this was broken in the downloads refactor. One example of it are the events click on install that were being sent in AppView or Editorial.
No
Open AppView, apps, editorial, promotions and try to perform downloads. Check that all events go accordingly, specially the ones in the beginning related with the click on install.
**What are the …
> [ASV-2202] Fix downloads events

- aptoide-analytics-default-implementation/build.gradle
- build.gradle
This PR bumps flurry to 12.1.0
No
Make sure requests to flurry are still being correctly sent;
Tickets related to this pull-request: [ASV-2169](https://aptoide.atlassian.net/browse/ASV-2169)
> [ASV-2169] Increased Flurry version to 12.1.0 to enable CCPA compliance;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/autoupdate/AutoUpdateService.kt
- app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
This PR aims at changing the api from auto update.
No
Open Aptoide and check the different requests being made. Also, generate a build with a lower vercode and check if you see the autoupdate dialog
Tickets related to this pull-request: [ASV-2115](https://aptoide.atlassian.net/browse/ASV-2115)
**Questions:**
> [ASV-2115] Auto update new api

- app/src/main/java/cm/aptoide/pt/home/Home.java
- app/src/main/java/cm/aptoide/pt/home/HomePromotionsWrapper.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionApp.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionAppDownloadingViewHolder.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionAppViewHolder.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionMeta.kt
- app/src/main/java/cm/aptoide/pt/promotions/PromotionViewApp.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionViewAppMapper.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsHomeDialog.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsManager.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsModel.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsService.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsView.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsViewHolderFactory.java
- app/src/main/res/drawable/ic_promotion_claimed_check.xml
- app/src/main/res/layout/promotion_app_card_top.xml
- app/src/main/res/layout/promotion_app_inactive.xml
- app/src/main/res/values/colors.xml
- app/src/test/java/cm/aptoide/pt/home/HomeContainerPresenterTest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/promotions/GetPromotionAppsResponse.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/promotions/GetPromotionsResponse.java
This PR implements messages and fiat values for promotions coming from server; It also changes the look and feel of the cards on the fragment, as per zeplin;
No
Use the rewrites in the ticket (this is not in production as of yet) and make sure everything is according to zeplin and that the messages shown match what you're getting from charles;
Tickets related to this pull-request: [ASV-2166](https://aptoide.atlassian.net/browse/ASV-2166)
> [ASV-2166] Implemented fiat values from server in promotions fragment;

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplicationAnalytics.java
- app/src/main/java/cm/aptoide/pt/GmsStatusValueProvider.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
- app/src/main/java/cm/aptoide/pt/analytics/view/AnalyticsActivity.java
Sending all rakam user properties at once as rakam is paid by events, so if we sent all properties in different "events" we would be spending more.
No
Run the app and check in Charles that the events are only sent once. 
Tickets related to this pull-request: [ASV-2214](https://aptoide.atlassian.net/browse/ASV-2214)
**Questions:**
> [ASV-2214] Rakam user properties

- app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
- app/src/main/java/cm/aptoide/pt/editorialList/EditorialListFragment.java
- app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
- app/src/main/java/cm/aptoide/pt/home/more/base/ListAppsFragment.kt
- app/src/main/java/cm/aptoide/pt/view/swipe/SwipeLoaderLayoutHandler.java
- app/src/main/res/layout/fragment_apps.xml
- app/src/main/res/layout/fragment_apps_see_more_appc.xml
- app/src/main/res/layout/fragment_editorial_list.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_list_apps.xml
- app/src/main/res/layout/list_store_apps_fragment_layout.xml
- app/src/main/res/layout/more_bundles_view.xml
- app/src/main/res/layout/my_stores.xml
- app/src/main/res/layout/post_comments_fragment.xml
- app/src/main/res/layout/recycler_swipe_fragment.xml
- app/src/main/res/layout/recycler_swipe_fragment_with_toolbar.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/themes.xml
- aptoide-views/src/main/java/cm/aptoide/aptoideviews/swipe/AptoideSwipeRefresh.kt
- aptoide-views/src/main/res/values/aptoide_views_styles.xml
This puts the pull to refresh background and progress colors to reference theme colors. For convenience, this is also now a custom view so we can rf 
No
Everything should still be the same in light/dark theme mode since I only changed the color value to an attribute reference.
ASV-1773](https://aptoide.atlassian.net/browse/ASV-1773)
> [feature/ASV-1773] Pull to Refresh theme reference

- app/src/main/java/cm/aptoide/pt/view/dialog/DialogBadgeV7.java
- app/src/main/res/layout/layout_dialog_badge.xml
This PR aims at implementing the dark theme for the trusted app dialog inside appview.
No
Run the app in a device with darktheme, open an appview, press the trusted badge and see that everything is the way it should.
Tickets related to this pull-request: [ASV-2020](https://aptoide.atlassian.net/browse/ASV-2020)
**Questions:**
> [ASV-2225] Trusted app dialog

- aptoide-analytics-default-implementation/src/main/java/cm/aptoide/analytics/implementation/loggers/RakamEventLogger.java
- aptoide-analytics-default-implementation/src/main/java/cm/aptoide/analytics/implementation/loggers/UXCamEventLogger.java
Remove code not being used.
No
Check events being sent correctly and nothing wront with the implementation.
Tickets related to this pull-request: [ASV-2217](https://aptoide.atlassian.net/browse/ASV-2217)
**Questions:**
Does this add new dependencies that need to be added? (Eg. new keys, etc.) 
Don't forget the UXCam and Rakam keys that are needed to see events being sent.
> [ASV-2217] task: remove unused code.

- app/src/main/res/drawable/default_nav_item_color_state_dark.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
Adds support for dark theme in bottom navigation.
No
Check if the bottom navigation looks ok for dark and light theme. Note that the Updates counter in Apps is not included in this.
[MOB-119](https://aptoide.atlassian.net/browse/MOB-119)
> [feature/MOB-119] BN Dark Theme

- app/src/main/java/cm/aptoide/pt/home/HomeContainerPresenter.java
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/res/drawable/default_search_button_background_white.xml
- app/src/main/res/drawable/search_buttons_background_black.xml
- app/src/main/res/layout-v21/global_search_fragment.xml
- app/src/main/res/layout/global_search_fragment.xml
- app/src/main/res/layout/search_ad.xml
- app/src/main/res/layout/search_app_row.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/themes.xml
- app/src/test/java/cm/aptoide/pt/home/HomeContainerPresenterTest.java
Search results cards & stores switch widget.
Removed some unused code from HomeContainer view
No
Test light & dark theme in SearchResultsFragment
Tickets related to this pull-request: [MOB-123](https://aptoide.atlassian.net/browse/MOB-123)
> [Feature/MOB-123] Support dark-theme in Search Results

- app/src/main/java/cm/aptoide/pt/store/view/my/StoreWidget.java
- app/src/main/java/cm/aptoide/pt/timeline/view/displayable/FollowUserDisplayable.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/FollowUserWidget.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowersFragment.java
- app/src/main/java/cm/aptoide/pt/timeline/view/follow/TimeLineFollowingFragment.java
- app/src/main/res/layout/store_displayable_layout.xml
- app/src/main/res/layout/timeline_follow_user.xml
- app/src/main/res/layout/white_message_displayable.xml
- app/src/main/res/values/styles_aptoide_text_view.xml
- app/src/main/res/values/themes.xml
This PR aims at fixing the follow and following views in darktheme.
Notice that the feature with that existed before where the store name would have the color of the store theme, was removed by recommendation from the designer.
Also, as I was touching on this part of the code, I also took the chance to fix the horrible bug we had where the following and followers views were navigating to the oposite detail view (ex: pressing following would navigate to the followers view).
No
Login in an account where you have a store that has followers and is following another stores. Check it in both darktheme and light theme. See if everything is correct.
**What are the relevant …
> [MOB-129] Follow and Following

- app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewNavigator.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/app/view/ReadMoreClickEvent.java
- app/src/main/java/cm/aptoide/pt/view/FragmentProvider.java
- app/src/main/java/cm/aptoide/pt/view/configuration/implementation/VanillaFragmentProvider.java
- app/src/main/java/cm/aptoide/pt/view/fragment/DescriptionFragment.java
- app/src/main/res/layout/fragment_app_view_description.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/themes.xml
This PR aims at fixing the APPC toolbar in the read more view. This should only be used for the light theme as in the dark theme the appc gradient is black so it won't be noticed.
No
Open APPC apps in dark and light theme and check that it has the correct background. 
Tickets related to this pull-request: [MOB-44](https://aptoide.atlassian.net/browse/MOB-44)
**Questions:**
> [MOB-44] Review APPC toolbar

- app/src/main/java/cm/aptoide/pt/store/view/GridStoreMetaDisplayable.java
- app/src/main/java/cm/aptoide/pt/view/recycler/displayable/DisplayablesFactory.java
- app/src/main/res/layout/app_install_cardview.xml
- app/src/main/res/layout/app_install_cardview_with_rating.xml
- app/src/main/res/layout/displayable_grid_add_store_comment.xml
- app/src/main/res/layout/install_app_view.xml
- app/src/main/res/values/styles_aptoide_button.xml
- app/src/main/res/values/themes.xml
Fixes install button and other misc. buttons such as "Follow" store button and "Comment store" button. 
No
Go to every place where an install button exists and check if it looks correct for both light and dark theme. Also check the same for the Follow button (in any store) and Comment Store button (in any store that has no comments yet).
[MOB-134](https://aptoide.atlassian.net/browse/MOB-134)
> [feature/MOB-134] Install Button Dark Theme

- app/src/main/java/cm/aptoide/pt/promotions/ClaimPromotionDialogFragment.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionAppViewHolder.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsHomeDialog.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsViewHolderFactory.java
- app/src/main/res/drawable/button_border_dark.xml
- app/src/main/res/drawable/card_border_fog_grey_wallet_promotion.xml
- app/src/main/res/drawable/edit_text_background_black.xml
- app/src/main/res/drawable/locked_button_background.xml
- app/src/main/res/drawable/promotions_shape_circular_textview_white.xml
- app/src/main/res/drawable/rating_shape_white.xml
- app/src/main/res/layout/displayable_row_review.xml
- app/src/main/res/layout/fragment_promotions.xml
- app/src/main/res/layout/insert_wallet_address_view.xml
- app/src/main/res/layout/promotion_app_active_download.xml
- app/src/main/res/layout/promotion_app_card_top.xml
- app/src/main/res/layout/promotion_app_inactive.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles_aptoide_text_view.xml
- app/src/main/res/values/themes.xml
Promotions view & claim dialog dark theme.
No
Test both Light & Dark theme promotions. (need rewrites to test promotions)
Tickets related to this pull-request: [MOB-150](https://aptoide.atlassian.net/browse/MOB-150)
> [Feature/MOB-150] Support dark-theme in Promotions view

- app/src/main/res/layout/my_account_product_cardview.xml
This PR aims at fixing the width of the textviews being fixed. Before, if the text was too long it was being cutoff. Now if the text does not fit it will add "..." to the end of it.
No
Change the strings for these texts and set a long text. Run the app and check that it is adding the "..." at the end.
Tickets related to this pull-request: [MOB-103](https://aptoide.atlassian.net/browse/MOB-103)
**Questions:**
> [MOB-103] Fixed text being cutoff at the end of view

- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/res/values/themes.xml
Fixes status bar in app view comments.
No
Check if app view comments status bar is correct for dark and light theme.
[MOB-166](https://aptoide.atlassian.net/browse/MOB-166)
> [MOB-166] Comments status bar

- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragmentView.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
Fixes the navigation issue when clicking update icon in the Upgrade to AppCoins version section in Apps.
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-171](https://aptoide.atlassian.net/browse/MOB-171)
Tickets related to this pull-request: [MOB-171](https://aptoide.atlassian.net/browse/MOB-171)
> [MOB-171] fix: upgrade to appcoins button navigation to appview.

- app/src/main/res/layout/timeline_follow_user.xml
Fixes follow/following items color background.
Minor margins adjustments.
No
Test in both dark & light theme - followers/following view
Tickets related to this pull-request: [MOB-22](https://aptoide.atlassian.net/browse/MOB-22)
> [MOB-22] fix: follow items minor UI adjustements.

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/wallet_install_activity.xml
- app/src/main/res/layout/wallet_install_download_view.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_aptoide_button.xml
- app/src/main/res/values/styles_aptoide_text_view.xml
This PR fixes the issue going on with the Wallet install dialog in the RC v9.13.0.0
No
Test wallet install dialog (deeplink in docs)
Tickets related to this pull-request: [MOB-222](https://aptoide.atlassian.net/browse/MOB-222)
> [MOB-222] fix: crash in wallet install dialog

- app/src/main/java/cm/aptoide/pt/account/view/AccountNavigator.java
This PR aims at fixing the navigation after creating a store.
No
Create a store and check that it navigates to home.
Tickets related to this pull-request: [MOB-266](https://aptoide.atlassian.net/browse/MOB-266)
**Questions:**
> [HOTFIX/ASV-266] Stuck store creation

- app/src/main/java/cm/aptoide/pt/home/bundles/RemoteBundleDataSource.java
revert changes to the gaid refactor in remote bundles data source, it was breaking apps&games behaviour.
No
Open apps & games
Tickets related to this pull-request: [MOB-265](https://aptoide.atlassian.net/browse/MOB-265)
> [MOB-265] fix: apps & games not loading

- app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
Attemps to fix a crash that was happening in Apps. Note that I couldn't reproduce it.
No
Check that you can't crash Apps? I couldn't reproduce it in the first place, but maybe try to rotate the screen and attempt to crash it.
[MOB-274](https://aptoide.atlassian.net/browse/MOB-274)
> [bugfix/MOB-274] Apps crash

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
This PR implements a new first_launch event to rakam as well as adding the version code to super properties;
No
Do a fresh aptoide install and make sure the event is sent. Also make sure its never sent again under any conditions (besides clear data and a new fresh install);
Tickets related to this pull-request: [MOB-248](https://aptoide.atlassian.net/browse/MOB-248)
> [MOB-248] Implemented new first_launch event to Rakam;

- app/src/main/java/cm/aptoide/pt/search/SearchManager.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetRecommendedRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListSearchAppsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/QueryStringMapper.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java
Migration of both listSearchApps and getRecommended to the ws75-cache host with @GET requests.
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-172](https://aptoide.atlassian.net/browse/MOB-172)
Tickets related to this pull-request: [MOB-172](https://aptoide.atlassian.net/browse/MOB-172)
> [Task/MOB-172] Migrate ws75 to ws75 cache

- app/src/main/java/cm/aptoide/pt/themes/DarkThemeDialogPresenter.kt
- app/src/main/java/cm/aptoide/pt/themes/DarkThemeMode.kt
- app/src/main/java/cm/aptoide/pt/themes/ThemeAnalytics.kt
- app/src/main/java/cm/aptoide/pt/themes/ThemeManager.kt
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
- app/src/main/java/cm/aptoide/pt/view/MainActivity.java
- app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
send new super property to rakam related to the dark theme mode (light, dark, system light, system dark)
No
Send a Rakam event (click on install in an app view) in all themes (light, dark, system light and system dark) and validate the event using Charles.
Tickets related to this pull-request: [MOB-277](https://aptoide.atlassian.net/browse/MOB-277)
> [MOB-277] send new superproperty to rakam related to the dark theme

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
- app/src/main/java/cm/aptoide/pt/app/view/OtherVersionsFragment.java
- app/src/main/java/cm/aptoide/pt/repository/RepositoryFactory.java
- app/src/main/java/cm/aptoide/pt/repository/request/RequestFactory.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/HardwareSpecsFilterPersistence.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/HardwareSpecsFilterProvider.java
- dataprovider/src/test/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManagerTest.java
refactor: modularize code around the AppBundlesVisibilityManager, while adding unit tests to it. 
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-246](https://aptoide.atlassian.net/browse/MOB-246)
Tickets related to this pull-request: [MOB-246](https://aptoide.atlassian.net/browse/MOB-246)
> [MOB-246] adding tests to AppBundlesVisibilityManager

- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
This PR removes the "app_shortcut" tag from previous context;
No
Tickets related to this pull-request: [MOB-501](https://aptoide.atlassian.net/browse/MOB-501)
> [MOB-501] Removed "app_shortcut" previous context;

- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/app/AppViewModelManager.java
- app/src/main/java/cm/aptoide/pt/app/DownloadStateParser.java
- app/src/main/java/cm/aptoide/pt/editorial/EditorialDownloadModel.java
- app/src/main/java/cm/aptoide/pt/editorial/EditorialManager.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppMapper.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionViewAppMapper.java
- app/src/main/java/cm/aptoide/pt/wallet/WalletAppProvider.kt
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallManager.kt
This PR aims giving feedback to the user while we are moving the files.
No
Perform downloads of big apps on all views where downloads are possible. Check that at the end of the download there is feedback while it is moving the files.
Tickets related to this pull-request: [MOB-563](https://aptoide.atlassian.net/browse/MOB-563)
**Questions:**
> [MOB-563] Feedback for moving files

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/install/FilePathProvider.kt
- app/src/main/java/cm/aptoide/pt/install/InstallAppSizeValidator.kt
- app/src/main/java/cm/aptoide/pt/install/InstallManager.java
- downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java
- downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/PathProvider.java
This PR aims at adding the file check (see if files is already downloaded before checking if there is enough space to download)
This is only contemplating fully downloaded apps and not temporary ones.
No
Perform a download of any app. Then fill your device up (or on the getAvailablespace() method in the (InstalledAppSizeValidator.kt) class set it to return 0 and then (with the fully downloaded apk), try installing it again. Check if it just pops the install dialog instead of showing the no space dialog.
Tickets related to this pull-request: [MOB-623](https://aptoide.atlassian.net/browse/MOB-623)
**Questions:**
Does this add new …
> [MOB-623] File Check

- app/src/main/java/cm/aptoide/pt/comments/view/CommentWidget.java
- build.gradle
This PR aims at increasing facebook sdk version for vanilla.
No
Open app try logging in with facebook.
Tickets related to this pull-request: [MOB-596](https://aptoide.atlassian.net/browse/MOB-596)
**Questions:**
> [MOB-596] Update Facebook

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- aptoide-authentication-core/src/main/kotlin/com/aptoide/authentication/network/RemoteAuthenticationService.kt
Title
No
Check if authorize calls go with the right user agent
Tickets related to this pull-request: [MOB-555](https://aptoide.atlassian.net/browse/MOB-555)
> [MOB-555] fix: inject okhttp client for the right user-agent.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
This PR aims at fixing facebook login integration, allowing to log-in even without the facebook installed app. We were missing the custom tabs manifest entry.
No
Run the app in prodRelease and try to login with and without the facebook app installed on your phone.
Tickets related to this pull-request: [MOB-596](https://aptoide.atlassian.net/browse/MOB-596)
**Questions:**
> [MOB-596] Increase Facebook

- aptoide-views/src/main/res/layout/updates_notification_with_icons.xml
Removed line from xml breaking first icon;
> Removed line from xml breaking icon in notification;

- app/build.gradle
- dataprovider/build.gradle
This PR aims at fixing the app crashing on devices <21
No
Open the app on android < 21 and check that everything is ok. Also give a small check on the app to see if nothing broke.
Tickets related to this pull-request: [MOB-890](https://aptoide.atlassian.net/browse/MOB-890)
**Questions:**
> [HOTFIX/MOB-890] Fix crash on devices < 21

- app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
- app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
- app/src/main/java/cm/aptoide/pt/editorial/EditorialAnalytics.java
- app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
- app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListAnalytics.kt
- app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListPresenter.kt
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsAnalytics.java
- app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallAnalytics.kt
- app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
Adds a new param app_version_code to the rakam download event.
No
Test different Download entry points to see if the rakam download event is sending the version code of the app.
Tickets related to this pull-request: [MOB-887](https://aptoide.atlassian.net/browse/MOB-887)
> [Task/MOB-887] More info invalidappexception for Rakam Download event 

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/search/SearchManager.java
- app/src/main/java/cm/aptoide/pt/search/SearchRepository.kt
- app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
This PR aims at fixing a bug we had on search where if you rotated the screen you would get an empty view.
No
Open app, perform a search and rotate the screen. Check that it has the same results. Also, test other flows, like opening appview and coming back, opening another tab and pressing back (see that it does not go to the results).
Tickets related to this pull-request: [MOB-1034](https://aptoide.atlassian.net/browse/MOB-1034)
**Questions:**
> [HOTFIX/MOB-1034] Search rotating screen fix

- app/src/main/java/cm/aptoide/pt/updates/UpdateRepository.java
This PR aims at fixing a bug we had where we if we excluded an update, on the next load (example pull to refresh, ou listappsupdates request) the list would be empty.
No
Exclude an update, do pull to refresh
Tickets related to this pull-request: [APP-100](https://aptoide.atlassian.net/browse/APP-100)
**Questions:**
> [APP-100] Fix excluding updates

- app/src/main/java/cm/aptoide/pt/app/view/donations/view/DonateDialogFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/donations/view/DonateDialogPresenter.java
- app/src/main/res/layout/appview_donations_dialog.xml
- app/src/main/res/layout/fragment_appview_donations_list.xml
- downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java
This PR aims at fixing some of the issues on the donations dialog.
No
Try to perform a donation with 0 as value. Check that the error is correctly shown.
Also, try devices with smaller screensizes to see that the buttons are not cut off.
Tickets related to this pull-request: [APP-66](https://aptoide.atlassian.net/browse/APP-66)
**Questions:**
> [APP-66] Donations dialog errors

- app/src/main/java/cm/aptoide/pt/home/bundles/appcoins/FeaturedAppcViewHolder.kt
- app/src/main/res/layout/bundle_featured_appcoins.xml
Make the whole featured AppCoins card clickable not only the flair.
No
Test all Featured AppCoins bundle interactions.
Tickets related to this pull-request: [APP-124](https://aptoide.atlassian.net/browse/APP-124)
> [APP-124] feature: make the whole featured AppCoins card clickable

- app/build.gradle
This PR aims at fixing the deeplink of aptoide website, by removing / and adding support to www.aptoide.com
No
Run the deeplink reported in the ticket without the / and check that it works.
Tickets related to this pull-request: [APP-190](https://aptoide.atlassian.net/browse/APP-190)
**Questions:**
> [APP-190] Fix Aptoide website deeplink

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
- app/src/main/java/cm/aptoide/pt/FirstLaunchManager.kt
- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
- app/src/main/java/cm/aptoide/pt/notification/PullingContentService.java
- app/src/main/java/cm/aptoide/pt/presenter/MainPresenter.java
- app/src/main/java/cm/aptoide/pt/presenter/MainView.java
- app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
- app/src/main/java/cm/aptoide/pt/view/MainActivity.java
- app/src/main/res/drawable/updates_badge_circle_small.xml
- app/src/main/res/layout/updates_badge.xml
- aptoide-views/src/main/res/drawable-night/updates_badge_circle.xml
- aptoide-views/src/main/res/drawable-night/updates_badge_circle_small.xml
- aptoidepreferences/src/main/java/cm/aptoide/pt/preferences/secure/SecureKeys.java
- aptoidepreferences/src/main/java/cm/aptoide/pt/preferences/secure/SecurePreferences.java
This PR aims at changing the updates logic. Now we are only making the updates request when the user navigates to the apps BN section. We also had to change the size of the updates badge.
Also took the chance to remove an unnecessary call.
No
Open the app, check that there are no updates and the badge is still shown to hook the user. Then navigate to apps, the request will be made and it will show the updates number. On the next sessions, everything should be normal.
Tickets related to this pull-request: [APP-139](https://aptoide.atlassian.net/browse/APP-139)
[APP-144](https://aptoide.atlassian.net/browse/APP-144)
**Questions:** …
> [APP-139/144] Updates request changes

- app/src/main/java/cm/aptoide/pt/socialmedia/SocialMediaNavigator.kt
This PR aims at changing the instagram url from Aptoide, since the account name was changed.
No
Go to a view where we have social media promotion card and click on Instagram. Notice that it is navigating to the correct url.
Tickets related to this pull-request: [APP-283](https://aptoide.atlassian.net/browse/APP-283)
**Questions:**
> [APP-283] Social Media Link

- app/src/main/java/cm/aptoide/pt/socialmedia/SocialMediaAnalytics.kt
This PR aims at fixing the social media events.
No
Open a view where this feature was implemented (example, AppCoins detail info view), click on one of the social media platforms and check that the event was correctly sent to facebook (charles).
Tickets related to this pull-request: [APP-135](https://aptoide.atlassian.net/browse/APP-135)
**Questions:**
> [APP-135] Fix Promote Social Media Events

- app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
- app/src/main/res/values/strings.xml
This PR aims at changing the delete account URL. This will redirect us to a page that is still being implemented hence why it can't be tested yet.
So maybe it shouldn't be accepted until the page is fully implemented by the web team.
No
Login and try to delete the account. DON'T do it an account that you don't want to delete.
Tickets related to this pull-request: [APP-333](https://aptoide.atlassian.net/browse/APP-333)
**Questions:**
> [APP-333] Update delete account link

- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
Tickets related to this pull-request: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
**Questions:**
> Task: remove blank lines.

- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
This PR aims at fixing the broken tests due to the development of the app bundles support features.
No
Run the tests
Tickets related to this pull-request: [APP-552](https://aptoide.atlassian.net/browse/APP-552)
**Questions:**
> [APP-552] Fix tests

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/abtesting/ABTestService.java
- app/src/main/java/cm/aptoide/pt/ads/AdsExperiment.kt
- app/src/main/java/cm/aptoide/pt/ads/MoPubAdsManager.java
- app/src/main/java/cm/aptoide/pt/ads/MoPubAnalytics.java
- app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
- app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
This PR aims at implementing the new ads super property values and the ab test for showing ads or not.
No
Open the app and check the ab test assignments. Also confirm that the super property is being sent correctly.
Tickets related to this pull-request: [APP-608](https://aptoide.atlassian.net/browse/APP-608)
**Questions:**
> [APP-608] Ads ab test

- app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
This PR aims at fixing a bug on apps where the user would not see progress if it was the 1st session for updates.
No
Open the app as a first session (clear cache before it, for example), and try to update any app on apps. Check that you see progress.
Tickets related to this pull-request: [APP-948](https://aptoide.atlassian.net/browse/APP-948)
**Questions:**
> [APP-948] Progress bar update

- app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
- app/src/main/java/cm/aptoide/pt/home/bundles/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/home/bundles/base/ActionItem.java
- app/src/main/java/cm/aptoide/pt/home/bundles/promotional/ComingSoonViewHolder.kt
- app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/ActionItemData.java
This PR aims at implementing the proposed api changes for the promotionals app coming soon card response.
We needed to add the package name and feature graphic. This is under development from the MS team, so you will need rewrites to test this.
No
Test all promotional cards to make sure nothing broke. Also test that it shows a feature graphic on the card. Also test the notification and cancelation flow.
Tickets related to this pull-request: [APP-901](https://aptoide.atlassian.net/browse/APP-901)
**Questions:**
> [APP-901] Implement api changes

- app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
- app/src/main/java/cm/aptoide/pt/home/bundles/BundlesResponseMapper.java
- app/src/main/java/cm/aptoide/pt/home/more/apps/ListAppsMoreManager.kt
- app/src/main/java/cm/aptoide/pt/home/more/apps/ListAppsMoreRepository.kt
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/GetStoreWidgets.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetEskillsAppsRequest.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java
- dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/WSWidgetsUtils.java
This PR aims at implementing the eskills changes coming from getStoreWidgets
No
Increase your version code to a number above 12000 (which the new web changes will apply) and check that the eskills bundle shows up.
Tickets related to this pull-request: [APP-993](https://aptoide.atlassian.net/browse/APP-993)
**Questions:**
> [APP-993] Eskills Widget changes

- app/src/main/java/cm/aptoide/pt/home/bundles/BundlesResponseMapper.java
This PR aims at fixing a null pointer exception caused by the webservices
No
Open home and check that everything is ok and that you see the highlighted bundle
Tickets related to this pull-request: [APP-1097](https://aptoide.atlassian.net/browse/APP-1097)
**Questions:**
> [APP-1097] Ads Highlighted bug

- app/build.gradle
- app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java
- app/src/main/java/cm/aptoide/pt/app/view/donations/utils/GenericPaymentIntentBuilder.java
Fixed login layout bug when the user did not select the terms and conditions checkbox.
No
Go to login page and try to authenticate with any of the options without accepting the terms and conditions.
Tickets related to this pull-request: [APP-1361](https://aptoide.atlassian.net/browse/APP-1361)
**Questions:**
> [APP-1361] Fixed login layout when user does not select TC.

- aptoide-authentication-core/build.gradle
- aptoide-views/build.gradle
- aptoide-views/src/main/java/cm/aptoide/aptoideviews/downloadprogressview/DownloadProgressView.kt
- aptoide-views/src/main/java/cm/aptoide/aptoideviews/downloadprogressview/StateMachine.kt
- gradle.properties
To make CI builds work again.
No
- By commits
CI should build without errors
No related ticket
> Fix builds

- .gitmodules
- app/build.gradle.kts
- app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/di/RepositoryModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/service/AptoideAppsNetworkService.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/service/WidgetsNetworkService.kt
- settings.gradle.kts
This PR aims at updating cobrand job to match the new variables.
Also using the MARKET_NAME gradle properties value to inject the store name to filter some requests as requested.
Some bundle content urls from getStoreWidgets are coming with a different store_id. I still added the store_name tag.
No
Run the app in cobrand and check that everything is correct (new icon, appname)
Check the okhttp request logs on console to make sure it is added on all app requests.
Tickets related to this pull-request: [DT-22](https://aptoide.atlassian.net/browse/DT-22)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new …
> [DT-22] Cobrand job

- buildSrc/src/main/kotlin/KeyHelper.kt
One more fix.
No
- No need
No need
Tickets related to this pull-request: [DT-22](https://aptoide.atlassian.net/browse/DT-22)
> [DT-22] Fix CI builds

- .gitmodules
- aptoide-analytics-default-implementation/src/main/java/cm/aptoide/analytics/implementation/network/AnalyticsEventRequestBody.java
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/base_response/BaseV7DataListResponse.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/base_response/BaseV7ListResponse.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/base_response/BaseV7Response.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/base_response/DataList.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/model/AppCoins.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/model/File.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/model/Malware.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/model/Rating.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/model/Stats.kt
- feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/data/network/ReactionsJson.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/AppJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/BaseV7DataListResponse.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/BaseV7Response.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/DataList.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/GetAppResponse.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/Layout.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetTypeJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetsJSON.kt
- feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/data/CampaignsResponseJson.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/network/EditorialDetailJson.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/network/model/EditorialJson.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/model/SearchAppListJson.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/response/SearchAutoCompleteSuggestionsResponse.kt
- finish-setup.sh
- push-all.sh
Add some useful scripts and keep desirializable classes from minification. 
No
- No need
No need
Tickets related to this pull-request: [DT-22](https://aptoide.atlassian.net/browse/DT-22)
> [DT-22] Finish build setup

- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
- feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/di/CampaignsModule.kt
This PR aims at replacing the base domain for campaigns requests
No
Open app, go to an appview and confirm that the requests are pointing to this subdomain
Tickets related to this pull-request: [DT-36](https://aptoide.atlassian.net/browse/DT-36)
**Questions:**
> [DT-36] Get Ads new domain

- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideBundlesRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetActionEventName.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetActionEventType.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetsJSON.kt
This PR aims to fix ofuscation of widget types and layout.
No
run the app on release and check that everything is ok.
Tickets related to this pull-request: [DT-37](https://aptoide.atlassian.net/browse/DT-37)
**Questions:**
> [DT-37] Fix proguard

- push-submodules-refs.sh
Change the script routine policy + check the changes in the submodule.
No
Nothing to test
Tickets related to this pull-request: [DT-43](https://aptoide.atlassian.net/browse/DT-43)
> [DT-43] Adjust the script

- settings.gradle.kts
Fix the crashes.
No
Run the app, try to install
Tickets related to this pull-request: [DT-57](https://aptoide.atlassian.net/browse/DT-57)
> [DT-57] Fix crashes and add credentials for the prod release builds

- app/src/main/java/cm/aptoide/pt/apps/AptoideMyAppsBundleProvider.kt
- app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideBundlesRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/MyAppsApp.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/MyAppsBundleProvider.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/di/RepositoryModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/Bundle.kt
This PR aims at implementing the my apps bundle, first screen logic.
No
Open the app and check that you see the my apps bundle with 2 random icons of 2 installed apps.
Tickets related to this pull-request: [DT-46](https://aptoide.atlassian.net/browse/DT-46)
**Questions:**
> [DT-46] my apps

- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideBundlesRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideWidgetsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/model/WidgetsJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/Bundle.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/Widget.kt
This PR aims at implementing the bundle background instead of the graphic field.
No
Open the app and test if the background is correct. Note that api still didnt update the image
Tickets related to this pull-request: [DT-58](https://aptoide.atlassian.net/browse/DT-58)
**Questions:**
> [DT-58] Bundle background

- app/src/main/java/cm/aptoide/pt/appview/AptoideTabsListProvider.kt
- app/src/main/java/cm/aptoide/pt/di/UseCaseModule.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppGridView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/BundlesView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/FeatureGraphicView.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/data/AptoideAppViewRepository.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/di/RepositoryModule.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/domain/model/RelatedCard.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/domain/usecase/GetRelatedContentUseCase.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewTab.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewUiState.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewView.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewViewModel.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/CustomScrollableTabRow.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/RelatedContentView.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/TabsListProvider.kt
Improvements to the App View UI to match the figma design. Some changes were to add flexibility to the common UI code in order to allow different ui implementation for the gameshub product.
No
See if UI matches figma files and info in ticket + UI notes from confluence (all in ticket)
Tickets related to this pull-request: [DT-45](https://aptoide.atlassian.net/browse/DT-45)
> [DT-45] make the app view layout according to the figma requirements.

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/Mappers.kt
Add cancelling apps installation.
No
Start app installation, then cancel it immediately, after navigation back and forth or after app restart
Tickets related to this pull-request: [DT-63](https://aptoide.atlassian.net/browse/DT-63)
> [DT-63] Cancel installation

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewUiState.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewViewModel.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/Mappers.kt
Fix the install button states changes issue for update failures.
Flow on how to test this or QA Tickets related to this use-case: [DT-270](https://aptoide.atlassian.net/browse/DT-270)
Tickets related to this pull-request: [DT-270](https://aptoide.atlassian.net/browse/DT-270)
[DT-270]: https://aptoide.atlassian.net/browse/DT-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-270]: https://aptoide.atlassian.net/browse/DT-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-270] Install button states controls

- buildSrc/src/main/kotlin/LibraryDependency.kt
Increases the accompanist pager dependency to the latest stable version, which does not crash on keyboard navigation.
No
- Test navigating out of the auto-carousel (Just arrived bundle and publisher takeover) using the keyboard up and down arrows.
- Also test navigating inside the auto-carousel with the arrow keys as well.
- Test the auto-carousel with the normal finger scroll just to check that nothing breaks.
Tickets related to this pull-request: [DT-273](https://aptoide.atlassian.net/browse/DT-273)
[DT-273]: https://aptoide.atlassian.net/browse/DT-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> [DT-273] Fix Auto-Carousel keyboard navigation

- app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
The goal of this PR is to force the name of the store to lower case. 
I used Locale.ROOT to be locale insensitive.
No
Tickets related to this pull-request: [DT-376](https://aptoide.atlassian.net/browse/DT-376)
[DT-376]: https://aptoide.atlassian.net/browse/DT-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-376] Force the store name to lower case

- app/src/main/java/cm/aptoide/pt/apps/WidgetsNetworkService.kt
- app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
The query param aptoide_vercode for getWidgets and getStoreWidgets was hardcoded. The main goal of this task was to change it to the real version code of the app.
No
Tickets related to this pull-request: [APP-384](https://aptoide.atlassian.net/browse/DT-384)
[APP-384]: https://aptoide.atlassian.net/browse/APP-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-384] Change aptoide_vercode query param to real version code

- buildSrc/src/main/kotlin/LibraryDependency.kt
- Declare the lottie-compose dependency in the project to allow the implementation of lottie animations with Jetpack Compose.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-383](https://aptoide.atlassian.net/browse/DT-383)
Tickets related to this pull-request: [DT-383](https://aptoide.atlassian.net/browse/DT-383)
[DT-383]: https://aptoide.atlassian.net/browse/DT-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-383]: https://aptoide.atlassian.net/browse/DT-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> [DT-383] Add lottie-compose dependency

- app/src/main/java/cm/aptoide/pt/di/AppModule.kt
- app/src/main/java/cm/aptoide/pt/firebase/FirebaseInfoProvider.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/di/RepositoryModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/firebase/AptoideFirebaseInfoProvider.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/network/service/AptoideAppsNetworkService.kt
Added the firebase token to the getAppsCategories endpoint.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-396](https://aptoide.atlassian.net/browse/DT-396)
Tickets related to this pull-request: [DT-396](https://aptoide.atlassian.net/browse/DT-396)
[DT-396]: https://aptoide.atlassian.net/browse/DT-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-396]: https://aptoide.atlassian.net/browse/DT-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-396] Added Firebase token management

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewViewModel.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/WalletInstallationViewModel.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
This aims at implementing the bottomsheet after clicking on install for an app with appcoins on the rest of the app.
On this repo, we had to change the getApp request to not be tied to a specific store, as for example, the wallet getApp request should be done with no store.
No
Install an app with appcoins and check if the bottomsheet shows
Tickets related to this pull-request: [DT-417](https://aptoide.atlassian.net/browse/DT-417)
**Questions:**
[DT-417]: https://aptoide.atlassian.net/browse/DT-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
> [DT-417] wallet install rest of app

- buildSrc/src/main/kotlin/LibraryDependency.kt
- Declares the accompanist permissions library as a dependency
No
Flow on how to test this or QA Tickets related to this use-case: [DT-390](https://aptoide.atlassian.net/browse/DT-390)
Tickets related to this pull-request: [DT-390](https://aptoide.atlassian.net/browse/DT-390)
[DT-390]: https://aptoide.atlassian.net/browse/DT-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-390]: https://aptoide.atlassian.net/browse/DT-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-390] Declare accompanist permissions library dependency

- .gitmodules
- buildSrc/src/main/kotlin/LibraryDependency.kt
- buildSrc/src/main/kotlin/ModuleDependency.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/BundlesView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/AppJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppGraphicView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppGridView.kt
- settings.gradle.kts
- Imports the most recent version of the library android-youtube-player as a module.
- Alters the necessary code in the new youtube player module to meet our requirements.
- Updates the android lifecycle dependency to a more recent but yet compatible version.
- Added new parameters related to videos to the AppJSON and App business model classes.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-325](https://aptoide.atlassian.net/browse/DT-325)
Tickets related to this pull-request: [DT-325](https://aptoide.atlassian.net/browse/DT-325)
[DT-325]: …
> [DT-325] Add android youtube player and video related parameters

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/BundlesView.kt
- feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/presentation/ViewModelProvider.kt
- feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/ui/ReactionsView.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/RelatedContentView.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/ViewModelProvider.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt
Fix the Lint warnings about composable functions naming.
No
Essentially it is a regression
Tickets related to this pull-request: [DT-442](https://aptoide.atlassian.net/browse/DT-442)
PRs related to this one: [#160](https://github.com/Aptoide/aptoide-client-dt/pull/160)
[DT-442]: https://aptoide.atlassian.net/browse/DT-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-442] Composable function naming convention

- buildSrc/src/main/kotlin/LibraryDependency.kt
Change navigation logic a bit to show bottom bar only on level 1 screens.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-409](https://aptoide.atlassian.net/browse/DT-409)
Tickets related to this pull-request: [DT-409](https://aptoide.atlassian.net/browse/DT-409)
PRs related to this one: [#163](https://github.com/Aptoide/aptoide-client-dt/pull/163)
[DT-409]: https://aptoide.atlassian.net/browse/DT-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-409]: …
> [DT-409] Bottom navigation graph logic

- app/src/main/java/cm/aptoide/pt/AptoideApplication.kt
- app/src/main/java/cm/aptoide/pt/analytics/Analytics.kt
- app/src/main/java/cm/aptoide/pt/analytics/presentation/AnalyticsViewModel.kt
- app/src/main/java/cm/aptoide/pt/analytics/presentation/ThemeListener.kt
- app/src/main/java/cm/aptoide/pt/di/AppModule.kt
- app/src/main/java/cm/aptoide/pt/home/BottomNavigationView.kt
Add analytics functions and theme listener usage to Aptoide Vanilla V10
No
Flow on how to test this or QA Tickets related to this use-case: [DT-336](https://aptoide.atlassian.net/browse/DT-336)
Tickets related to this pull-request: [DT-336](https://aptoide.atlassian.net/browse/DT-336)
[DT-336]: https://aptoide.atlassian.net/browse/DT-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-336]: https://aptoide.atlassian.net/browse/DT-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-336] Analytics

- app/src/main/java/cm/aptoide/pt/home/BottomNavigationView.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/EditProfileView.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/MyProfileView.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileButton.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
Refactor the profile view following the settings view structure
No
Flow on how to test this or QA Tickets related to this use-case: [DT-336](https://aptoide.atlassian.net/browse/DT-336)
Tickets related to this pull-request: [DT-336](https://aptoide.atlassian.net/browse/DT-336)
[DT-336]: https://aptoide.atlassian.net/browse/DT-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-336]: https://aptoide.atlassian.net/browse/DT-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-336] Profile View Refactor

- buildSrc/src/main/kotlin/LibraryDependency.kt
- Declares Kotlin WorkManage as a dependency
No
Flow on how to test this or QA Tickets related to this use-case: [DT-411](https://aptoide.atlassian.net/browse/DT-411)
Tickets related to this pull-request: [DT-411](https://aptoide.atlassian.net/browse/DT-411)
[DT-411]: https://aptoide.atlassian.net/browse/DT-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-411]: https://aptoide.atlassian.net/browse/DT-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-411] Declare WorkManager dependency

- buildSrc/src/main/kotlin/LibraryDependency.kt
- buildSrc/src/main/kotlin/plugin/HiltPlugin.kt
- Declares hilt compiler and hilt work dependencies
No
Flow on how to test this or QA Tickets related to this use-case: [DT-453](https://aptoide.atlassian.net/browse/DT-453)
Tickets related to this pull-request: [DT-453](https://aptoide.atlassian.net/browse/DT-453)
[DT-453]: https://aptoide.atlassian.net/browse/DT-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-453]: https://aptoide.atlassian.net/browse/DT-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-453] Declare hilt compiler and hilt work dependencies

- buildSrc/src/main/kotlin/LibraryDependency.kt
- feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewScreen.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialsCardView.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchView.kt
This PR replaces the Image widget with the Coil AsyncImage
No
Flow on how to test this or QA Tickets related to this use-case: [DT-485](https://aptoide.atlassian.net/browse/DT-485)
Tickets related to this pull-request: [DT-485](https://aptoide.atlassian.net/browse/DT-485)
[DT-485]: https://aptoide.atlassian.net/browse/DT-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-485]: https://aptoide.atlassian.net/browse/DT-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT 485] Replace Image with Coil AsyncImage

- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/BundlesView.kt
This PR replaces the new GamesMatch drawables by ImageVectors
No
Flow on how to test this or QA Tickets related to this use-case: [DT-493](https://aptoide.atlassian.net/browse/DT-493)
Tickets related to this pull-request: [DT-493](https://aptoide.atlassian.net/browse/DT-493)
[DT-493]: https://aptoide.atlassian.net/browse/DT-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-493]: https://aptoide.atlassian.net/browse/DT-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT 493] Change Image to use imageVector instead of painter

- aptoide-account-manager/build.gradle
- aptoide-installer/build.gradle.kts
- buildSrc/src/main/kotlin/LibraryDependency.kt
- buildSrc/src/main/kotlin/plugin/AndroidModulePlugin.kt
- buildSrc/src/main/kotlin/plugin/ComposablePlugin.kt
This PR was created the fix the issue in building the release in jenkins.
I had to add a library to fix this issue. According to the documentation its a false positive.
I also reorganized the lint in the application and libraries modules.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-474](https://aptoide.atlassian.net/browse/DT-474)
Tickets related to this pull-request: [APP-474](https://aptoide.atlassian.net/browse/DT-474)
[APP-474]: https://aptoide.atlassian.net/browse/APP-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [DT 474] Restore release lint checks

- feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchViewModel.kt
Fixed a crash when an endpoint was failing on search.
No
> [DT 519] Fixed crash on Search

- app/src/main/java/cm/aptoide/pt/home/BottomNavigationView.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/dialogs/AptoideDialog.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/icons/AptoideTVIcon.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/icons/FacebookIcon.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/icons/InstagramIcon.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/icons/TwitterIcon.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/theme/Color.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/theme/Gradients.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/theme/Theme.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/EditProfileView.kt
- feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
- feature-settings/src/main/java/cm/aptoide/pt/settings/presentation/SendFeedbackView.kt
- feature-settings/src/main/java/cm/aptoide/pt/settings/presentation/SettingsView.kt
Fixes the UI alignment, color, style, etc. of any component in any of the My Profile views, that includes: Profile view; Edit Profile view; Settings view; Send Feedback view.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-505](https://aptoide.atlassian.net/browse/DT-505)
Tickets related to this pull-request: [DT-505](https://aptoide.atlassian.net/browse/DT-505)
[DT-505]: https://aptoide.atlassian.net/browse/DT-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-505]: https://aptoide.atlassian.net/browse/DT-505?atlOrigin=eyJpIjoiNWRkNT …
> [DT-505] Profile UI Review

- app/src/main/java/cm/aptoide/pt/home/BottomNavigationView.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/AptoideWidgetsRepository.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/WidgetsRepository.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/BundlesView.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/BundlesViewModel.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/ViewModelProvider.kt
Adds the filter to the bottom Navigator for the Games and Apps tabs.
**Warning**: GH won't run after this PR is approved, in order to run review the following PR: [#229](https://github.com/Aptoide/aptoide-client-dt/pull/229) 
No
Flow on how to test this or QA Tickets related to this use-case: [DT-522](https://aptoide.atlassian.net/browse/DT-522)
Tickets related to this pull-request: [DT-522](https://aptoide.atlassian.net/browse/DT-522)
PRs related to this one: [#229](https://github.com/Aptoide/aptoide-client-dt/pull/229)
[DT-522]: …
> [DT-522] Menu Games/Apps Filter

- feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/data/di/RepositoryModule.kt
This PR aims at changing the endpoint for reactions
No
Open the app, perform a reaction and check that everything is ok.
Tickets related to this pull-request: [DT-481](https://aptoide.atlassian.net/browse/DT-481)
**Questions:**
[DT-481]: https://aptoide.atlassian.net/browse/DT-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-481] Change reactions endpoint

- app/proguard-rules.pro
- buildSrc/src/main/kotlin/plugin/AndroidModulePlugin.kt
Fixes a crash on firebase
No
Flow on how to test this or QA Tickets related to this use-case: [DT-562](https://aptoide.atlassian.net/browse/DT-562)
Tickets related to this pull-request: [DT-562](https://aptoide.atlassian.net/browse/DT-562)
[DT-562]: https://aptoide.atlassian.net/browse/DT-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-562]: https://aptoide.atlassian.net/browse/DT-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT 562] Fix firebase crash

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/UserActionHandler.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/domain/UrlsCache.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/ChannelExtensions.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/LoremIpsumExtensions.kt
- feature-flags/src/main/java/cm/aptoide/pt/feature_flags/domain/FeatureFlags.kt
- feature_apps/build.gradle.kts
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_categories/build.gradle.kts
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/domain/Category.kt
Add feature flag to the GamesMatch. 
Had to refactor the code first to consolidate the logic and avoid bugs.
Yes
Flow on how to test this or QA Tickets related to this use-case: [DT-673](https://aptoide.atlassian.net/browse/DT-673)
Tickets related to this pull-request: [DT-673](https://aptoide.atlassian.net/browse/DT-673)
PRs related to this one: [#275](https://github.com/Aptoide/aptoide-client-dt/pull/275)
[DT-673]: https://aptoide.atlassian.net/browse/DT-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-673]: …
> [DT-673] Games match feature flag

- app/src/main/java/cm/aptoide/pt/context/PayloadMapperImpl.kt
- app/src/main/java/cm/aptoide/pt/context/di/PayloadDataModule.kt
- aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/AptoideTaskInfoRepository.kt
- aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/TaskInfoDatabase.kt
- aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/model/TaskInfoData.kt
- aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/di/TaskInfoModule.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/domain/model/Mappers.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/domain/model/PayloadMapper.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
- feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/dto/InstallPackageInfo.kt
This PR was created to store metadata on the installation task info.
For this it was necessary to:
1. Extract the campaign id from the impressions or clicks url
2. Store the new metadata into the task info database
3. Create a new ContextDataProvider that stores data which is common between analytics and the new metadata data
Yes
Flow on how to test this or QA Tickets related to this use-case: [APP-666](https://aptoide.atlassian.net/browse/DT-666)
Tickets related to this pull-request: [APP-666](https://aptoide.atlassian.net/browse/DT-666)
[APP-666]: …
> [DT-666] Send meta data in SL

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/AndroidConfig.kt
- buildSrc/src/main/kotlin/GradleDependency.kt
- buildSrc/src/main/kotlin/LibraryDependency.kt
This PR adds the widget for GH for cricket.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-697](https://aptoide.atlassian.net/browse/DT-697)
Tickets related to this pull-request: [DT-697](https://aptoide.atlassian.net/browse/DT-697)
[DT-697]: https://aptoide.atlassian.net/browse/DT-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-697]: https://aptoide.atlassian.net/browse/DT-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-697] Create cricket empty widget

- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/MyGamesApp.kt
- feature_editorial/build.gradle.kts
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/Article.kt
- Create randoms extension file in dedicated extensions module.
- Moves the random string getter to the new file.
- Adds the extensions dependency to the feature_apps module.
- Add random getter for MyGames app.
No
- See by commit.
Flow on how to test this or QA Tickets related to this use-case: [DT-575](https://aptoide.atlassian.net/browse/DT-575)
Tickets related to this pull-request: [DT-575](https://aptoide.atlassian.net/browse/DT-575)
[DT-575]: https://aptoide.atlassian.net/browse/DT-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-575]: …
> [DT-575] Create random extensions and random MyGames app getter

- app/src/main/java/cm/aptoide/pt/search/presentation/SearchView.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchViewModel.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/utils/SearchUtils.kt
- Refactors the search view and removes unnecessary code.
- Adds search utils for queries in the search feature module.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-535](https://aptoide.atlassian.net/browse/DT-535)
Tickets related to this pull-request: [DT-535](https://aptoide.atlassian.net/browse/DT-535)
[DT-535]: https://aptoide.atlassian.net/browse/DT-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-535]: https://aptoide.atlassian.net/browse/DT-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> [DT-535] Refactor search v10

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideDownloader.kt
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/textformatter/TextFormatter.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/domain/model/Mappers.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/LongExtensions.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/App.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/RealApp.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/RealInstallManager.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/Task.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/workers/PackageDownloader.kt
- install-manager/src/test/java/cm/aptoide/pt/install_manager/TestData.kt
- Adds support to deferred app installations, by adding the necessary logic in the install manager and App and Task implementations.
- Adds long primitive type extension functions related to dealing with app sizes.
No
- See by commit.
Flow on how to test this or QA Tickets related to this use-case: [DT-529](https://aptoide.atlassian.net/browse/DT-529)
Tickets related to this pull-request: [DT-529](https://aptoide.atlassian.net/browse/DT-529)
[DT-529]: https://aptoide.atlassian.net/browse/DT-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-529]: …
> [DT-529] Add support for deferred install tasks and add long extensions

- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/data/AptoideSearchRepository.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/di/RepositoryModule.kt
Fix 2-touch attribution on missing cases
No
Flow on how to test this or QA Tickets related to this use-case: [DT-686](https://aptoide.atlassian.net/browse/DT-686)
Tickets related to this pull-request: [DT-686](https://aptoide.atlassian.net/browse/DT-686)
[DT-686]: https://aptoide.atlassian.net/browse/DT-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-686]: https://aptoide.atlassian.net/browse/DT-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-686] Fix 2 touch attribution missing cases

- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/manager/PaymentManager.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/manager/domain/PurchaseRequest.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/payment/PaymentMethod.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/payment/credit_card/CreditCardPaymentMethod.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/payment/credit_card/CreditCardPaymentMethodFactory.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/presentation/PaymentMethodsUiState.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/presentation/PaymentMethodsViewModel.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/presentation/ViewModelProvider.kt
- payments/osp-handler/src/main/AndroidManifest.xml
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentActivity.kt
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentScreenContentProvider.kt
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/handler/OSPHandler.kt
- payments/osp-handler/src/main/res/values/styles.xml
This PR aims at implementing the initial payments UI. This currenytly only contains the portrait one as the landscape one is being developed, but it should be quick. We separated just to avoid having other people waiting.
Database changed?
No
MainPaymentsView.kt
Run the app ricardo developed, send an app link and check it opens ok. Remeber you need to have a release version from GH.
Tickets related to this pull-request: [DT-709](https://aptoide.atlassian.net/browse/DT-709)
**Questions:**
[DT-709]: https://aptoide.atlassian.net/browse/DT-709?atlOrigin=eyJpIjoiNWRkNT …
> [DT-709] Build initial payments UI

- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentActivity.kt
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentScreenContentProvider.kt
This PR is the continuation of [709](https://github.com/Aptoide/aptoide-client-v8/pull/1709).
Implements the payments ui in landscape.
No
Use Ricardo app to simulate a payment with trivial drive. Check the layout in landscape.
Tickets related to this pull-request: [DT-709](https://aptoide.atlassian.net/browse/DT-709)
**Questions:**
[DT-709]: https://aptoide.atlassian.net/browse/DT-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-801] build landscape payments ui

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/manager/domain/PurchaseRequest.kt
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/handler/OSPHandler.kt
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
Tickets related to this pull-request: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
**Questions:**
> [DT-710] Wallet installation flow

- payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/transaction/Transaction.kt
- payments/osp-handler/build.gradle.kts
- payments/osp-handler/src/main/AndroidManifest.xml
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentActivity.kt
- payments/osp-handler/src/main/java/cm/aptoide/pt/osp_handler/PaymentScreenContentProvider.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/CreditCardPaymentMethod.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/CreditCardTransaction.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/di/NetworkModule.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/presentation/AdyenCreditCardScreenUiState.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/AdyenV2Repository.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/model/AdyenPayment.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/model/TransactionResponse.kt
Added redirect and 3DS (not handling the result yet)
No
- start by testing the flow of a normal card, than a card with redirect
Flow on how to test this or QA Tickets related to this use-case: [DT-715](https://aptoide.atlassian.net/browse/DT-715)
Flow on how to test this or QA Tickets related to this use-case: [DT-714](https://aptoide.atlassian.net/browse/DT-714)
Tickets related to this pull-request: [DT-715](https://aptoide.atlassian.net/browse/DT-715)
Tickets related to this pull-request: [DT-714](https://aptoide.atlassian.net/browse/DT-714)
[DT-715]: …
> [DT-714 and DT-715] Add Redirect and 3DS

- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/AdyenExceptions.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/AdyenV2Repository.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/model/ResponseErrorBody.kt
- payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/model/TransactionResponse.kt
- Adds all the necessary exceptions to use in case of payment failures.
- Adds all the logic to extract and map the payment errors to the corresponding exceptions.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-719](https://aptoide.atlassian.net/browse/DT-719)
Tickets related to this pull-request: [DT-719](https://aptoide.atlassian.net/browse/DT-719)
[DT-719]: https://aptoide.atlassian.net/browse/DT-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-719]: https://aptoide.atlassian.net/browse/DT-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> [DT-719] Add adyen payment error mappings and exceptions

- buildSrc/src/main/kotlin/GradleDependency.kt
- buildSrc/src/main/kotlin/LibraryDependency.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/DpExtensions.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppsByTagUseCase.kt
- Adds Kotlin serialization dependency.
- Increases Jetpack Glance version.
- Refactor some use cases to not be scoped to viewmodels.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-477](https://aptoide.atlassian.net/browse/DT-477)
Tickets related to this pull-request: [DT-477](https://aptoide.atlassian.net/browse/DT-477)
**Questions:**
[DT-477]: https://aptoide.atlassian.net/browse/DT-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-477]: …
> [DT-477] Widget for cricket

- payments/base/payment-prefs/src/main/java/com/aptoide/pt/payments_prefs/domain/PreSelectedPaymentUseCase.kt
Turn payments pre-selected feature off
No
Flow on how to test this or QA Tickets related to this use-case: [DT-953](https://aptoide.atlassian.net/browse/DT-953)
Tickets related to this pull-request: [DT-953](https://aptoide.atlassian.net/browse/DT-953)
[DT-953]: https://aptoide.atlassian.net/browse/DT-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-953]: https://aptoide.atlassian.net/browse/DT-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-953] Turn payments pre-selected feature off

- extensions/src/main/java/cm/aptoide/pt/extensions/Composables.kt
Add landscape preview annotation
No
Flow on how to test this or QA Tickets related to this use-case: [APP-879](https://aptoide.atlassian.net/browse/DT-879)
Tickets related to this pull-request: [APP-879](https://aptoide.atlassian.net/browse/DT-879)
[APP-879]: https://aptoide.atlassian.net/browse/APP-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-879]: https://aptoide.atlassian.net/browse/APP-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-879] Add landscape previews

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
Add a total size of download/installation parameter.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-850](https://aptoide.atlassian.net/browse/DT-850)
Tickets related to this pull-request: [DT-850](https://aptoide.atlassian.net/browse/DT-850)
PRs related to this one: [#389](https://github.com/Aptoide/aptoide-client-dt/pull/389)
[DT-850]: https://aptoide.atlassian.net/browse/DT-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-850]: https://aptoide.atlassian.net/browse/DT-850?atlOrigin=eyJpIjoiNWRkNTljNz …
> [DT-850] Augment Downloading/Installing states

- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
- install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
- install-manager/src/test/java/cm/aptoide/pt/install_manager/TasksTest.kt
Fix automatic installs.
Had to remove confusing ui states and replace them with constraints resolver
No
Flow on how to test this or QA Tickets related to this use-case: [DT-852](https://aptoide.atlassian.net/browse/DT-852)
Tickets related to this pull-request: [DT-852](https://aptoide.atlassian.net/browse/DT-852)
PRs related to this one: [#394](https://github.com/Aptoide/aptoide-client-dt/pull/394)
[DT-852]: https://aptoide.atlassian.net/browse/DT-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-852]: …
> [DT-852] Fix automatic installs

- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/domain/UrlsCache.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/AptoideUrlsCacheInitializer.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/SimilarAppcAppsUseCase.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/SimilarAppsUseCase.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/Article.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/ArticlesMetaUseCase.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/RelatedArticlesMetaUseCase.kt
Fixes the URLs cache misses when navigate with deep links (e.g. from a widget).
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1003](https://aptoide.atlassian.net/browse/DT-1003)
Tickets related to this pull-request: [DT-1003](https://aptoide.atlassian.net/browse/DT-1003)
[DT-1003]: https://aptoide.atlassian.net/browse/DT-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1003]: https://aptoide.atlassian.net/browse/DT-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1003] Fix urls cache miss

- aptoide-ui/build.gradle.kts
- aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/toolbar/AptoideToolbar.kt
Add preview to AptoideToolbar
No
Flow on how to test this or QA Tickets related to this use-case: [APP-604](https://aptoide.atlassian.net/browse/DT-604)
Tickets related to this pull-request: [APP-604](https://aptoide.atlassian.net/browse/DT-604)
[APP-604]: https://aptoide.atlassian.net/browse/APP-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-604]: https://aptoide.atlassian.net/browse/APP-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-604] Add preview to AptoideToolbar

- buildSrc/src/main/kotlin/LibraryDependency.kt
- buildSrc/src/main/kotlin/plugin/ComposablePlugin.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
Add method to open browser from url
No
Click on a link to open the url in browser.
Flow on how to test this or QA Tickets related to this use-case: [DT-999](https://aptoide.atlassian.net/browse/DT-999)
Tickets related to this pull-request: [DT-999](https://aptoide.atlassian.net/browse/DT-999)
[DT-999]: https://aptoide.atlassian.net/browse/DT-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-999]: https://aptoide.atlassian.net/browse/DT-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-999] Add terms and conditions view

- buildSrc/src/main/kotlin/LibraryDependency.kt
- buildSrc/src/main/kotlin/plugin/ComposablePlugin.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
Add method to open browser from url
No
Click on a link to open the url in browser.
Flow on how to test this or QA Tickets related to this use-case: [DT-1019](https://aptoide.atlassian.net/browse/DT-1019)
Tickets related to this pull-request: [DT-1019](https://aptoide.atlassian.net/browse/DT-1019)
[DT-999]: https://aptoide.atlassian.net/browse/DT-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-999]: https://aptoide.atlassian.net/browse/DT-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1019]: …
> [DT-1019] Add terms and conditions view

- payments/payment-methods/paypal/src/main/java/cm/aptoide/pt/payment_method/paypal/presentation/PaypalResultContract.kt
- payments/payment-methods/paypal/src/main/java/cm/aptoide/pt/payment_method/paypal/presentation/PaypalUIState.kt
- payments/payment-methods/paypal/src/main/java/cm/aptoide/pt/payment_method/paypal/presentation/PaypalViewModel.kt
Add handling the user cancel case. 
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1044](https://aptoide.atlassian.net/browse/DT-1044)
Tickets related to this pull-request: [DT-1044](https://aptoide.atlassian.net/browse/DT-1044)
**Questions:**
PRs related to this one: [#426](https://github.com/Aptoide/aptoide-client-dt/pull/426)
[DT-1044]: https://aptoide.atlassian.net/browse/DT-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [DT-1044] Fix the generic error after tapping the Back button from the PayPal screen

- payments/billing-sdk/build.gradle.kts
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingService.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingSdkConstants.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingType.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/billing_support/BillingSupportErrorMapper.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/di/SdkModule.kt
Implement is billing supported
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1057](https://aptoide.atlassian.net/browse/DT-1057)
Tickets related to this pull-request: [APP-1057](https://aptoide.atlassian.net/browse/DT-1057)
[APP-1057]: https://aptoide.atlassian.net/browse/APP-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1057]: https://aptoide.atlassian.net/browse/APP-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1057] Implement is billing supported

- payments/base/arch/src/main/java/com/appcoins/payments/arch/PaymentMethod.kt
- payments/base/arch/src/main/java/com/appcoins/payments/arch/ProductInfoData.kt
- payments/billing-sdk/build.gradle.kts
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingErrorMapper.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingSdkConstants.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/di/SdkModule.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/sku_details/ProductSerializer.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/sku_details/SKU.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/ProductInventoryRepository.kt
Implemented get SKU details on sdk binder
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1058](https://aptoide.atlassian.net/browse/DT-1058)
Tickets related to this pull-request: [APP-1058](https://aptoide.atlassian.net/browse/DT-1058)
[APP-1058]: https://aptoide.atlassian.net/browse/APP-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1058]: https://aptoide.atlassian.net/browse/APP-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1058] Implemented get SKU details on sdk binder

- payments/base/arch/src/main/java/com/appcoins/payments/arch/PurchaseInfoData.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingErrorMapper.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingSdkConstants.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/ProductInventoryRepository.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/model/PurchasesResponse.kt
- Implements the getPurchases method in the aidl binder, that is responsible for fetching the purchases related to a merchant and of a certain type.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1059](https://aptoide.atlassian.net/browse/DT-1059)
Tickets related to this pull-request: [DT-1059](https://aptoide.atlassian.net/browse/DT-1059)
[DT-1059]: https://aptoide.atlassian.net/browse/DT-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1059]: https://aptoide.atlassian.net/browse/DT-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
> [DT-1059] Implement billing aidl binder getPurchases

- payments/base/arch/src/main/java/com/appcoins/payments/arch/PurchaseUriParameters.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingSdkConstants.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/PayloadHelper.java
- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/CreditCardPaymentMethod.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/PaypalPaymentMethod.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalViewModel.kt
- payments/uri-handler/src/main/AndroidManifest.xml
- payments/uri-handler/src/main/java/com/appcoins/uri_handler/handler/UriHandler.kt
- Implements the method that creates the intent to return to the billing client app.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1060](https://aptoide.atlassian.net/browse/DT-1060)
Tickets related to this pull-request: [DT-1060](https://aptoide.atlassian.net/browse/DT-1060)
[DT-1060]: https://aptoide.atlassian.net/browse/DT-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1060]: https://aptoide.atlassian.net/browse/DT-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1060] Implement getBuyIntent in billing AIDL binder

- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingErrorMapper.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/ProductInventoryRepository.kt
Implemented consumePurchase on sdk binder
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1061](https://aptoide.atlassian.net/browse/DT-1061)
Tickets related to this pull-request: [APP-1061](https://aptoide.atlassian.net/browse/DT-1061)
[APP-1061]: https://aptoide.atlassian.net/browse/APP-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1061]: https://aptoide.atlassian.net/browse/APP-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1061] Implemented consumePurchase on sdk binder

- payments/base/arch/src/main/java/com/appcoins/payments/arch/Transaction.kt
- payments/base/payment-manager/src/main/java/com/appcoins/payment_manager/repository/broker/BrokerRepository.kt
- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/CreditCardPaymentMethod.kt
- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/CreditCardTransaction.kt
- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/repository/AdyenV2Repository.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/Constants.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/PaypalPaymentMethod.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/PaypalPaymentMethodFactory.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/model/PaypalTransaction.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalViewModel.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/repository/PaypalRepository.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/ProductInventoryRepository.kt
This PR adds payments pooling on settled state
No
Test payments using the SDK on client app
Flow on how to test this or QA Tickets related to this use-case: [APP-1097](https://aptoide.atlassian.net/browse/DT-1097)
Tickets related to this pull-request: [APP-1097](https://aptoide.atlassian.net/browse/DT-1097)
[APP-1097]: https://aptoide.atlassian.net/browse/APP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1097]: https://aptoide.atlassian.net/browse/APP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1097] Allow GH IAB to wait for pending payment transactions to be completed

- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalScreenUiState.kt
- payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalViewModel.kt
- Fixes some naming and code style issues
- Adds support for no connection view in the paypal payment method screen.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1071](https://aptoide.atlassian.net/browse/DT-1071)
Tickets related to this pull-request: [DT-1071](https://aptoide.atlassian.net/browse/DT-1071)
[DT-1071]: https://aptoide.atlassian.net/browse/DT-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1071]: https://aptoide.atlassian.net/browse/DT-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> [DT-1071] Paypal no connection view

- payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
Fixed the issue of the user pressing the back button on webview when paying with credit card.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1104](https://aptoide.atlassian.net/browse/DT-1104)
Tickets related to this pull-request: [APP-1104](https://aptoide.atlassian.net/browse/DT-1104)
[APP-1104]: https://aptoide.atlassian.net/browse/APP-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1104]: https://aptoide.atlassian.net/browse/APP-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> [DT-1104] Fix back button behavior on redirect 3 ds webview

- extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
This PR aims at standarizing all email templates for aptoide
No
Open settings and test all emails
Tickets related to this pull-request: [DT-1115](https://aptoide.atlassian.net/browse/DT-1115)
**Questions:**
[DT-1115]: https://aptoide.atlassian.net/browse/DT-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1115] Update emails templates

- app/src/main/java/cm/aptoide/pt/AptoideApplication.java
This PR aims at adding two new parameters for indicative.
No
Open the app perform any indicative event (download for example) and check on charles the event and see if it goes with the correct info.
Tickets related to this pull-request: [APP-2237](https://aptoide.atlassian.net/browse/APP-2237)
**Questions:**
[APP-2237]: https://aptoide.atlassian.net/browse/APP-2237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2237] indicative params

- app/src/main/java/cm/aptoide/pt/appview/AppViewScreen.kt
- app/src/main/java/cm/aptoide/pt/appview/ReviewsView.kt
- app/src/main/java/cm/aptoide/pt/search/presentation/SearchView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppGraphicView.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppGridView.kt
Use pRating in reviews and use a hyphen if no ratings
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2221](https://aptoide.atlassian.net/browse/APP-2221)
Tickets related to this pull-request: [APP-2221](https://aptoide.atlassian.net/browse/APP-2221)
[APP-2221]: https://aptoide.atlassian.net/browse/APP-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2221]: https://aptoide.atlassian.net/browse/APP-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2221] fix v10 ratings

- app-games/src/main/java/cm/aptoide/pt/app_games/home/MainView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/AppColors.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/Theme.kt
AppGames now supports theme's change 
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2252](https://aptoide.atlassian.net/browse/APP-2252)
Tickets related to this pull-request: [APP-2252](https://aptoide.atlassian.net/browse/APP-2252)
**Questions:**
[APP-2252]: https://aptoide.atlassian.net/browse/APP-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2252]: https://aptoide.atlassian.net/browse/APP-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> [APP-2252] Support Dark/Light/System theme change

- app-games/src/main/java/cm/aptoide/pt/app_games/appview/AppViewScreen.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/AppGridView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/CarouselLargeAppView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/PublisherTakeoverAppView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/home/MainView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/AppColors.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/Theme.kt
- app-games/src/main/res/values/strings.xml
In this PR the appView is created and when you click the bundle items you navigate to the appViewScreen
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2301](https://aptoide.atlassian.net/browse/APP-2301)
Tickets related to this pull-request: [APP-2301](https://aptoide.atlassian.net/browse/APP-2301)
**Questions:**
[APP-2301]: https://aptoide.atlassian.net/browse/APP-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2301]: …
> [APP-2301] Navigate to app view

- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingErrorMapper.kt
- payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/BillingSupportMapper.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/ProductInventoryRepository.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/error/ServerErrorException.kt
- payments/product-inventory/src/main/java/com/appcoins/product_inventory/model/BillingSupport.kt
Replace the network errors with new arch network errors.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1177](https://aptoide.atlassian.net/browse/DT-1177)
Tickets related to this pull-request: [APP-1177](https://aptoide.atlassian.net/browse/DT-1177)
[APP-1177]: https://aptoide.atlassian.net/browse/APP-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1177]: https://aptoide.atlassian.net/browse/APP-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1177] Move sdk api error handling to product inventory module

- app-games/src/main/java/cm/aptoide/pt/app_games/AptoideApplication.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/appview/AppViewScreen.kt
In this PR, the install button works just like v10
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2302](https://aptoide.atlassian.net/browse/APP-2302)
Tickets related to this pull-request: [APP-2302](https://aptoide.atlassian.net/browse/APP-2302)
**Questions:**
[APP-2302]: https://aptoide.atlassian.net/browse/APP-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2302]: https://aptoide.atlassian.net/browse/APP-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
> [APP-2302] Install button works like v10

- app-games/src/main/java/cm/aptoide/pt/app_games/home/BundlesView.kt
This PR aims to fix the content in home 
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2282](https://aptoide.atlassian.net/browse/APP-2282)
Tickets related to this pull-request: [APP-2282](https://aptoide.atlassian.net/browse/APP-2282)
**Questions:**
[APP-2282]: https://aptoide.atlassian.net/browse/APP-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2282]: https://aptoide.atlassian.net/browse/APP-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> [APP-2282] Fix show a content in home

- app/src/main/java/cm/aptoide/pt/home/BundlesView.kt
- feature-home/build.gradle.kts
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Bundle.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Widget.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/presentation/ViewModelProvider.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/ViewModelProvider.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt
This PR aims at creating the bundles view preview
No
Open the app and check if everything is ok with the bundles. also check the previews
Tickets related to this pull-request: [DT-589](https://aptoide.atlassian.net/browse/DT-589)
**Questions:**
[DT-589]: https://aptoide.atlassian.net/browse/DT-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-589] bundles view preview

- payments/uri-handler/src/main/AndroidManifest.xml
It replaces the launchMode in paymentActivity, to support different activities to be launched on top of it.
No
Test all the support flows for the contactus click and see if the contactus screen opens on top of the app where the payments are being done, instead of opening GH for it. See if it doesn't break anything else.
Flow on how to test this or QA Tickets related to this use-case: [DT-1158](https://aptoide.atlassian.net/browse/DT-1158)
Tickets related to this pull-request: [DT-1158](https://aptoide.atlassian.net/browse/DT-1158)
[DT-1158]: https://aptoide.atlassian.net/browse/DT-1158?atlOrigin=eyJpIjoiNWR …
> [DT-1158] changes in feedback

- app-games/src/main/java/cm/aptoide/pt/app_games/bottom_bar/AppGamesBottomBar.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/categories/presentation/CategoryDetailView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/categories/presentation/CategoryGridView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/AppItems.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/home/BottomBarMenus.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/home/MainView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/installer/presentation/InstallViewShort.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/installer/presentation/ProgressText.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/search/presentation/SearchView.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/AppColors.kt
- app-games/src/main/java/cm/aptoide/pt/app_games/theme/Theme.kt
- app-games/src/main/res/values/strings.xml
This PR aims to create a category screen
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [APP-2338](https://aptoide.atlassian.net/browse/APP-2338)
Tickets related to this pull-request: [APP-2338](https://aptoide.atlassian.net/browse/APP-2338)
**Questions:**
[APP-2338]: https://aptoide.atlassian.net/browse/APP-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2338] Add category screen

- payments/arch/src/main/java/com/appcoins/payments/di/Payments.kt
- payments/manager/src/main/java/com/appcoins/payments/di/PaymentsManager.kt
- payments/manager/src/main/java/com/appcoins/payments/manager/repository/broker/PaymentsRepository.kt
- payments/methods/adyen/src/main/java/com/appcoins/payments/methods/adyen/CreditCardPaymentMethod.kt
- payments/methods/adyen/src/main/java/com/appcoins/payments/methods/adyen/PaymentDetails.kt
- payments/methods/paypal/src/main/java/com/appcoins/payments/methods/paypal/PaypalPaymentMethod.kt
- payments/methods/paypal/src/main/java/com/appcoins/payments/methods/paypal/repository/model/PaymentDetailsRequest.kt
- payments/network/src/main/java/com/appcoins/payments/di/PaymentsNetwork.kt
- payments/network/src/main/java/com/appcoins/payments/network/GetUserAgent.kt
- payments/network/src/main/java/com/appcoins/payments/network/RestClient.kt
- payments/network/src/main/java/com/appcoins/payments/network/RestClientImpl.kt
- payments/network/src/main/java/com/appcoins/payments/network/RestClientInjectParams.kt
- Moves the channel parameter injection from each specific call to the payments rest client.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1203](https://aptoide.atlassian.net/browse/DT-1203)
Tickets related to this pull-request: [DT-1203](https://aptoide.atlassian.net/browse/DT-1203)
[DT-1203]: https://aptoide.atlassian.net/browse/DT-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1203]: https://aptoide.atlassian.net/browse/DT-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1203] Refactor channel parameter propagation

- app-games/build.gradle.kts
- app-games/src/dev/google-services.json
- app-games/src/main/AndroidManifest.xml
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/AppModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/FirebaseModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/firebase/FirebaseInfoProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/AptoideGamesNotificationService.kt
- app-games/src/prod/google-services.json
This PR aims to integrate firebase into Aptoide Games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2398](https://aptoide.atlassian.net/browse/APP-2398)
Tickets related to this pull-request: [APP-2398](https://aptoide.atlassian.net/browse/APP-2398)
**Questions:**
[APP-2398]: https://aptoide.atlassian.net/browse/APP-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2398]: https://aptoide.atlassian.net/browse/APP-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> [APP-2398]Add firebase integration

- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialView.kt
Update EditorialBundle to match designed UI.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2447](https://aptoide.atlassian.net/browse/APP-2447)
Tickets related to this pull-request: [APP-2447](https://aptoide.atlassian.net/browse/APP-2447)
[APP-2447]: https://aptoide.atlassian.net/browse/APP-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2447]: https://aptoide.atlassian.net/browse/APP-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2447] Update editorial bundle UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
Updated the AppGridView for app games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2444](https://aptoide.atlassian.net/browse/APP-2444)
Tickets related to this pull-request: [APP-2444](https://aptoide.atlassian.net/browse/APP-2444)
[APP-2444]: https://aptoide.atlassian.net/browse/APP-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2444]: https://aptoide.atlassian.net/browse/APP-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2444] Update app grid view

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
Update carousel and carousel large views for app games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
Tickets related to this pull-request: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
[APP-2445]: https://aptoide.atlassian.net/browse/APP-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2445]: https://aptoide.atlassian.net/browse/APP-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2445] Update carousel and carousel large views

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppItems.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
Updated the "See all" section.
Also update the installation progress text.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2465](https://aptoide.atlassian.net/browse/APP-2465)
Tickets related to this pull-request: [APP-2465](https://aptoide.atlassian.net/browse/APP-2465)
[APP-2465]: https://aptoide.atlassian.net/browse/APP-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2465]: https://aptoide.atlassian.net/browse/APP-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2465] Update UI of the see more screen with the items

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallView.kt
Updated the install views ui.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2470](https://aptoide.atlassian.net/browse/APP-2470)
Tickets related to this pull-request: [APP-2470](https://aptoide.atlassian.net/browse/APP-2470)
[APP-2470]: https://aptoide.atlassian.net/browse/APP-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2470]: https://aptoide.atlassian.net/browse/APP-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2470] Update install views UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
Update carousel and carousel large views for app games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
Tickets related to this pull-request: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
[APP-2445]: https://aptoide.atlassian.net/browse/APP-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2445]: https://aptoide.atlassian.net/browse/APP-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2445] Update carousel and carousel large

- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Theme.kt
This PR aims to update the categories screen UI
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2466](https://aptoide.atlassian.net/browse/APP-2466)
Tickets related to this pull-request: [APP-2466](https://aptoide.atlassian.net/browse/APP-2466)
**Questions:**
[APP-2466]: https://aptoide.atlassian.net/browse/APP-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2466]: https://aptoide.atlassian.net/browse/APP-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
> [APP-2466] Update categories screen UI

- extensions/src/main/java/cm/aptoide/pt/extensions/DateExtensions.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/StringExtensions.kt
- feature-flags/src/main/java/cm/aptoide/pt/feature_flags/domain/FeatureFlags.kt
Add new method to get jsons from FeatureFlags object.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1227](https://aptoide.atlassian.net/browse/DT-1227)
Tickets related to this pull-request: [APP-1227](https://aptoide.atlassian.net/browse/DT-1227)
[APP-1227]: https://aptoide.atlassian.net/browse/APP-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1227]: https://aptoide.atlassian.net/browse/APP-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1227] Client self update of games hub update get settings

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/WifiDialogIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_oos/OutOfSpaceAppItem.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_oos/OutOfSpaceDialog.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/presentation/WifiPromptDialog.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AppGamesButton.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AppIcons.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Theme.kt
This PR aims to update the Out of space and wait for wifi  UI dialog 
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2469](https://aptoide.atlassian.net/browse/APP-2469)
Tickets related to this pull-request: [APP-2469](https://aptoide.atlassian.net/browse/APP-2469)
**Questions:**
[APP-2469]: https://aptoide.atlassian.net/browse/APP-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2469]: https://aptoide.atlassian.net/browse/APP-2469?atlOrigin=eyJpIjoiNWR …
> [APP-2469] Update out of space and wait for wifi UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/AptoideLogo.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/CaretRight.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AppIcons.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Theme.kt
This PR aims to update the settings screen UI
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2473](https://aptoide.atlassian.net/browse/APP-2473)
Tickets related to this pull-request: [APP-2473](https://aptoide.atlassian.net/browse/APP-2473)
**Questions:**
[APP-2473]: https://aptoide.atlassian.net/browse/APP-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2473]: https://aptoide.atlassian.net/browse/APP-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [APP-2473] Update settings UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
Update Editorials UI
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2472](https://aptoide.atlassian.net/browse/APP-2472)
Tickets related to this pull-request: [APP-2472](https://aptoide.atlassian.net/browse/APP-2472)
**Questions:**
[APP-2472]: https://aptoide.atlassian.net/browse/APP-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2472]: https://aptoide.atlassian.net/browse/APP-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
> [App-2472] Update editorials UI

- app-games/build.gradle.kts
- Changes the store/market name of aptoide-games, which reflects changes in the endpoints used.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
Tickets related to this pull-request: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> [APP-2388] Change store name to aptoide-games

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/AppcoinsClearLogo.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Done.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/NoConnectionSimple.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/PaymentsErrorIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/WalletGift.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AppGamesPaymentBottomSheet.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AppGamesPurchaseInfo.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/ErrorViews.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/SuccessView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/di/PaymentsModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/LandscapePaymentView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/PortraitPaymentView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/presentation/PreSelectedPaymentMethod.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/repository/PaymentsPreferencesRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/repository/PreSelectedPaymentMethodRepository.kt
Added payment methods list to AppGames.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2474](https://aptoide.atlassian.net/browse/APP-2474)
Tickets related to this pull-request: [APP-2474](https://aptoide.atlassian.net/browse/APP-2474)
[APP-2474]: https://aptoide.atlassian.net/browse/APP-2474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2474]: https://aptoide.atlassian.net/browse/APP-2474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2474] Add payment methods list

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/permissions/AppPermissionsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoryDetailView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/SeeAllMyGamesScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/TransitionAnimation.kt
Moved the TransitionAnimation.kt class from deprecated aptoide_ui to extensions module.
Started using the staticComposable and animatedComposable in the AppGames.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2549](https://aptoide.atlassian.net/browse/APP-2549)
Tickets related to this pull-request: [APP-2549](https://aptoide.atlassian.net/browse/APP-2549)
[APP-2549]: https://aptoide.atlassian.net/browse/APP-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2549]: https://aptoide.atlassian.net/browse/APP-2549?atlOrigin=eyJpIjoiNW …
> [APP-2549] Refactor composable TransitionAnimation

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/PaymentButtonsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/paypal/PaypalScreen.kt
Added Paypal payment method
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2476](https://aptoide.atlassian.net/browse/APP-2476)
Tickets related to this pull-request: [APP-2476](https://aptoide.atlassian.net/browse/APP-2476)
[APP-2476]: https://aptoide.atlassian.net/browse/APP-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2476]: https://aptoide.atlassian.net/browse/APP-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2476] Implement paypal UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/AptoideGamesToolbarLogo.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/AptoideGamesToolbarLogoDev.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/ToolBarUtils.kt
Added new logo for aptoide games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2556](https://aptoide.atlassian.net/browse/APP-2556)
Tickets related to this pull-request: [APP-2556](https://aptoide.atlassian.net/browse/APP-2556)
[APP-2556]: https://aptoide.atlassian.net/browse/APP-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2556]: https://aptoide.atlassian.net/browse/APP-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2556] Added new logo for app games

- app-games/proguard-rules.pro
Added missing pro guard rules.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2560](https://aptoide.atlassian.net/browse/APP-2560)
Tickets related to this pull-request: [APP-2560](https://aptoide.atlassian.net/browse/APP-2560)
[APP-2560]: https://aptoide.atlassian.net/browse/APP-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2560]: https://aptoide.atlassian.net/browse/APP-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2560] Dev release nightly breaking on app open

- app-games/build.gradle.kts
Added signing config for release mode
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2550](https://aptoide.atlassian.net/browse/APP-2550)
Tickets related to this pull-request: [APP-2550](https://aptoide.atlassian.net/browse/APP-2550)
[APP-2550]: https://aptoide.atlassian.net/browse/APP-2550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2550]: https://aptoide.atlassian.net/browse/APP-2550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [App-2550] Dev release signed apk

- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- app-games/src/main/res/values/strings.xml
This PR aims to fix the Terms and Conditions string
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
Tickets related to this pull-request: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
**Questions:**
[APP-2347]: https://aptoide.atlassian.net/browse/APP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2347]: https://aptoide.atlassian.net/browse/APP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
> [APP-2347] Terms Conditions Privacy Policy

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- Makes the YouTube player used in AppView previewable in compose.
Also:
- Adds the missing releaseUpdateDate on the randomApp getter used for previews
- Adds the AppView previews in appgames
No
Flow on how to test this or QA Tickets related to this use-case: [DT-577](https://aptoide.atlassian.net/browse/DT-577)
Flow on how to test this or QA Tickets related to this use-case: [APP-2471](https://aptoide.atlassian.net/browse/APP-2471)
Tickets related to this pull-request: [DT-577](https://aptoide.atlassian.net/browse/DT-577)
Tickets related to this pull-request: [APP-2471](https://aptoide.atlassian.net/browse/APP-2471)
**Code Review …
> [DT-577] Make YouTube player previewable

- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideQLogicInterceptor.kt
This PR aims to remove myDensity and maxScreen from qValue
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2392](https://aptoide.atlassian.net/browse/APP-2392)
Tickets related to this pull-request: [APP-2392](https://aptoide.atlassian.net/browse/APP-2392)
**Questions:**
[APP-2392]: https://aptoide.atlassian.net/browse/APP-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2392]: https://aptoide.atlassian.net/browse/APP-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> [APP-2392] Remove myDensity and maxScreen from q

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Bonus.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/WalletInstalled.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstallationScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstalledScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewShort.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Palette.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
It implements the wallet installation UI and its flow. It also adds an onCancel parameter to the InstallViewShort.
We should wait for the payments to get the whole flow in, but I believe the majority of the code can already be reviewed.
No
First commit:
Second Commit
Flow on how to test this or QA Tickets related to this use-case: [APP-2477](https://aptoide.atlassian.net/browse/APP-2477)
Tickets related to this pull-request: [APP-2477](https://aptoide.atlassian.net/browse/APP-2477)
[APP-2477]: https://aptoide.atlassian.net/browse/APP-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> [APP-2477] - Implement wallet installation UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
This PR aims to fix some small misses in UI
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2533](https://aptoide.atlassian.net/browse/APP-2533)
Tickets related to this pull-request: [APP-2533](https://aptoide.atlassian.net/browse/APP-2533)
**Questions:**
[APP-2533]: https://aptoide.atlassian.net/browse/APP-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2533]: https://aptoide.atlassian.net/browse/APP-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> [APP-2533] small miss in UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GMSExtensions.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/AppModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/launch/AppLaunchPreferencesManager.kt
This PR aims at implementing user properties for indicative platform.
Also had to implement the first session management based on datastore.
No
When events are implemented you will be able to see they are being sent attached to those events.
Tickets related to this pull-request: [APP-2561](https://aptoide.atlassian.net/browse/APP-2561)
**Questions:**
[APP-2561]: https://aptoide.atlassian.net/browse/APP-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2561] Indicative user properties

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideGetHeaders.kt
- app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
- app/src/main/java/cm/aptoide/pt/network/AptoideGetHeaders.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/AcceptLanguageInterceptor.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/UserAgentInterceptor.kt
Added missing "Accept-language" header to payment requests
No
The user can start by testing the payments with a different language and validate that the payment methods are transalated.
Flow on how to test this or QA Tickets related to this use-case: [DT-1293](https://aptoide.atlassian.net/browse/DT-1293)
Tickets related to this pull-request: [DT-1293](https://aptoide.atlassian.net/browse/DT-1293)
[DT-1293]: https://aptoide.atlassian.net/browse/DT-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1293]: …
> [DT-1293] Add accept language to the payment methods request

- app-games/src/main/java/com/aptoide/android/aptoidegames/SupportActivity.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/paypal/PaypalScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
This PR aims to add behaviour when clicking “Contact Support Team”
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2578](https://aptoide.atlassian.net/browse/APP-2578)
Tickets related to this pull-request: [APP-2578](https://aptoide.atlassian.net/browse/APP-2578)
**Questions:**
[APP-2578]: https://aptoide.atlassian.net/browse/APP-2578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2578]: https://aptoide.atlassian.net/browse/APP-2578?atlOrigin=eyJpIjoiNWRkNT …
> [APP-2578] Settings contact support

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
This PR aims to check if the Apps have obb's or not so the first installation doesn't fail on the first install of an APP without obb's
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2537](https://aptoide.atlassian.net/browse/APP-2537)
Tickets related to this pull-request: [APP-2537](https://aptoide.atlassian.net/browse/APP-2537)
**Questions:**
[APP-2537]: https://aptoide.atlassian.net/browse/APP-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2537]: …
> [APP-2537] Make single apk with obb work

- app-games/src/main/java/com/aptoide/android/aptoidegames/design_system/AGTextButton.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AdyenExceptionMapper.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/PaymentButtonsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/presentation/WifiPromptDialog.kt
- app-games/src/main/res/values/colors.xml
- app-games/src/main/res/values/styles.xml
- Adds the credit card screen to aptoide games.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2475](https://aptoide.atlassian.net/browse/APP-2475)
Tickets related to this pull-request: [APP-2475](https://aptoide.atlassian.net/browse/APP-2475)
[APP-2475]: https://aptoide.atlassian.net/browse/APP-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2475]: https://aptoide.atlassian.net/browse/APP-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2475] Implement credit card UI in app games

- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideGetHeaders.kt
- Change the channel used in aptoide games payments
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2604](https://aptoide.atlassian.net/browse/APP-2604)
Tickets related to this pull-request: [APP-2604](https://aptoide.atlassian.net/browse/APP-2604)
[APP-2604]: https://aptoide.atlassian.net/browse/APP-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2604]: https://aptoide.atlassian.net/browse/APP-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2604] Change aptoide games payment channel

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideGetHeaders.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/DeviceInfoViewModel.kt
This PR aims to change instances where AppGames is still used to Aptoide Games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2608](https://aptoide.atlassian.net/browse/APP-2608)
Tickets related to this pull-request: [APP-2608](https://aptoide.atlassian.net/browse/APP-2608)
**Questions:**
[APP-2608]: https://aptoide.atlassian.net/browse/APP-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2608]: …
> [APP-2608] Change App Name, Apk Name and User Agent

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/DynamicSplit.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/AppJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/DynamicSplitJSON.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/DynamicSplitsUseCase.kt
**NOTE: Contains some TODO's of refactors that might need to be done**
- Adds the required mappings for the aab base split apks and adds the splits as installation files.
- Adds dynamic splits to aab app installations.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2543](https://aptoide.atlassian.net/browse/APP-2543)
Tickets related to this pull-request: [APP-2543](https://aptoide.atlassian.net/browse/APP-2543)
[APP-2543]: https://aptoide.atlassian.net/browse/APP-2543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2543]: …
> [APP-2543] Install apps with aabs

- app-games/build.gradle.kts
**Still in draft** - Missing SDK update from apptech to finalize it.
This PR integrates the AppCoins SDK in AG. It also adds the payments user agent as well as oemid/package extractor.
It's still missing the APPCOINS_SDK version update in `LibraryDependency.kt` -> Waiting for apptech so I can put the right version there
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2595](https://aptoide.atlassian.net/browse/APP-2595)
Tickets related to this pull-request: [APP-2595](https://aptoide.atlassian.net/browse/APP-2595)
**Questions:** …
> [APP-2595] - Support AppCoins SDK - AptoideGames

- app-games/build.gradle.kts
This PR aims to fix the version name that I forgot to add on the previous PR
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2646](https://aptoide.atlassian.net/browse/APP-2646)
Tickets related to this pull-request: [APP-2646](https://aptoide.atlassian.net/browse/APP-2646)
**Questions:**
[APP-2646]: https://aptoide.atlassian.net/browse/APP-2646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2646]: …
> [APP-2646] Fix version name to 0.9.0

- app/src/main/java/cm/aptoide/pt/ApplicationModule.java
- app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
- app/src/main/java/cm/aptoide/pt/apkfy/ApkFyParser.kt
- app/src/main/java/cm/aptoide/pt/apkfy/ApkfyModel.kt
- app/src/main/java/cm/aptoide/pt/apkfy/ApkfyResponse.kt
- app/src/main/java/cm/aptoide/pt/apkfy/AptoideApkfyService.kt
- app/src/main/java/cm/aptoide/pt/app/AppNavigator.java
- app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
This PR aims at adding support to utm on the apkfy flow in order to add it as user properties. Also fixes the oemid mapping.
No
Test the apkfy flow, adding utm values and check that on the following events to indicative, everything goes correctly with the right values.
Tickets related to this pull-request: [APP-2656](https://aptoide.atlassian.net/browse/APP-2656)
**Questions:**
[APP-2656]: https://aptoide.atlassian.net/browse/APP-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2656] UTM support on APKFY

- app/src/main/java/cm/aptoide/pt/apkfy/ApkFyParser.kt
- app/src/main/java/cm/aptoide/pt/app/AppNavigator.java
- app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
This PR aims at implementing apkfy through package name. Also keep supporting app id.
This will be closed as soon as it is open.
No
Test apkfy.
Tickets related to this pull-request: [APP-2676](https://aptoide.atlassian.net/browse/APP-2676)
**Questions:**
[APP-2676]: https://aptoide.atlassian.net/browse/APP-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2676] Support package name

- feature-flags/src/main/java/cm/aptoide/pt/feature_flags/domain/FeatureFlags.kt
This PR aims at implementing a feature flag for the terms and conditions dialog show
No
API was not changed yet, so you will need to change the values locally (change the default value when getting it from the feature flags).
Tickets related to this pull-request: [DT-1336](https://aptoide.atlassian.net/browse/DT-1336)
**Questions:**
[DT-1336]: https://aptoide.atlassian.net/browse/DT-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DT-1336] Support TC & PP Dialog feature flag

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
- feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/AptoideMMPCampaign.kt
- feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt
It implements all Aptoide MMP logic for Aptoide Games for impressions, clicks and installs in PTO and installs all over the app for apps with aptoide mmp campaigns. It also adds logic to have searchMeta in SearchView so we have search keyword on search install.
No
- See by commit
Flow on how to test this or QA Tickets related to this use-case: [APP-2735](https://aptoide.atlassian.net/browse/APP-2735)
Tickets related to this pull-request: [APP-2735](https://aptoide.atlassian.net/browse/APP-2735)
[APP-2735]: https://aptoide.atlassian.net/browse/APP-2735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> [APP-2735] - Implement Aptoide MMP

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AppGamesPurchaseInfo.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
- Adds nullability to the fetch of an app name, to account for cases where the passed package name is not installed on the user's device.
- Adds a loading skeleton for the purchase request app name, when the app name is still not available.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1346](https://aptoide.atlassian.net/browse/DT-1346)
Tickets related to this pull-request: [DT-1346](https://aptoide.atlassian.net/browse/DT-1346)
[DT-1346]: https://aptoide.atlassian.net/browse/DT-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [DT-1346] Improve initial payment methods loading

- app-games/src/main/java/com/aptoide/android/aptoidegames/SupportActivity.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/permissions/AppPermissionsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BonusIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/PaymentButtonsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/paypal/PaypalScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstallationScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstalledScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
It replaces all the hardcoded (That aren't supposed to be hardcoded) strings with local ones, as well as all the changes needed for them to work as intended.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2830](https://aptoide.atlassian.net/browse/APP-2830)
Tickets related to this pull-request: [APP-2830](https://aptoide.atlassian.net/browse/APP-2830)
[APP-2830]: https://aptoide.atlassian.net/browse/APP-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2830]: https://aptoide.atlassian.net/browse/APP-2830?atlOrigin=eyJpIjoiNWRkNTl …
> [APP-2830]  Replace hardcoded strings with local strings

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BonusOnEveryPurchase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/WantMore.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppItems.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/AptoideWidgetsRepository.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/model/WidgetTypeJSON.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/model/WidgetsJSON.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Bundle.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Widget.kt
This PR aims to receive the bonus banner from the API and to display it, when you click 2 things can happen
If banner has URL:
Yes, open URL in a web page inside the app.
No, then we go to a new page.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
Tickets related to this pull-request: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
**Questions:**
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [APP-2813] App coins banner v2

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
Makes the whole banner clickable
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
Tickets related to this pull-request: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2813] - Make whole bonus banner clickable

- app-games/build.gradle.kts
Adds api versioning to Aptoide Games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2873](https://aptoide.atlassian.net/browse/APP-2873)
Tickets related to this pull-request: [APP-2873](https://aptoide.atlassian.net/browse/APP-2873)
[APP-2873]: https://aptoide.atlassian.net/browse/APP-2873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2873]: https://aptoide.atlassian.net/browse/APP-2873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2873] Add versioning to aptoide games

- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
Editorial View had an outdated and incorrect App Item pasted from GH back then. This PR makes it as it's supposed to be
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2906](https://aptoide.atlassian.net/browse/APP-2906)
Tickets related to this pull-request: [APP-2906](https://aptoide.atlassian.net/browse/APP-2906)
[APP-2906]: https://aptoide.atlassian.net/browse/APP-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2906]: https://aptoide.atlassian.net/browse/APP-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> [APP-2906] - Fix App Item in Editorial View

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
- Adds a check for empty tab splits and required splits to avoid making unnecessary calls for the dynamic splits request.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2886](https://aptoide.atlassian.net/browse/APP-2886)
Tickets related to this pull-request: [APP-2886](https://aptoide.atlassian.net/browse/APP-2886)
[APP-2886]: https://aptoide.atlassian.net/browse/APP-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2886]: https://aptoide.atlassian.net/browse/APP-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> [APP-2886] Add check for empty aab splits and required splits

- app-games/src/main/java/com/aptoide/android/aptoidegames/support/SupportScreen.kt
- Replaces the button in SupportScreen by the correct one, which is the primary button type.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2912](https://aptoide.atlassian.net/browse/APP-2912)
Tickets related to this pull-request: [APP-2912](https://aptoide.atlassian.net/browse/APP-2912)
[APP-2912]: https://aptoide.atlassian.net/browse/APP-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2912]: https://aptoide.atlassian.net/browse/APP-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> [APP-2912] Fix button in SupportScreen to match design

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BookmarkStar.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/AppJSON.kt
This PR aims to add the what's new box to the App View
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
Tickets related to this pull-request: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
**Questions:**
[APP-2881]: https://aptoide.atlassian.net/browse/APP-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2881]: https://aptoide.atlassian.net/browse/APP-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> [APP-2881] Add whats new to app view

- app-games/build.gradle.kts
This PR aims to replace all ws75.aptoide.com requests with ws2-cache.aptoide.com
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2943](https://aptoide.atlassian.net/browse/APP-2943)
Tickets related to this pull-request: [APP-2943](https://aptoide.atlassian.net/browse/APP-2943)
**Questions:**
[APP-2943]: https://aptoide.atlassian.net/browse/APP-2943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2943]: …
> [APP-2943] Change Store Domain

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt
This PR aims to make the buy button in payments always visible for the landscape view
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2973](https://aptoide.atlassian.net/browse/APP-2973)
Tickets related to this pull-request: [APP-2973](https://aptoide.atlassian.net/browse/APP-2973)
**Questions:**
[APP-2973]: https://aptoide.atlassian.net/browse/APP-2973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2973]: …
> [APP-2973] Make Buy button always visible in landscape

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Forward.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
This PR aims at fixing the forward button following the deisgn review. Somtimes it needs to be 24.dp with 18 just for the icon, other 32.dp
No
Open app and check if it is according to figma.
Tickets related to this pull-request: [APP-2975](https://aptoide.atlassian.net/browse/APP-2975)
**Questions:**
[APP-2975]: https://aptoide.atlassian.net/browse/APP-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2975] Fix foward button

- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/backgrounds/MoreBonusViewFooter.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/backgrounds/MoreBonusViewHeader.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/backgrounds/WantMoreViewFooter.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/backgrounds/WantMoreViewHeader.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Forward.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- Fixes design issues in the second design review of AG. Specifically, it fixes typography issues and issues in the paddings and flexibility of the bonus views.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2975](https://aptoide.atlassian.net/browse/APP-2975)
Tickets related to this pull-request: [APP-2975](https://aptoide.atlassian.net/browse/APP-2975)
[APP-2975]: https://aptoide.atlassian.net/browse/APP-2975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2975]: https://aptoide.atlassian.net/browse/APP-2975?atlOrigin=eyJpIjoiNWRk …
> [APP-2975] Design review v2

- app-games/build.gradle.kts
> Release 0.9.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
This PR aims to fix the Latest Box which in some languages words clip through the container.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
Tickets related to this pull-request: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
**Questions:**
[APP-2881]: https://aptoide.atlassian.net/browse/APP-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2881]: …
> [APP-2881] Fix whats new to app view

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/network/DownloaderRepository.kt
- Adds support for partial file downloads, through HTTP range requests.
- Removes file deletion in case of errors that cause its download to be complete. The file remains and if the download is retried it starts from the partial file, instead of downloading the entire file again.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3010](https://aptoide.atlassian.net/browse/APP-3010)
Tickets related to this pull-request: [APP-3010](https://aptoide.atlassian.net/browse/APP-3010)
**Questions:**
[APP-3010]: …
> [APP-3010] Add support for partial file downloads

- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- Fixes the navigation delay in AG by improving the logic that avoids duplicate navigation events.
- Replaces the navigation debouncer with a check for the screen destinations and the current destination lifecycle state. It should not navigate if the screen to navigate to is the same as the current one and the current screen lifecycle is not resumed yet.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2969](https://aptoide.atlassian.net/browse/APP-2969)
- Try duplicate clicks on an app item and check if it opens the AppView twice.
- Try clicking a category and immediately clicking an app item to check if there is a dela. It should be …
> [APP-2969] Fix navigation delay

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
- aptoide-installer/src/main/AndroidManifest.xml
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstallManager.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstaller.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/ObbService.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/InstallPermissions.kt
- extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
> Release ag 0.9.1

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstaller.kt
Add exceptions catching on abandoning past sessions.
I didn't find how to work with this correctly or how to restore the past sessions. So for now just mute the exceptions to not crash the app.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3021](https://aptoide.atlassian.net/browse/APP-3021)
[APP-3021]: https://aptoide.atlassian.net/browse/APP-3021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-3021] Fix app crashes on start

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
- Fixes the deeplink used in the bonus bundle screen.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
Tickets related to this pull-request: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2813] Fix bonus bundle screen deeplink

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
This PR aims to make the download string not hardcoded
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2643](https://aptoide.atlassian.net/browse/APP-2643)
Tickets related to this pull-request: [APP-2643](https://aptoide.atlassian.net/browse/APP-2643)
**Questions:**
[APP-2643]: https://aptoide.atlassian.net/browse/APP-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2643]: https://aptoide.atlassian.net/browse/APP-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> [APP-2643] Make downloads string not hardcoded

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
Tickets related to this pull-request: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)
**Questions:**
[APP-2881]: https://aptoide.atlassian.net/browse/APP-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> [APP-2881] Fix date format

- app-games/build.gradle.kts
It replaces all ws2-cache requests to ws75-cache ones.
No
See if every request is working as intended.
Flow on how to test this or QA Tickets related to this use-case: [APP-3078](https://aptoide.atlassian.net/browse/APP-3078)
Tickets related to this pull-request: [APP-3078](https://aptoide.atlassian.net/browse/APP-3078)
[APP-3078]: https://aptoide.atlassian.net/browse/APP-3078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3078]: https://aptoide.atlassian.net/browse/APP-3078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> [APP-3078] - Change Store Domain

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
(In draft while waiting for an answer to João's question in [APP-3014](https://aptoide.atlassian.net/browse/APP-3014)
Implements the new PTO design, occupying less space and also having less empty spaces
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3079](https://aptoide.atlassian.net/browse/APP-3079)
Tickets related to this pull-request: [APP-3079](https://aptoide.atlassian.net/browse/APP-3079)
[APP-3079]: https://aptoide.atlassian.net/browse/APP-3079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3079]: …
> [APP-3079] - New PTO Design

- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/ObbService.kt
- Fixes the cause of crashes related to the OBB Service, by improving the service binding and error handling.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3082](https://aptoide.atlassian.net/browse/APP-3082)
Tickets related to this pull-request: [APP-3082](https://aptoide.atlassian.net/browse/APP-3082)
[APP-3082]: https://aptoide.atlassian.net/browse/APP-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3082]: https://aptoide.atlassian.net/browse/APP-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> [APP-3082] Fix OBB related crashes

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
- Fixes deprecated code that started after the compose dependencies version was updated.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2991](https://aptoide.atlassian.net/browse/APP-2991)
Tickets related to this pull-request: [APP-2991](https://aptoide.atlassian.net/browse/APP-2991)
[APP-2991]: https://aptoide.atlassian.net/browse/APP-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2991]: https://aptoide.atlassian.net/browse/APP-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-2991] Fix compose deprecated code

- app-games/build.gradle.kts
Separates versioning between release & internal builds. 
Now we don't need to specify version by hand - it's automatically extracted from the release branch name.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3080](https://aptoide.atlassian.net/browse/APP-3080)
Tickets related to this pull-request: [APP-3080](https://aptoide.atlassian.net/browse/APP-3080)
[APP-3080]: https://aptoide.atlassian.net/browse/APP-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3080]: https://aptoide.atlassian.net/browse/APP-3080?atlOrigin=eyJpIjoiNW …
> [APP-3080] separate release and internal versioning

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
Makes UTM source different betwween prod and dev 
No
Flow on how to test this or QA Tickets related to this use-case: [AND-50](https://aptoide.atlassian.net/browse/AND-50)
Tickets related to this pull-request: [AND-50](https://aptoide.atlassian.net/browse/AND-50)
[AND-50]: https://aptoide.atlassian.net/browse/AND-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-50]: https://aptoide.atlassian.net/browse/AND-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-50] Make UTM source different betwween prod and dev

- app-games/src/main/res/values-el-rGR/strings.xml
- app-games/src/main/res/values-fa-rIR/strings.xml
- app-games/src/main/res/values-fr-rFR/strings.xml
- app-games/src/main/res/values-ro-rRO/strings.xml
- app-games/src/main/res/values-ru-rRU/strings.xml
- app-games/src/main/res/values-tr-rTR/strings.xml
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
Tickets related to this pull-request: [APP-XXXX](https://aptoide.atlassian.net/browse/APP-XXXX)
**Questions:**
> Apt games crowdin

- app-games/src/main/res/values-el-rGR/strings.xml
- app-games/src/main/res/values-fa-rIR/strings.xml
- app-games/src/main/res/values-fr-rFR/strings.xml
- app-games/src/main/res/values-nl-rNL/strings.xml
- app-games/src/main/res/values-ro-rRO/strings.xml
- app-games/src/main/res/values-ru-rRU/strings.xml
- app-games/src/main/res/values-tr-rTR/strings.xml
Merge new translations updates
> Translations updates

- extensions/src/main/java/cm/aptoide/pt/extensions/IntExtensions.kt
This PR aims to fix the download string format
No
Flow on how to test this or QA Tickets related to this use-case: [AND-96](https://aptoide.atlassian.net/browse/AND-96)
Tickets related to this pull-request: [AND-96](https://aptoide.atlassian.net/browse/AND-96)
**Questions:**
[AND-96]: https://aptoide.atlassian.net/browse/AND-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-96]: https://aptoide.atlassian.net/browse/AND-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> [AND-96] fix download string format

- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
It applies the design changes made on home review 2.0 related to the Categories Bundle, namely the items background, icon and text(only for the AllCategoriesView) colors for the home and the all categories.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-106](https://aptoide.atlassian.net/browse/AND-106)
Tickets related to this pull-request: [AND-106](https://aptoide.atlassian.net/browse/AND-106)
[AND-106]: https://aptoide.atlassian.net/browse/AND-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-106]: …
> [AND-106] - Apply Categories changes in Home Review 2.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/Mappers.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/di/RepositoryModule.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesViewModel.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/ViewModelProvider.kt
It connects the saved updates to the UI, including the sorting logic.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-89](https://aptoide.atlassian.net/browse/AND-89)
Tickets related to this pull-request: [AND-89](https://aptoide.atlassian.net/browse/AND-89)
[AND-89]: https://aptoide.atlassian.net/browse/AND-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-89]: https://aptoide.atlassian.net/browse/AND-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-89] - Connect saved updates to the UI

- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesViewModel.kt
It removes apps from the updates list when they are updated or uninstalled.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-87](https://aptoide.atlassian.net/browse/AND-87)
Tickets related to this pull-request: [AND-87](https://aptoide.atlassian.net/browse/AND-87)
[AND-87]: https://aptoide.atlassian.net/browse/AND-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-87]: https://aptoide.atlassian.net/browse/AND-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-87] - Handle apps updates and removals in updates logic

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BoltIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
**This is in draft because the strings are hardcoded**
This PR aims to create a List of App's that need Updating
No
Flow on how to test this or QA Tickets related to this use-case: [AND-84](https://aptoide.atlassian.net/browse/AND-84)
Tickets related to this pull-request: [AND-84](https://aptoide.atlassian.net/browse/AND-84)
**Questions:**
[AND-84]: https://aptoide.atlassian.net/browse/AND-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-84]: …
> [AND-84] Implement List of Updates UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
This PR aims to add a bottom padding to the bonus Banner Title
No
Flow on how to test this or QA Tickets related to this use-case: [AND-76](https://aptoide.atlassian.net/browse/AND-76)
Tickets related to this pull-request: [AND-76](https://aptoide.atlassian.net/browse/AND-76)
**Questions:**
[AND-76]: https://aptoide.atlassian.net/browse/AND-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-76]: https://aptoide.atlassian.net/browse/AND-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> [AND-76] Adds a bottom padding to bonus banner title

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesNotificationBuilder.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesPreferencesViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/repository/UpdatesPreferencesRepository.kt
This PR aims at creating a new setting for auto update
Yes 
Open, go to settings, check if it is on by default. Then try changing and check if in the next session it is ok.
Tickets related to this pull-request: [AND-146](https://aptoide.atlassian.net/browse/AND-146)
**Questions:**
[AND-146]: https://aptoide.atlassian.net/browse/AND-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-146] new auto update setting

- app-games/build.gradle.kts
- app-games/schemas/com.aptoide.android.aptoidegames.promotions.data.database.PromotionsDatabase/1.json
- app-games/src/main/java/com/aptoide/android/aptoidegames/ahab/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/PromotionBackground.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/PromotionBonusIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/analytics/AnalyticsProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/analytics/PromotionsAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/AGPromotionsRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/PromotionsRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/database/PromotionsDatabase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/database/SkippedPromotionEntity.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/database/SkippedPromotionsDao.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/database/SkippedPromotionsRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/model/PromotionsJson.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/domain/CompatiblePromotionsUseCase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/domain/Promotion.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/presentation/PromotionDialog.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/presentation/PromotionsViewModel.kt
Implements all the AHAB v2 logic, UI and analytics
Campaigns for Mobile Legends and Matchington Mansion created in dev.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-9](https://aptoide.atlassian.net/browse/AND-9)
Tickets related to this pull-request: [AND-9](https://aptoide.atlassian.net/browse/AND-9)
[AND-9]: https://aptoide.atlassian.net/browse/AND-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-9]: https://aptoide.atlassian.net/browse/AND-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> [AND-9] - ahab home dialog

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppItems.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
This PR aims add a string specific for AG inside the AppItem
No
Flow on how to test this or QA Tickets related to this use-case: [AND-149](https://aptoide.atlassian.net/browse/AND-149)
Tickets related to this pull-request: [AND-149](https://aptoide.atlassian.net/browse/AND-149)
**Questions:**
[AND-149]: https://aptoide.atlassian.net/browse/AND-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-149]: https://aptoide.atlassian.net/browse/AND-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> [AND-149] Create AppItemUpdate with a string specific for AG

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsInstallPackageInfoMapper.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
- feature_updates/build.gradle.kts
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/AutoUpdateWorker.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/di/RepositoryModule.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/di/ViewModelProvider.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesPreferencesViewModel.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/repository/UpdatesPreferencesRepository.kt
- install-info-mapper/src/main/java/cm/aptoide/pt/install_info_mapper/domain/CachingInstallPackageInfoMapper.kt
- install-info-mapper/src/main/java/cm/aptoide/pt/install_info_mapper/domain/InstallPackageInfoMapper.kt
It makes AG autoupdate all the apps that are installed by it every 24 hours (automatically), if the user has the auto-update setting on.
It also makes the getMeta calls on InstallPackageInfoMapper optional so we don't make getMeta requests when we auto-update, as we already have the needed information.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-147](https://aptoide.atlassian.net/browse/AND-147)
Tickets related to this pull-request: [AND-147](https://aptoide.atlassian.net/browse/AND-147)
[AND-147]: https://aptoide.atlassian.net/browse/AND-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> [AND-147] - Implement auto-update worker

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideAsyncImage.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
- buildSrc/src/main/kotlin/LibraryDependency.kt
This PR aims to add the possibility to click screenshots to see them in fullscreen
No
Flow on how to test this or QA Tickets related to this use-case: [AND-127](https://aptoide.atlassian.net/browse/AND-127)
Tickets related to this pull-request: [AND-127](https://aptoide.atlassian.net/browse/AND-127)
**Questions:**
[AND-127]: https://aptoide.atlassian.net/browse/AND-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-127]: https://aptoide.atlassian.net/browse/AND-127?atlOrigin=eyJpIj …
> [AND-127]support fullscreen screenshots

- app-games/src/main/java/com/aptoide/android/aptoidegames/network/repository/IdsRepository.kt
- Fixes crashes related to fetching the advertising id from google play services.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-131](https://aptoide.atlassian.net/browse/AND-131)
Tickets related to this pull-request: [AND-131](https://aptoide.atlassian.net/browse/AND-131)
**Questions:**
[AND-131]: https://aptoide.atlassian.net/browse/AND-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-131]: https://aptoide.atlassian.net/browse/AND-131?atlOrigin=eyJpIjo …
> [AND-131] Fix play services advertising id related crashes

- app-games/src/main/res/values-ar-rSA/strings.xml
- app-games/src/main/res/values-ms-rMY/strings.xml
Adds new strings and/or translations
> New strings and translations

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyBottomSheetContent.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/BadgeStateProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/TrustedIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/VerifiedIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Palette.kt
Adds trusted/certified badge to the Apkfy bottom sheet for the corresponding apps. And only if the corresponding feature flag is enabled 
Currently missing the actual feature flags repository implementation.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-160](https://aptoide.atlassian.net/browse/AND-160)
Tickets related to this pull-request: [AND-169](https://aptoide.atlassian.net/browse/AND-169)
**Related PRs:** [AND-163](#2117)
[AND-160]: https://aptoide.atlassian.net/browse/AND-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [AND-169] Apkfy client badge

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_flags/AptoideFeatureFlagsRepository.kt
- gradle/libs.versions.toml
- Adds firebase remote config dependency and a repository to use it and fetch config flags.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-163](https://aptoide.atlassian.net/browse/AND-163)
Tickets related to this pull-request: [AND-163](https://aptoide.atlassian.net/browse/AND-163)
[AND-163]: https://aptoide.atlassian.net/browse/AND-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-163]: https://aptoide.atlassian.net/browse/AND-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-163] Add Firebase Remote Config

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/TextInputBar.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
NOTE: This PR depends on https://github.com/Aptoide/aptoide-client-v8/pull/2117
This PR removes hardcoded strings and updates to strings from resources
No
Open the app and check the strings are there
Tickets related to this pull-request: [AND-184](https://aptoide.atlassian.net/browse/AND-184)
**Questions:**
[AND-184]: https://aptoide.atlassian.net/browse/AND-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-184] Replace hardcoded strings

- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
Adds indicative and firebase analytics for GameGenie as described in the ticket.
No
Check analytics on Firebase
Flow on how to test this or QA Tickets related to this use-case: [AND-199](https://aptoide.atlassian.net/browse/AND-199)
Tickets related to this pull-request: [AND-199](https://aptoide.atlassian.net/browse/AND-199)
**Questions:**
[AND-199]: https://aptoide.atlassian.net/browse/AND-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-199]: …
> [AND-199] Add GameGenie Analytics

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppItems.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
This PR aims to limit the title and the error message to one line and use ellipsis if it overflows
No
Flow on how to test this or QA Tickets related to this use-case: [AND-211](https://aptoide.atlassian.net/browse/AND-211)
Tickets related to this pull-request: [AND-211](https://aptoide.atlassian.net/browse/AND-211)
**Questions:**
[AND-211]: https://aptoide.atlassian.net/browse/AND-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-211]: …
> [AND-211] Limit the title and error  message to 1 line

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
It adds the app size in MB by segments like it's described in the documentation
No
Flow on how to test this or QA Tickets related to this use-case: [AND-195](https://aptoide.atlassian.net/browse/AND-195)
Tickets related to this pull-request: [AND-195](https://aptoide.atlassian.net/browse/AND-195)
**Questions:**
[AND-195]: https://aptoide.atlassian.net/browse/AND-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-195]: https://aptoide.atlassian.net/browse/AND-195?atlOrigin=eyJpIjoiN …
> [AND-195] Add app size to install analytics

- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyBottomSheetContent.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/DownloadPermissionState.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyStateProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/DownloadPermissionStateViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/InstallPermissions.kt
Aligns the Variant C UI behaviour to align with the requirements. 
Had to perform a minor refactoring to differentiate user permissions rejection in custom and system dialogs.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-222](https://aptoide.atlassian.net/browse/AND-222)
Tickets related to this pull-request: [AND-222](https://aptoide.atlassian.net/browse/AND-222)
[AND-222]: https://aptoide.atlassian.net/browse/AND-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-222]: …
> [AND-222] Update Apkfy Variant C UI behaviour

- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyBottomSheetContent.kt
Changes "See more" button caption with the new copy. 
No
Flow on how to test this or QA Tickets related to this use-case: [AND-231](https://aptoide.atlassian.net/browse/AND-231)
Tickets related to this pull-request: [AND-231](https://aptoide.atlassian.net/browse/AND-231)
**Questions:**
[AND-231]: https://aptoide.atlassian.net/browse/AND-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-231]: https://aptoide.atlassian.net/browse/AND-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [AND-231] Change copy on the Variant D

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
- aptoide-installer/build.gradle.kts
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchDownloader.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchFileDownloadListener.kt
- gradle/libs.versions.toml
- settings.gradle.kts
- Adds a package downloader that downloads files using the Fetch library.
No
See by commit.
Flow on how to test this or QA Tickets related to this use-case: [AND-215](https://aptoide.atlassian.net/browse/AND-215)
Tickets related to this pull-request: [AND-215](https://aptoide.atlassian.net/browse/AND-215)
[AND-215]: https://aptoide.atlassian.net/browse/AND-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-215]: https://aptoide.atlassian.net/browse/AND-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-215] Add Fetch package downloader

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/PoweredByAi.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/SuggestionBox.kt
Fix auto scrolling.
Auto scrolling had an issue that it wouldn't scroll all the way to the bottom of the last message and would get increasingly worse the more messages were sent.
No
Send some messages to GameGenie and check if the scroll is behaving correctly.
Flow on how to test this or QA Tickets related to this use-case: [AND-235](https://aptoide.atlassian.net/browse/AND-235)
Tickets related to this pull-request: [AND-235](https://aptoide.atlassian.net/browse/AND-235)
**Questions:**
[AND-235]: …
> [AND-235] Fixes auto-scrolling

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
- Fixes the download speed start time to avoid starting the timer while the user is still accepting permissions, before the download actually starts.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-196](https://aptoide.atlassian.net/browse/AND-196)
Tickets related to this pull-request: [AND-196](https://aptoide.atlassian.net/browse/AND-196)
[AND-196]: https://aptoide.atlassian.net/browse/AND-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-196]: https://aptoide.atlassian.net/browse/AND-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [AND-196] Fix download speed start time

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- Fixes setting the fetch downloader user property in indicative user properties.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-213](https://aptoide.atlassian.net/browse/AND-213)
Tickets related to this pull-request: [AND-213](https://aptoide.atlassian.net/browse/AND-213)
[AND-213]: https://aptoide.atlassian.net/browse/AND-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-213]: https://aptoide.atlassian.net/browse/AND-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-213] Fix fetch downloader analytics user property

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/analytics/AnalyticsProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/analytics/GameGenieAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/SuggestionBox.kt
Implement GameGenie Suggestion Analytics, making it possible to analyze which suggestions are being clicked by users
No
Flow on how to test this or QA Tickets related to this use-case: [AND-228](https://aptoide.atlassian.net/browse/AND-228)
Tickets related to this pull-request: [AND-228](https://aptoide.atlassian.net/browse/AND-228)
**Questions:**
[AND-228]: https://aptoide.atlassian.net/browse/AND-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-228]: …
> [AND-228] Implement GameGenie Suggestion Analytics

- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchDownloader.kt
Merge back unmerged changes from release-ag_1.5.0
> Release AG 1.5.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
Fixes a bug where the client was not sending the conversation id to the API and it was always returning a new one for each message. 
No
Flow on how to test this or QA Tickets related to this use-case: [AND-258](https://aptoide.atlassian.net/browse/AND-258)
Tickets related to this pull-request: [AND-258](https://aptoide.atlassian.net/browse/AND-258)
**Questions:**
[AND-258]: https://aptoide.atlassian.net/browse/AND-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-258]: …
> [AND-258] Fix conversation id not being sent to the API

- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
Unblocks updates DB cleaning on Updates initialisation. 
It was blocked by the `installManager.appsChanges` collection before, so effectively it never happened.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-247](https://aptoide.atlassian.net/browse/AND-247)
Tickets related to this pull-request: [AND-247](https://aptoide.atlassian.net/browse/AND-247)
[AND-247]: https://aptoide.atlassian.net/browse/AND-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-247]: https://aptoide.atlassian.net/browse/AND-247?atlOrigin=eyJpIjoiNWRkNTljNzYx …
> [AND-247] Aptoide Games self-update stays in list of updates

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
This PR aims at fixing the removed code based on the conflicts after mergin the chat history pr
No
Open app check it is ok. Test if gamegenie requests are using the same id after it is attributed.
Tickets related to this pull-request: [AND-258](https://aptoide.atlassian.net/browse/AND-258)
**Questions:**
[AND-258]: https://aptoide.atlassian.net/browse/AND-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-258] Save chat id for GameGenie requests

- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/repository/UpdatesPreferencesRepository.kt
This PR aims to check if the auto-update is turned on otherwise it wont update automatically
No
Flow on how to test this or QA Tickets related to this use-case: [AND-241](https://aptoide.atlassian.net/browse/AND-241)
Tickets related to this pull-request: [AND-241](https://aptoide.atlassian.net/browse/AND-241)
**Questions:**
[AND-241]: https://aptoide.atlassian.net/browse/AND-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-241]: …
> [AND-241] Add check to auto update method

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- build-logic/convention/src/main/kotlin/KeyHelper.kt
Make OEM provided from environment variables. 
It is easier to control this from the Jenkins Job side like we do with the signature.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-253](https://aptoide.atlassian.net/browse/AND-253)
Tickets related to this pull-request: [AND-253](https://aptoide.atlassian.net/browse/AND-253)
[AND-253]: https://aptoide.atlassian.net/browse/AND-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-253]: https://aptoide.atlassian.net/browse/AND-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> [AND-253] Make OEM provided from environment variables

- app-games/src/main/AndroidManifest.xml
- Turns off IAB in AG by disabling the payments entry points through manifest attribute replacement.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-281](https://aptoide.atlassian.net/browse/AND-281)
Tickets related to this pull-request: [AND-281](https://aptoide.atlassian.net/browse/AND-281)
[AND-281]: https://aptoide.atlassian.net/browse/AND-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-281]: https://aptoide.atlassian.net/browse/AND-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> [AND-281] Turn off IAB in AG

- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/presentation/PromotionDialog.kt
Fixes mmp values for the promotions. 
Hod to refactor promotions UI logic and add missing analytics context overrides.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-244](https://aptoide.atlassian.net/browse/AND-244)
Tickets related to this pull-request: [AND-244](https://aptoide.atlassian.net/browse/AND-244)
[AND-244]: https://aptoide.atlassian.net/browse/AND-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-244]: https://aptoide.atlassian.net/browse/AND-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> [AND-244] Aptoide mmp value is wrong

- app-games/src/main/java/com/aptoide/android/aptoidegames/design_system/AGButton.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewShort.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
- app/src/main/java/cm/aptoide/pt/appview/DownloadView.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
- download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/Mappers.kt
This PR aims at implementing the migration flow. Meaning we can update apps that have a different signature (google versions)
PS: We are missing design and translations/copy confirmation. For that reason, there are hardcoded strings on the InstallView and InstallViewShort.
No
You can find any app that integrated with a different signature, or just edit on the DownloadViewModel signature check on the if condition, by adding +"random" to ensure the signature is different.
Then check if the button says Update to Appc (hardcoded) or Update in home (or other places where we have the short install view). After pressing it, make sure it uninstalls the currently installed …
> [AND-103] update to appc

- app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
This PR aims to allow promo codes usage to outdated wallets 
No
Flow on how to test this or QA Tickets related to this use-case: [AND-284](https://aptoide.atlassian.net/browse/AND-284)
Tickets related to this pull-request: [AND-284](https://aptoide.atlassian.net/browse/AND-284)
**Questions:**
[AND-284]: https://aptoide.atlassian.net/browse/AND-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-284]: https://aptoide.atlassian.net/browse/AND-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> [AND-284] Makes the outdated wallet count as installed

- app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/analytics/PromoCodeAnalytics.kt
- Removes the analytics context usage from the promo codes analytics events.
- Fixes the type parameter used in the promo codes analytics events.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-245](https://aptoide.atlassian.net/browse/AND-245)
Tickets related to this pull-request: [AND-245](https://aptoide.atlassian.net/browse/AND-245)
[AND-245]: https://aptoide.atlassian.net/browse/AND-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-245]: https://aptoide.atlassian.net/browse/AND-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [AND-245] Fix promocodes analytics

- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/AGPromotionsRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/data/model/PromotionsJson.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/domain/CompatiblePromotionsUseCase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/domain/Promotion.kt
Adds support for non-PSV Ahab campaigns. 
Had to refactor the use case a bit for readability and maintainability.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-252](https://aptoide.atlassian.net/browse/AND-252)
Tickets related to this pull-request: [AND-252](https://aptoide.atlassian.net/browse/AND-252)
[AND-252]: https://aptoide.atlassian.net/browse/AND-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-252]: https://aptoide.atlassian.net/browse/AND-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
> [AND-252] Add support for non-PSV Ahab campaigns

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/TextInputBar.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AGTypography.kt
Update GameGenie typography with a new Chat and ChatBold typography
No
See commit
Open GameGenie and check the new typography
Tickets related to this pull-request: [AND-200](https://aptoide.atlassian.net/browse/AND-200)
**Questions:**
[AND-200]: https://aptoide.atlassian.net/browse/AND-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-200] Update GameGenie typography

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewAppPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewAppVersionPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewsPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
This Pr aims to add the news item promotional card to AG
No
Flow on how to test this or QA Tickets related to this use-case: [AND-265](https://aptoide.atlassian.net/browse/AND-265)
Tickets related to this pull-request: [AND-265](https://aptoide.atlassian.net/browse/AND-265)
**Questions:**
[AND-265]: https://aptoide.atlassian.net/browse/AND-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-265]: https://aptoide.atlassian.net/browse/AND-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
> [AND-265] implement news item promotional card

- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/EventPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
This PR aims to create the event promotional card for AG
No
Flow on how to test this or QA Tickets related to this use-case: [AND-264](https://aptoide.atlassian.net/browse/AND-264)
Tickets related to this pull-request: [AND-264](https://aptoide.atlassian.net/browse/AND-264)
**Questions:**
[AND-264]: https://aptoide.atlassian.net/browse/AND-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-264]: https://aptoide.atlassian.net/browse/AND-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
> [AND-264] Create event promotional card

- app-games/src/main/java/com/aptoide/android/aptoidegames/firebase/FirebaseNotificationBuilder.kt
- Includes all extras that come with a firebase notification message in firebase notifications that are created while AG is on foreground.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-282](https://aptoide.atlassian.net/browse/AND-282)
Tickets related to this pull-request: [AND-282](https://aptoide.atlassian.net/browse/AND-282)
[AND-282]: https://aptoide.atlassian.net/browse/AND-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-282]: https://aptoide.atlassian.net/browse/AND-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> [AND-282] Fix click intent in foreground firebase notifications

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/terms_and_conditions/LegalUrls.kt
Removes payments section from the settings screen. 
Also removed unused code.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-290](https://aptoide.atlassian.net/browse/AND-290)
Tickets related to this pull-request: [AND-290](https://aptoide.atlassian.net/browse/AND-290)
[AND-290]: https://aptoide.atlassian.net/browse/AND-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-290]: https://aptoide.atlassian.net/browse/AND-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-290] Remove payments section from the settings screen

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- Updates all the outdated dependency versions declared in the version catalog.
- Updates the gradle version in the gradle wrapper.
No
- Check the app in general to make sure there are no changes in behavior.
Flow on how to test this or QA Tickets related to this use-case: [AND-302](https://aptoide.atlassian.net/browse/AND-302)
Tickets related to this pull-request: [AND-302](https://aptoide.atlassian.net/browse/AND-302)
[AND-302]: https://aptoide.atlassian.net/browse/AND-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-302]: …
> [AND-302] Update AG dependency versions

- feature-apkfy/src/main/java/cm/aptoide/pt/feature_apkfy/domain/ApkfyModel.kt
- Fixes obfuscated parameter names in ApkfyModel instances that are sent to mmp analytics
No
Flow on how to test this or QA Tickets related to this use-case: [AND-314](https://aptoide.atlassian.net/browse/AND-314)
Tickets related to this pull-request: [AND-314](https://aptoide.atlassian.net/browse/AND-314)
[AND-295]: https://aptoide.atlassian.net/browse/AND-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-295]: https://aptoide.atlassian.net/browse/AND-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [AND-314] Fix obfuscated ApkfyModel in mmp analytics

- app-games/src/main/res/values/strings.xml
- Removes AG unused strings and their respective translations.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-312](https://aptoide.atlassian.net/browse/AND-312)
Tickets related to this pull-request: [AND-312](https://aptoide.atlassian.net/browse/AND-312)
[AND-312]: https://aptoide.atlassian.net/browse/AND-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-312]: https://aptoide.atlassian.net/browse/AND-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-312] Remove AG unused strings and respective translations

- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialMoreScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/GamesScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRow.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRowStateProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/TopChartsView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsListRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsListRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppsBySortUseCase.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/AllCategoriesUiState.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/AllCategoriesViewModel.kt
- Creates the UI required to show a view with the top charts app list. In this case, the app list sorted by downloads.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-317](https://aptoide.atlassian.net/browse/AND-317)
Tickets related to this pull-request: [AND-317](https://aptoide.atlassian.net/browse/AND-317)
[AND-317]: https://aptoide.atlassian.net/browse/AND-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-317]: https://aptoide.atlassian.net/browse/AND-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> [AND-317] Create top charts UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/AdViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/MintegralAd.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/ViewModelProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstallManager.kt
- extension/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt
Merge back the release branch changes.
> Release AG 1.10.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
This PR aims to remove the duplicated Indicative download event
No
Install AG (clean install) & prepare to use Charles
Start the apkfy flow for an app with obbs such as downloading pubg from the web
Open AG and download the game from the step above
Finish the flow by installing, then wait until all the Indicative events are present in Charles
Tickets related to this pull-request: [AND-376](https://aptoide.atlassian.net/browse/AND-376)
**Questions:**
[AND-376]: https://aptoide.atlassian.net/browse/AND-376?atlOrigin=eyJpIjoiNWRkNTljN …
> [AND-376] Check process name before starting Indicative

- app-games/schemas/com.aptoide.android.aptoidegames.gamegenie.data.database.GameGenieDatabase/3.json
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieApiService.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieAppRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieAppRepositoryImpl.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieDatabase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/di/GameGenieModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/domain/ChatInteractionHistory.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/domain/GameGenieChatHistory.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/io_models/ChatInteractionResponse.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/io_models/GameGenieRequest.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/io_models/GameGenieResponse.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieFeatureProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieManager.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieUseCase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/Mappers.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
This PR aims to adapt the client to the backend sending the full app information got from getPackages call. This includes adapting the saving conversation history since we can't be saving that much information locally.
This PR also aims to get the device's apps that are not system apps to give more context to the LLM.
No
See commit
Open the app and check everything is working fine, including history.
Tickets related to this pull-request: [AND-359](https://aptoide.atlassian.net/browse/AND-359)
Tickets related to this pull-request: [AND-360](https://aptoide.atlassian.net/browse/AND-360)
**Questions:**
Does this add new dependencies …
> [AND-359/360] Update client to receive full app data/Send device metadata to backend

- app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/AppComingSoonPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/EventPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewAppPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewAppVersionPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewsPromotionalView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
This PR aims to remove the allocated space from widgets that fail to load
No
Flow on how to test this or QA Tickets related to this use-case: [AND-350](https://aptoide.atlassian.net/browse/AND-350)
Tickets related to this pull-request: [AND-350](https://aptoide.atlassian.net/browse/AND-350)
**Questions:**
[AND-305]: https://aptoide.atlassian.net/browse/AND-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-305]: https://aptoide.atlassian.net/browse/AND-305?atlOrigin=eyJpIjoiNWRkNTl …
> [AND-350] Remove empty space from  unsupported widget types

- app-games/src/main/java/com/aptoide/android/aptoidegames/Platform.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieAppRepositoryImpl.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/InstallerSelector.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideAABInterceptor.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/AABInterceptor.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/AptoideWidgetsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsListRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/SplitsRepositoryImpl.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/data/AptoideCategoriesRepository.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/network/UpdatesApi.kt
- Adds an interceptor that decides whether or not endpoints should fetch apps with AABs.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-397](https://aptoide.atlassian.net/browse/AND-397)
Tickets related to this pull-request: [AND-397](https://aptoide.atlassian.net/browse/AND-397)
[AND-397]: https://aptoide.atlassian.net/browse/AND-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-397]: https://aptoide.atlassian.net/browse/AND-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-397] Disable aab for miui under api 30

- app-games/src/main/java/com/aptoide/android/aptoidegames/Platform.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieAppRepositoryImpl.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieDatabase.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/di/GameGenieModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/InstallerSelector.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideAABInterceptor.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/AABInterceptor.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/data/AptoideWidgetsRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsListRepository.kt
- feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/SplitsRepositoryImpl.kt
- feature_categories/src/main/java/cm/aptoide/pt/feature_categories/data/AptoideCategoriesRepository.kt
- feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
- feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/network/UpdatesApi.kt
Merge back the release branch changes.
> Release AG 1.11.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/dto/AnalyticsData.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/GamesScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsData.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsInstallPackageInfoMapper.kt
This PR aims to add tab param for clicks/download/install events
Yes | No
Flow on how to test this or QA Tickets related to this use-case: [AND-389](https://aptoide.atlassian.net/browse/AND-389)
Tickets related to this pull-request: [AND-389](https://aptoide.atlassian.net/browse/AND-389)
**Questions:**
[AND-389]: https://aptoide.atlassian.net/browse/AND-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-389]: https://aptoide.atlassian.net/browse/AND-389?atlOrigin=eyJpIjoiNWRkNTljNz …
> [AND-389] Add tab for clicks/download/install event for all tabs

- app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/Platform.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
This PR aims to disable the Mintegral ads for HMD devices
No
Flow on how to test this or QA Tickets related to this use-case: [AND-416](https://aptoide.atlassian.net/browse/AND-416)
Tickets related to this pull-request: [AND-416](https://aptoide.atlassian.net/browse/AND-416)
**Questions:**
[AND-416]: https://aptoide.atlassian.net/browse/AND-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-416]: https://aptoide.atlassian.net/browse/AND-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> [AND-416] Hide CPI Ads for HMD

- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/backgrounds/MoreBonusViewHeader.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreScreen.kt
This PR aims to fix the banner when on landscape view
No
Flow on how to test this or QA Tickets related to this use-case: [AND-379](https://aptoide.atlassian.net/browse/AND-379)
Tickets related to this pull-request: [AND-379](https://aptoide.atlassian.net/browse/AND-379)
**Questions:**
[AND-379]: https://aptoide.atlassian.net/browse/AND-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-379]: https://aptoide.atlassian.net/browse/AND-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [AND-379] update 20% bonus view UI

- app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRow.kt
Merge back the release branch changes.
> Release AG 1.12.0

- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/AptoideVIPUpdatesProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesNotificationBuilder.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/VIPUpdatesProvider.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/VIPUpdatesWorker.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesNotificationProvider.kt
This PR aims at implementing vip updates where certain apps (defined on firebase) will be polled every hour to check if there are updates available. If so, we show an update notification.
We also developed the code for it to be automatically downloaded, but we kept if under a hardcoded flag.
No
Install old verisons of the apps in the firebase remote config for vip updates: Roblox, free fire and free fire max and check the result of the worker and its notifications.
Tickets related to this pull-request: [AND-433](https://aptoide.atlassian.net/browse/AND-433)
**Questions:**
Does this add new dependencies which need to be added? (Eg. …
> [AND-433] VIP updates

- app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
- Fixes an issue with the Youtube player in the AppView, where the mute button freezes the video. Also fixes the full screen YouTube view not being focusable and its controls not being shown.
- Makes the YoutubePlayer view actually be fullscreen in the dialog/fullscreen view.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-451](https://aptoide.atlassian.net/browse/AND-451)
Tickets related to this pull-request: [AND-451](https://aptoide.atlassian.net/browse/AND-451)
[AND-451]: https://aptoide.atlassian.net/browse/AND-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> [AND-451] Fix YoutubePlayerView state and view focus issues

- app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/AptoideVIPUpdatesProvider.kt
Merge back the release branch changes.
> Release AG 1.15.0

- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/VIPUpdatesWorker.kt
- feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
This PR implements Auto update on VIP updates feature.
No
Change the timming of the worker. Install an old version of a VIP app with vanilla (For example). Check if you receive the notification. Install an old version of a VIP app with AG (deeplink). Check if it automatically updates.
Confirm if you dont receive the notification more than once.
Remember about the rules of the unknown sources permissions, shouldAutoupdate flag.
Tickets related to this pull-request: [AND-461](https://aptoide.atlassian.net/browse/AND-461)
**Questions:**
**Code Review …
> [AND-461] trigger auto update vip

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/di/NetworkModule.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/presentation/RTBAppListViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/presentation/RTBSectionView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/presentation/ViewModelProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/AptoideRTBRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/RTBApi.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/RTBRepository.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/RTBRequest.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/RTBResponse.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
- aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
- environment-info/src/main/java/cm/aptoide/pt/environment_info/DeviceInfo.kt
- environment-info/src/main/java/cm/aptoide/pt/environment_info/repository/DeviceInfoRepository.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Bundle.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
- feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Widget.kt
This PR aims at implementing the RTB bundle mapping and respective call.
Note that there is still no widget and the RTB system has not been deployed yet. To test it you will have to add a rewrite to add the widget (ask me for it) and you will have to change the call from the RTB system to the local json response (hence some of the commented code) or rewrite it with charles as well (but be careful with the response code, which you can not change on some versions of charles).
No
Check by commit
As mentioned before, the api part is not done yet. So you will have to map it locally or rewrite.  …
> [AND-460] Integrate RTB

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieYoutubePlayer.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GenieSearchView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
This PR aims to fix video flickering when scrolling and exchanging messages, make the chat scroll to the top of the last user message instead of the bottom of the conversation, maintaining the default scroll to the bottom when opening a chat from history.
No
See commit
Ask Genie for videos and scroll the chat and check if there are flickers, also ask for long messages and check where it scrolls to 
Tickets related to this pull-request: [AND-506](https://aptoide.atlassian.net/browse/AND-506)
**Questions:**
[AND-506]: …
> [AND-506] Fix video flickering, scroll when sending message, text input copy

- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/ProfileNoAccountIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRow.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesToolBar.kt
- Implement structural and icon changes in AG top app bar, to match design changes.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-500](https://aptoide.atlassian.net/browse/AND-500)
Tickets related to this pull-request: [AND-500](https://aptoide.atlassian.net/browse/AND-500)
[AND-500]: https://aptoide.atlassian.net/browse/AND-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-500]: https://aptoide.atlassian.net/browse/AND-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-500] Implement top app bar changes

- app-games/build.gradle.kts
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyHandler.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyRobloxInstallView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyStateProvider.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/ApkfyUiState.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/CompanionAppsSelectionViewModel.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/presentation/RobloxApkfyMultiInstallScreen.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/FireIcon.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/InstallerQueueHandler.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
- app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt
This PR aims at implementing experiment 8 for roblox apkfy. Where users will see a list of companion apps to install with roblox apk.
No
See by commit.
Open the app through apkfy flow with roblox check if everything is ok. Confirm that analytics and campaigns are converted.
Tickets related to this pull-request: [AND-497](https://aptoide.atlassian.net/browse/AND-497)
**Questions:**
[AND-497]: https://aptoide.atlassian.net/browse/AND-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-497] experiment 8

- app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/GameCompanionIcon.kt
This PR aims to fix the pixelated images on the game companion section of the GameGenie entry screen.
It also scales up adaptive icons which can have a larger background and were being rendered with it.
No
GameCompanionIcon.kt
Open entry screen and check the icons
Tickets related to this pull-request: [AND-552](https://aptoide.atlassian.net/browse/AND-552)
**Questions:**
[AND-552]: https://aptoide.atlassian.net/browse/AND-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-552] Fix Game Companion icons
