Aptoide/aptoide-client-v8

model/src/main/java/cm/aptoide/pt/model/v7/timeline/MinimalCard.java
model/src/main/java/cm/aptoide/pt/model/v7/timeline/SocialCardStats.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/CardToDisplayableConverter.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialArticleDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialInstallDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialStoreLatestAppsDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialVideoDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialArticleWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialInstallWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialStoreLatestAppsWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialVideoWidget.java
v8engine/src/main/res/layout/social_info_bar_timeline.xml
v8engine/src/main/res/layout/social_last_comment_bar.xml
v8engine/src/main/res/layout/timeline_sub_minimal_card.xml

This pull-request adds the social info bar (likes preview + number of comments + last comment made) to the Aggregated card shares (sub-cards - minimal cards).
Open Aptoide v8 > Apps Timeline > Find aggregated cards > check if it has likes & comments and if they show up in the social info bar. If not, make a comment/like in it.
Tickets related to this pull-request: [AN-1646](https://aptoide.atlassian.net/browse/AN-1646).
Screenshots (if appropriate)
N/A
Questions:

[AN-1646] Add social info bar to the aggregated minimal cards.

---

v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialArticleDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialInstallDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialStoreLatestAppsDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/displayable/AggregatedSocialVideoDisplayable.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialArticleWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialInstallWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialStoreLatestAppsWidget.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/timeline/view/widget/AggregatedSocialVideoWidget.java
v8engine/src/main/res/layout/apps_timeline_multiple_heads_card_header.xml
v8engine/src/main/res/layout/timeline_sub_minimal_card.xml

This pull-request adds the possibility to show multiple people that shared via the same social card and generated an Aggregated social card.
This will show up multiple heads/names inside minimal cards of the Aggregated cards.
Open Aptoide v8 > Apps Timeline > Find aggregated cards > check if multiple people show up in some of the minimal cards. (if you are following ana2016, nzxt, trinkes15, it should happen, ask me about this).
Tickets related to this pull-request: [AN-1641](https://aptoide.atlassian.net/browse/AN-1641).
[Final result example](https://my.pcloud.com/publink/show?code=XZgYU3ZqlQ7G27pbqQd7jG5STRygVRA3KFk)
Questions:
Is there …

[AN-1641] Added multiple names support to the minimal card headers

---

v8engine/src/main/java/cm/aptoide/pt/v8engine/store/StoreTheme.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/view/account/MyAccountNavigator.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/view/account/store/ManageStoreFragment.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/view/account/store/ManageStorePresenter.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/view/account/store/ThemeSelectorViewAdapter.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/view/store/GridStoreMetaWidget.java

This pull request fixes the ticket https://aptoide.atlassian.net/browse/AN-1764
This was not related to the store image but the store theme was going as an empty string in the request so the services returned a different error in each case (having store picture or not).
In case the user does not press a specific theme the default is used to create the store since it is also the default selected theme in the presented UI.

AN-1764: fixed error message related to create store

---

v8engine/src/main/java/cm/aptoide/pt/v8engine/view/wizard/WizardFragment.java

What does this pull request do?
This pull request is an attemp to fix this [issue](https://www.fabric.io/aptoide2/android/apps/cm.aptoide.pt/issues/596f626dbe077a4dcccd145f?time=last-seven-days).
Navigate in the wizard pages and try pressing the round icons to check if app crashes

Wizard Presenter is throwing a null pointer on page selection

---

v8engine/src/main/java/cm/aptoide/pt/v8engine/social/presenter/TimelinePresenter.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/TimelineFragment.java
v8engine/src/main/java/cm/aptoide/pt/v8engine/social/view/TimelineView.java

This pull-request fixes the UX when a Post in Timeline is submitted. The loading spinner stays until getUserTimeline with cardId response arrives.
Open Aptoide v8 > Timeline > click on FAB > make a Post > check if spinner stays until Timeline with cardId response gets to client.
Tickets related to this pull-request: [AN-1866](https://aptoide.atlassian.net/browse/AN-1866)
N/A
Questions:

[AN-1866] Fixing Post in Timeline navigation.

---

v8engine/src/main/java/cm/aptoide/pt/v8engine/social/data/share/SharePostViewSetup.java

This pull-request fixes the share preview behaviour when user does not have store. It now shows userName and default avatar.
Open Aptoide v8 > create account  with username without store > go to timeline > share any card > check if card preview shows default avatar + username on the header.
Tickets related to this pull-request: [AN-1885](https://aptoide.atlassian.net/browse/AN-1885)
N/A
Questions:

[AN-1885] Show userName instead of storeName when there is no store.

---

app/src/main/java/cm/aptoide/pt/social/data/MinimalCardViewFactory.java
app/src/main/java/cm/aptoide/pt/social/presenter/TimelinePresenter.java
app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialMediaViewHolder.java
app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialPostMediaViewHolder.java
app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialPostRecommendationViewHolder.java
app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialRecommendationViewHolder.java
app/src/main/java/cm/aptoide/pt/social/view/viewholder/SocialStoreViewHolder.java

This PR fixes the click on likes preview (user/store images that liked a card) on social Social Post cards (we were dealing with a cast exception).
This PR also adds the option to click on likes text (8 likes / User X Liked) text to go to the likes list. (in the future we should change User X Liked to jump directly to the user's store/timeline.)

[AN-2007] Fixing click on likes preview (social post cards) & likes text clickable

---

app/src/main/java/cm/aptoide/pt/spotandshare/view/SpotAndShareActivityView.java

Spot and share was crashing after pressing start button.
It was not using vanilla's ActivityView interface so it was crashing while trying to cast to ActivityView on BaseActivity.

[AN-2212] SpotAndShareActivityView now extends Vanilla's ActivityView

---

dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppRequest.java

Change from using the body with uname to the one with md5 on the getAppRequest, on method ofMd5.

[AN-2211] Fixed rollback on updated app

---

app/src/main/java/cm/aptoide/pt/view/recycler/displayable/DisplayablesFactory.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/MyStore.java

The problem:
1. Logout if you're logged in;
2. Go to MyStoreFragment tab;
- problem: displays a create store widget;
- expected: displays a login widget;
The fix:
When the user is logged out, the MyStoresFragment should have a LoginDisplayable.
The current scenario was adding a CreateStoreWidget, because the MyStore viewObject was the one giving information if the user is or is not logged in.
This responsibility is from the AptoideAccountManager, so now the DisplayablesFactory adds the right displayable according to the user's log in state.

[AN-2218] Fixed misplaced CreateStoreDisplayble on MyStoresFragment

---

app/src/main/java/cm/aptoide/pt/account/AccountAnalytics.java
app/src/main/java/cm/aptoide/pt/account/GoogleSignUpAdapter.java
app/src/main/java/cm/aptoide/pt/account/GoogleSignUpException.java

Login FAIL is now split in FAIL (aptoide failure) and INVALID (user failure - includes back on permissions/social login, invalid signup fields (empty + validate), google error status code 12501.

[AN-2233] add login invalid status code

---

app/proguard-rules.pro
app/src/androidTest/java/cm/aptoide/pt/MockApplicationModule.java
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/search/suggestions/SearchSuggestionRemoteRepository.java

In production variant, calls to the suggestions api would crash (search app & search store).
This was due to the fact Single was being used in the retrofit interface. ref ( https://github.com/square/retrofit/issues/1584)
solution was to add proguard rule.
Also did some name refactoring and moved the suggestions api version to the base url, which is provided by the dagger app module.

[Hotfix/AN-2235] ANR suggestions add store

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/analytics/ScreenTagHistory.java
app/src/main/java/cm/aptoide/pt/analytics/analytics/AnalyticsManager.java
app/src/main/java/cm/aptoide/pt/analytics/analytics/AnalyticsNormalizer.java
app/src/test/java/cm/aptoide/pt/analytics/ScreenTagHistoryTest.java
app/src/test/java/cm/aptoide/pt/analytics/analytics/AnalyticsManagerTest.java
app/src/test/java/cm/aptoide/pt/analytics/analytics/AnalyticsNormalizerTest.java

This pull request deploys a fix to the Analytics lib that was throwing a NullPointerException when a certain key-value pair attribute in the Event body had a null value. 
Now every value in that situation will be set to an empty string: ""
The ScreenTagHistory class was also affected by this PR changes. 
The getters now don't return null when requested, they return "" otherwise.
No
**How should this be tested?**
Unit tests: AnalyticsNormalizerTest ; ScreenTagHistoryTest.java
Tickets related to this pull-request: [ASV-141](https://aptoide.atlassian.net/browse/ASV-141)

[Hotfix/ASV-141] Appview error analytics NPE

---

app/src/main/java/cm/aptoide/pt/home/BottomNavigationNavigator.java
app/src/main/java/cm/aptoide/pt/search/SearchNavigator.java
app/src/main/java/cm/aptoide/pt/store/view/StoreFragment.java
app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
app/src/vanilla/java/cm/aptoide/pt/presenter/MainPresenter.java
app/src/vanilla/java/cm/aptoide/pt/view/ActivityModule.java

Navigates to the desired views without sending BN analytics
It also solves the problem with the wrong navigation from the search widget(check 253 ticket)
No
DeepLinkManager
Uses the search widget and the shortcuts navigation and see if it crashes
Also, a request focus was put in StoreFragment. As you know this class is old and used in a lot of places so check if the BN button of the stores doesn't get focused when it shouldn't be
https://aptoide.atlassian.net/browse/ASV-291
https://aptoide.atlassian.net/browse/ASV-253

[bugfix/ASV-291]  DeepLinks sending BN analytics

---

app/src/main/java/cm/aptoide/pt/home/AptoideBottomNavigator.java
app/src/main/java/cm/aptoide/pt/home/BottomHomeFragment.java
app/src/main/java/cm/aptoide/pt/home/BottomNavigationActivity.java
app/src/main/java/cm/aptoide/pt/view/BaseFragment.java

This PR should solve the loading more not being shown correctly issue.
We were not using distinct until changed correctly since it wasn't filtering out by boolean but by scroll event, which was why it was emitting more than once that it reached bottom, causing race condition problems that would end up hiding the loading more animation right after showing it.
No
scroll until the end of the list, rotate screen, scroll, go to app view, go back etc
Tickets related to this pull-request: [ASV-223](https://aptoide.atlassian.net/browse/ASV-223)

[Bugfix/ASV-223] bug fix: Home menu - loading more

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
app/src/main/res/layout/apps_active_download_app_item.xml
app/src/main/res/layout/apps_completed_download_app_item.xml
app/src/main/res/layout/apps_error_download_app_item.xml
app/src/main/res/layout/apps_error_update_app_item.xml
app/src/main/res/layout/apps_header_item.xml
app/src/main/res/layout/apps_header_updates_item.xml
app/src/main/res/layout/apps_installed_app_item.xml
app/src/main/res/layout/apps_standby_download_app_item.xml
app/src/main/res/layout/apps_standby_update_app_item.xml
app/src/main/res/layout/apps_update_app_item.xml
app/src/main/res/layout/apps_updating_app_item.xml
app/src/main/res/layout/fragment_apps.xml

Fix the filling of the AppsFragment. Before, the installed would come first and then, when the updates and the downloads (if existent) were added to the view, the view would be still be focused on the installed apps.
Now it only shows the list when all apps are ready.
No
- AppsFragment
Open AppsFragment and the view should be focused on the Downloads or the updates (if there are any at the moment).
Tickets related to this pull-request: [ASV-265](https://aptoide.atlassian.net/browse/ASV-265)
**Questions:**

[bugfix/ASV-265] Correctly Fill Apps Fragment

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsAdapter.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsFragmentView.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java

There is a problem regarding the lib we use to manage the downloads (FileDownloader). When a download is cancelled, "the lib" will pause it and remove it. This means that after we cancel a download, we will also get an update with a paused download (a paused download will be drawn on the view).  After that update, there would be also another one with empty information regarding the cancelled download (only with packagename and md5).
The ideal fix for this problem would be to update the lib (current version = 1.4.1, last available version =
1.7.2). This would possibly require to update all the callbacks on the DownloadTask class. Ideally there should be a callback for the removed downloads, if not we should create an issue.
This pull request fixed this issue, but …

[ASV-266] Remove download after cancelling it

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/search/SearchManager.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListSearchAppsRequest.java

This PR aims to fix the problem with mature not being sent on listSearchApps request
No
Open charles, do search, verify that the mature field matches the preference you have selected 
Tickets related to this pull-request: [ASV-285](<https://aptoide.atlassian.net/browse/ASV-285>)

[ASV-285] Fixed mature not being sent in the listSearchApps request;

---

app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java

This PR aims to fix a bug where aptoide would crash when you tried to install the ASF wallet without an internet connection
No
Make sure you don't have ASF Wallet installed -> install trivial drive -> turn off internet -> open trivial drive -> try to install the wallet through aptoide -> you should now go to the home no network empty state instead of crashing
Tickets related to this pull-request: [ASV-406](<https://aptoide.atlassian.net/browse/ASV-406>)

[ASV-406] Fixed the crash when you try to navigate to install wallet without internet connection

---

app/src/main/java/cm/aptoide/pt/share/NotLoggedInShareFragment.java

If the user is not logged in, and tries to install an app on the AppView, on the 2nd and 4th install, a popup dialog will be shown asking the user to log in. Before, the clickhandler was not being unregistered
No
Install an app for the 2nd and 4th time and you will see the popup. Then try pressing the back button to leave the AppView.
Tickets related to this pull-request: [ASV-430](https://aptoide.atlassian.net/browse/ASV-430)
**Questions:**

[ASV-430] Back button does not respond

---

app/src/main/java/cm/aptoide/pt/home/AdsBundleViewHolder.java
app/src/main/java/cm/aptoide/pt/home/AppsBundleViewHolder.java
app/src/main/java/cm/aptoide/pt/home/EditorsBundleViewHolder.java

Home bundle titles are now being translated again locally by the Translator.java class.
Have in mind that this Translator class needs to be refactored in the future, here: [ASV-486](https://aptoide.atlassian.net/browse/ASV-486)
No
Get PT translations (you can copy the strings.xml to a values-pt folder in res/ and make your own translations). Change phone to portuguese and see if home bundle titles are being translated.
Tickets related to this pull-request: [ASV-402](https://aptoide.atlassian.net/browse/ASV-402)

[Bugfix/ASV-402] home bundles translations

---

app/src/main/res/layout/home_bundle_header.xml

The bundles title in home is now aligned with the center of the More button
No
Tickets related to this pull-request: [ASV-499](https://aptoide.atlassian.net/browse/ASV-499)

[Bugfix/ASV-499] home bundles centered title

---

app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java

Fixed install on appview deeplink from aptoide website. Before, the getApp request coming from the deeplink was being done with an empty string as package name.
Also fixed the share on toolbar that was crashing every time it was clicked because it was trying to show things on the view without being on the main thread.
No
Open appview deeplink from the aptoide website. This should correctly open the appview. Check that the get app request doesn't have any errors.
Tickets related to this pull-request: [ASV-555](https://aptoide.atlassian.net/browse/ASV-555)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new …

[ASV-555] app view install deep link fix

---

app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/vanilla/java/cm/aptoide/pt/app/AppViewViewModel.java
app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewView.java
app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java

Starts the installation after opening appview if the appview open type is OPEN_AND_INSTALL or OPEN_WITH_INSTALL_POPUP. If the type is OPEN_WITH_INSTALL_POPUP, then a dialog should be shown to the user asking confirmation if he really wants to install the app.
The start of the download should be the same as it is in the normal flow. The recommends dialog should be shown when it is needed (if not logged in, on the 2nd and 4th install click, if logged in, every time until the user presses don't show me again) and the same analytics should be logged.
No
Open any part of the app where these open types are passed.
If you want to test it in an easier way, just change the …

[ASV-550] AppView open type

---

app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java

Before, when the appview get app request was done, if the response had an error, the appview would be locked on the loading state. Now it navigates to the error view.
Also fixed the retry button click. Before, if you pressed the retry button and there was an error again, that chain would also break and the retry button would stop working.
No
Turn off network before opening appview to force an error on the getApp request. Then check if the no network view is shown.
Check if the retry button also works.
Tickets related to this pull-request: [ASV-559](https://aptoide.atlassian.net/browse/ASV-559)
**Questions:**
Does this add new …

[ASV-559] Get app request error

---

app/src/main/res/xml/settings.xml
app/src/vanilla/java/cm/aptoide/pt/view/settings/SettingsFragment.java

Added the delete account preference. If the user clicks on it, it will open a webview where the user can delete his account. This preference is only available if the user is logged in.
No
Open settings after being logged in.
Tickets related to this pull-request: [ASV-580](https://aptoide.atlassian.net/browse/ASV-580)
**Questions:**

[ASV-580] delete account client

---

app/src/main/res/layout/app_home_item.xml
app/src/main/res/layout/displayable_grid_ad.xml
app/src/main/res/layout/displayable_grid_app.xml
app/src/main/res/layout/reward_app_home_item.xml

Sets the width of the App Card to the one in zeplin
**NOTE:** In the bundles that it's just a list of apps (Highlights, specific bundles...) there's a small odd space on the right, don't know if it's suppose or not or if it's ok. Still need to talk to Luis about it.
No
See if there's any problem with the size of the appCard in different devices
https://aptoide.atlassian.net/browse/ASV-444

[ASV-444] Set App Card Width to 104dp

---

app/src/main/java/cm/aptoide/pt/networking/BodyInterceptorV7.java
app/src/main/java/cm/aptoide/pt/networking/RefreshTokenInvalidator.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java

This is an action that needs to be done following the ticket ASV-564. On that ticket, we are logging out the user but the request that failed was not being repeated. On this ticket we are repeating the request that failed, but now without the access token since it is invalid.
No
To test this, you should create an account (if you dont want to delete one that you already have), then delete it. Wait for the confirmation email that the account was deleted and then there 2 possible ways to test it : 
- 1) Leave the app open before receiving the confirmation email on any bottom navigation section (apps for example) and then as soon as you receive the confirmation email …

[ASV-672] repeat failed request

---

app/src/main/res/layout-v21/my_store_displayable_layout.xml
app/src/main/res/layout/my_store_displayable_layout.xml

Possibly fixes compile errors in some machines.
Not instantiating id before referencing it in the xml. This should be the reason why build was not successful in some machines, even though there is no clear documentation on how this error can occur because in most cases it would be error free. A theory is that by having both default and v21 version of the xml (one without the id instantiation mistake, other with it) in compile time the file that would be parsed first would define if the build was successful or not.
No
./gradlew clean assembleVanillaDevDebug  …

[ASV-705] fix compilation errors in some machines.

---

app/src/main/java/cm/aptoide/pt/view/Translator.java
app/src/main/res/layout/button.xml
app/src/main/res/values/strings.xml

"Editor's choice" bundle title was not in the Translator.java file
No
- Remember that translations are not in aptoide-client-v8 repo.
- Manually create values-pt
- Add strings file with 
<string name="home_title_editors_choice">Escolha dos editores</string>
- Open the app
https://aptoide.atlassian.net/browse/ASV-737
**Questions:**
No

ASV-737_editor_choice

---

app/src/main/java/cm/aptoide/pt/networking/image/ImageLoader.java
app/src/vanilla/java/cm/aptoide/pt/app/view/MiniTopReviewViewHolder.java

Implements a possible solution to solve the Out of Memory problem with glide's load.
In glide 3.x the default diskcachestdrategy was Resource/Result and in glide 4.x the default is Automatica which may be the cause of that.
No
ImageLoader.java
I wasn't able to replicate this, fabric says that this happens mostly on android 4.x, probably due to these being older and having less memory.
Just go to places where the glide is being used to be sure that the diskCacheStrategy didn't affect other stuff
https://aptoide.atlassian.net/browse/ASV-733

[hotfix/ASV-733] OOM on glide's load

---

app/src/main/java/cm/aptoide/pt/networking/image/ImageLoader.java

Disables hardware glide configurations in Android O or higher. This is an attempt to fix a crash in Android O and P that would happen in certain views. 
Also an optimization is being done regarding older api's that should use the old Glide default decode format RGB_565 instead of ARGB_8888, which is now only being use for Android O and higher.
No
Open many different app views. It would crash immediately in Android O/P devices in some app views. 
Tickets related to this pull-request: [ASV-761](https://aptoide.atlassian.net/browse/ASV-761)

[ASV-761] fix: disable hardware configuration in Android O or higher api.

---

app/src/main/java/cm/aptoide/pt/install/view/remote/ReceiverDeviceAdapter.java
app/src/main/java/cm/aptoide/pt/install/view/remote/RemoteInstallDialog.java
app/src/main/res/layout/dialog_remote_install.xml
app/src/main/res/layout/fragment_app_view_description.xml
app/src/main/res/layout/row_remote_install.xml
app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java

Changes the image size when there's a tv found. Changes the text layout in case no tvs were found.
No
dialog_remote_install.xml
Change the language to pt-pt (go to crowdin github page and download the project, then go to AndroidAppStore -> Vanilla -> app and copy all the files from the language you want to the local aptoide-client-v8 project you have on the res file)
Click on the install on tv button and wait for it to say that there's no devices and see if the text doesn't overlap the button.
Click on the install on tv button with aptoide-guest and check if the image on the found device has the correct size (image on the ticket)
This is just a quick fix and a …

[ASV-606] Change on install on tv dialog layout

---

app/src/main/java/cm/aptoide/pt/billing/view/login/PaymentLoginFragment.java
app/src/main/java/cm/aptoide/pt/view/FragmentComponent.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/main/res/layout-land/fragment_payment_login.xml
app/src/main/res/layout/fragment_payment_login.xml

**NOTE:** this is not in the sprint, move the two tickets from the backlog to the sprint if it's supposed to go to the sprint.
This PR fixes the crash on rotation of the fragment and puts the toolbar with the correct theme
There's a bug when you press back the view navigates to the fragment again, this is not fixed since it was supposed to be small and quick fix and that would take a lot more time if it was to fix that, since it's happening since 8.6.4.*
No
PaymentLoginFragment.java
Go to CutTheRope press the buy/install button while not logged in, rotate the screen see if it crashes.
https://aptoide.atlassian.net/browse/ASV-746 …

[bugfix/ASV-746-775] Fix PaymentLoginFragment

---

app/src/main/java/cm/aptoide/pt/account/AccountAnalytics.java

In this ticket we aimed to fix several login problems reported on facebook analytics.
Those problems were:
- several unknown records (with no status, status code, detail or description).
- change status detail from the the logs with User_cancelled and permissions denied from failed to invalid.
- the records with SDK ERROR or general error have unknown status code and status detail.
These mentioned problems don't happen in the most recent versions (from 8.6.4.1 -> 9.0.0.*)
The only fix done in this PR was to improve the facebook login errors log, by adding a default case to that switch statement.
No
Just added a default case to the switch statement. I can not …

[ASV-718] Added default case for facebook error logging

---

app/src/main/res/layout/brick_app_item_list.xml

If you opened the more section from the editors choice bundle and you rotated the screen, the feature graphic image would be stretched out. This happened because the item card had fixed size values.
No
Open more from editors choice , rotate device and check if the image is too stretched.
Tickets related to this pull-request: [ASV-803](https://aptoide.atlassian.net/browse/ASV-803)
**Questions:**

[ASV-803] Removed fixed width from editors choice more item

---

app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewPresenter.java
aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/AptoideAuthenticationException.java

Share dialog ab test is not requested anymore if user is not logged in.
No
Clear data > no login > app view > install > cancel > install > close on share diagram > check if ab testing ws was not called.
Clear data > logged in > app view > install > share dialog pops up > check if ab testing ws was called.
Tickets related to this pull-request: [ASV-823](https://aptoide.atlassian.net/browse/ASV-823)

[ASV-823] fix: share dialog ab test is not requested anymore if user is not logged in.

---

app/src/main/java/cm/aptoide/pt/analytics/analytics/AnalyticsBodyInterceptorV7.java
aptoide-analytics-default-implementation/src/main/java/cm/aptoide/analytics/implementation/network/AnalyticsBaseBody.java

In Aptoide BI events, calls to the addEvent were being made with the aptoide id parameter as: "aptoide_id". Now it is corrected to "aptoide_uid". 
No
Make an aptoide bi event call and check charles request body.
Tickets related to this pull-request: [ASV-860](https://aptoide.atlassian.net/browse/ASV-860)

[ASV-860] fix: aptoide bi events are now correctly sending the aptoide id parameter as "aptoide_uid" instead of "aptoide_id"

---

app/src/main/java/cm/aptoide/pt/updates/view/excluded/ExcludedUpdatesFragment.java

Make excluded updates fragment layout xml not use theme properties, because it isn't supported by widgets/displayables.
No
Ignore an Update and go to excluded updates in the settings.
Tickets related to this pull-request: [ASV-878](https://aptoide.atlassian.net/browse/ASV-878)

[ASV-878] fix: make excluded updates fragment layout xml not use theme properties, because it isn't supported by widgets/displayables.

---

app/src/main/java/cm/aptoide/pt/networking/RefreshTokenInvalidator.java

Solution to the crash that would happen when user tried to refresh token and ws would return 200 OK with errors. We would emit an AccountException that was not being handled in the retry (retry refresh token) and after max refresh token retries attempts failed, it would throw a RuntimeException, crashing the app. Now we logout the user and propagate the error through the chain.
No
Charles > make a request that uses access token (like getSubscribed stores) with invalid access token > mock oAuth2Authentication ws response so it returns errors > fail 3 times > check if user logs out.  …

[Bugfix/ASV-774] Refresh token account exception

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java

Fixes the logger bug in fabric
No
ApplicationModule.java
Tried several scenarios like huge string or huge while cycle in the setup BIEvent, the second one actually produced a OOM, but not with the stackTrace of the one in Fabric
But since this PR removes the class where the error occurs it should eliminate the error
https://aptoide.atlassian.net/browse/ASV-886

[ASV-886] Fabric Logger

---

app/src/main/res/layout/app_install_cardview.xml
app/src/main/res/layout/fragment_appcoints_info.xml

This PR aims to change the layout of the bottom card on the appc info fragment; The new card is smaller and has no elevation;
No
Press "Know more" in the appc card in home. Check the new card at the bottom of the fragment this navigates you to;
Tickets related to this pull-request: [ASV-928](<https://aptoide.atlassian.net/browse/ASV-928>)

[ASV-928] Changed Appc info fragment bottom card

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java

Title
No
Download this apk: https://my-wafa.pt.aptoide.com/ > Generate an Aptoide APK (vanillaProdRelease) > unzip it > unzip my-wafa in another directory > cp 3 files (aob, utm, tracking) from META/INF wafa directory into the META/INF Aptoide directory >  zip -r aptoide.apk > run Aptoide > check if utms and entry point are populated in the First_Launch event > close Aptoide > open Aptoide > check if First_launch is not sent anymore.
Tickets related to this pull-request: [ASV-970](https://aptoide.atlassian.net/browse/ASV-970)

[ASV-970] fix: first_launch event is now correctly populated with the entry_point + utms. First_launch is also only sent once.

---

app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java

On My Home shortcut, checks if user has store. If he does, navigates to StoreFragment. If he doesn't navigates to ManageStoreFragment
No
- DeepLinkManager.java
Click on My Home shortcut (Android Oreo) with 2 accounts: 1 with store, 1 without.
Tickets related to this pull-request: [ASV-974](https://aptoide.atlassian.net/browse/ASV-974)

ASV 974 - My Store shortcut bug

---

app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java

This PR aims to fix the events related to editor's choice not being sent. These are:
- Editors_Choice_Clicks: Now being properly sent;
- Editors_Choice_Application_Install: Now being properly sent;
- Editors_Choice_Download_Completed: Out of the scope of this ticket; Should be fixed along with the other download events not being correctly sent to facebook;
No
Click an app in the editor's choice bundle in home. Verify that this produces the corresponding event. Afterwards, download the app, install it and verify that the correct event is being sent; …

[ASV-967] Fixed 2 of the 3 requested events

---

app/src/main/java/cm/aptoide/pt/abtesting/ABTestService.java
app/src/main/java/cm/aptoide/pt/abtesting/experiments/SimilarAdExperiment.java
app/src/main/java/cm/aptoide/pt/ads/AppNextAdRepository.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/vanilla/java/cm/aptoide/pt/ads/AdsRepository.java
app/src/vanilla/java/cm/aptoide/pt/app/AdsManager.java
app/src/vanilla/java/cm/aptoide/pt/app/view/AppViewView.java
app/src/vanilla/java/cm/aptoide/pt/app/view/NewAppViewFragment.java

Action/Impressions were not working, this essentially fixes it. The main problems were that the requests were being done on the main thread (and should be on IO thread), AppNext clicks were not being registered (as they have their own click listener) and for the default ads, actions were being sent after navigating to another screen.
No
Should be checked in AB Testing platform and/or with Charles that action/impressions are correctly working. Note at most it will appear 1 action/impression per device on the platform as those are unique actions/impressions. Both AppNext ads (bucket: "appnext_ad") and Aptoide Ads (bucket: "default_ad") should be tested.
**What are the …

[Bugfix/ASV-1111] AppNext Action/Impressions

---

app/src/main/java/cm/aptoide/pt/view/fragment/DescriptionFragment.java

It changes the theme back to default when coming back from DescriptionFragment. Previously, if there was a store theme, when coming back to AppView, the theme would not reset back to default and the colors were mismatched.
No
_Example described in the ticket:_
In Home, click on an app with a store with theme (Metal Commando - Squad Metal... in Spend Your AppCoins bundle), click on the “Read More” in the description of the AppView, then go back to the AppView. When going back to AppView, the status bar color should be the default color, and not the store theme color.
[ASV-1131](https://aptoide.atlassian.net/browse/ASV-1131)
**Code …

[bugfix/ASV-1131] - Status Bar color on Read More 

---

app/src/main/java/cm/aptoide/pt/abtesting/experiments/HighlightedAdExperiment.java
app/src/main/java/cm/aptoide/pt/ads/data/ApplicationAdError.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java

Registers impression when there's no AppNext ad in the highlighted bundle. 
No
Check if when the Highlighted ad experiment AB test bucket is 'no_appnext_ad', impressions events are being sent.
[ASV-1135](https://aptoide.atlassian.net/browse/ASV-1135)

[Bugfix/ASV-1135] Highlighted Impression

---

app/src/main/java/cm/aptoide/pt/ads/model/AppNextNativeAd.java
app/src/main/java/cm/aptoide/pt/ads/model/ApplicationAd.java
app/src/main/java/cm/aptoide/pt/ads/model/AptoideNativeAd.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppViewHolder.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewSimilarAppsAdapter.java
app/src/main/java/cm/aptoide/pt/home/AdInBundleViewHolder.java
app/src/main/java/cm/aptoide/pt/home/AdsInBundleAdapter.java
app/src/main/res/layout/displayable_grid_ad_appnext.xml
app/src/vanilla/java/cm/aptoide/pt/app/AppViewSimilarApp.java

AppNext ad views should be encapsulated with NativeAdView to make sure impressions work correctly. This PR does that.
No
Check if AppNext ads are actually encapsulated with NativeAdView. Impression analytics tests will probably be done later.
Tickets related to this pull-request: [ASV-1141](https://aptoide.atlassian.net/browse/ASV-1141)

[Monetization/ASV-1141] NativeAdView encapsulation

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsAdapter.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsFragmentView.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java

Before, after pressing the cancel button on an app card of the apps bottom navigation section, the card would stay in the Standby state (with the indeterminate progress bar). This pull request aims to fix this problem.
No
Start a download, pause it and then press cancel. The card will disappear. In my opinion, the card should go back to the normal/initial state, but that will be done in the future.
Tickets related to this pull-request: [ASV-1127](https://aptoide.atlassian.net/browse/ASV-1127)
**Questions:**

[ASV-1127] Fix cancel button

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java

The new download manager implementation has a queue. When a download is started, the downloads are added to the database in the IN_QUEUE download state. If the user presses update all, all the updates will be added to the database in the queued state which will trigger the queue and make the download manager start the first download. The problem is that since several downloads are added to the queue at the same time, it made the download manager start the first download more than once. This is PR fixes this aforementioned problem.
Also, took the chance to fix an open stream left in the Apps Manager, that would generate a leak and affect performance.
No
Open the Apps …

[ASV-1152] Repeated first download

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java

🔨
This pull request is a fix for the campaigns notification showing problems. 
Because the RootInstallationRetryHandler dependency in AptoideApplication depends on the AnalyticsManager & NavigationTracker, the SystemNotificationShower would be populated with null values. This fix only changes the order of when the dependencies are provided, making everything work. This will be subject of a refactor in a near-future task.
No
Rewrite campaign notifications request - Please ask me for the rewrite file to not provide the webservice information here in public.
Open the app, see if campaign notification is shown.
Tickets related to this …

[Bugfix/ASV-1064] Campaign Notifications fix

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/values/strings_accountmanager.xml
aptoide-analytics-core/build.gradle
aptoide-analytics-default-implementation/build.gradle
build.gradle
downloadmanager/build.gradle
gradle/wrapper/gradle-wrapper.properties

Had to update build tools, update fabric, remove minimum sdk from manifest, fix string (since in this new build tools version they seem to be checked in compile time), minor gradle scripts fixes and refactor (like extracting variables - fix the variants dependencies when switching from debug to release - fix downloads lib scope).
from spike: "To update gradle we need to also update the gradle wrapper to 4.6, build tools need to be updated to 28.0.3 (current & default version - we probably should think of removing this, since we should always use the default version) and fabric update to 1.25.4.
Minimum sdk version has to be removed from the Manifest.
After this gradle scripts will work.
Compilation is failling because this version of build tools seem to verify …

[ASV-1159] task: update gradle version

---

app/build.gradle
app/src/main/java/cm/aptoide/pt/app/view/donations/utils/GenericPaymentIntentBuilder.java
build.gradle

Remove web3j dependency from the APPC proxy lib to shrink apk size.
Extract appc proxy lib version to the project build.gradle
Instead of using the SpongyCastle lib to do the Hex encoding and then to string, used the common utils from google already in the Android framework. 
No
Check apk size. Test donation flow.
Tickets related to this pull-request: [ASV-1191](https://aptoide.atlassian.net/browse/ASV-1191)

[ASV-1191] refactor: exclude web3j from appc proxy

---

app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java
app/src/main/java/cm/aptoide/pt/billing/view/login/PaymentLoginFragment.java
app/src/main/java/cm/aptoide/pt/billing/view/login/PaymentLoginPresenter.java
app/src/main/java/cm/aptoide/pt/billing/view/login/PaymentLoginView.java
app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsPresenter.java
app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsView.java

This PR removes the request for TC and PP acceptance when login in with Facebook or Google.
No
Open the app, go to my account, try to login with google or facebook. The TC and PP toast should not appear and the flow should be completed.
Open the app, search for a **paid** app, click buy, try to login with google or facebook. The TC and PP toast should not appear and the flow should be completed.
https://aptoide.atlassian.net/browse/ASV-1190

[ASV-1190] Remove accept TC and PP for Google and Facebook logins.

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/app/view/EditorialAnalytics.java
app/src/main/java/cm/aptoide/pt/home/HomeAnalytics.java

This PR changes the events used for analytics from a global used string to a unique string. Now we have CURATION_CARD_IMPRESSION, CURATION_CARD_CLICK and CURATION_CARD_INSTALL instead of reusing home_interact and click.
No
Check the analytics on facebook analytics to see if the new events are entered correctly.
https://aptoide.atlassian.net/browse/ASV-1234

[ASV-1234] Change analytics events for curation flow.

---

app/src/main/java/cm/aptoide/pt/home/LoggedInTermsAndConditionsDialog.java

This PR aims to fix the crash in the GDPR dialog reported in fabric;
No
We can't at present time reproduce this bug;
Tickets related to this pull-request: [ASV-1201](<https://aptoide.atlassian.net/browse/ASV-1201>)

[ASV-1201] Fixed crash on GDPR dialog navigation;

---

app/src/main/java/cm/aptoide/pt/app/view/EditorialFragment.java
app/src/main/res/layout/editorial_layout.xml
app/src/main/res/layout/fragment_promotions.xml

This pr aims at fixing the scrolling bug on the first promotions view. There was a bug where the image on the collapsable toolbar would be extended, but the rest of the view is not. 
Also extracted the same flag for the editorial from the fragment to the layout file
No
Scroll on the promotions fragment and try to see inconsistencies.
Tickets related to this pull-request: [ASV-1282](https://aptoide.atlassian.net/browse/ASV-1282)
**Questions:**

[ASV-1282] collapsable toolbar bug

---

app/src/main/java/cm/aptoide/pt/home/Home.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/HomePromotionsWrapper.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsHomeDialog.java

Showing promotions dialog only when there are apps to claim. Also changed the promotion dialog message to show the total promotion appc instead of the unclaimed promotion appc.
No
Open Aptoide, check that since everything is already claimed in the office, no dialog should popup and there should be no notification on the promotions toolbar icon. Then, rewrite on charles or active your mobile data to unclaimed apps and see that there will be the ticker and the promotions dialog will be shown with the total amount of appc instead of the unclaimed amount. …

[ASV-1288] Promotions notification and first dialog

---

app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsView.java
app/src/main/res/layout/fragment_promotions.xml

This PR aims to add a loading element to the promotions fragment, while the data to display loads; It also adds an error state with a retry button to the view;
No
Open the promotions and check that it loads and then displays consistent information afterwards;
Open the promotions fragment without connection and check that everything about the error state is working
Tickets related to this pull-request: [ASV-1269](<https://aptoide.atlassian.net/browse/ASV-1269>)

[ASV-1269] Added loading to PromotionsFragment;

---

app/src/main/java/cm/aptoide/pt/home/LoggedInTermsAndConditionsDialog.java

Releases button listeners to avoid leaks. Also hides dialog if destroy dialog is called.
No
Remove HomePresenter's filter from line 483 so it is easy to test the dialog while logged in.
Tickets related to this pull-request: [ASV-1341](https://aptoide.atlassian.net/browse/ASV-1341)

[ASV-1341] fix to gdpr dialog leaks

---

app/src/cobrand/java/cm/aptoide/pt/FlavourApplicationModule.java
app/src/cobrand/java/cm/aptoide/pt/account.view.user/NewsletterManager.java
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/account/view/user/ManageUserFragment.java
app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
app/src/main/java/cm/aptoide/pt/view/settings/SupportEmailProvider.java
app/src/main/res/layout/dialog_about.xml
app/src/vanilla/java/cm/aptoide/pt/FlavourApplicationModule.java
app/src/vanilla/java/cm/aptoide/pt/account/view/user/NewsletterManager.java

Hides the Aptoide support email in cobrand versions.
Hides the Newsletter checkbox in cobrand versions.
No
Test both vanilla and cobrand variants - Aptoide Support email is in the about us under settings, newsletter is in the User creation view at the beginning of the signup process.
Tickets related to this pull-request: [ASV-1356](https://aptoide.atlassian.net/browse/ASV-1356)

[Feature/ASV-1356] cobrand remove newsletter and support

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AppDownloadManager.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java

Send download complete event only when the full app is downloaded and not when any file inside the app is downloaded.
No
Test an installation of an app with obbs (Sonic Dash has 133MB~) and see if it goes well + analytics (Download event).
Tickets related to this pull-request: [ASV-1384](https://aptoide.atlassian.net/browse/ASV-1384)

[Hotfix/ASV-1384] install app with OBB's

---

app/src/main/java/cm/aptoide/pt/install/InstalledIntentService.java

Null checking PackageInfo before trying to convert campaign - this goes inline with what the send install event implementation is doing, since the PackageInfo might be null.
This fixes the crash in production but we will continue loosing some APPC campaign conversion events.
What should be done in the future: Investigate why is the PackageInfo returning null. This might be a problem if we are not converting successfully installed campaigns.
If there is a problem with the campaigns convertion, we should try to find a way to not depend on the PackageInfo to get the version code or find a version code alternative that does not make the event depend on the PackageInfo. This should only be considered if we are really loosing successfully installed appc campaigns event …

[ASV-1422] fix: installed service npe

---

app/src/main/java/cm/aptoide/pt/app/AppViewViewModel.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java

This PR aims at removing interstitial ads from AppViews of APPC apps.
No
Open an appview from a normal app and download. You should see and interstitial ad. Then, go to an appview of an appc app and you should not see an interstitial ad.
In case of failure of seeing any interstitial ads, please check you have all the correct keys and use try with a vpn (sometimes we can not see ads because we are in Portugal).
Tickets related to this pull-request: [ASV-1402](https://aptoide.atlassian.net/browse/ASV-1402)
**Questions:**

[ASV-1402] No ads for APPC apps

---

app/src/main/java/com/mopub/nativeads/AppLovinCustomEventNative.java
app/src/main/java/com/mopub/nativeads/AppLovinNativeAdapter.java

This PR aims at fixing native ads in production from AppLovin. In a thread of emails, the AppLovin team suggested us to re-check the documentation and see if anything is wrong. I found out that we did import the correct adapter classes, but they were not put in the correct package (this information was only on mopub's documentation and not on the AppLovin documentation which is what was followed in the previous iteration).
No
This is an attempt at fixing native ads with AppLovin. We will have to release it and check if we start getting impressions. Another alternative would be to lock all of the ad networks except for AppLovin (for the native ads) and see if there …

[ASV-1399] AppLovin native ads fix

---

app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsService.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsView.java

fix: wallet claimed but not installed now locks other apps in promotion and shows the install button for the wallet.
No
internal
or dev/prod with vercode > 9600 and https://ws75.aptoide.com/api/7/appcoins/promotions/get/limit=30 with "aptoide_md5sum": "00000000000000000000000000000000"
Wallet must be claimed already for this.
Tickets related to this pull-request: [ASV-1264](https://aptoide.atlassian.net/browse/ASV-1264)

[Bugfix/ASV-1264] wallet claimed not installed

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/view/MainActivity.java
app/src/main/java/com/mopub/nativeads/AppLovinBaseAdapterConfiguration.java

After upgrading mopub from version 5.4 to version 5.5, the initialization of non-certified networks should be done in a class that extends the BaseAdapterConfiguration class from MoPub. This PR implemented that and added that configuration to the mopub initialization
No
Open App check if there are ads. We should see in the nightly if there are AppLovin ads. If you want to do a more severe test, you could go to the mopub dashboard, disable all the networks except for AppLovin and see if you have ads (that way you would be sure that all the ads are coming from AppLovin, ensuring that it is correctly integrated.
These ads should be shown in: 
- Home (banner above …

[ASV-1443] Adapt AppLovin to new MoPub version

---

app/src/main/java/cm/aptoide/pt/view/recycler/displayable/DisplayablesFactory.java
app/src/main/res/layout/editorial_item_layout.xml
app/src/main/res/layout/editorial_layout.xml
app/src/main/res/layout/media_layout.xml

fix: editorial content images/graphics/thumbnails are now with centerCrop scale type.
home meta followers/following are now correct (numbers were swapped).
No
home > click oscars article (or current editorial content article) > check feature graphic on top and screenshots inside.
stores > check if followers/following numbers make sense.
Tickets related to this pull-request: [ASV-1463](https://aptoide.atlassian.net/browse/ASV-1463)
[ASV-1441](https://aptoide.atlassian.net/browse/ASV-1441)

[ASV-1463/ASV-1441] editorial scale type to crop. store meta followers/following swapped.

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialItemsViewHolder.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialView.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java

This PR aims to fix the button on the card at the bottom of the curation view not working. It also fixed this card not supporting the downgrade of apps;
No
You'll need to have a editorial with the card at the bottom (if you need a rewrite for charles, talk to me). In that card make sure you can do all the actions regarding downloads;
Tickets related to this pull-request: [ASV-1457](https://aptoide.atlassian.net/browse/ASV-1457)

[ASV-1457] Editorial Fragment download now supports downgrades;

---

app/src/main/res/drawable-v21/appc_gradient_transition.xml

Fixed a bug with the last ASV-1445 ticket, where the app view would not load with devices with API lower than 21.
No
Check if the app view loads fine in any supported API version. For devices with API lower than 21, the background transition will not appear.
[ASV-1445](https://aptoide.atlassian.net/browse/ASV-1445)

[ASV-1445] Fixed visual bug with devices with API < 21

---

app/src/main/java/cm/aptoide/pt/editorialList/EditorialListFragment.java
app/src/main/java/cm/aptoide/pt/editorialList/EditorialListPresenter.java
app/src/main/java/cm/aptoide/pt/editorialList/EditorialListView.java
app/src/test/java/cm/aptoide/pt/editorialList/EditorialListPresenterTest.java

Makes it so that the error view hides the cards on the list
No
EditorialListFragment.java
EditorialListPresenter.java
ticket
https://aptoide.atlassian.net/browse/AS-110

[AS-110] Error screen now hides cards

---

app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/view/app/AppService.java
app/src/main/java/cm/aptoide/pt/view/app/DetailedApp.java
app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/GetAppMeta.java

This PR aims at removing ads from appviews of apps which are considered mature.
No
Open Aptoide and if you don't have the show adult content option enabled, please enable it. Then, search for an adult content app and confirm that no ads are shown (or requested, see the logcat there should be an error log saying no banners found, which means that there was no network providing us an ad). Then, please confirm that everything is correct for the "normal" apps.
Tickets related to this pull-request: [ASV-1464](https://aptoide.atlassian.net/browse/ASV-1464)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new …

[ASV-1464] No ads on adult content

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/abtesting/ABTestCenterRepository.java
app/src/main/java/cm/aptoide/pt/abtesting/ABTestManager.java
app/src/main/java/cm/aptoide/pt/abtesting/AbTestRepository.java
app/src/main/java/cm/aptoide/pt/abtesting/AbTestSearchRepository.java
app/src/main/java/cm/aptoide/pt/abtesting/SearchAbTestService.java
app/src/main/java/cm/aptoide/pt/abtesting/SearchExperiment.java
app/src/main/java/cm/aptoide/pt/autoupdate/AbSearchGroupResponse.java
app/src/main/java/cm/aptoide/pt/search/SearchManager.java
app/src/main/java/cm/aptoide/pt/search/analytics/SearchAnalytics.java
app/src/main/java/cm/aptoide/pt/search/model/SearchAppResultWrapper.java
app/src/main/java/cm/aptoide/pt/search/model/SearchResultCount.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultAdapter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.java
app/src/test/java/cm/aptoide/pt/search/SearchResultPresenterTest.java

This PR tackles 3 different things: verifies a new parameter sent in the search request (items) and only sends action events if position<=items in list. It also adds two new analytic parameters for both impression and actions. Finally it handles situations where the search AB test cannot be retrieved (e.g. 404).
No
Check if analytic parameters are being sent correctly, check if actions are only recorded if the app is in position <= items (sent in the response) and check with Charles how the app behaves when the search_ab_test_mobile request cannot be retrieved (e.g. 404). Previously the search would not work when a 404 happened. …

[feature/ASV-1469] Search AB Test Parameter

---

app/src/main/res/layout/action_bar.xml
app/src/main/res/layout/fragment_home_container.xml

One of the ASV-1431 tasks was to center the action bar logo/name, this ended up not being done due to changes on dev that were not taken into account at the time
No
action_bar.xml
fragment_home_container.xml
Change between home, stores and apps fragment
https://aptoide.atlassian.net/browse/ASV-1431

[hotfix/ASV-1431] Action bar logo/cobrand name is now centered in home

---

app/src/main/java/cm/aptoide/pt/abtesting/AbTestSearchRepository.java

Wasabi action for search ab test was being recorded even when it shouldn't, this essentially fixes it. E.g. if items = 5, position 5 was being recorded where it shouldn't (only 0-4).
No
Check the flow again to make sure it doesn't happen.
[ASV-1469](https://aptoide.atlassian.net/browse/ASV-1469)

[bugfix/ASV-1469] Item position bug fix

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
app/src/main/java/cm/aptoide/pt/view/wizard/WizardPageTwoFragment.java

This PR does two things:
1. Adds context to Google_Play_Protect event so that it can be sent to BI and adds it to the BI event list.
2. For FIRST_LAUNCH event, removes unnecessary call to BI analytics and instead sends it through the library. Note that FIRST_LAUNCH and Aptoide_First_Launch should remain separate for record purposes.
No
Check if both FIRST_LAUNCH and Google_Play_Protect events are being sent to BI. You might need to use Charles for this as I don't think Bi events are being logged.
[ASV-1524](https://aptoide.atlassian.net/browse/ASV-1524)

[feature/ASV-1524] Google Play Protect event to BI

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java

This PR aims at fixing wallet ads offer analytics events.
If the wallet ads offer is active then an attribute to the download complete event is added saying if the offer blocked the ads (true) or not (false).
Also, if the user does not see an interstitial ad due to the offer, an event without parameters is sent (Ads_Block_By_Offer).
No
Do a download, check that the event is sent with the ads_block_by_offer false. Then install the wallet. Do another download, check that the same parameter is with true. Also, no interstitial ad should be shown there and the Ads_Block_By_Offer event should also be sent.
Tickets related to this …

[ASV-1403] Fix wallet ads offer events

---

app/src/main/java/cm/aptoide/pt/app/view/MoreBundleManager.java

This PR aims at fixing a bug where we wouldn't load the next bundles in home in case the first bundles returned from the api were empty.
No
Open the app, go to the spend your appcoins bundle, open the applications bundle by presisng the more button and then check if new categories were opened. Before fixing this, there wouldn't be any bundles because the first bundles in that category were all empty.
Tickets related to this pull-request: [ASV-1552](https://aptoide.atlassian.net/browse/ASV-1552)
**Questions:**

[ASV-1552] Category views fix

---

dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v2/aptwords/GetAdsRequest.java

This PR aims to add a new field to send in the getAds request from appview with the packagename of the respective app. This will be used to return ads relative to the app category
No
This isn't in production from the backend side so the only way you can test this is by checking getAds requests on charles, verifying that the new field is being sent from the appview and nowhere else;
Tickets related to this pull-request: [ASV-1583](https://aptoide.atlassian.net/browse/ASV-1583)

[ASV-1583] Added category package name to get ads request from appview;

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java

Facebook UserProperties like UTM's/EntryPoint are only being sent on first launch.
They should be set every launch so all session events have the correct user properties.
Some code was deleted from FirstLaunch Analytics because it was not being used. This might be due to a bug that will be open on Jira.
No
Check if all UTM's an entry point user properties are being correctly set in Facebook SDK 
Tickets related to this pull-request: [ASV-1556](https://aptoide.atlassian.net/browse/ASV-1556)

[Bugfix/ASV-1556] entrypoint utm user properties not being set on second launch

---

app/src/cobrand/java/cm/aptoide/pt/FlavourApplicationModule.java
app/src/cobrand/java/cm/aptoide/pt/ads/MoPubConsentManager.java
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/ads/MoPubAdsManager.java
app/src/main/java/cm/aptoide/pt/ads/MoPubConsentDialogManager.java
app/src/main/java/cm/aptoide/pt/ads/MoPubConsentDialogView.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
app/src/main/java/cm/aptoide/pt/home/Home.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/HomeView.java
app/src/vanilla/java/cm/aptoide/pt/FlavourApplicationModule.java
app/src/vanilla/java/cm/aptoide/pt/ads/MoPubConsentManager.java

This PR aims at showing mopub consent dialog. This is important in order to increase the revenue we get from showing ads.
PS: MoPub provides a method to ask if the consent dialog should be shown or not (where they check if the user already answered or if GDPR applies) but that method has inconsistencies as if we answer the dialog and then request if the dialog should be shown or not it will still answer yes.
No
Open the app and you should get the mopub consent dialog straightaway, since it is being requested for the ads in home and for the ads in the appview. Interact with it and test both scenarios (yes or no). In order to get the dialog again, after interacting …

HOTFIX [ASV-1603] MoPub consent

---

app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java

Fixed curation link from the bottom appeared in editorial content to appview not working on first click (not loading the app view)
No
-EditorialPresenter.java
Go to the editorial view and click on the editorial card. It should navigate to the app view loading the app that was clicked.
https://aptoide.atlassian.net/browse/ASV-1497

[AS-1497] Fixed curation link to appview not working on first click

---

app/src/cobrand/java/cm/aptoide/pt/ads/WalletAdsOfferCardManager.java
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/blacklist/BlacklistManager.java
app/src/main/java/cm/aptoide/pt/blacklist/BlacklistUnit.java
app/src/main/java/cm/aptoide/pt/blacklist/BlacklistUnitMapper.java
app/src/main/java/cm/aptoide/pt/blacklist/Blacklister.java
app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
app/src/main/java/cm/aptoide/pt/home/Home.java
app/src/vanilla/java/cm/aptoide/pt/ads/WalletAdsOfferCardManager.java

This PR aims at implementing the blacklisting on the appc card. Since the mark as read api was deprected, we changed the blacklisting to the clientside. The code regarding the impressions of this card had to be adapted to this new clientside blacklist manager.
Also, i refactored the blacklist manager a bit in order to allow dynamic card id blacklisting.
No
Since the APPC card is not live, you need to rewrite it on charles. Then scroll up and down to increase the impressions and check that after 10 impressions it was removed. Note: it is possible that it is cached so to check if it was correctly removed, you can just pull to refresh, which bypasses the cache.
**What …

[ASV-1502] Blacklist Appc Card

---

app/src/vanilla/java/cm/aptoide/pt/FlavourApplicationModule.java
app/src/vanilla/java/cm/aptoide/pt/ads/MoPubConsentManager.java

This PR aims at fixing the MoPub GDPR impression. There was a bug created after merging this code from release/v9.7.0.2 to dev because when adding the ads entry point, the MoPubAdsManager started being initialized on the app startup and here the MoPub wasn't initialized yet, meaning that the personalInfoManager was null, leading to a crash when trying to show the MoPub GDPR dialog.
No
Reset advertising id and open the app. You should see the MoPub GDPR dialog.
Please remember that this is only shown to the users that should see ads, so make sure you are on the correct ab test group and that you dont have the Appcoins wallet installed.
**What are the relevant …

[ASV-1628] MoPub GDPR Dialog fix

---

app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java

Fixes a bug where no login button appeared on the toast on the Editorial.
No
Without being logged in, navigate to editorial, chose an article, an try to react more than 5 times. The toast should be displayed and have a button to log in.
https://aptoide.atlassian.net/browse/ASV-1653

[ASV-1653] - Login button toast

---

app/src/main/java/cm/aptoide/pt/home/AdsBundleViewHolder.java
app/src/main/java/cm/aptoide/pt/reactions/network/ReactionsRemoteService.java

This PR aims to remove the un-needed fields from the Reactions request Body.
No
Open the editorial, react to a card, and check that request in charles. The body should only have:
```
BODY:
{  
"type": "thumbs_up",
"group_uid": "apps-group",
"object_uid": "23r2f24f24f2e424f"
}
```    
for the first reaction.
and:
```
BODY:
{  
"type": "love"
}
```  
for the second or higher reaction.
https://aptoide.atlassian.net/browse/ASV-1665

[ASV-1665] Remove base body from requests

---

app/src/main/java/cm/aptoide/pt/home/HomePresenter.java

Attempt to fix recycler view IndexOutOfBoundsException. First, reactions should not be called on pull to refresh, second - it seems that the updateEditorial method in the BundlesAdapter is causing this problem. By disabling reactions completely we will be able to measure if this specific method was indeed crashing the app.
No
Open home, pull-to-refresh > swipe down until load more - repeat very fast 100 times until it crashes (this would crash in my hands in 20~ secs)
Tickets related to this pull-request: [ASV-1675](https://aptoide.atlassian.net/browse/ASV-1675)

[Hotfix/ASV-1675] Recycler View IndexOutOfBoundsException

---

app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/apps/BundleView.java
app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java

This PR aims to fix the reported crash regarding reactions in home
No
Try to reproduce the bug (pull-to-refresh in home, followed by rapidly scrolling now). The crash should not be happening anymore
Tickets related to this pull-request: [ASV-1678](https://aptoide.atlassian.net/browse/ASV-1678)

[ASV-1678] Fixed bug related to reactions crashing view;

---

app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java

downloadAction is null on resume. avoiding npe by reverting the equals verification.
For future investigation we should check why action is null on resume, might be the same reason we are not able to fire installations in some cases. 
No
Test downloads in appview, editorial and apps. Pause/resume/cancel.
Tickets related to this pull-request: [ASV-1690](https://aptoide.atlassian.net/browse/ASV-1690)

[Bugfix/ASV-1690] fix resume download appview

---

app/src/main/java/cm/aptoide/pt/home/HomeContainerNavigator.java
app/src/main/java/cm/aptoide/pt/navigator/FragmentNavigator.java
app/src/main/java/cm/aptoide/pt/navigator/FragmentResultNavigator.java
app/src/main/java/cm/aptoide/pt/view/BaseFragment.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/main/res/layout/fragment_home_container.xml

This PR aims at fixing the navigation in home and keeping the state of all home fragments (games, apps and home). When you navigate to another view and comeback, the previous view should keep its state.
No
Open app, scroll down and open an appview. Press the back button and the home fragment should in the same position as before. Also same thing should happen on any of the "chips" fragments
Tickets related to this pull-request: [ASV-1654](https://aptoide.atlassian.net/browse/ASV-1654)
**Questions:**

[ASV-1654] Fix home navigation

---

app/src/main/java/cm/aptoide/pt/home/HomeContainerNavigator.java

This PR aims at fixing the apps chip request. Before, the apps chip was showing games bundles instead of apps.
**NOTE:
Please accept the PR https://github.com/Aptoide/aptoide-client-v8/pull/1020 first, because I checkout from that branch in order to fix this issue.**
No
Open both chips and check that the bundles are different and now make sense to the chip name.
Tickets related to this pull-request: [ASV-1679](https://aptoide.atlassian.net/browse/ASV-1679)
**Questions:**

[ASV-1679] Fix bundles inside the chips

---

app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java

Fixes the store/apps/details http deeplink that is used in many apps/web clients to redirect users to an App view. uri.getPath returns the path with a trailling slash and we were comparing with an equals with (store/apps/details) which would return false with /store/apps/details. Since I feel this behaviour was working correctly in the past and no one touchs this validation for more than one year, I think is safer to use contains to support store/apps/details.
No
There is an app called Deep Link Tester which makes deeplink testing easier.
Flow on how to test this or QA Tickets related to this use-case: [ASV-1708](https://aptoide.atlassian.net/browse/ASV-1708)
**What …

[Bugfix/ASV-1708] fix deep link play

---

app/src/main/java/cm/aptoide/pt/notification/PullingContentService.java

This essentially fixes a timer bug with the updates alarm, where it would trigger after the first 5000ms. Since we were also updating the updates list at the start of the application, this would mean we had duplicated requests in the first 5-20s. 
No
Check if there is no repeated listAppsUpdates and listAppcAppsUpgrades calls on first launch. 
Tickets related to this pull-request: [ASV-1694](https://aptoide.atlassian.net/browse/ASV-1694)

[bugfix/ASV-1694] Duplicated list apps updates

---

app/src/main/AndroidManifest.xml
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/DeepLinkAnalytics.java
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/view/ActivityComponent.java
app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
app/src/main/java/cm/aptoide/pt/view/BackButtonActivity.java
app/src/main/java/cm/aptoide/pt/view/BaseActivity.java
app/src/main/java/cm/aptoide/pt/view/ThemedActivityView.java
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallActivity.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallNavigator.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallView.kt
app/src/main/res/layout/wallet_install_activity.xml
app/src/main/res/values/styles.xml

This PR creates a base activity for the wallet install dialog. The way it's setup, there's a main container in the activity layout used to inflate the actual content of the view (similar to MainActivity). 
This activity uses a specific custom dialog theme ('Aptoide.DialogTheme'). This theme defines several aspects of the dialog, namely: the minimum width in portrait/landscape mode (%) according to Zeplin, the dialog background with rounded edges etc.
Finally, this activity is launched as a new task, and 'taskAffinity', 'noHistory' and 'excludeFromRecents' are used in combination to properly use this activity independently from Aptoide task itself. DeepLinkIntentReceiver, which launches the dialog activity also needs a custom 'taskAffinity'.
Relevant analytics …

[feature/ASV-1734] Dialog Base View for Wallet Install Dialog

---

app/src/main/java/cm/aptoide/pt/wallet/WalletInstallActivity.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallManager.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallView.kt
app/src/main/res/layout/wallet_install_activity.xml

Reverted initStyling order because of animations
Added null return on error for app icon
This adds support for non-installed app source. It means that if the user does not have the app_source package installed, it should still work and show the Aptoide icon instead. Additionally, it reverses some styling and visibility changes that were done, to have better animations and reduce flickering.
Just as a note, this ticket was accomplished by deferring the error on getAppIcon() to a null value (which does nothing). We could return the path to the default aptoide icon instead of null, but I think this would be non-trivial, since I'd have to get the actual path of the drawable.
No
**How should this be manually …

[feature/ASV-1755] Support for app source not installed 

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultAdapter.java
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultAdViewHolder.java
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultItemView.java
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.java

This PR aims to change the way we pass viewholder positions to search results. Instead of using the position provided when onBind is called, we now call getAdapterPosition inside the viewHolder
No
Check if the position is being correctly passed;
Tickets related to this pull-request: [ASV-1721](https://aptoide.atlassian.net/browse/ASV-1721)

[ASV-1721] Search RV now using getAdapterPosition() in items;

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoNavigator.java
app/src/main/res/values/strings.xml

Replaces hardcoded references to bds-store to catappult, which is the new AppCoins certified developers store).
One is the default following stores, the other one is the AppCoins information view to getApp
No
Fresh install to check default following stores (only run at first run)
Click in the wallet inside the AppCoins information view.
Tickets related to this pull-request: [ASV-1744](https://aptoide.atlassian.net/browse/ASV-1744)

[ASV-1744] fix: replace bds-store with catappult

---

app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/BundleView.java

Only notify new bundle additions, instead of invalidating every bundle in the adapter. This will prevent the view apps images flicker from happening when user hits load more.
No
Scroll home, test different bundle management methods (pull to refresh/load more/navigation)
Tickets related to this pull-request: [ASV-1722](https://aptoide.atlassian.net/browse/ASV-1722)

[Bugfix/ASV-1722] fix: home adapter notify

---

app/src/main/java/cm/aptoide/pt/wallet/WalletInstallActivity.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallView.kt

This PR shows a new "screen" when the user has the wallet app already installed. See ticket for details.
No
Test two scenarios: wallet app installed and not installed. If the wallet is installed, the new screen should appear. Otherwise the regular flow applies.
[ASV-1781](https://aptoide.atlassian.net/browse/ASV-1781)

[feature/ASV-1781] - Wallet Install Dialog - Handle installed wallet

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
app/src/main/java/cm/aptoide/pt/editorial/CaptionBackgroundPainter.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialService.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialViewModel.java
app/src/main/java/cm/aptoide/pt/editorialList/CurationCard.java
app/src/main/java/cm/aptoide/pt/editorialList/EditorialListAdapter.java
app/src/main/java/cm/aptoide/pt/editorialList/EditorialListFragment.java
app/src/main/java/cm/aptoide/pt/editorialList/EditorialListService.java
app/src/main/java/cm/aptoide/pt/editorialList/LoadingViewHolder.java
app/src/main/java/cm/aptoide/pt/editorialList/ProgressCard.java
app/src/main/java/cm/aptoide/pt/home/ActionItem.java
app/src/main/java/cm/aptoide/pt/home/BundlesAdapter.java
app/src/main/java/cm/aptoide/pt/home/BundlesResponseMapper.java
app/src/main/java/cm/aptoide/pt/home/EditorialBundleViewHolder.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java
app/src/test/java/cm/aptoide/pt/editorialList/EditorialListPresenterTest.java
app/src/test/java/cm/aptoide/pt/navigation/HomePresenterTest.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/v7/EditorialCard.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/EditorialListData.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/ActionItemData.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/Appearance.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/home/Caption.java

show background caption color given in the editorial ws response. default is orange
No
Home > check editorial content card caption
Aptoide > Editorial > check cards caption
Aptoide > Click an editorial content card > check feature graphic caption 
Tickets related to this pull-request: [ASV-1710](https://aptoide.atlassian.net/browse/ASV-1710)

[feature/ASV-1710] show background caption color given in the ws

---

app/src/main/java/cm/aptoide/pt/app/view/MoreBundleFragment.java
app/src/main/java/cm/aptoide/pt/home/HomeContainerFragment.java
app/src/main/java/cm/aptoide/pt/home/HomeContainerNavigator.java
app/src/main/java/cm/aptoide/pt/home/HomeContainerPresenter.java
app/src/main/java/cm/aptoide/pt/home/HomeContainerView.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/ScrollableView.java

This PR adds navigation logic to home BN item clicks (in the case where the home item is already selected). The expected flow is described below.
No
You can test four different flows to see if it's implemented correctly:
1. In home, without chips selected, scroll down and click Home. It should scroll back up (this was already implemented).
2. In home, with a chip selected, scroll down and click Home. It should scroll back up and the chip should still be selected.
3. In home, with a chip selected, scroll down and click Home two times. It should scroll back up and then unselect the chip.
4. In home, with a chip selected, **don't** scroll down and click Home. It should unselect the chip.
**What are the …

[ASV-1716] - Home BN Item selection flow

---

app/src/main/java/cm/aptoide/pt/DeepLinkAnalytics.java

This PR does what the title says. It adds a hostname parameter to "Aptoide Launch" event.
No
Try different deeplinks and check if the hostname is correct
[ASV-1685](https://aptoide.atlassian.net/browse/ASV-1685)

[ASV-1685] - Add hostname to launch metrics

---

app/src/main/java/cm/aptoide/pt/home/AdsBundlesViewHolderFactory.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java

This PR aims at fixing a problem reported in fabric (link in the ticket) related with the ads. Since the crash happens on MoPub's code and we could not reproduce it is not possible to know if this solution actually fixes the problem reported.
No
Since we can not reproduce this issue and it is in MoPub's code this is unreproducible. According to João we applied this fix (searched this solution online) and we will see if the issue on fabric resurfaces.
Tickets related to this pull-request: [ASV-1778](https://aptoide.atlassian.net/browse/ASV-1778)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new keys, …

[ASV-1778] AdView Controler bug

---

app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java

This PR aims at fixing navigation when sending the helping appcoins wallet installation deeplinks. 
If the utm source is myappcoins we should navigate to appview. If the utmsource is appcoinssdk we should navigate to the new dialog.
In both cases we should send the deeplink event.
No
Send both deeplinks and check that the event is being sent on both cases and that we are navigating the correct places: 
If the utm source is myappcoins we should navigate to appview. If the utmsource is appcoinssdk we should navigate to the new dialog.
Tickets related to this pull-request: [ASV-1757](https://aptoide.atlassian.net/browse/ASV-1757) …

[ASV-1757] Fix navigation flow

---

app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java

As the title says, this PR adds deeplink support for the appc info view (the view that pops up if you click the PoA view in an appc compatible app). 
No
Test the new deeplink to check if it goes to the appc info view as expected.
Deeplink: `adb shell am start -a "android.intent.action.VIEW" -d "aptoide://cm.aptoide.pt/deeplink?name=appc_info_view"`
[ASV-1453](https://aptoide.atlassian.net/browse/ASV-1453)

[ASV-1453] - Add deeplink for appc info view

---

app/src/main/java/cm/aptoide/pt/install/InstallAnalytics.java
app/src/main/java/cm/aptoide/pt/install/InstallEvents.java
app/src/main/java/cm/aptoide/pt/install/InstallerAnalytics.java
app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java

adds new INSTALL event variation that is sent to the BI. 
This will be sent everytime an installation cancel happens, which currently can be only known when we use the new installation method from PackageInstaller.
No
Install an APPC app, cancel install wizard. This can only be tested in Cobrand & Nightly (dev)
Tickets related to this pull-request: [ASV-1748](https://aptoide.atlassian.net/browse/ASV-1748)

[Analytics/ASV-1748] cancel installation event

---

app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialAnalytics.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialManager.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java

This PR aims at fixing the problem related with a download being stuck at 100% on editorial.
This fix could also avoid it from happening on other views.
No
Perform download on all views where you can do downloads and check that there is a notification and that there when the download finishes, the android install dialog pops up.
Tickets related to this pull-request: [ASV-1814](https://aptoide.atlassian.net/browse/ASV-1814)
**Questions:**

[ASV-1814] Fix download at 100%

---

app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/appview/InstallAppView.java
app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java

This PR aims at fixing a problem where the user wouldn't be able to resume a paused download.
Note that AppView is being refactored and we will be able to have a single model coming from the manager where we will also have the download model. This was not the best solution but it is a quick temporary one.
No
Open appview, try to perform a download, pause it and then try to resume it.
It should resume the download and send the download events correctly
Tickets related to this pull-request: [ASV-1832](https://aptoide.atlassian.net/browse/ASV-1832)
**Questions:**
Does this add new dependencies which need to be added? (Eg. new keys, …

[HOTFIX/ASV-1832] Fix resume download

---

app/src/main/java/cm/aptoide/pt/app/AppCoinsAdvertisingModel.kt
app/src/main/java/cm/aptoide/pt/app/AppCoinsManager.java
app/src/main/java/cm/aptoide/pt/app/AppCoinsService.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppCoinsViewModel.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java

This PR aims at fixing the appc value being shown in the appview reward message.
Before, this message was only being shown if we came from the earn your appcoins bundle. This is now fixed, because we were doing the request but we were only getting if there was any campaign or not, now we also pass the reward value when it exists.
No
Open appview of an app with a reward (ex World Mine), from everywhere and check that the message is correctly shown.
Tickets related to this pull-request: [ASV-1834](https://aptoide.atlassian.net/browse/ASV-1834)
**Questions:** …

[HOTFIX/ASV-1834] Fix appc value

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/promotions/ClaimPromotionDialogFragment.java

Fixes the issue with the claim dialog not responding to any clicks. The attachpresenter was not being done because of a merge issue.
No
Open the claim dialog and click on get wallet/cancel/next to see if all work. You can see a promotion with a migrated app. Twitch clips is what I use to test. Install Twitch Clips Play version, go to Aptoide apps, follow promotion flow.
Tickets related to this pull-request: [ASV-1848](https://aptoide.atlassian.net/browse/ASV-1848)

[ASV-1848] hotfix: claim dialog clicks now working.

---

app/build.gradle
app/src/main/java/cm/aptoide/pt/app/AppViewModelManager.java
build.gradle

This reverts ReplayingShare so that retry on error is fixed. This should be reintroduced if we ever migrate to RxJava 2 though, as it is fixed in later versions.
No
Go to home -> Turn off internet -> Go to AppView -> Turn on internet -> Click 'Retry'
The retry should work correctly and load the app. Before this wasn't the case.
[ASV-1800](https://aptoide.atlassian.net/browse/ASV-1800)

[bugfix/ASV-1800] Retry error fix

---

app/src/main/res/values/strings.xml
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AppDownloadStatus.java

This PR fixes a bug where apps with big file sizes would display a negative progress. This was because integer/float was used for interim calculations which probably caused overflow problems. This PR essentially changes it do long / double.
No
Go to a big app, e.g. Grand Theft Auto San Andreas, and start a download. The progress should display positive values correctly.
[ASV-1879](https://aptoide.atlassian.net/browse/ASV-1879)

[bugfix/ASV-1879] Negative Progress

---

aptoide-views/build.gradle

since we need to migrate everything to srcCompat, support to drawable support lib is disabled.
No
Tickets related to this pull-request: [ASV-1889](https://aptoide.atlassian.net/browse/ASV-1889)
https://fabric.io/aptoide2/android/apps/cm.aptoide.pt.dev/issues/cc1b291641763828d6298e380c9fcb3f?time=1565222400000%3A1565308799000
https://fabric.io/aptoide2/android/apps/cm.aptoide.pt.dev/issues/75b825ce18933926652ac1cdb57c868e?time=1565222400000%3A1565308799000

[ASV-1889] fix: disable vector drawable support lib

---

app/build.gradle
aptoide-views/build.gradle

This PR removes a testCoverage command in release that was causing the release to be set as debuggable. It also improves the resolution strategy for different versions of certain dependencies (e.g. support libraries), so that we don't have to put exclude in every dependency.
This fix for release also has the positive side effect that now launch times are a lot faster.
No
Check if the release variant now isn't debuggable... I think you can check this in the manifest of the apk, but I generally check the generated BuildConfig after gradle sync.
[ASV-1847](https://aptoide.atlassian.net/browse/ASV-1847)

[bugfix/ASV-1847] Release set as debuggable

---

app/src/main/java/cm/aptoide/pt/app/AppModel.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java

This PR fixes two issues with Editors Choice analytics, namely 'App_Viewed_Open_From' and 'Editors_Choice_Download_Complete'. Please check the ticket for details.
No
Check if 'App_Viewed_Open_From' and 'Editors_Choice_Download_Complete' is being correctly sent when navigating from an Editors' Choice app.
[ASV-1859](https://aptoide.atlassian.net/browse/ASV-1859)

[bugfix/ASV-1859] - Fix for Editors Choice Analytics

---

app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java

null check the drawable.getConstantState  which is null in some scenarios and prevents the user from logging in. This solution will prevent the checkbox from becoming red when getConstantState returns null.
Could only reproduce the null on a Moto G device.
No
Flow on how to test this or QA Tickets related to this use-case: [ASV-1916](https://aptoide.atlassian.net/browse/ASV-1916)
Tickets related to this pull-request: [ASV-1916](https://aptoide.atlassian.net/browse/ASV-1916)

[ASV-1916] fix: null check the drawable.getConstantState 

---

app/src/main/java/cm/aptoide/pt/view/CustomTextInputLayout.java
app/src/main/res/layout/fragment_manage_store.xml

This fix is basically a null fix to avoid the crash on the edit store. Because of the AndroidX migration, this custom view is not working as expected since the view it was based on changed behaviour (textinputlayout).
The goal is to fix visual problems in the future, for now we prevent the crash. From the tests I've done, the view is functional. The errors are displayed but in the right place.
Also deleted some code that was not being used.
No
Login to an account with store > edit store > play with the youtube/twitch/facebook/twitter elements. …

[Hotfix/ASV-1919] app crash edit store

---

app/src/main/res/layout/load_more_error.xml

This PR aims at fixing the load more error view inflating. Due to the change to androidx and the fact that this view was still using the support constraint layout, it was crashing.
No
Open home, turn off internet, scroll and check that the load more error shows correctly
Tickets related to this pull-request: [ASV-1807](https://aptoide.atlassian.net/browse/ASV-1807)
**Questions:**

[HOTFIX/ASV-1807] Fixed load more inflate error

---

app/src/main/res/xml/settings.xml

This PR aims at fixing the default value for settings "set adult content", which was being set to false because the default value was not being saved in the shared preferences.
No
Open settings (after fresh install or clear cache) and check that all values are set correctly to the default value. Then change a setting and check that it was saved correctly.
Tickets related to this pull-request: [ASV-1959](https://aptoide.atlassian.net/browse/ASV-1959)
**Questions:**

[ASV-1959] Adult content false

---

app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialRepository.kt

This PR aims at fixing the Editorial download and open the appview. The request was not being correctly cached which would cause the editorialviewmodel to be wrongly created, meaning that the navigation to appview and download would not work.
No
Open Editorial and try to download the app and try to navigate to appview.
Tickets related to this pull-request: [ASV-1980](https://aptoide.atlassian.net/browse/ASV-1980)
**Questions:**

[Hotfix ASV-1980] Editorial fix

---

app/src/main/java/cm/aptoide/pt/editorial/EditorialItemsViewHolder.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialMedia.java
app/src/main/res/layout/editorial_item_layout.xml

This PR implements embedded videos on a webvideo in editorials;
No
You'll need to rewrite a charles request for an editorial card so as to include a piece of media with type "video-webview" and an embedded youtube link (youtube.com/embed/<videoId>). Check that the video plays correctly on the editorial fragment
Tickets related to this pull-request: [ASV-2022](https://aptoide.atlassian.net/browse/ASV-2022)

[ASV-2022] Editorial now supports embedded videos;

---

app/src/main/java/cm/aptoide/pt/editorialList/EditorialListFragment.java
aptoide-views/src/main/res/layout/editorial_list_action_item_skeleton.xml

This PR implements the skeleton view on editorial;
No
Check that the editorial fragment shows the skeleton while loading;
Tickets related to this pull-request: [ASV-1984](https://aptoide.atlassian.net/browse/ASV-1984)

[ASV-1984] Implemented skeleton for editorial;

---

dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/listapps/ListAppsUpdatesRequest.java

This ticket enables aabs everywhere but in Apps.
No
Check if search shows apps with splits (airbnb - split store)
Check if apps does not show apps with splits (install 2nd latest linkedin, force Apps request and check if there is no updates to do)
Tickets related to this pull-request: [ASV-2036](https://aptoide.atlassian.net/browse/ASV-2036)

[ASV-2036] task: enable app bundles everywhere but Apps

---

app/src/main/java/cm/aptoide/pt/view/wizard/WizardPageTwoFragment.java
app/src/main/res/drawable/oval_grey.xml
app/src/main/res/layout-land/credentials_edit_texts.xml
app/src/main/res/layout/credentials_edit_texts.xml
app/src/main/res/layout/fragment_login_signup_wizard_layout.xml
app/src/main/res/layout/fragment_wizard.xml
app/src/main/res/layout/fragment_wizard_model_page.xml
app/src/main/res/values/styles_aptoide_text_view.xml

This PR aims at changing wizard view to show text on all devices, including the ones with smaller screensizes (ex: 4.0'').
Also took the chance to fix background color from radio buttons and the Recover your password button text color (as requested by Luis).
No
Open view on different devices (with different screensizes) and check that everything is visible and that there are no problems.
Tickets related to this pull-request: [ASV-2027](https://aptoide.atlassian.net/browse/ASV-2027)
**Questions:**

[ASV-2027] Fixed wizard height

---

app/src/main/java/cm/aptoide/pt/presenter/MainPresenter.java
app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
app/src/test/java/cm/aptoide/pt/navigation/BottomNavigationPresenterTest.java

This PR aims at improving downloads performance. After the spike in https://aptoide.atlassian.net/browse/ASV-2064 we discovered that one of the main problems related with the downloads performance is the fact that the getInstall() method is being subscribed multiple times, which leads to multiple emissions (as it has several subscriptions). As some of these subscriptions were not necessary for all users (for example, the ones that were related with root installation timeouts, which were fixed here).
No
Do several downloads on a rooted device and check that it installs normally. You may try to reproduce a timeout but I could not force it.
**What are the relevant …

[ASV-2075] Fix timed out installations

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java

OkHTTP clients cache GET requests by default. Because we now are migrating some POST requests to GET we surfaced an issue that was intentionally clearing the cache every time app is launched. That logic was because of billing requirements (based on comment), feature that we do not support anymore. So I only removed both method calls and refactored the code a bit to reuse logic.
No
Flow on how to test this or QA Tickets related to this use-case: [ASV-2114](https://aptoide.atlassian.net/browse/ASV-2114)
Tickets related to this pull-request: [ASV-2114](https://aptoide.atlassian.net/browse/ASV-2114)

[Bugfix/ASV-2114] fix to okhttp cache getting cleared on start

---

app/src/dev/java/cm/aptoide/pt/abtesting/experiments/SimilarAppsExperiment.kt
app/src/internal/java/cm/aptoide/pt/abtesting/experiments/SimilarAppsExperiment.kt
app/src/leak/java/cm/aptoide/pt/abtesting/experiments/SimilarAppsExperiment.kt
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/monetisation/java/cm/aptoide/pt/abtesting/experiments/SimilarAppsExperiment.kt
app/src/prod/java/cm/aptoide/pt/abtesting/experiments/SimilarAppsExperiment.kt

This is an attempt to fix the issue that is going on with the experiment in Rakam. Wasabi numbers are 50/50 but rakam is like 70/30 for the control group. I've separated the default from the control and now added checks for experiment validation in both impression and conversion events.
No
App view > click install > record impression when similar is visible > record conversion when any app in similar is clicked (appc or not)
Tickets related to this pull-request: [ASV-2107](https://aptoide.atlassian.net/browse/ASV-2107)
**Questions:**
Does this add new dependencies which need to be added? Rakam key if you want to see Charles events. …

[Bugfix/ASV-2107] Rakam Analytics ab testing similar issue

---

app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java

Interstitial ads are not loaded or shown anymore in AppCoins wallet app view.
No
Check if ads are not shown in appcoins wallet app view.
Check if ads are shown in other appviews that are not appcoins wallet or appc iab/billing
Tickets related to this pull-request: [ASV-2045](https://aptoide.atlassian.net/browse/ASV-2045)

[Feature/ASV-2045] remove interstitial appcoins wallet app view

---

app/src/main/java/cm/aptoide/pt/home/Home.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/bundles/BundleDataSource.java
app/src/main/java/cm/aptoide/pt/home/bundles/BundlesAdapter.java
app/src/main/java/cm/aptoide/pt/home/bundles/BundlesRepository.java
app/src/main/java/cm/aptoide/pt/home/bundles/FakeBundleDataSource.java
app/src/main/java/cm/aptoide/pt/home/bundles/RemoteBundleDataSource.java
app/src/main/java/cm/aptoide/pt/home/bundles/base/ActionBundle.java
app/src/test/java/cm/aptoide/pt/home/BundlesRepositoryTest.java

This PR makes it so that the home bundles are now loaded one by one for skeleton. It also does other minor refactors. 
Please note that the solution is not 100% ideal. Part of this is because we're manipulating GetStoreWidgets response which causes concurrency issues in certain scenarios (we should only handle immutable data instead).
No
Test the initial home bundles load (close the app and open it). Each bundle should be loaded separately (only for the first GetStoreWidgets request). Also scroll through home and verify that there's no repeated bundles, and go to other fragments and come back and check if everything's ok. You can also test if it behaves correctly if the requests get cancelled (when the …

[feature/ASV-2032] Skeleton one by one

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java

This PR aims at fixing the interstitial ads not being shown in AppView through the APKFY flow. This was broken because after a refactor on appview we were only listening to the click on the install button, which does not happen on the APKFY flow.
No
Open app through apkfy flow (replace the app id - instead of it being extracted, change it to a known app id of any app). After opening an apk with this change, it will pop the appview and after accepting permissions (etc) it should start the download and if a network is available to return an add you should be able to see the ad (use vpn if needed) …

[HOTFIX/ASV-2138] Showing interstitial ads in APKFY

---

app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
app/src/main/res/values/strings_settings.xml

This PR adds the device's density value to the hardware specs dialog in settings;
No
Go to the hardware specs dialog in settings and make sure everything is showing up according to the ticket;
Tickets related to this pull-request: [ASV-2135](https://aptoide.atlassian.net/browse/ASV-2135)

[ASV-2135] Added q density value to hardware specs in settings;

---

app/src/main/res/values/attrs.xml
app/src/main/res/values/styles_aptoide_text_view.xml
app/src/main/res/values/themes.xml

This PR simply makes it so that text styles now reference a theme's attribute instead of a color directly.
No
Everything should all be the same seeing as I didn't change any values, only the references.
[ASV-1770](https://aptoide.atlassian.net/browse/ASV-1770)

[feature/ASV-1770] TextView styles to themes color attributes

---

app/src/main/java/cm/aptoide/pt/view/ThemeUtils.java
app/src/main/java/cm/aptoide/pt/view/ThemedActivityView.java

This PR aims at setting the "theme" configured in the system as the theme of the app. This means that if the system is in dark theme mode, the app will also change to dark mode.
No
Open the app on a device with light theme and check that the app is in light theme. Repeat the test in a device with dark theme and check if ti is in dark theme as well.
Tickets related to this pull-request: [ASV-1766](https://aptoide.atlassian.net/browse/ASV-1766)
**Questions:**

[ASV-1766] Theme from settings

---

app/src/main/java/cm/aptoide/pt/reactions/ui/ReactionsPopup.java
app/src/main/res/drawable/rounded_corners_white.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/themes.xml

This PR adds a new color for the reactions popup background with dark theme;
No
Make sure the color is working on dark theme;
Tickets related to this pull-request: [ASV-1772](https://aptoide.atlassian.net/browse/ASV-1772)

[ASV-1772] Added background color for reactions pop up with dark theme;

---

app/src/main/res/layout/app_home_item.xml
app/src/main/res/layout/apps_appc_promotion_upgrade_app_item.xml
app/src/main/res/layout/apps_installed_app_item.xml
app/src/main/res/layout/apps_update_app_item.xml
app/src/main/res/layout/displayable_grid_ad.xml
app/src/main/res/layout/editorial_action_item.xml
app/src/main/res/layout/feature_graphic_home_item.xml
app/src/main/res/layout/frame_layout.xml
app/src/main/res/layout/reward_app_home_item.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml
aptoide-views/src/main/res/layout/apps_app_card_item.xml
aptoide-views/src/main/res/layout/apps_download_app_item.xml
aptoide-views/src/main/res/layout/editorial_action_item_skeleton.xml

This PR tries to uniformize cards in home and apps. Due to the StoreThemes class and how it's being used, I left store cards out of this ticket until we decide what to do with it
No
Make sure apps and home cards have the same background are are being set in the same way;
Tickets related to this pull-request: [ASV-1774](https://aptoide.atlassian.net/browse/ASV-1774)

[ASV-1774] Uniformization of card backgrounds in home and apps;

---

app/src/main/java/cm/aptoide/pt/permission/DialogPermissions.java
app/src/main/res/layout/layout_dialog_permissions.xml
app/src/main/res/values/styles_aptoide_text_view.xml

This PR aims at fixing the dark theme dialog on appview.
No
Open any appview in a device with dark theme. Click on the "See Permissions" button at the end of the view.
Tickets related to this pull-request: [ASV-2223](https://aptoide.atlassian.net/browse/ASV-2223)
**Questions:**

[ASV-2223] Permissions on app view

---

app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java

The goal of PR is to solve the issue of "duplicated" impression events of the similar apps bundles in the app view when the user clicks install. What is currently happening in production is that when the user clicks install an app view with similar apps bundles, we send an similar appc and similar apps impression event. Then when the user scrolls down and has both bundles fully visible in the screen it would send a second impression event. 
With this fix, we either send an event when user clicks install or when the user scrolls down to the fully visible bundle.
No
Home > Open an App (with similar apps) > Click install > should send Appc_Similar_App_Interact …

[ASV-1846] fix: similar appc apps impression events 

---

app/src/main/java/cm/aptoide/pt/search/analytics/SearchAnalytics.java

This PR changes the search_result_clicked event for empty searches. Before, when this happened, position was being filled with empty and everything else was not being filled at all. Since this creates null properties in rakam that make very little sense, we're now sending empty on all the properties for that event to make it clear what is going on;
No
Do a search that returns no results and make sure the properties to rakam are being filled with empty in charles;
Tickets related to this pull-request: [ASV-2201](https://aptoide.atlassian.net/browse/ASV-2201)

[ASV-2201] Sending "empty" on all properties related to empty searchs

---

app/src/main/java/cm/aptoide/pt/search/SearchNavigator.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
app/src/main/res/layout/incl_no_search_results_layout.xml
app/src/test/java/cm/aptoide/pt/search/SearchResultPresenterTest.java

This PR implements the new empty state for search;
No
Make sure you have adult content turned off. Do a search with the word "sex" (or any other adult content related keyword). You should see the new empty state. Press the settings button. Turn on adult content and go back. The search results page should reload with the related results;
Tickets related to this pull-request: [MOB-112](https://aptoide.atlassian.net/browse/MOB-112)

[MOB-112] Implemented new empty state for search;

---

app/src/main/java/cm/aptoide/pt/home/HomeContainerFragment.java
app/src/main/res/layout/fragment_appcoins_info.xml

Set the right dark theme color in AppCoinsInfo view.
Fix crash going on with the chips when you unselected them.
No
Select, unselect chips in both themes.
Open App view info fragment in both light and dark theme.
Tickets related to this pull-request: [MOB-120](https://aptoide.atlassian.net/browse/MOB-120)

[Feature/MOB-120] Support dark-theme in AppCoins Information View.

---

app/src/main/java/cm/aptoide/pt/account/view/user/CreateStoreDisplayable.java
app/src/main/java/cm/aptoide/pt/store/view/CreateStoreWidget.java
app/src/main/java/cm/aptoide/pt/view/recycler/displayable/DisplayablesFactory.java
app/src/main/res/layout/create_store_displayable_layout.xml

This adds support for the create store widget in the Stores tab, when the user has no registered store.
No
Get an account without store, go to the Stores tab and check if the "Create store" widget looks ok for light and dark theme.
[ASV-122](https://aptoide.atlassian.net/browse/ASV-122)

[feature/MOB-122] Added support for dark theme in create store widget

---

app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java

Hardware specs dialog theme change
No
Test settings > hw specs dialog in both Light and Dark theme
Tickets related to this pull-request: [MOB-137](https://aptoide.atlassian.net/browse/MOB-137)

[MOB-137] feature: Support dark-theme in hardware specs dialog.

---

app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java
app/src/main/java/cm/aptoide/pt/account/view/store/ManageStoreFragment.java
app/src/main/java/cm/aptoide/pt/account/view/user/ManageUserFragment.java
app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepOneFragment.java
app/src/main/java/cm/aptoide/pt/account/view/user/ProfileStepTwoFragment.java
app/src/main/java/cm/aptoide/pt/store/view/AddStoreDialog.java
app/src/main/java/cm/aptoide/pt/store/view/PrivateStoreDialog.java
app/src/main/java/cm/aptoide/pt/view/fragment/BaseDialogFragment.java
app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
app/src/main/res/layout/dialog_choose_avatar_source.xml
app/src/main/res/layout/fragment_manage_store.xml
app/src/main/res/layout/fragment_manage_user.xml
app/src/main/res/layout/fragment_profile_step_two.xml
app/src/main/res/values/styles_aptoide_button.xml
app/src/main/res/values/styles_aptoide_text_view.xml
utils/src/main/java/cm/aptoide/pt/utils/GenericDialogs.java

This deals with fixes and quality of life improvements.
fixes:
- ProgressDialogs dark theme
- Orange Title
improvement
- Clicking enter in both username and storename fields actually submit field and remove keyboard, instead of a line break.
No
Create accounts in both Light & Dark themes.
Tickets related to this pull-request: [MOB-121](https://aptoide.atlassian.net/browse/MOB-121)

[Feature/MOB-121] Support dark-theme in Create/Edit Profile flow 

---

app/src/main/res/layout-v21/appview_poa_layout.xml
app/src/main/res/layout/appview_poa_layout.xml

Budget element in App View now supports dark-theme
No
Test in both Light & Dark (PoA ending soon)
Tickets related to this pull-request: [MOB-128](https://aptoide.atlassian.net/browse/MOB-128)

[MOB-128] feature: Support dark-theme in PoA budget element in app view.

---

app/src/main/java/cm/aptoide/pt/home/HomeContainerFragment.java
app/src/main/res/drawable/default_home_chips_background_white.xml
app/src/main/res/drawable/default_home_chips_text_color.xml
app/src/main/res/drawable/default_home_chips_text_color_dark_theme.xml
app/src/main/res/drawable/ic_cancel_black_24dp.xml
app/src/main/res/layout/home_action_bar_chips.xml
app/src/main/res/layout/view_home_chips.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/themes.xml

Home Category filter chips now support dark theme.
Two attrs created, one for the chips background, one for the textcolor, which is orange and white for light theme and white & black for the dark theme, this was achieved with a selector xml.
Also has a fix for the bug that was showing up 1px dots in the chips layout corners. In light theme this would not be noticeable since its white on white but in dark theme, orange dots would show up. this was achieved by removing the unnecessary card view layout for the chips background. We wanted the cardview because of the elevation, but the app bar layout already gives the behaviour and elevation that we want.
No
Test in both …

[Feature/MOB-118] Support dark-theme in home category chips

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/list/AppsController.kt
app/src/main/java/cm/aptoide/pt/home/apps/list/models/UpdateCardModel.kt
app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
app/src/main/res/drawable/ic_refresh_action_white.xml
app/src/main/res/layout/apps_header_item.xml
app/src/main/res/layout/apps_update_app_item.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles_aptoide_text_view.xml
app/src/main/res/values/themes.xml
aptoide-views/src/main/res/drawable/ic_pause_to_resume_white.xml
aptoide-views/src/main/res/drawable/ic_resume_to_pause_white.xml
aptoide-views/src/main/res/layout/download_progress_view.xml

Fixes icons and Update all text color to support dark theme in Apps.
No
Test Apps (download controls) in both light & dark theme.
Tickets related to this pull-request: [MOB-125](https://aptoide.atlassian.net/browse/MOB-125)

[Feature/MOB-125] Support dark theme in Apps icons

---

app/src/main/java/cm/aptoide/pt/account/view/store/ManageStoreFragment.java
app/src/main/java/cm/aptoide/pt/account/view/user/ManageUserFragment.java
app/src/main/java/cm/aptoide/pt/store/view/BadgeDialogFactory.java
app/src/main/java/cm/aptoide/pt/store/view/StoreTabWidgetsGridRecyclerFragment.java
app/src/main/res/drawable/ic_edit_white_9dp.xml
app/src/main/res/layout/badge_progress_layout.xml
app/src/main/res/layout/displayable_store_meta.xml
app/src/main/res/layout/store_badge_dialog.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/themes.xml

This PR does 3 things: 
- Adds dark theme support for badge dialog next to the edit store button;
- Fixes the edit button color;
- Edit your store -> Upload photo dialog colors fixed.
No
Test light/dark theme for 3 things:
- Badge dialog next to the edit store button;
- Edit button drawable color;
- Edit your store -> Upload photo dialog colors.
[MOB-152](https://aptoide.atlassian.net/browse/MOB-152)

[feature/MOB-152] Badge Dialog Dark Theme

---

app/src/main/java/cm/aptoide/pt/account/view/AccountNavigator.java
app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
app/src/main/java/cm/aptoide/pt/navigator/ExternalNavigator.kt
app/src/main/java/cm/aptoide/pt/view/settings/MyAccountFragment.java
app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java

Fixes the click on developer catappult card. we were passing the color data instead of res id.
Also fixes other custom chrome tab navigations like Terms and Conditions and Privacy Policy.
No
Click on developer card in app view.

[MOB-22] fix: catapput developer card now navigates correctly to the web page.

---

app/src/main/java/cm/aptoide/pt/home/HomeNavigator.java
app/src/main/java/cm/aptoide/pt/store/view/StoreGridHeaderWidget.java
app/src/main/java/cm/aptoide/pt/store/view/StorePagerAdapter.java
app/src/main/java/cm/aptoide/pt/store/view/StoreTabGridRecyclerFragment.java
app/src/main/java/cm/aptoide/pt/store/view/StoreTabNavigator.java
app/src/main/java/cm/aptoide/pt/store/view/my/MyStoresFragment.java
app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
app/src/main/java/cm/aptoide/pt/view/FragmentProvider.java
app/src/main/java/cm/aptoide/pt/view/configuration/implementation/VanillaFragmentProvider.java
app/src/main/java/cm/aptoide/pt/view/recycler/widget/GridDisplayWidget.java

This PR aims at fixing a bug where we had double search bars in some views of the stores. This was happening on the tabs that were listApps of type API.
No
Open the several grid views in Aptoide. In Home, in stores, navigate through it and check if everything is ok with the toolbars.
Tickets related to this pull-request: [MOB-83](https://aptoide.atlassian.net/browse/MOB-83)
**Questions:**

[MOB-83] Double Search

---

app/src/main/res/layout/fragment_with_toolbar_no_theme.xml
app/src/main/res/layout/row_excluded_update.xml
app/src/main/res/values/styles.xml

Excluded updates dark-theme (titles, menu dropdown background)
No
Test excluded updates view in both light & dark 
Tickets related to this pull-request: [MOB-22](https://aptoide.atlassian.net/browse/MOB-22)

[MOB-22] feature: Support dark-theme in excluded updates fragment.

---

app/src/main/res/layout/dialog_comment_on_review.xml
app/src/main/res/layout/fragment_my_account.xml
app/src/main/res/values/colors_stores_themes.xml
app/src/main/res/values/themes.xml

Small specific stores theme color adjustements.
Fix to the settings button spacing in my account.
No
validate my account and color changes on both themes.
Black was the most important one (comment dialog would show text in black)
Tickets related to this pull-request: [MOB-45](https://aptoide.atlassian.net/browse/MOB-45)

[MOB-45] fix: colors used in some specific store themes

---

app/src/main/AndroidManifest.xml
app/src/main/res/values/colors_stores_themes.xml
app/src/main/res/values/themes.xml
aptoide-views/src/main/res/drawable-night-v23/splash_screen.xml
aptoide-views/src/main/res/drawable-night/splash_screen.xml
aptoide-views/src/main/res/values-night/colors_stores_themes.xml

Adds dark mode support for splashscreen in Android 10 devices.
No
In an Android 10 device, check if light/dark mode shows the correct splash screen.
[MOB-170](https://aptoide.atlassian.net/browse/MOB-170)

[feature/MOB-170] Splash screen dark mode

---

app/src/main/java/cm/aptoide/pt/store/view/AddStoreDialog.java
app/src/main/java/cm/aptoide/pt/store/view/GridStoreMetaDisplayable.java
app/src/main/java/cm/aptoide/pt/store/view/GridStoreMetaWidget.java
app/src/main/java/cm/aptoide/pt/store/view/TopStoresFragment.java
app/src/main/java/cm/aptoide/pt/view/FragmentComponent.java
app/src/main/res/layout/displayable_grid_app.xml

Fixes App spacing between items in Stores Grid-like layouts.
Also fixes the Top Stores Fragment layout, which items are not decorated with spacing between them.
Also minimizes the issue of navigating to an empty list of followers when you click on the number of followers inside store view.
No
Test app items in general, especially where the layout is used (Grid apps/ListStoreApps)
Test top stores (go to stores > add store > discover top stores)
Test navigation to followers inside store view (click followers number).
Tickets related to this pull-request: [MOB-167](https://aptoide.atlassian.net/browse/MOB-167)
**Code Review …

[MOB-167] fix: app spacing in store grid layouts.

---

app/src/main/res/drawable/aptoide_gradient.xml
app/src/main/res/drawable/aptoide_gradient_rounded.xml
app/src/main/res/layout/action_bar_stores.xml
app/src/main/res/layout/app_install_cardview.xml
app/src/main/res/layout/fragment_app_view.xml
app/src/main/res/layout/my_stores.xml

Editorial download buttons (app card in bottom, not placeholder)
Orange gradient direction in Android 10 (both toolbar & install buttons)
Remove some code not being used (like fab in storesfragment)
No
install controls in editorial when app is in the bottom (only 1 app articles) in both light & dark
Android 10 orange gradient in toolbar  (home & app view & stores for light theme) and orange gradient install buttons (both light and dark theme)
Tickets related to this pull-request: [MOB-45](https://aptoide.atlassian.net/browse/MOB-45)
[MOB-169](https://aptoide.atlassian.net/browse/MOB-169)

[MOB-45] fix: Editorial download buttons & gradient direction fix

---

app/src/main/java/cm/aptoide/pt/autoupdate/AutoUpdateDialogFragment.kt
app/src/main/res/layout/auto_update_dialog_fragment.xml
app/src/main/res/layout/pushnotificationlayout.xml
app/src/main/res/values/styles.xml

This PR aims at allowing auto update dialog to support dark theme. Also fixed notifications dark theme.
No
Open Aptoide, go through the auto update flow and check the dialog in dark theme. If you need the rewrite let me know.
Tickets related to this pull-request: [MOB-218](https://aptoide.atlassian.net/browse/MOB-218)
**Questions:**

[MOB-218] AutoUpdate dialog darktheme

---

app/src/main/java/cm/aptoide/pt/view/fragment/BaseDialogFragment.java

This would happen because the onCreate of the MainActivity would run after the onCreate of the dialog, which means it would overwrite the style setted for the dialog. By changing the setStyle of the dialog to the onCreateDialog, which runs between the onCreate() and onViewCreated(), we guarantee that the theme is always correctly set for everyone that extends this base dialog fragment.
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-232](https://aptoide.atlassian.net/browse/MOB-232)
Tickets related to this pull-request: [MOB-232](https://aptoide.atlassian.net/browse/MOB-232)

[MOB-232] fix: fragment dialogs would lose theme when orientation changes

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/ads/AdsUserPropertyManager.java

This PR fixes ads super property to Rakam being set too late and not being sent on session_start events;
No
From a fresh install check charles and make sure the ads property is being sent on the first _session_start event to Rakam;
Tickets related to this pull-request: [MOB-142](https://aptoide.atlassian.net/browse/MOB-142)

[MOB-142] Fixed ads super property being set too late;

---

app/src/main/java/cm/aptoide/pt/app/view/widget/OtherVersionWidget.java
app/src/main/res/layout/other_version_row.xml

Store view now displays correctly in other versions view when the version name is very long. Also the version name ellipsize is now in the middle (easier to compare version names) and on long press it shows an Android tooltip with the full version name.
No
Apps where I tested: Play Games, Netflix, Facebook
Tickets related to this pull-request: [MOB-199](https://aptoide.atlassian.net/browse/MOB-199)

[MOB-199] fix: store view now displays correctly in other versions view

---

app/src/main/res/layout/fragment_appcoins_info.xml
aptoide-views/src/main/res/drawable-night/editorial_install_card_background.xml
aptoide-views/src/main/res/drawable/editorial_install_card_background.xml

This PR aims at fixing the editorial view. Also took the chance to fix a dark theme bug that Luis reported. In the appc info view we are using the wrong separator color
No
Open editorial fragment on devices above and below android 4.4.2
Tickets related to this pull-request: [MOB-241](https://aptoide.atlassian.net/browse/MOB-241)
**Questions:**

[hotfix/MOB-241] Editorial crashing

---

app/src/main/java/cm/aptoide/pt/sync/alarm/SyncStorage.java

Fixes a bug where the notifications PNP endpoint was not being called. 
No
Check that if with the Charles rewrite in the ticket below, a notification appears on launch.
[MOB-270](https://aptoide.atlassian.net/browse/MOB-270)

[bugfix/MOB-270] No request at PNP endpoint

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/app/view/OtherVersionsFragment.java
app/src/main/java/cm/aptoide/pt/repository/RepositoryFactory.java
app/src/main/java/cm/aptoide/pt/repository/request/RequestFactory.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java

Shows app bundles to users that disable the "Show compatible apps only" setting, even if its a MIUI rom.
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-246](https://aptoide.atlassian.net/browse/MOB-246)
Tickets related to this pull-request: [MOB-246](https://aptoide.atlassian.net/browse/MOB-246)

[MOB-246] fix: show app bundles if 'Show compatible apps only' is disabled

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java

This fixes an issue where if searching an app in a specific store resulted in other results (like from apps & catappult store).
No
Go to stores and follow 'nzxt', then go to the store page and search for an app (e.g. 'tft'), it should only return apps inside that store, and not others.
[MOB-273](https://aptoide.atlassian.net/browse/MOB-273)

[bugfix/MOB-273] Search Store Apps fix

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java

App View open type behaviour (dialog or auto-download) only fires once per app view instance.
No
Test 3 flows: 
-  apkfy (go to Apkfy.java and replace line 75 with     `return 51150866L; `
- automatic download (go to the reviews, click install in top right, pause download then go to other versions and press back -> it shouldn't start download again.)
- install dialog (deep link from web) - similar to apkfy behaviour
Tickets related to this pull-request: [MOB-413](https://aptoide.atlassian.net/browse/MOB-413)

[MOB-413] fix: app view open types now only work once per app view

---

app/src/main/java/cm/aptoide/pt/wallet/WalletInstallActivity.kt
app/src/main/res/layout/wallet_install_activity.xml
app/src/main/res/values/strings.xml

Because AppCoins sdk changed behaviour, the current copy makes less sence. 
Changed both wallet install success copy (removed) & Got it button (to continue)
No
Deeplink ->  adb shell am start -a "android.intent.action.VIEW" -d "market://details?id=com.appcoins.wallet\&utm_source=appcoinssdk\&app_source=cm.aptoide.pt"
Tickets related to this pull-request: [MOB-271](https://aptoide.atlassian.net/browse/MOB-271)

[MOB-271] fix: copy amend in wallet install deeplink flow.

---

app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java

This PR aims at fixing the ab test participating event in the installed with aptoide events
No
Open apps, and check that it is only sent 1 event. Also check that contrarily to what was happening before, when you pull to refresh or when you update any app, it does not send any event new participating event.
Tickets related to this pull-request: [MOB-472](https://aptoide.atlassian.net/browse/MOB-472)
**Questions:**

[MOB-472] Fixed installed with aptoide ab test events

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/appview/InstallAppView.java

show generic error dialog when App validation fails on download creation. 
This is only for the app view.
No
You need to start a download on app view of a download that fails AppValidation in AppValidator.kt
Tickets related to this pull-request: [MOB-414](https://aptoide.atlassian.net/browse/MOB-414)

[MOB-414] fix: show generic error dialog when App validation fails 

---

app/src/main/java/cm/aptoide/pt/view/FragmentComponent.java

This PR aims at fixing a null pointer exception while opening the recommended stores fragment after pressing the "more" button.
No
Open stores and press the more button from the recommended stores section
Tickets related to this pull-request: [MOB-552](https://aptoide.atlassian.net/browse/MOB-552)
**Questions:**

[HOTFIX/MOB-552] Recommended More Fragment

---

app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/appview/InstallAppView.java
app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
app/src/main/java/cm/aptoide/pt/download/DownloadFactory.java
app/src/main/java/cm/aptoide/pt/download/InvalidAppException.java

This PR aims at changing the message that is shown when the app is not valid (meaning that something important is missing on the webservice response, like md5, path to download, etc). 
**PS:** This error is only being mapped in AppView as the errors for the other views where we have downloads were not thought yet.
No
Change on download factory, instead of returning the download, just throw an InvalidAppException. Either that or just make a rewrite where you put one of the important fields as empty.
Tickets related to this pull-request: [MOB-496](https://aptoide.atlassian.net/browse/MOB-496)
**Questions:**
Does this add new …

[MOB-496] New error message for app not valid

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/install/InstallAppSizeValidator.kt
app/src/main/java/cm/aptoide/pt/install/InstallManager.java

This PR aims at implementing a check to see if the device has enough space to install the app. Since the app after installing has occupies more space than the original apk, I added a buffer of 20%.
No
On a device with low space, check that if you try to download a big app (example: creative destruction), you won't even start the download (you can check this by looking at Charles and by seeing that the progress bar won't be shown)
Tickets related to this pull-request: [MOB-538](https://aptoide.atlassian.net/browse/MOB-538)
**Questions:**
**Code Review …

[MOB-538] Check available space

---

app/src/main/java/cm/aptoide/pt/home/Home.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java
app/src/main/java/cm/aptoide/pt/home/bundles/RemoteBundleDataSource.java

This attempts to fix a bug where home wouldn't fully load and remain stuck in skeleton. In reality it actually loaded but then went again to the skeleton state. It seems that the reason was that adding the ads bundle was delaying the emission of HomeBundle and was causing issues. At this point it's not 100% clear that it is fixed but it seems to be.
No
Simply open home several times (try to clear cache and force stop as well) and check that the skeleton bug doesn't appear again.
[MOB-540](https://aptoide.atlassian.net/browse/MOB-540)

[bugfix/MOB-540] Home Skeleton bug

---

app/src/main/java/cm/aptoide/pt/app/AppViewAnalytics.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/download/DownloadAnalytics.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialAnalytics.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListAnalytics.kt
app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListPresenter.kt
app/src/main/java/cm/aptoide/pt/promotions/PromotionsAnalytics.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallAnalytics.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallPresenter.kt
app/src/test/java/cm/aptoide/pt/app/view/EditorialPresenterTest.java

It sends analytics for when there is not enough space to install an app. 
No
Check for every place where there's a download (appview, promotions, earnappclist, editorial) if it sends the correct event when there's no space. Either check this with a device with no space, or go to InstallManager and always set the NOT_ENOUGH_SPACE_ERROR (~line 243)
[MOB-582](https://aptoide.atlassian.net/browse/MOB-582)

[feature/MOB-582] Analytics for NotEnoughSpace error

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/download/FileDownloadTask.java
app/src/main/java/cm/aptoide/pt/install/InstallManager.java
aptoide-database/src/main/java/cm/aptoide/pt/database/realm/Download.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AppDownloadManager.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AppDownloadStatus.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadStatusMapper.java
utils/src/main/java/cm/aptoide/pt/utils/AptoideUtils.java

This fixes a bug where file integrity (with a md5 check) was being done in the main thread. It's now in a background thread and this file integrity check now is being represented by a new download status so that the download progress is indeterminate during that time. Also improves md5 check time by increasing the input buffer size.
No
Check first that downloads are working correctly in general. Then check that big app downloads (with OBB) do not block the main thread at any point during the download (move the screen while downloading, especially at around 99+%). You can also check that the app download status during the integrity check (md5) of the last file is indeterminate (check that the log …

[bugfix/MOB-597] Async MD5 Calculation

---

app/src/main/java/cm/aptoide/pt/install/InstallAppSizeValidator.kt

This PR aims at removing a buffer from the download available space check
No
In a device low on storage try download apps and check that it is coherent.
Tickets related to this pull-request: [MOB-615](https://aptoide.atlassian.net/browse/MOB-615)
**Questions:**

[MOB-615] Remove buffer space in download

---

app/src/main/java/cm/aptoide/pt/home/apps/AppMapper.java

This PR aims at fixing the apps updates and or downloads getting stuck in the indeterminate state. This was happening because for the indeterminate state we were setting it to "installing" state which would "cancel" the download view
No
Open apps and perform updates. Check that it is not stuck in the indeterminate state. Also, download on appview and then go to apps to see that it is in the correct state as well.
Tickets related to this pull-request: [MOB-627](https://aptoide.atlassian.net/browse/MOB-627)
**Questions:**

[MOB-627] Apps Fix

---

downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AppDownloadStatus.java

Fixes an issue where some apps would get stuck on 100%.
No
Go to "Legends of Runeterra" (either editorial or appview) and check that it downloads correctly and doesn't get stuck on 100% as before.
[MOB-647](https://aptoide.atlassian.net/browse/MOB-647)

[hotfix/MOB-647] Download stuck on 100%

---

app/src/main/java/cm/aptoide/pt/app/AppViewModelManager.java

Fixes a bug where when an appview opened from a deeplink without store name, the deeplink popup dialog worked fine, but the regular install button in appview did not.
No
Test that the regular install button coming from a deeplink now works fine. You easily test this by searching for "Crab War" (Crab War : Idle Swarm Evolution), downloading version 3.19.0, or similar. Then open the game and it should ask to update it. Open the deeplink with aptoide and test the flow.
Also pls try to test if nothing broke with regular install flow in other scenarios (I don't think it's possible though)
[MOB-600](https://aptoide.atlassian.net/browse/MOB-600)

[bugfix/MOB-600] Deeplink install bug

---

app/src/main/java/cm/aptoide/pt/database/RoomUpdatePersistence.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
app/src/main/java/cm/aptoide/pt/home/apps/UpdatesManager.java
app/src/main/java/cm/aptoide/pt/install/InstalledIntentService.java
app/src/main/java/cm/aptoide/pt/updates/UpdatePersistence.java
app/src/main/java/cm/aptoide/pt/updates/UpdateRepository.java
aptoide-database/src/main/java/cm/aptoide/pt/database/room/UpdateDao.java

This pr aims at fixing the button of the install button in appview after updating them. On André's phone, initially, any installation (update, downgrade, whatever) would not update the button, later on it was discovered that it was phone specific. After that i was able to discover that i could reproduce that behavior by downgrading an app and then trying to update it. Then, after the update was installed, the button would not update to open because the update from the db would be removed in the downgrade and then when we would try to get it on the database replaced (update) call, it would not exist so the db would not emit (Room does not reply wiht an empty list like Realm, BUT in case the method is single it will throw an exception that we can map to null). …

[HOTFIX/MOB-646] Install button refresh

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/app/AppCoinsService.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsService.java
app/src/main/java/cm/aptoide/pt/repository/request/RewardAppCoinsAppsRepository.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppCoinsCampaignsRequest.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/V7.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/WSWidgetsUtils.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/promotions/GetPromotionsRequest.java

Adds "aab=true" to promotions WS so that it can return correctly apps with aabs. Right now it isn't implemented in the WS so it can't be tested, but it shouldn't break current function.
No
As the functionality isn't implemented yet in the WS, for now you can just test that nothing broke and that the 'aab=true' is indeed being sent by checking with Charles on promotions request (like in Earn Appc section).
[MOB-618](https://aptoide.atlassian.net/browse/MOB-618)

[bugfix/MOB-618] Poa Campaigns missing AABs

---

app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewView.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialPresenter.java
app/src/main/java/cm/aptoide/pt/editorial/EditorialView.java
app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListFragment.kt
app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListPresenter.kt
app/src/main/java/cm/aptoide/pt/home/more/appcoins/EarnAppcListView.kt
app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsView.java

Fixes a bug where if an user clicked install and an out of space error occured and then the user went back and re-entered the download view, the out of space error would appear without the user even clicking install.
I'm not very much a fan of how it was eventually done, but my LOGAF is pretty low for this :) I think when we isolate downloads in general we can maybe think of a better solution. 
No
Ideally every fragment where there's downloads should be checked for the bugs presence. This is: app view, promotions view, editorial view, wallet install view, earn appc list view.
[MOB-601](https://aptoide.atlassian.net/browse/MOB-601)

[bugfix/MOB-601] Out of space error bug

---

app/src/main/java/cm/aptoide/pt/bottomNavigation/BottomNavigationActivity.java

This PR fixes a bug caught in QA for the apps name AB test where some translations would be cut off
No
Check the comment in the ticket for the problem strings. The solution was to ellipsize at the end and was discussed and approved by both Luis and Carlos
Tickets related to this pull-request: [MOB-512](https://aptoide.atlassian.net/browse/MOB-512)

[MOB-512] Fixed text getting cut in some translations;

---

app/src/androidTest/java/cm/aptoide/pt/MockApplicationModule.java
app/src/cobrand/java/cm/aptoide/pt/presenter/LoginSignupCredentialsFlavorPresenter.java
app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/account/AccountServiceV3.java
app/src/main/java/cm/aptoide/pt/account/FacebookSignUpAdapter.java
app/src/main/java/cm/aptoide/pt/account/GoogleSignUpAdapter.java
app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsPresenter.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/vanilla/java/cm/aptoide/pt/presenter/LoginSignupCredentialsFlavorPresenter.java
aptoide-account-manager/src/main/java/cm/aptoide/accountmanager/AccountService.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v3/OAuth2AuthenticationRequest.java

This PR aims at removing not needed permissions form social login. Also removed a field that was always being sent as null.
No
Perform both google sign in and facebook sign in. Don't forget to remove aptoide access on the accounts of those social platforms that you will use, so that you can check the login permissions dialog in both scenarios.
Tickets related to this pull-request: [MOB-625](https://aptoide.atlassian.net/browse/MOB-625)
**Questions:**

[MOB-625] Remove Permissions from social login

---

app/src/main/java/cm/aptoide/pt/account/view/LoginSignUpCredentialsFragment.java
app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsPresenter.java
app/src/main/java/cm/aptoide/pt/presenter/LoginSignUpCredentialsView.java
app/src/vanilla/java/cm/aptoide/pt/presenter/LoginSignupCredentialsFlavorPresenter.java

show pp & tc error  if user tries to login with fb/google without accepting the pp & tc
No
Try to login with google/fb without accepting the terms and conditions
Tickets related to this pull-request: [MOB-555](https://aptoide.atlassian.net/browse/MOB-555)

[MOB-555] fix: show pp & tc error 

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/app/view/OtherVersionsFragment.java
app/src/main/java/cm/aptoide/pt/repository/request/RequestFactory.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java
dataprovider/src/test/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManagerTest.java
utils/src/main/java/cm/aptoide/pt/utils/AptoideUtils.java

Devices with MIUI 11.2 should technically have a fix that allows the sideload of app with splits without error. This fix is to try to enable, without breaking, newer miui devices that can already do that. More information inside the issue about past investigations.
No
This in new MIUI devices (should show aab), old MIUI devices (should not show aab)  and non MIUI devices (should show aab) the installation of an app with app bundles.
Tickets related to this pull-request: [MOB-397](https://aptoide.atlassian.net/browse/MOB-397) [MOB-399](https://aptoide.atlassian.net/browse/MOB-399)

[MOB-397] enhancement: support aab for newer MIUI devices

---

app/src/main/java/cm/aptoide/pt/account/AgentPersistence.kt
aptoide-authentication-core/src/main/kotlin/com/aptoide/authentication/model/CodeAuth.kt

According to the API documentation, agent can be null in the first authorize response. This PR makes agent nullable.
No
Test the login flow, dev environment is already sending a null agent.
Tickets related to this pull-request: [MICRO-850](https://aptoide.atlassian.net/browse/MICRO-850)

[MOB-555] fix: accept agent as nullable since it is not currently being used.

---

app/src/main/AndroidManifest.xml

fix: separting the app.aptoide intent from the other ones seems to fix the aptoideinstall:// issue
No
adb shell am start -a "android.intent.action.VIEW" -d "aptoideinstall://package=com.tencent.tmgp.sskeus\&store=catappult\&show_install_popup=false"
Tickets related to this pull-request: [MOB-757](https://aptoide.atlassian.net/browse/MOB-757)
**Questions:**

[MOB-757] fix: aptoideinstall:// not showing Aptoide issue

---

app/src/main/java/cm/aptoide/pt/editorial/EditorialFragment.java

Fixes an issue where you couldn't install an app in Editorial through the bottom card (i.e. when you only have one app and you don't scroll down).
No
Check if the issue is now fixed (i.e. you can now download through the bottom card on Editorial).
[MOB-764](https://aptoide.atlassian.net/browse/MOB-764)

MOB-764 - Changed click observable to subject

---

app/src/main/java/cm/aptoide/pt/app/view/MoreBundlePresenter.java
app/src/main/java/cm/aptoide/pt/home/HomeFragment.java
app/src/main/java/cm/aptoide/pt/home/HomePresenter.java

restore scroll state when showing skeleton views, so it doesn't do the visual flicker while navigating back to it.
change hide loading method calls to after show so we don't end with an empty screen between those two operations.
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-770](https://aptoide.atlassian.net/browse/MOB-770)
Tickets related to this pull-request: [MOB-770](https://aptoide.atlassian.net/browse/MOB-770)

[MOB-770] fix: home visual flicker in navigation

---

app/src/main/java/cm/aptoide/pt/database/RoomDownloadPersistence.java
app/src/main/java/cm/aptoide/pt/install/InstallManager.java
app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
app/src/main/java/cm/aptoide/pt/install/installer/DownloadInstallationAdapter.java
app/src/main/java/cm/aptoide/pt/install/installer/Installation.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadPersistence.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadsRepository.java

Fixes one of the bugs reported in sentry. Basically the save operation of a download was not being in a Rx chain. This changes that.
No
Check if the download downloads as expected and if possible, check if it doesn't crash when there's no space (it might be difficult to replicate that though so it might not be possible, or just throw an exception).
[MOB-782](https://aptoide.atlassian.net/browse/MOB-782)

[bugfix/MOB-782] SqlLiteFullException

---

app/src/main/res/layout/fragment_login_sign_up_credentials.xml
app/src/main/res/values-v21/styles_aptoide_button.xml
app/src/main/res/values/strings_appstimeline.xml
app/src/main/res/values/styles_aptoide_button.xml

This PR aims at fixing login translations. We were using the wrong string for the connect with google button, which made Portuguese be inconsistent (Connectar while other buttons said entrar). Also removed the other translations. Btw, in BR, the connect with google string is still not correct as all other buttons say connectar and the login with email says entrar.
No
Copy translations from crodwin repo from pt pt and pt br, paste it on your project and confirm that the reported error does not happen anymore.
Tickets related to this pull-request: [MOB-806](https://aptoide.atlassian.net/browse/MOB-806)
**Questions:**
Does this add …

[MOB-806] Fixed login translations

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java

This pr aims at deleting the apk after an installation of an app. This might not be the best solution, but considering the state of default installer, this is the possible one.
No
Perform several downloads, updates, downgrades, check that everything is ok. State updates, Apps, etc.
Tickets related to this pull-request: [MOB-778](https://aptoide.atlassian.net/browse/MOB-778)
**Questions:**

[MOB-778] Delete apk after install

---

app/build.gradle
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/app/AppModel.java
app/src/main/java/cm/aptoide/pt/app/AppNavigator.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/AppViewModelManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewFragment.java
app/src/main/java/cm/aptoide/pt/download/DownloadApkPathsProvider.java
app/src/main/java/cm/aptoide/pt/download/DownloadFactory.java
app/src/main/java/cm/aptoide/pt/presenter/MainPresenter.java
app/src/main/java/cm/aptoide/pt/util/ApkFyManager.java
app/src/main/java/cm/aptoide/pt/util/ApkfyParameters.kt
app/src/main/java/cm/aptoide/pt/view/ActivityModule.java
app/src/main/java/cm/aptoide/pt/view/AppViewConfiguration.java
app/src/main/java/cm/aptoide/pt/view/DeepLinkManager.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/test/java/cm/aptoide/pt/app/AppViewManagerTest.java
app/src/test/java/cm/aptoide/pt/app/AppViewModelManagerTest.kt
app/src/test/java/cm/aptoide/pt/app/AppViewPresenterTest.java
app/src/test/java/cm/aptoide/pt/navigation/BottomNavigationPresenterTest.java

Adds support for oemid in the apkfy flow. In essence, if the apk contains the "oemid=" parameter in the aob file, it will send that parameter in the app download url list. It only sends this if it exists and if it is the apkfy app.
Also, I've disabled v2 signing for the debug app so that it is easier to test these things in debug (and release has it disabled anyway).
No
Either get an apk with the aob file (w/ oemid) already included, or build a debug apk and insert the apkfy files (and remember to put the 'oemid=' parameter in the aob file). Then, you can check with Charles that when you download the app, this parameter is being sent. …

[feature/MOB-849] Support for apkfy oem_id

---

app/src/main/res/layout/ads_bundle_item.xml
app/src/main/res/layout/apps_bundle_item.xml

Fixes a bug where the 'more' button was on top of the bundle title (specifically in the Highlighted bundle) when there was only 1 app.
No
Either modify the getStoreWidgets response in Charles to only return on app for "Highlighted" bundle, or you can go to "AdsBundleViewHolder" (or "AdsWithMoPubViewHolder") and simply subList the incoming content, e.g.: 
appsInBundleAdapter.update((List<Application>) homeBundle.getContent().subList(0, 1));
Tickets related to this pull-request: [MOB-809](https://aptoide.atlassian.net/browse/MOB-809)

[bugfix/MOB-809] Highlighted Bundle - More Button bug

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java

This PR aims at fixing a search filter problem where we get different results if we apply the search filters in a different order.
To summarize the problem, we perform the load more request (2nd request) when the list of search reaches the bottom. In case the previous results were "no results", then we don't reach the bottom, which means that if we change the filter, we will only make the 1st request. 
The problem is that some filters are not being correctly filtered by the API (this will be implemented in the future, in the ticket: https://aptoide.atlassian.net/browse/MICRO-937) , meaning that they will return us an empty list on that call and some results on the 2nd call. Since we not always make the 2nd call (like previously stated), we might get empty results …

[HOTFIX/MOB-931] Fix Search Filter

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultAdapter.java

This PR aims at fixing an issue where if you do a search, open an AppView, then come back, the results would change. Basically we would loose the results that we had before and we would just load new results (with the next offset value).
This was happening because in the restoration of the search view, we were clearing the list.
No
Open search, search for example for facebook. After that navigate to the first result, opening its appview. Then, navigate back, and check that the results being shown are the same as before you navigated to the appview.   …

[HOTFIX/MOB-938] Wrong results after navigating from search

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java

This PR aims at fixing a load more request after coming from the appview.
When we open search, we make a request, to load the apps. The problem is that if we come back from the appview, the search view will be created (we will restore the correct state as fixed in a previous pull request) and we will end up doing a "false" first load search request. This is happening because in the search refactor we removed a filter we had in the doFirstSearch() method where we would check the offset.
Visually this has no side effects, but we will be doing load more requests for each appview opened from this search, which is not ideal.
No
Search an app, click on any result to go to …

[HOTFIX/MOB-940] Avoiding a false first load request 

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultPresenter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultView.java
app/src/main/res/layout-v21/global_search_fragment.xml
app/src/main/res/layout/global_search_fragment.xml

This PR aims at fixing different results for the same filters. Just like in a previous issue, we were allowing that the conditions/results from one query could affect the conditions or results of the next one. In this case, the fact that we had no results in a previous query was not allowing us to make the respective load more request from the new query (filters changed).
I took the chance to refactor the code from another ticket where we were not able to load more after getting 2 no results in a row, by merging everything on the same place, which makes it way easier to manage than the previous solution.
No
Search for "lords mobile" apply the filters Followed stores …

[HOTFIX/MOB-941] Different results for the same filters

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/install/InstallManager.java
app/src/main/java/cm/aptoide/pt/install/Installer.java
app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
app/src/main/java/cm/aptoide/pt/install/installer/InstallationCandidate.kt

This fixes a bug where the cancel wasn't being properly detected when using a package installer installation. This actually had other implications, such as certain analytics events not being sent in these cases as well.
To give technical context to the issue: the issue was that the defaultInstall() chain in DefaultInstaller needs to observe emissions throughout the installation progress, however the parent chain that called this (install() chain in DefaultInstaller) was a Completable and was only listening for the first emission, so it was not updating the status accordingly. The fix was basically to separate these two chains to their own subscription through a subject. This way the installation status is continually updated in it's own subscription, while the …

[hotfix/MOB-939] Cancel Installation bug

---

app/src/main/java/cm/aptoide/pt/toolbox/ToolboxContentProvider.java

Adds two fields necessary for the new AutoLogin uploader view.
Name (nickname) and the Avatar path.
No
- ToolboxContentProvider.java
Using an uploader version with the autologin changes, login in vanilla and then go to uploader and check if the name and avatar show up.
https://aptoide.atlassian.net/browse/MOB-964

[MOB-964] ToolboxContentProvider changes

---

dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppRequest.java

This PR aims at implementing a fix to the getapp request where we would send a null app id or package name. Now it is sending {}
No
I could only reproduce it for the app id being null, not for the package name. 
For the app id, send the following deeplink: `adb shell am start -a "android.intent.action.VIEW" -d "aptoideinstall://package=org.nanobit.taboo&store=catappult&show_install_popup=false"
`
Make sure all appviews are opening (different opening types) as well as the things inside of it like the other versions, etc.
Tickets related to this pull-request: [MOB-876](https://aptoide.atlassian.net/browse/MOB-876)
**Questions:**
Does …

[MOB-876] Nodes Parameter

---

dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/GetAppRequest.java

This PR aims at removing a redundant package name or app id being sent in the nodes
No
I could only reproduce it for the app id being null, not for the package name.
For the app id, send the following deeplink: adb shell am start -a "android.intent.action.VIEW" -d "aptoideinstall://package=org.nanobit.taboo&store=catappult&show_install_popup=false"
Make sure all appviews are opening (different opening types) as well as the things inside of it like the other versions, etc.
Tickets related to this pull-request: [MOB-876](https://aptoide.atlassian.net/browse/MOB-876)
**Questions:**
Does this add new dependencies which need to be …

[MOB-876] Removed redundant package name and app id

---

app/src/main/res/values/attrs.xml
app/src/main/res/values/themes.xml
aptoide-views/src/main/res/drawable-night/background_triangle.xml
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/model/MinimalAdInterface.java

fix: change the way we show the search results triangle in the background of each result. It was using an attr inside a drawable, which is not allowed in older versions and causes a runtime crash. Now we use (default/night) modes to show each search result version.
No
On a device/emulator 16 -> search for something on both dark and light themes. 
Tickets related to this pull-request: [MOB-1015](https://aptoide.atlassian.net/browse/MOB-1015)

[MOB-1015] Fix crash in Search for Android 16

---

app/src/main/java/cm/aptoide/pt/search/view/SearchResultAdapter.java
app/src/main/java/cm/aptoide/pt/search/view/SearchResultFragment.java

Temporary fix to search crash on scroll - IndexOutOfBoundsException: Inconsistency detected. Invalid item position
No
Flow on how to test this or QA Tickets related to this use-case: [MOB-1021](https://aptoide.atlassian.net/browse/MOB-1021)
Tickets related to this pull-request: [MOB-1021](https://aptoide.atlassian.net/browse/MOB-1021)

[MOB-1021] Temporary fix to search crash on scroll

---

app/src/main/java/cm/aptoide/pt/download/view/DownloadDialogProvider.kt
app/src/main/java/cm/aptoide/pt/download/view/DownloadEvent.kt
app/src/main/java/cm/aptoide/pt/download/view/DownloadViewActionPresenter.kt
app/src/main/java/cm/aptoide/pt/download/view/DownloadViewStatusHelper.kt

Error dialogs were missing in the new download component. This basically adds them back.
No
Get a device with low storage (or simulate it) and go to search and look for "Creative Destruction". If you click install (and assuming you have low storage), an out of space error should appear correctly.
[MOB-1037](https://aptoide.atlassian.net/browse/MOB-1037)

[hotfix/MOB-1037] Out of Space Dialog Missing- Highlighted

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java

making sure analytics initialize before doing parallel work
delayed sending first run analytics so first session is set immediately after. 
removed duplicated events from the rakam events whitelist
No
Test startup flow, check if we only send "aptoide_first_launch" event once and if rakam works every session
Tickets related to this pull-request: [APP-57](https://aptoide.atlassian.net/browse/APP-57)

[APP-57] making sure analytics initialize before doing parallel work

---

app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoFragment.java
app/src/main/res/layout/fragment_appcoins_info.xml

Removes the PoA info section from AppCoinsInfo page.
Talking with localization team I was asked to keep these strings in the repository so we can use them again in the future.
Did not remove anything from App view because we only display PoA app view if the app has an active campaign which is the way it is supposed to work.
No
Go to AppCoinsInfo view and review/validate copies.
Tickets related to this pull-request: [APP-64](https://aptoide.atlassian.net/browse/APP-64)

[APP-64] task: Review PoA strings

---

app/src/main/java/cm/aptoide/pt/view/settings/SettingsFragment.java
app/src/main/res/values/strings.xml

This PR aims at replacing the delete account url for a new one.
No
Open my account and go to delete account section. This section only shows up when you are logged in
Tickets related to this pull-request: [APP-82](https://aptoide.atlassian.net/browse/APP-82)
**Questions:**

[APP-82] Replace delete account URL

---

app/src/main/java/cm/aptoide/pt/view/MainActivity.java

This fixes the issue with the editorial deeplink. This was probably happening for other deeplinks aswell.
This is just a temporary fix for the RC because deeplinks shouldn't be handled this way. A new issue will be create for the refactor.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-127](https://aptoide.atlassian.net/browse/APP-127)
Tickets related to this pull-request: [APP-127](https://aptoide.atlassian.net/browse/APP-127)

[Hotfix/APP-127] Editorial Deeplink Broken

---

app/src/main/java/cm/aptoide/pt/search/suggestions/TrendingService.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/ws/v7/ListAppsRequest.java

This PR aims at changing trending from 30d to 60d. This does not affect the trending bundle in home because that one comes from web a ticket for it to be changed on MICRO was already created ( [MICRO-1046](https://aptoide.atlassian.net/browse/MICRO-1046) ) . It only affects the trending on search.
No
Check on charles that the request is being made with 60d.
Tickets related to this pull-request: [APP-112](https://aptoide.atlassian.net/browse/APP-112)
**Questions:**

[APP-112] Change trending to 60d

---

app/src/main/AndroidManifest.xml

Support new web pattern /app for both http and https
Example: https://game-of-sultans.en.aptoide.com/app
No
Test both deeplinks:
- adb shell am start -a "android.intent.action.VIEW" -d "https://game-of-sultans.en.aptoide.com/app"
- adb shell am start -a "android.intent.action.VIEW" -d "http://game-of-sultans.en.aptoide.com/app"
Tickets related to this pull-request: [APP-118](https://aptoide.atlassian.net/browse/APP-118)

[APP-118] feature: support new web pattern /app for both http and https

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/app/view/OtherVersionsFragment.java
app/src/main/java/cm/aptoide/pt/install/InstallManager.java
app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java
app/src/main/java/cm/aptoide/pt/repository/request/RequestFactory.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml
aptoidepreferences/src/main/java/cm/aptoide/pt/preferences/managed/ManagedKeys.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManager.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilitySettingsProvider.java
dataprovider/src/main/java/cm/aptoide/pt/dataprovider/aab/HardwareSpecsFilterProvider.java
dataprovider/src/test/java/cm/aptoide/pt/dataprovider/aab/AppBundlesVisibilityManagerTest.java

new setting - enforce native installer. This will allow Xiaomi users to recover from the state of not being able to install any application in the app because of the PackageInstaller.
EDIT: Strings on this branch are on temporary. The ones from dev are the correct ones.
No
- Test installations with both setting on/off on Xiaomi and non-xiaomi devices.
Tickets related to this pull-request: [APP-103](https://aptoide.atlassian.net/browse/APP-103)

[Feature/APP-103] new setting: enforce native installer

---

downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/AptoideDownloadManager.java

This PR aims at setting the download to the error state when it encounters an error while trying to move the download files. We are setting the general error because from the exception we can not distinguish the different exceptions.
Please confirm that the everything is working correctly
No
On a low storage device try to perform a download that only fails due to storage at the end of the download. For example, I tested downloading Lords Mobile on an emulator with 1000MB of internal storage and no SD Card.
This leads do the weird state that we were getting where it is possible do start the download, but it is not possible to move the file (this happens because when …

[APP-81] Fix out of space inconsistency

---

app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoView.java
app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoPresenter.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/test/java/cm/aptoide/pt/app/view/AppCoinsInfoPresenterTest.java

This PR aims at fixing the hardcoded bonus we had on the AppCoins detail info view.
No
Navigate to the AppCoinsInfo view and see that we dont have 25% anymore. If you want, rewrite the bonus response to also test the no bonus available messages.
Tickets related to this pull-request: [APP-271](https://aptoide.atlassian.net/browse/APP-271)
**Questions:**

[APP-271] Fix Bonus

---

app/src/main/java/cm/aptoide/pt/download/view/outofspace/OutOfSpaceDialogFragment.kt
app/src/main/java/cm/aptoide/pt/download/view/outofspace/OutOfSpaceDialogPresenter.kt
app/src/main/java/cm/aptoide/pt/download/view/outofspace/OutOfSpaceManager.kt
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java

This PR aims at fixing the size we display on the out of space dialog. Before we were displaying the size of the app we need to install, but after some testing we realizaed it wouldn't make sense. It should be the appsize - available storage, meaning we would only have to get the missing space instead of the whole app space.
No
Same as before. Try to get a device with lower storage (can user an emulator where you can set your own memory values) and perform the flow of downloading an app that does not fit in order to get to the dialog. 
Tickets related to this pull-request: [APP-30](https://aptoide.atlassian.net/browse/APP-30) …

[APP-30] Fix out of space dialog title size

---

app/src/main/java/cm/aptoide/pt/install/installer/DefaultInstaller.java

This PR aims at fixing a bug where after an app with obbs gets updated, the old obbs would still remain inside the obbs folder.
No
Download the PUBG versions just like it is in the ticket and check if there are more than one version of obb files.
Tickets related to this pull-request: [APP-133](https://aptoide.atlassian.net/browse/APP-133)
**Questions:**

[APP-133] Clearing obbs folder for the app before moving them

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/install/InstalledIntentService.java
app/src/main/java/cm/aptoide/pt/install/InstalledRepository.java
aptoide-database/src/main/java/cm/aptoide/pt/database/room/RoomInstalled.java

This PR aims at fixing the app size being shown on the out of space dialog. Before we were not counting with the obb's, only the app size.
No
Install an app with obb's. Trigger the out of space flow and then check in the dialog that the app size being shown counts with the obbs.
Tickets related to this pull-request: [APP-30](https://aptoide.atlassian.net/browse/APP-30)
**Questions:**

[HOTFIX/APP-30] Counting with the obbs size for the calculation of the app size

---

app/src/main/java/cm/aptoide/pt/autoupdate/AutoUpdateManager.kt
app/src/main/java/cm/aptoide/pt/download/DownloadFactory.java

This PR aims at fixing a bug where Apps BN section wouldn't open if the auto update download was running in the background.
No
Set the app to perform the auto update and then try to open the Apps BN section
Tickets related to this pull-request: [APP-426](https://aptoide.atlassian.net/browse/APP-426)
**Questions:**

[APP-426] Apps BN does not open if autoupdate is running

---

aptoide-database/src/main/java/cm/aptoide/pt/database/room/RoomInstalled.java

This PR aims at fixing an issue where if sometimes you try to open the APPS BN section, it will give an error and stay stuck on loading forever.
No
Open Apps check that it is not crashing.
Tickets related to this pull-request: [APP-435](https://aptoide.atlassian.net/browse/APP-435)
**Questions:**

[HOTFIX/APP-435] Apps Fix

---

app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoFragment.java
app/src/main/java/cm/aptoide/pt/app/view/AppCoinsInfoView.java
app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoNavigator.java
app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoPresenter.java
app/src/main/res/layout/fragment_appcoins_info.xml

This PR aims at implementing the eskills information inside the appc info view.
Also changed the youtube video being displayed there for a new one.
Also fixed a navigation/thread bug we had where if the user navigated to the appcoins info view and then navigated back, the app would be unusable.
No
Open the view, check that everything is ok. Click on the "here" button and check that you can navigate to the eskills more bundle view.
Tickets related to this pull-request: [APP-538](https://aptoide.atlassian.net/browse/APP-538)
[APP-564](https://aptoide.atlassian.net/browse/APP-564)
**Questions:**
Does this add new dependencies which …

[APP-538] Update appc info view with eskills

---

app/src/main/res/layout/fragment_list_apps.xml

This PR aims at fixing the visibility issues related to the eskills header.
It was being shown in the more view of the other bundles.
No
Open the more view from other bundles and check that it shows the more view correctly
Tickets related to this pull-request: [APP-646](https://aptoide.atlassian.net/browse/APP-646)
**Questions:**

[APP-646] Fixed eskills header visibility issues

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/AptoideApplicationAnalytics.java
app/src/main/java/cm/aptoide/pt/ads/MoPubAnalytics.java
app/src/main/java/cm/aptoide/pt/analytics/FirstLaunchAnalytics.java
build.gradle

Updates the Flurry sdk to the latest version 13.0.1. 
Migrates all the Flurry session properties to user properties. 
Adds a new property for login to both rakam and flurry.
No
For Rakam check batch of events being sent on Charles with the new property.
For Flurry check newly added user properties in Flurry Dashboard.
Tickets related to this pull-request: [APP-706](https://aptoide.atlassian.net/browse/APP-706)

[Feature/APP-706] Flurry + Rakam Loggedin user property

---

app/src/main/java/cm/aptoide/pt/database/RoomDownloadPersistence.java
app/src/main/java/cm/aptoide/pt/download/view/DownloadViewActionPresenter.kt
app/src/main/java/cm/aptoide/pt/home/apps/AppsFragment.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsManager.java
app/src/main/java/cm/aptoide/pt/home/apps/AppsPresenter.java
app/src/main/java/cm/aptoide/pt/install/InstallAppSizeValidator.kt
app/src/main/java/cm/aptoide/pt/install/InstallManager.java
aptoide-database/src/main/java/cm/aptoide/pt/database/room/DownloadDAO.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadPersistence.java
downloadmanager/src/main/java/cm/aptoide/pt/downloadmanager/DownloadsRepository.java

This PR aims at fixing the download out of space event that was not being sent for the apps BN section and the search higlighted result download view.
Yes (?)
Change the InstallAppValidator class in order to return no space available or fill your phone with apps (which will take more time)
Tickets related to this pull-request: [APP-676](https://aptoide.atlassian.net/browse/APP-676)
**Questions:**

[APP-676] Fix out of space event

---

app/src/main/java/cm/aptoide/pt/download/view/DownloadViewStatusHelper.kt
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.kt

Now the highlighted view correctly reacts to download error events since the download state is now being updated correctly to the download state error handler.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-676](https://aptoide.atlassian.net/browse/APP-676)
Tickets related to this pull-request: [APP-676](https://aptoide.atlassian.net/browse/APP-676)

[APP-676] fix: search highlighted result view errors not being shown

---

app/src/main/java/cm/aptoide/pt/presenter/MainPresenter.java

This PR aims at fixing a bug where if the user rotated the screen and accepted the gdpr dialog, home would not load properly.
No
Open home, rotate your screen and check that home loads correctly.
Tickets related to this pull-request: [APP-968](https://aptoide.atlassian.net/browse/APP-968)
**Questions:**

[APP-968] Handling gdpr dialog acceptance in case it is not the first run

---

app/src/main/java/cm/aptoide/pt/download/view/DownloadViewActionPresenter.kt
app/src/main/java/cm/aptoide/pt/download/view/DownloadViewStatusHelper.kt
app/src/main/java/cm/aptoide/pt/search/view/item/SearchResultViewHolder.kt

This PR aims implementing a fix for the bug we had on the highlighted result from search. If we downloaded an app through the highlighted result, installed the app and then tried to open it by pressing the open button, it will actually try to start the download again.
No
Download an app through the highlighted result, install the app and then try to open it by pressing the open button, it should open the app but before it was trying to download everything again.
Tickets related to this pull-request: [APP-1024](https://aptoide.atlassian.net/browse/APP-1024)
**Questions:**
Does this add new dependencies which need to be added? (Eg. …

[APP-1024] Highlighted result fix

---

app/src/main/java/cm/aptoide/pt/notification/NotificationPolicyFactory.java
app/src/main/java/cm/aptoide/pt/notification/policies/AlwaysShowPolicy.java

Fix: because of the new dependencies in the campaign notification (whitelisted packages) the Campaign notification policy should not be reused in other notification types. This creates a new policy, the same as the campaignpolicy used to be, in order to be used for Ready to install, appc promotion and new feature notifications.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-1280](https://aptoide.atlassian.net/browse/APP-1280)
Tickets related to this pull-request: [APP-1280](https://aptoide.atlassian.net/browse/APP-1280)

[APP-1280] Ready to install notification fix

---

app/src/main/java/cm/aptoide/pt/download/FileDownloadManagerProvider.java
app/src/main/java/cm/aptoide/pt/download/FileDownloadTask.java

This pr aims at removing the md5 check in lords mobile
No
Perform a download of an app different than lords mobile. Confirm that the md5 is checked (there is a log for it with "computeMd5"). Check that there is not that confirmation for the lords mobile download.
Tickets related to this pull-request: [APP-1341](https://aptoide.atlassian.net/browse/APP-1341)
**Questions:**

[APP-1341] Lords Mobile md5

---

app/src/main/java/cm/aptoide/pt/notification/ReadyToInstallNotificationManager.kt

This PR aims at setting the ready to install notification non dismissable.
No
Perform a download, put the app in the background and check for the ready to install notification.
Dont forget to repeat this to test the multi app ready to install notifications.
Tickets related to this pull-request: [APP-1356](https://aptoide.atlassian.net/browse/APP-1356)
**Questions:**

[APP-1356] Make ready to install non dismissable

---

app/src/main/java/cm/aptoide/pt/ApplicationModule.java
app/src/main/java/cm/aptoide/pt/app/AppViewManager.java
app/src/main/java/cm/aptoide/pt/app/appsflyer/AppsFlyerManager.kt
app/src/main/java/cm/aptoide/pt/app/appsflyer/AppsFlyerRepository.kt
app/src/main/java/cm/aptoide/pt/app/appsflyer/AppsFlyerResponse.kt
app/src/main/java/cm/aptoide/pt/app/appsflyer/AppsFlyerService.kt
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java

This PR aims at implementing a request to apps flyer impressions when opening the lords mobile appview
No
Open the app go to lords mobile appview and confirm that you see the request to impression apps flyer endpoint on charles. 
Note that you will have to enable ssl proxying for it and to make it easier, focus that endpoint.
Tickets related to this pull-request: [APP-1376](https://aptoide.atlassian.net/browse/APP-1376)
**Questions:**

[APP-1376] Request Apps Flyer impression

---

feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewView.kt
feature_report_app/src/main/java/cm/aptoide/pt/feature_report_app/presentation/ReportAppView.kt

This PR aims at adding navigation to appview from home bundles & more.
Also took the chance to fix unnecessary padding on bottom of appview and report app view.
referenced PR: [DT-37](https://github.com/Aptoide/aptoide-client-dt/pull/13)
No
Open app and check the navigation to app view from home.
Tickets related to this pull-request: [DT-37](https://aptoide.atlassian.net/browse/DT-37)
**Questions:**

[DT-37] Navigate to app view

---

aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/textformatter/DateUtils.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/di/UseCaseModule.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/domain/usecase/ReactionsUseCase.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/presentation/ReactionsUiState.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/presentation/ReactionsViewModel.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/presentation/ViewModelProvider.kt
feature-reactions/src/main/java/cm/aptoide/pt/feature_reactions/ui/ReactionsView.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideBundlesRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/di/RepositoryModule.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/Bundle.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/BundlesView.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/Article.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/EditorialRepository.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/di/UseCaseModule.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/network/RemoteAppViewRepository.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/network/service/EditorialNetworkService.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/EditorialMeta.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/EditorialsMetaUseCase.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialView.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialViewModel.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialsMetaUiState.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialsMetaViewModel.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt

Make editorial an reactions logic easy to reuse.
No
Start the app, go the the editorial article
Tickets related to this pull-request: [DT-44](https://aptoide.atlassian.net/browse/DT-44)

[DT-44] Refactor and extend the editorial and reactions modules

---

feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
feature_categories/build.gradle.kts
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/domain/GetCategoryAppsListUseCase.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/CategoryDetailViewModel.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/CategoryDetailViewUiState.kt

- Creates the necessary methods to fetch the app list from a single category.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-354](https://aptoide.atlassian.net/browse/DT-354)
Tickets related to this pull-request: [DT-354](https://aptoide.atlassian.net/browse/DT-354)
[DT-354]: https://aptoide.atlassian.net/browse/DT-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-354]: https://aptoide.atlassian.net/browse/DT-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-354] Add category app list business logic

---

feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/AppViewViewModel.kt
feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/ViewModelProvider.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt

Make adListId nullable and don't actually call campaign actions when adListId is null.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-373](https://aptoide.atlassian.net/browse/DT-373)
Tickets related to this pull-request: [DT-373](https://aptoide.atlassian.net/browse/DT-373)
PRs related to this one: [#102](https://github.com/Aptoide/aptoide-client-dt/pull/102)
[DT-373]: https://aptoide.atlassian.net/browse/DT-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-373]: …

[DT-373] Make adListId nullable

---

install-manager/src/test/java/cm/aptoide/pt/install_manager/TasksTest.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TestData.kt

This PR enables cancelation for downloads that are pending on installation.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-418](https://aptoide.atlassian.net/browse/DT-418)
Tickets related to this pull-request: [DT-418](https://aptoide.atlassian.net/browse/DT-418)
[DT-418]: https://aptoide.atlassian.net/browse/DT-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-418]: https://aptoide.atlassian.net/browse/DT-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-418] Cancel installation while in queue

---

feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt

This PR aims at implementing the flow of wallet install from a bottom sheet on appview.
On this case, here we needed to remove the storename parameter from the getApp request in case the app was the appcoins wallet.
No
Try to install an app with appcoins, check if the bottomsheet pops up, click on learn more and check that the request is not for a specific store
Tickets related to this pull-request: [DT-418](https://aptoide.atlassian.net/browse/DT-418)
**Questions:**
[DT-418]: …

[DT-416] wallet install on appview

---

feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppVersionsUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppsByPackagesUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppsByTagUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/CategoryAppsUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/ESkillsAppsUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/SimilarAppcAppsUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/SimilarAppsUseCase.kt

Add use case to get apps by a list of packages. 
Using a comma separated string is a bit dirty, though it complies with the interface.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-447](https://aptoide.atlassian.net/browse/APP-447)
Tickets related to this pull-request: [APP-447](https://aptoide.atlassian.net/browse/APP-447)
PRs related to this one: [#170](https://github.com/Aptoide/aptoide-client-dt/pull/170)
[APP-447]: https://aptoide.atlassian.net/browse/APP-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

[DT-447] Apps list by packages

---

app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
app/src/main/java/cm/aptoide/pt/network/AptoideQLogicInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/LanguageInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/QLogicInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/VersionCodeInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/q/QManager.kt

Adds the implementation of the Q Logic responsible for filtering the apps that comes on the http requests according to the user's device. 
PS: In order to allow DT to run, take a look at [#176](https://github.com/Aptoide/aptoide-client-dt/pull/176) PR
No
Flow on how to test this or QA Tickets related to this use-case: [DT-338](https://aptoide.atlassian.net/browse/DT-338)
Tickets related to this pull-request: [DT-338](https://aptoide.atlassian.net/browse/DT-338)
PRs related to this one: https://github.com/Aptoide/aptoide-client-v8/pull/176
[DT-338]: …

[DT-338] Q Logic

---

app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
app/src/main/java/cm/aptoide/pt/home/BottomNavigationView.kt
app/src/main/java/cm/aptoide/pt/search/AptoideSearchStoreManager.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/di/RepositoryModule.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/domain/repository/SearchStoreManager.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchAppBarState.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchUiState.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchView.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchViewModel.kt

This PR aims at putting v10 search in DT, where it should be store based. Meanwhile, in V10 it should stay for all stores.
No
Open the app and make a search
Tickets related to this pull-request: [DT-465](https://aptoide.atlassian.net/browse/DT-465)
**Questions:**
[DT-465]: https://aptoide.atlassian.net/browse/DT-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-465] port v10 search

---

feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchUiState.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchView.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/presentation/SearchViewModel.kt

- Refactor the search ui state and adds loading, no connection and error states
No
Flow on how to test this or QA Tickets related to this use-case: [DT-469](https://aptoide.atlassian.net/browse/DT-469)
Tickets related to this pull-request: [DT-469](https://aptoide.atlassian.net/browse/DT-469)
[DT-469]: https://aptoide.atlassian.net/browse/DT-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-469]: https://aptoide.atlassian.net/browse/DT-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-469] Refactor search ui state and add missing search states

---

app/build.gradle.kts
app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
app/src/main/java/cm/aptoide/pt/search/AptoideAutoCompleteSuggestionsRepository.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/AptoideSearchRepository.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/AutoCompleteSuggestionsRepository.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/RemoteSearchRepository.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/di/RepositoryModule.kt

- Extract the search buzz / auto-complete into a separate repository and set it as a app-level dependency.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-489](https://aptoide.atlassian.net/browse/DT-489)
Tickets related to this pull-request: [DT-489](https://aptoide.atlassian.net/browse/DT-489)
[DT-489]: https://aptoide.atlassian.net/browse/DT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-489]: https://aptoide.atlassian.net/browse/DT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[DT-489] New search auto complete

---

download-view/build.gradle.kts
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/WalletInstallationViewModel.kt
extensions/src/main/java/cm/aptoide/pt/extensions/Composables.kt
extensions/src/main/java/cm/aptoide/pt/extensions/IntExtensions.kt

Add predefined previews annotation and a function to make view model containing composables previewable.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-492](https://aptoide.atlassian.net/browse/DT-492)
Tickets related to this pull-request: [DT-492](https://aptoide.atlassian.net/browse/DT-492)
PRs related to this one: [#206](https://github.com/Aptoide/aptoide-client-dt/pull/206)
[DT-492]: https://aptoide.atlassian.net/browse/DT-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-492]: …

[DT-492] Add and use some useful extensions and composables

---

extensions/src/main/AndroidManifest.xml
extensions/src/main/java/cm/aptoide/pt/extensions/Composables.kt
extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt

- Creates extracted context extension functions to check if the network is metered
No
Flow on how to test this or QA Tickets related to this use-case: [DT-516](https://aptoide.atlassian.net/browse/DT-516)
Tickets related to this pull-request: [DT-516](https://aptoide.atlassian.net/browse/DT-516)
[DT-516]: https://aptoide.atlassian.net/browse/DT-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-516]: https://aptoide.atlassian.net/browse/DT-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-516] Extract extension and composable for metered connection

---

extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt

Created a new extension function to check if app has notifications permissions
No
Flow on how to test this or QA Tickets related to this use-case: [DT-228](https://aptoide.atlassian.net/browse/DT-228)
Tickets related to this pull-request: [DT-228](https://aptoide.atlassian.net/browse/DT-228)
[DT-228]: https://aptoide.atlassian.net/browse/DT-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-228]: https://aptoide.atlassian.net/browse/DT-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT 497] Matches in home

---

feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt

Add `aab=1` query parameter to the search query to include AAB apps in the search results.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-525](https://aptoide.atlassian.net/browse/APP-525)
Tickets related to this pull-request: [APP-525](https://aptoide.atlassian.net/browse/APP-525)
[APP-525]: https://aptoide.atlassian.net/browse/APP-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-525]: https://aptoide.atlassian.net/browse/APP-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-525] Add `aab=1` query parameter to the search query

---

feature_search/build.gradle.kts
feature_search/schemas/cm.aptoide.pt.feature_search.data.database.SearchHistoryDatabase/1.json
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/database/SearchHistoryDatabase.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/database/model/SearchHistoryEntity.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/di/RepositoryModule.kt

Search was case sensitive. If searched for "Mobile Legends" and then searched for "mobile legends" than you would have 2 entries on the recent searches.
Changed the database to ignore case, and now you will only have the last searched query if it matches another query on database ignoring the query case.
Yes
Flow on how to test this or QA Tickets related to this use-case: [APP-517](https://aptoide.atlassian.net/browse/DT-517)
Tickets related to this pull-request: [APP-517](https://aptoide.atlassian.net/browse/DT-517)

[DT 517] Recent upper lower case search results

---

aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/AcceptLanguageInterceptor.kt

- Adds an OkHttp interceptor responsible of adding the Accept-Language header with both the language and country locales.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-551](https://aptoide.atlassian.net/browse/DT-551)
Tickets related to this pull-request: [DT-551](https://aptoide.atlassian.net/browse/DT-551)
[DT-551]: https://aptoide.atlassian.net/browse/DT-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-551]: https://aptoide.atlassian.net/browse/DT-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

[DT-551] Add Accept-Language okhttp interceptor

---

feature_categories/src/main/java/cm/aptoide/pt/feature_categories/data/AptoideCategoriesRepository.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/data/CategoriesRepository.kt

This PR aims at changing the sort used on the games match categories. We are getting the same value that is being used on the categories request that comes from the getStoreWidgets. We also started doing the games match categories request on the categories bundle
No
Open the categories bundle and open the games match categories view. Check that the order is the same. In case it isn't please confirm if its not the diference in the api. (Currently when i am opening this PR, the categories more view is only returning 9 apps).
Tickets related to this pull-request: [DT-560](https://aptoide.atlassian.net/browse/DT-560)
**Questions:** …

[DT-560] change gm categories sort

---

download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/data/CampaignUrlNormalizer.kt
feature_campaigns/src/test/java/cm/aptoide/pt/feature_campaigns/CampaignImplTest.kt

This PR adds a new parameter to the campaigns click endpoint.
To do this, I separated the click and impressions events.
I also needed to change the database in order to store the click endpoints to be send after the installation is successful.
I also fixed an issue that was blocking multiple installations.
Yes
Flow on how to test this or QA Tickets related to this use-case: [APP-686](https://aptoide.atlassian.net/browse/DT-686)
Tickets related to this pull-request: [APP-686](https://aptoide.atlassian.net/browse/DT-686)
[APP-686]: https://aptoide.atlassian.net/browse/APP-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

[DT 686] MMP links 2 touch attribution

---

feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt

- Refactors the key used in the related editorials ViewModel, in order to avoid conflicts with other ViewModels.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-734](https://aptoide.atlassian.net/browse/DT-734)
Tickets related to this pull-request: [DT-734](https://aptoide.atlassian.net/browse/DT-734)
[DT-734]: https://aptoide.atlassian.net/browse/DT-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-734]: https://aptoide.atlassian.net/browse/DT-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

[DT-734] Refactor related editorials ViewModel key

---

app/build.gradle.kts
app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
feature-oos/src/main/java/cm/aptoide/pt/feature_oos/RepositoryModule.kt
feature-oos/src/main/java/cm/aptoide/pt/feature_oos/domain/InstalledAppsUseCase.kt
feature-oos/src/main/java/cm/aptoide/pt/feature_oos/presentation/InstalledAppsListViewModel.kt
feature-oos/src/main/java/cm/aptoide/pt/feature_oos/presentation/ViewModelInjectionsProvider.kt
feature-oos/src/main/java/cm/aptoide/pt/feature_oos/repository/AvailableSpaceRepository.kt

This PR aims at applying fixes to the oos dialog.
In spanish the dialog had issues with longer app names due to the uninstall being bigger.
We added margin on the size to calculate if the out of space dialog should be shown or not.
Removal of gameshub from the list
If an app is being updated and runs out of space then we dont show that app on the dialog of out of space
Only using base apk to calculate the size needed to install, since dt does not have obbs. 
No
You can go to the availablespaceviewmodel and hardcode a small size to always see the dialog, or on the installview you can change the if condition to show the dialog to be always true..
**What are the …

[DT-664] Bugfix OOS

---

payments/base/payment-manager/src/main/java/cm/aptoide/pt/payment_manager/payment/PaymentMethod.kt
payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/ClearRecurringDetails.kt
payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/CreditCardPaymentMethod.kt
payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/presentation/AdyenCreditCardScreenUiState.kt
payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
payments/payment-methods/adyen/src/main/java/cm/aptoide/pt/payment_method/adyen/repository/AdyenV2Repository.kt

- Add flag to enable recurring credit card payments.
- Add necessary logic to forget stored credit card payments (to disable recurring payments).
No
Flow on how to test this or QA Tickets related to this use-case: [DT-720](https://aptoide.atlassian.net/browse/DT-720)
Tickets related to this pull-request: [DT-720](https://aptoide.atlassian.net/browse/DT-720)
[DT-720]: https://aptoide.atlassian.net/browse/DT-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-720]: https://aptoide.atlassian.net/browse/DT-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

[DT-720] Add handling for recurring payments

---

download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt

A small refactoring for more convenient usage. 
No
Flow on how to test this or QA Tickets related to this use-case: [DT-841](https://aptoide.atlassian.net/browse/DT-841)
Tickets related to this pull-request: [DT-841](https://aptoide.atlassian.net/browse/DT-841)
**What are relevant PR's?**
PR's related to this one: [#387](https://github.com/Aptoide/aptoide-client-dt/pull/387)
[DT-841]: https://aptoide.atlassian.net/browse/DT-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-841]: https://aptoide.atlassian.net/browse/DT-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

[DT-841] Replace perAppViewModel with rememberDownloadState

---

download-view/build.gradle.kts
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
network-listener/src/main/java/cm/aptoide/pt/network_listener/NetworkConnectionImpl.kt
network-listener/src/main/java/cm/aptoide/pt/network_listener/di/NetworkListenerModule.kt

- Rename the download ViewModel processing state to waiting and make it more advanced, being able to distinguish between different waiting states.
- Refactor the Network connection implementation dependency injection.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-855](https://aptoide.atlassian.net/browse/DT-855)
Tickets related to this pull-request: [DT-855](https://aptoide.atlassian.net/browse/DT-855)
[DT-855]: https://aptoide.atlassian.net/browse/DT-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-855]: …

[DT-855] Make DownloadViewModel processing state more advanced

---

app/src/main/java/cm/aptoide/pt/home/BundlesView.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/AptoideUrlsCacheInitializer.kt
feature_editorial/build.gradle.kts
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/Article.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/ArticlesMetaUseCase.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/RelatedArticlesMetaUseCase.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialsCardViewModel.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt

Improve editorials url caching by filling up the cache with "related" tags and urls.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1012](https://aptoide.atlassian.net/browse/DT-1012)
Tickets related to this pull-request: [DT-1012](https://aptoide.atlassian.net/browse/DT-1012)
PRs related to this one: [#409](https://github.com/Aptoide/aptoide-client-dt/pull/409)
[DT-1012]: https://aptoide.atlassian.net/browse/DT-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1012]: …

[DT-1012] Improve editorials url caching

---

payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingBinder.kt
payments/billing-sdk/src/main/java/com/appcoins/billing/sdk/AppcoinsBillingService.kt

- Creates the onTransact method that instantiates the merchant package name (calling app) to be used in the binder.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1056](https://aptoide.atlassian.net/browse/DT-1056)
Tickets related to this pull-request: [DT-1056](https://aptoide.atlassian.net/browse/DT-1056)
[DT-1056]: https://aptoide.atlassian.net/browse/DT-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1056]: https://aptoide.atlassian.net/browse/DT-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

[DT-1056] Implement onTransact in appcoins aidl binder

---

app/src/main/java/cm/aptoide/pt/feature_flags/AptoideFeatureFlagsRepository.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/WalletInstallationViewModel.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/data/FeatureFlagsLocalRepository.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/data/FeatureFlagsRepository.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/data/SettingsLocalRepositoryImpl.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/domain/FeatureFlags.kt
payments/base/arch/src/main/java/com/appcoins/payments/arch/PaymentMethodFactory.kt
payments/base/payment-manager/src/main/java/com/appcoins/payment_manager/manager/PaymentManager.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/CreditCardPaymentMethodFactory.kt
payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/PaypalPaymentMethodFactory.kt

Adds flexibility to alter payment methods by feature flags. 
In order to do so 2 things were made:
1. Allow FeatureFlags operate with more complex structures than strings via JSON.
2. Make the PaymentMethodFactory create call suspend to be able to do network calls.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1068](https://aptoide.atlassian.net/browse/DT-1068)
Tickets related to this pull-request: [DT-1068](https://aptoide.atlassian.net/browse/DT-1068)
PRs related to this one: [#431](https://github.com/Aptoide/aptoide-client-dt/pull/431)
[DT-1068]: …

[DT-1068] Make payment methods initialised by feature flags

---

feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/ArticleUseCase.kt

- Fixes an issue where its not possible to fetch editorial articles that are not cached in the custom urls cache. This happens through deeplinks when fetching editorials outside of the latest nine articles, since the urls cache only caches those latest editorial urls.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-424](https://aptoide.atlassian.net/browse/DT-424)
Tickets related to this pull-request: [DT-424](https://aptoide.atlassian.net/browse/DT-424)
[DT-424]: https://aptoide.atlassian.net/browse/DT-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

[DT-424] Fix limited and uncached editorial article fetching

---

download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt

This PR aims at fixing several things regarding campaigns.
Fix widget campaign conversion due to null ad list id.
Adapt click url conversion based on new requirements.
No
Test if downloads work correctly
Tickets related to this pull-request: [DT-1049](https://aptoide.atlassian.net/browse/DT-1049)
**Questions:**
[DT-1049]: https://aptoide.atlassian.net/browse/DT-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-1049] Convert campaign click after download starts

---

payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardScreenUiState.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalUIState.kt
payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/presentation/PaypalViewModel.kt

This PR aims at supporting both attribution v4 and v6. This was done by just removing the analytic event from the success view.
No
Check that the event is not being sent. if you want you can also test both attribution flows, eventhough those were not changed.
Tickets related to this pull-request: [DT-1120](https://aptoide.atlassian.net/browse/DT-1120)
**Questions:**
[DT-1120]: https://aptoide.atlassian.net/browse/DT-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DT-1120] Remove attribution event from Success View

---

app/src/main/java/cm/aptoide/pt/appview/AppViewScreen.kt
app/src/main/java/cm/aptoide/pt/appview/OtherVersionsView.kt
app/src/main/java/cm/aptoide/pt/appview/RelatedContentView.kt
feature_appview/src/main/java/cm/aptoide/pt/feature_appview/presentation/CustomScrollableTabRow.kt

This PR fixes the repopulating of the Related and Versions tabs for the appview by replacing the lazyItems inside of those tabs with "normal" items, and it also hides the Related tab when the app doesn't have related editorials.
Note that on CustomScrollableTabRow the indicatorWidths list has a fixed size, if we change the number of possible tabs in the appview we should change that as well.
No
The tester should open several appviews and test going in and out of Related and Versions (to info for example) to see if they don't get duplicated content in the appview or content where it shouldn't be.
They should also open and close different appviews to see if the …

[APP-2226] Appview for Related and Versions tabs

---

app/src/main/java/cm/aptoide/pt/appview/RelatedContentView.kt
app/src/main/java/cm/aptoide/pt/editorial/EditorialScreen.kt
app/src/main/java/cm/aptoide/pt/editorial/EditorialsCardView.kt

Fixes the background color of the Editorial Label. 
Since it's a Card, its background color is dictated by its backgroundColor parameter and not by the background inside the modifier.
No
Open every view Editorial related, both in light and dark theme, and see if the label background color always stays the correct one. 
Flow on how to test this or QA Tickets related to this use-case: [APP-2222](https://aptoide.atlassian.net/browse/APP-2222)
Tickets related to this pull-request: [APP-2222](https://aptoide.atlassian.net/browse/APP-2222)
[APP-2222]: https://aptoide.atlassian.net/browse/APP-2222?atlOrigin=eyJpIj …

[APP-2222] fix editorial label color

---

payments/billing-sdk/src/main/AndroidManifest.xml
payments/uri-handler/src/main/AndroidManifest.xml

- Makes PaymentActivity and AppcBillingService components disabled by default in the respective manifests.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1152](https://aptoide.atlassian.net/browse/DT-1152)
Tickets related to this pull-request: [DT-1152](https://aptoide.atlassian.net/browse/DT-1152)
[DT-1152]: https://aptoide.atlassian.net/browse/DT-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1152]: https://aptoide.atlassian.net/browse/DT-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

[DT-1152] Make iab payments entry components disabled by default

---

app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/di/RepositoryModule.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/ArticlesMetaUseCase.kt

Fixed the empty content for more articles on the related tab. The related where relying on the editorials of the bundle screen, but when the editorials where not on getWidgets api, we didn't have a fallback. The PR adds that fallback.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1150](https://aptoide.atlassian.net/browse/DT-1150)
Tickets related to this pull-request: [DT-1150](https://aptoide.atlassian.net/browse/DT-1150)
[DT-1150]: https://aptoide.atlassian.net/browse/DT-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1150]: …

[DT-1150] Fixed the "no content for more articles" at the related tab

---

payments/base/payment-prefs/src/main/java/com/appcoins/payment_prefs/domain/PreSelectedPaymentUseCase.kt

It allows for the GH to save the last successful payment method, so when we are doing a second payment we enter that payment's view immediately, to save clicks.
No
Test by doing some IAB purchases with different payment methods and see if the saved state is always the last successful payment (fail some payments on purpose to make sure every flow is working as intended)
Flow on how to test this or QA Tickets related to this use-case: [DT-813](https://aptoide.atlassian.net/browse/DT-813)
Tickets related to this pull-request: [DT-813](https://aptoide.atlassian.net/browse/DT-813)
[DT-813]: …

[DT-813] Save last successful payment method

---

payments/base/arch/src/main/java/com/appcoins/payments/arch/PaymentsInitializer.kt
payments/base/payment-manager/src/main/java/com/appcoins/payment_manager/di/PaymentsModule.kt
payments/base/payment-manager/src/main/java/com/appcoins/payment_manager/repository/broker/PaymentsRepository.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/CreditCardPaymentMethod.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/PaymentDetails.kt
payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/PaypalPaymentMethod.kt
payments/payment-methods/paypal/src/main/java/com/appcoins/payment_method/paypal/repository/model/PaymentDetailsRequest.kt

It sends a channel parameter in the [broker/8.20230522/methods?channel=<channel>](http://localhost/api/broker/8.20230522/methods?channel=<channel>) and in the body of the transactions creations `gateways/*/transactions` (in this case - adyen and paypal). 
No
Make successful purchases with credit card and paypal and see if the `channel` parameter is called correctly in the supposed requests. (making it by gameshub it should send `GAMESHUB`)
Flow on how to test this or QA Tickets related to this use-case: [DT-1199](https://aptoide.atlassian.net/browse/DT-1199) …

[DT-1199] Send channel parameter in broker methods/transactions

---

app-games/src/main/java/cm/aptoide/pt/app_games/di/RepositoryModule.kt

- Fixes missing default editorial url error by adding a provides method.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2298](https://aptoide.atlassian.net/browse/APP-2298)
Tickets related to this pull-request: [APP-2298](https://aptoide.atlassian.net/browse/APP-2298)
[APP-2298]: https://aptoide.atlassian.net/browse/APP-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2298]: https://aptoide.atlassian.net/browse/APP-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APPP-2998] Fix missing default editorial url error

---

aptoide-installer/src/main/AndroidManifest.xml
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt

This PR aims to add App ownership and to update the app without the user having to accept it.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2310](https://aptoide.atlassian.net/browse/APP-2310)
Tickets related to this pull-request: [APP-2310](https://aptoide.atlassian.net/browse/APP-2310)
**Questions:**
[APP-2310]: https://aptoide.atlassian.net/browse/APP-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2310]: …

[APP-2310] Support update ownership api

---

payments/payment-methods/adyen-compose/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt

- Adds a known key to the stored payment method CardComponent (which is a ViewModel). This key can then be used to invalidate/clear this ViewModel.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-895](https://aptoide.atlassian.net/browse/DT-895)
Tickets related to this pull-request: [DT-895](https://aptoide.atlassian.net/browse/DT-895)
[DT-895]: https://aptoide.atlassian.net/browse/DT-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-895]: https://aptoide.atlassian.net/browse/DT-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

[DT-895] Fix Adyen saved card prefix asterisks not being shown

---

app-games/src/main/java/cm/aptoide/pt/app_games/categories/presentation/CategoryGridView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/editorial/EditorialView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/feature_apps/presentation/PublisherTakeoverAppView.kt
app/src/main/java/cm/aptoide/pt/home/BundlesView.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/ViewModelProvider.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt

- Renames editorial and categories state fetching composable
- Fixes errors in app games imports related to the BundleView preview changes
No
Flow on how to test this or QA Tickets related to this use-case: [DT-589](https://aptoide.atlassian.net/browse/DT-589)
Tickets related to this pull-request: [DT-589](https://aptoide.atlassian.net/browse/DT-589)
[DT-589]: https://aptoide.atlassian.net/browse/DT-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-589]: https://aptoide.atlassian.net/browse/DT-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

[DT-589] Rename state composable and fix app games import errors

---

payments/payment-methods/adyen-compose/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardScreenUiState.kt
payments/payment-methods/adyen-compose/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenCreditCardViewModel.kt
payments/payment-methods/adyen/build.gradle.kts
payments/payment-methods/adyen/src/main/AndroidManifest.xml
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/di/AdyenModule.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/Adyen3DS2Activity.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenActionResolveContract.kt
payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/presentation/AdyenRedirectActivity.kt
payments/payment-methods/adyen/src/main/res/values/styles.xml
payments/uri-handler/src/main/AndroidManifest.xml
payments/uri-handler/src/main/java/com/appcoins/uri_handler/PaymentActivity.kt
payments/uri-handler/src/main/java/com/appcoins/uri_handler/PaymentScreenContentProvider.kt

Encapsulate Adyen components specific logic to simplify Adyen payment method implementation.
Add custom WebView to the redirection activity to gain control over user click back actions
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1098](https://aptoide.atlassian.net/browse/DT-1098)
Tickets related to this pull-request: [DT-1098](https://aptoide.atlassian.net/browse/DT-1098)
PRs related to this one: [#497](https://github.com/Aptoide/aptoide-client-dt/pull/497)
[DT-1098]: https://aptoide.atlassian.net/browse/DT-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

[DT-1098] Encapsulate Adyen components specific logic and add WebView

---

environment-info/src/main/java/cm/aptoide/pt/environment_info/DeviceInfo.kt

`joinToString` function parameter `separator` is by default `separator=", "` making it have a space between CPU configurations, which we don't want and it's not supported by the backend, now we send `separator=","` in order to fix this issue
No
Open the app and test different flows, to see if the q is being correctly sent and in the right places. Try with a device with multiple CPU confs (might need an emulator for that) to see if the myCPU q parameter is not coming with spaces.
Flow on how to test this or QA Tickets related to this use-case: [DT-1034](https://aptoide.atlassian.net/browse/DT-1034)
Tickets related to this …

[DT-1034] Fix myCPU Q-logic

---

feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppsByTagUseCase.kt

- Creates a new method in the Apps by tag use case that allows to define a new limit on the number of apps fetched.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1134](https://aptoide.atlassian.net/browse/DT-1134)
Tickets related to this pull-request: [DT-1134](https://aptoide.atlassian.net/browse/DT-1134)
**Questions:**
[DT-1134]: https://aptoide.atlassian.net/browse/DT-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1134]: …

[DT-1134] Add way to fetch apps by tag with defined limit (for widget purposes)

---

app-games/build.gradle.kts
app-games/src/main/java/cm/aptoide/pt/app_games/AptoideApplication.kt
app-games/src/main/java/cm/aptoide/pt/app_games/di/RepositoryModule.kt
app-games/src/main/java/cm/aptoide/pt/app_games/network/AptoideQLogicInterceptor.kt

This PR aims to fix the filter app's q parameter that now doesn't take into account if the user has that option selected like in v10
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2392](https://aptoide.atlassian.net/browse/APP-2392)
Tickets related to this pull-request: [APP-2392](https://aptoide.atlassian.net/browse/APP-2392)
**Questions:**
[APP-2392]: https://aptoide.atlassian.net/browse/APP-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2392]: …

[APP-2392] Filtering apps Q parameter

---

app-games/build.gradle.kts
app-games/src/main/AndroidManifest.xml
app-games/src/main/java/cm/aptoide/pt/app_games/UrlActivity.kt
app-games/src/main/java/cm/aptoide/pt/app_games/UrlView.kt
app-games/src/main/java/cm/aptoide/pt/app_games/terms_and_conditions/LegalUrls.kt
app-games/src/main/java/cm/aptoide/pt/app_games/terms_and_conditions/TermsAndConditions.kt
app-games/src/main/java/cm/aptoide/pt/app_games/toolbar/AppGamesToolBar.kt
app-games/src/main/res/values/strings.xml

This PR aims to add links to privacy policy and terms & conditions so the user can click them and be redirected to their pages
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
Tickets related to this pull-request: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
**Questions:**
[APP-2347]: https://aptoide.atlassian.net/browse/APP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2347]: …

[APP-2347] Add links to privacy policy and terms & conditions

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/res/values/strings.xml

- Adds the specific version name and version code to the settings screen.
- Removes UI theme options from the settings screen.
- Refactors the legal section in the settings: removes the opt in/opt out toggle and adds Privacy Policy and Terms & Condition redirect buttons.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2415](https://aptoide.atlassian.net/browse/APP-2415)
Tickets related to this pull-request: [APP-2415](https://aptoide.atlassian.net/browse/APP-2415)
[APP-2415]: https://aptoide.atlassian.net/browse/APP-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

[APP-2415] Refactor aptoide games settings

---

app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/AptoideGamesCircularLoading.kt

- Implements the new circular progress icons for aptoide games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2442](https://aptoide.atlassian.net/browse/APP-2442)
Tickets related to this pull-request: [APP-2442](https://aptoide.atlassian.net/browse/APP-2442)
[APP-2442]: https://aptoide.atlassian.net/browse/APP-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2442]: https://aptoide.atlassian.net/browse/APP-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-2442] Implement circular loading progress icon

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/InstallerNotificationsBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationUtils.kt
app-games/src/main/res/drawable/notification_icon.xml
app-games/src/main/res/drawable/notification_icon_dev.xml

There's not much notification customization we can do since Android 12, so (for now) I just added the new notifications icons and made the color change according to the system theme. For Android 11 and below it's a bit different but they seem okay as well, I think.
No
Test the install notifications flow in both light and dark theme (system-level). See if it seems okay for both and different Android devices as well.
Flow on how to test this or QA Tickets related to this use-case: [APP-2443](https://aptoide.atlassian.net/browse/APP-2443)
Tickets related to this pull-request: [APP-2443](https://aptoide.atlassian.net/browse/APP-2443) …

[APP-2443] - Add Notifications Icons

---

app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Forward.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

Refactors BundleHeader to uniformize and remove MyGamesBundleHeader and updates it according to the new design.
No
Test different bundles headers, including My Games and PTO
Flow on how to test this or QA Tickets related to this use-case: [APP-2450](https://aptoide.atlassian.net/browse/APP-2450)
Tickets related to this pull-request: [APP-2450](https://aptoide.atlassian.net/browse/APP-2450)
[APP-2450]: https://aptoide.atlassian.net/browse/APP-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2450]: …

[APP-2450] - Update bundles headers

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/DownloadView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoryDetailView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/banners/ChessPatternBanner.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppItems.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/EmptyView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/GenericErrorView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/NoConnectionView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewShort.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/network/presentation/WifiPromptDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/support/SupportScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/terms_and_conditions/TermsAndConditions.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AppGamesButton.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesToolBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesTopBar.kt

- Refactors all aptoide games composable previews to be in dark mode only
- Adds PTO composable preview
- Adds the chess pattern banner from the design
- Updates the PTO to match the design
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2446](https://aptoide.atlassian.net/browse/APP-2446)
Tickets related to this pull-request: [APP-2446](https://aptoide.atlassian.net/browse/APP-2446)
[APP-2446]: https://aptoide.atlassian.net/browse/APP-2446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2446]: …

[APP-2446] Update aptoide games PTO

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/permissions/AppPermissionsView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Muted.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Unmuted.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/SmallEmptyView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/theme/AppIcons.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/theme/Theme.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/VideoSettingsViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/repository/VideoSettingsRepository.kt
extensions/src/main/java/cm/aptoide/pt/extensions/DateExtensions.kt
extensions/src/main/java/cm/aptoide/pt/extensions/StringExtensions.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppUiState.kt

**PR in draft, waiting for the permissions view UI and the editorials card design updates.**
- Updates the app view UI to match the design.
- Adds the missing Related and Info tabs, including the tab row to access them.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2471](https://aptoide.atlassian.net/browse/APP-2471)
Tickets related to this pull-request: [APP-2471](https://aptoide.atlassian.net/browse/APP-2471)
[APP-2471]: https://aptoide.atlassian.net/browse/APP-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2471]: …

[APP-2471] Update aptoide games app view UI

---

app/src/main/java/cm/aptoide/pt/AptoideApplication.java
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java
app/src/main/java/cm/aptoide/pt/ads/AdsUserPropertyManager.java
app/src/main/java/cm/aptoide/pt/app/view/AppViewPresenter.java
app/src/main/java/cm/aptoide/pt/database/RoomInstalledPersistence.java
app/src/main/java/cm/aptoide/pt/download/view/outofspace/OutOfSpaceManager.kt
app/src/main/java/cm/aptoide/pt/install/AptoideInstalledAppsRepository.java
app/src/main/java/cm/aptoide/pt/promotions/ClaimPromotionDialogFragment.java
app/src/main/java/cm/aptoide/pt/promotions/ClaimPromotionsNavigator.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsFragment.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsManager.java
app/src/main/java/cm/aptoide/pt/promotions/PromotionsPresenter.java
app/src/main/java/cm/aptoide/pt/view/AppCoinsInfoNavigator.java
app/src/main/java/cm/aptoide/pt/view/EskillsInfoNavigator.java
app/src/main/java/cm/aptoide/pt/view/FragmentModule.java
app/src/main/java/cm/aptoide/pt/wallet/WalletAppProvider.kt
app/src/main/java/cm/aptoide/pt/wallet/WalletInstallManager.kt
app/src/vanilla/java/cm/aptoide/pt/ads/WalletAdsOfferCardManager.java
app/src/vanilla/java/cm/aptoide/pt/ads/WalletAdsOfferManager.java
aptoide-database/src/main/java/cm/aptoide/pt/database/room/InstalledDao.java

This PR aims at fixing wallet install feature. We had a bug where when the wallet install dialog was not showing its correct state. This was happening because the sync of the db was being done too late, meaning it would show the wrong dialog state.
Yes 
With for example, the game "Last day on earth: survival", try to make a purchase without having the wallet installed. Check if it downloads correctly (meaning it showed the correct initial state)
Tickets related to this pull-request: [APP-2425](https://aptoide.atlassian.net/browse/APP-2425)
**Questions:** …

[APP-2425] SDK Wallet install

---

app/src/main/java/cm/aptoide/pt/notification/SystemNotificationShower.java

This PR aims at fixing the push notifications, which were not working after changing the target sdk as it woudl require changes on the way they were built (use channels)
No
Using rewrites test the push notifications. 
Since i changed the others, you can also test them, like the ready to install one or the new feature one (may have to force it in the code).
Tickets related to this pull-request: [APP-2408](https://aptoide.atlassian.net/browse/APP-2408)
**Questions:**
[APP-2408]: …

[APP-2408] Push notification fix

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

- Updates the getWidgets endpoint and removes the context filter from the request.
- Updates the editorials URL by changing te aptoide_uid query parameter.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
Tickets related to this pull-request: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljN …

[APP-2426] Update aptoide games domains

---

app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoryDetailView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppsListUiState.kt

- Improves app items lists previews by adding more PreviewParameterProvider's for uistates and adding a random state for the rememberDownloadState previewable. 
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2519](https://aptoide.atlassian.net/browse/APP-2519)
Tickets related to this pull-request: [APP-2519](https://aptoide.atlassian.net/browse/APP-2519)
[APP-2519]: https://aptoide.atlassian.net/browse/APP-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2519]: https://aptoide.atlassian.net/browse/APP-2519?atlOrigin=eyJpIjoiNWRk …

[APP-2519] Improve app item lists previews

---

aptoide-account-manager/build.gradle
aptoide-analytics-core/build.gradle
aptoide-analytics-default-implementation/build.gradle
aptoide-views/build.gradle
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/AndroidConfig.kt
buildSrc/src/main/kotlin/GradleDependency.kt
buildSrc/src/main/kotlin/plugin/AndroidModulePlugin.kt
crashreports/build.gradle
dataprovider/build.gradle
gradle/wrapper/gradle-wrapper.properties
utils/build.gradle

It updates AGP and Gradle versions, from 8.1.1 to 8.2.2 and from 8.0 to 8.2, respectively.
No
See if no build is broken and everything's working accordingly.
Flow on how to test this or QA Tickets related to this use-case: [DT-1280](https://aptoide.atlassian.net/browse/DT-1280)
Tickets related to this pull-request: [DT-1280](https://aptoide.atlassian.net/browse/DT-1280)
**Questions:**
[DT-1280]: https://aptoide.atlassian.net/browse/DT-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[DT-1280] - Update gradle and gradle plugin versions

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
extensions/src/main/java/cm/aptoide/pt/extensions/StringExtensions.kt

- Adds exception handling to date parsing, since it could cause crashes in the app in case the original date string was null.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2551](https://aptoide.atlassian.net/browse/APP-2551)
Tickets related to this pull-request: [APP-2551](https://aptoide.atlassian.net/browse/APP-2551)
[APP-2551]: https://aptoide.atlassian.net/browse/APP-2551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2551]: https://aptoide.atlassian.net/browse/APP-2551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[APP-2551] Add exception handling in date parsing

---

app-games/src/main/java/com/aptoide/android/aptoidegames/search/repository/AppGamesSearchStoreManager.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/data/network/service/SearchRetrofitService.kt
feature_search/src/main/java/cm/aptoide/pt/feature_search/domain/repository/SearchStoreManager.kt

- Makes aptoide games pass its store name in search requests.
- Makes SearchStoreManager provide a limit for the search
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
Tickets related to this pull-request: [APP-2426](https://aptoide.atlassian.net/browse/APP-2426)
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2426]: https://aptoide.atlassian.net/browse/APP-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

[APP-2426] Fix issues in domains

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/InstallPackageInfoMapperImpl.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/di/AptoideInstallerModule.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/GetMetaResponse.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt

This PR aims to fix an issue with the InstallViewShorts. When the install button is clicked, it now includes a check to see if the app has a path. If the path is empty, the AppMetaUseCase will be called to retrieve the app's path.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2454](https://aptoide.atlassian.net/browse/APP-2454)
Tickets related to this pull-request: [APP-2454](https://aptoide.atlassian.net/browse/APP-2454)
**Questions:**
[APP-2454]: …

[APP-2454] Make install view short work

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselLargeAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt

- Fixes the app name in carousels to have two lines when there is no download progress, and only one line if there is.
- Also fixes some accessibility issues with the progress text in these items if the device's font is slightly larger.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
Tickets related to this pull-request: [APP-2445](https://aptoide.atlassian.net/browse/APP-2445)
[APP-2445]: https://aptoide.atlassian.net/browse/APP-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[APP-2445] Fix app name in carousels

---

app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt

Fix the bottom navigation icons spacing
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2580](https://aptoide.atlassian.net/browse/APP-2580)
Tickets related to this pull-request: [APP-2580](https://aptoide.atlassian.net/browse/APP-2580)
[APP-2580]: https://aptoide.atlassian.net/browse/APP-2580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2580]: https://aptoide.atlassian.net/browse/APP-2580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[App-2580] Bottom navigation items spacing

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/terms_and_conditions/LegalUrls.kt

This PR aims to add a URL to billing terms on settings
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
Tickets related to this pull-request: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)
**Questions:**
[APP-2347]: https://aptoide.atlassian.net/browse/APP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2347]: https://aptoide.atlassian.net/browse/APP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

[APP-2347] Settings billing terms of use url

---

app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt

This PR aims to fix the navigation problems(opening the same screen many times) using the same solution on GH
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2579](https://aptoide.atlassian.net/browse/APP-2579)
Tickets related to this pull-request: [APP-2579](https://aptoide.atlassian.net/browse/APP-2579)
**Questions:**
[APP-2579]: https://aptoide.atlassian.net/browse/APP-2579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2579]: …

[APP-2579] Fix navigation

---

feature_categories/src/main/java/cm/aptoide/pt/feature_categories/domain/CategoriesUseCase.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/AllCategoriesViewModel.kt

This PR aims to create a fallback for when the categories bundle don't appear in the home view
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2589](https://aptoide.atlassian.net/browse/APP-2589)
Tickets related to this pull-request: [APP-2589](https://aptoide.atlassian.net/browse/APP-2589)
**Questions:**
[APP-2589]: https://aptoide.atlassian.net/browse/APP-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2589]: …

[APP-2589] Categories view working

---

network-listener/src/main/java/cm/aptoide/pt/network_listener/NetworkConnectionImpl.kt

Adds check for validated network connection. 
To make sure the network is actually available when emitting the event.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1291](https://aptoide.atlassian.net/browse/DT-1291)
Tickets related to this pull-request: [DT-1291](https://aptoide.atlassian.net/browse/DT-1291)
[DT-1291]: https://aptoide.atlassian.net/browse/DT-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1291]: https://aptoide.atlassian.net/browse/DT-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

[DT-1291] Fix network connection detection logic

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/ErrorViews.kt

- Fixes missing text colors in aptoide games payment error views.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2607](https://aptoide.atlassian.net/browse/APP-2607)
Tickets related to this pull-request: [APP-2607](https://aptoide.atlassian.net/browse/APP-2607)
[APP-2607]: https://aptoide.atlassian.net/browse/APP-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2607]: https://aptoide.atlassian.net/browse/APP-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-2607] Fix text colors in aptoide games payment error views

---

app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoryDetailView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt

It adds the analytics event app_promo_click to the MoreBundleView and to the CategoryDetailView
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2619](https://aptoide.atlassian.net/browse/APP-2619)
Tickets related to this pull-request: [APP-2619](https://aptoide.atlassian.net/browse/APP-2619)
**Questions:**
[APP-2619]: https://aptoide.atlassian.net/browse/APP-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2619]: …

[APP-2619] - Send AppPromoClick on Categories & See All Views

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/permissions/AppPermissionsView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstallationScreen.kt
app/src/main/java/cm/aptoide/pt/appview/AppViewScreen.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppInfoUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppViewModel.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt

- Replaces getApp requests with getMeta in the AppViewModel.
- Refactors the composable used to fetch the AppViewModel to be previewable. It now returns the ui state and the reload function instead of returning the ViewModel directly.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2667](https://aptoide.atlassian.net/browse/APP-2667)
Tickets related to this pull-request: [APP-2667](https://aptoide.atlassian.net/browse/APP-2667)
[APP-2667]: https://aptoide.atlassian.net/browse/APP-2667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[APP-2667] Replace getApp requests with getMeta

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideGamesBottomSheet.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyBottomSheetContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt

- Adds the AptoideGames APKFY flow implementation, including the bottom sheet that follows the design.
- Changes the getMeta call to be able to fetch an app by app id.
No
1.   Run the /download endpoint in the Aptoide MMP OpenAPI, with the package name of the app you want to test and an oemID.
2. Perform a clean install on the app and check if the apkfy flow starts correctly and the bottom sheet shows up.
Flow on how to test this or QA Tickets related to this use-case: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)
Tickets related to this pull-request: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)
**Code …

[APP-2614] Aptoide games APKFY flow implementation

---

app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyBottomSheetContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/AppViewModel.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt

- Adds a method to getMeta by app id in the apps repository.
- Changes the conditions logic to fetch the app in the ApkfyViewModel. It prioritizes app id over package name and it does not fetch if the package name is the same as the AptoideGames,.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)
Tickets related to this pull-request: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)
[APP-2614]: https://aptoide.atlassian.net/browse/APP-2614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

[APP-2614] Change apkfy app fetching logic

---

app/src/main/java/cm/aptoide/pt/appview/AppViewScreen.kt
app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt

As the feature campaign was refactored and the AppData changed, we don't have AdListId in v10 anymore, nor CampaignUrlNormalizer exists.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2733](https://aptoide.atlassian.net/browse/APP-2733)
Tickets related to this pull-request: [APP-2733](https://aptoide.atlassian.net/browse/APP-2733)
[APP-2733]: https://aptoide.atlassian.net/browse/APP-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2733]: https://aptoide.atlassian.net/browse/APP-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

[APP-2733] - Remove AdListId and CampaignUrlNormalizer from v10

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/AGLogger.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/PaymentsWarningIcon.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AGPaymentScreenContentProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/ErrorViews.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/analytics/PaymentContext.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/LandscapePaymentView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/PortraitPaymentView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/paypal/PaypalScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/transaction/TransactionScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletPaymentMethod.kt

Adds checks for the  pending purchase and ongoing transaction before starting a payment
Had to perform some refactoring, especially in analytics, to implement it without much technical debt.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1322](https://aptoide.atlassian.net/browse/DT-1322)
Tickets related to this pull-request: [DT-1322](https://aptoide.atlassian.net/browse/DT-1322)
PRs related to this one: [#552](https://github.com/Aptoide/aptoide-client-dt/pull/552)  [#5](https://github.com/Catappult/appcoins-payments-android/pull/5)
[DT-1322]: …

[DT-1322] Add checks into payment flow

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/terms_and_conditions/LegalUrls.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesToolBar.kt

It fixes the redirect logic for the Aptoide Games legal urls. We have automatic redirects without subdomain and lang parameter for aptoide.com/legal 
No
Change your device's language and open the links from the AG app (with cache cleared)
Flow on how to test this or QA Tickets related to this use-case: [APP-2831](https://aptoide.atlassian.net/browse/APP-2831)
Tickets related to this pull-request: [APP-2831](https://aptoide.atlassian.net/browse/APP-2831)
[APP-2831]: https://aptoide.atlassian.net/browse/APP-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[APP-2831] - Implement correct Legal Urls

---

feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt

Pull to refresh had clean cache for every request except on getWidgets (meaning that the content inside each section would get updated but not the sections list itself.). This PR fixes that part, now when we pull to refresh we also perform the getWidgets request with no cache
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2837](https://aptoide.atlassian.net/browse/APP-2837)
Tickets related to this pull-request: [APP-2837](https://aptoide.atlassian.net/browse/APP-2837)
[APP-2837]: https://aptoide.atlassian.net/browse/APP-2837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[APP-2837] - Fix cache on getWidgets request on pull to refresh

---

app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/NotificationBell.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/NotificationsPermissionIcon.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/launch/AppLaunchPreferencesManager.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationsPermissionRequester.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesToolBar.kt

It implements the new Notifications Dialog design and specific logic -> Bell on toolbar always appears and notification dialog on launch only appears if it isn't first launch.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2844](https://aptoide.atlassian.net/browse/APP-2844)
Tickets related to this pull-request: [APP-2844](https://aptoide.atlassian.net/browse/APP-2844)
[APP-2844]: https://aptoide.atlassian.net/browse/APP-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2844]: …

[APP-2844] - Implement Notifications Dialog

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt

This PR aims to remove the blinking in the credit card screen by adding a delay so the card only turns visible after the correct form fields are drawn
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2827](https://aptoide.atlassian.net/browse/APP-2827)
Tickets related to this pull-request: [DT-1340](https://aptoide.atlassian.net/browse/DT-1340)
**Questions:**
[APP-2827]: https://aptoide.atlassian.net/browse/APP-2827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[APP-2827] Remove the blinking from the credit card screen

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/cm/aptoide/pt/DeepLinkIntentReceiver.java

This PR aims at implementing the applinks in vanilla.
Note: We are still not supporting the homepage (eventhough we are supporting everything else), but we have all subdomains  commented on purpose in the manifest, as it might get fixed after.
Also fixed some url handling as the url tags changed on the web since the last time we worked on it.
No
Generate a signed apk, test the different applinks while navigating on the web.
Tickets related to this pull-request: [APP-2835](https://aptoide.atlassian.net/browse/APP-2835)
**Questions:**
**Code Review …

[APP-2835] Implement applinks support and updated some url handles

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_oos/OutOfSpaceDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/network/presentation/WifiPromptDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationsPermissionRequester.kt

Replaces the fillMaxWidth on the dialogs with the correct design width
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2859](https://aptoide.atlassian.net/browse/APP-2859)
Tickets related to this pull-request: [APP-2859](https://aptoide.atlassian.net/browse/APP-2859)
[APP-2859]: https://aptoide.atlassian.net/browse/APP-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2859]: https://aptoide.atlassian.net/browse/APP-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-2859] - Update dialogs width according to the design

---

app-games/src/main/AndroidManifest.xml
app-games/src/main/res/values/themes.xml

It disables the edge to edge enforcement imposed on Android 15.
No
Flow on how to test this or QA Tickets related to this use-case: [DT-1351](https://aptoide.atlassian.net/browse/DT-1351)
Tickets related to this pull-request: [DT-1351](https://aptoide.atlassian.net/browse/DT-1351)
PRs related to this one: 
[#560](https://github.com/Aptoide/aptoide-client-dt/pull/560)
[#9](https://github.com/Catappult/appcoins-payments-android/pull/9)
[DT-1351]: https://aptoide.atlassian.net/browse/DT-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1351]: …

[DT-1351] - Disable Edge to Edge enforcement

---

app-games/src/main/java/com/aptoide/android/aptoidegames/UrlActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/dto/AnalyticsData.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

Fixes two bugs:
- When we searched for an app putting a % in the search keyword, clicking on an app from search results would crash the app.
- When we had a % sign in a bundle/section title, it's see more section wouldn't decode the symbol correctly.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2867](https://aptoide.atlassian.net/browse/APP-2867)
Tickets related to this pull-request: [APP-2867](https://aptoide.atlassian.net/browse/APP-2867)
[APP-2867]: https://aptoide.atlassian.net/browse/APP-2867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

[APP-2867] - Fix "%" encoding and decoding 

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt

Changes the bonus banner text that contained the bundle title to the string "Up to 20% bonus".
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
Tickets related to this pull-request: [APP-2813](https://aptoide.atlassian.net/browse/APP-2813)
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2813]: https://aptoide.atlassian.net/browse/APP-2813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

[APP-2813] - Change Bonus banner text

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/DeviceInfoViewModel.kt

Feedback emails were coming without PID (Wallet Address), it was added to the device info so it comes on emails as well, just like in GH.
No
Go to the Contact Us after a payment fail, go through the flow and see if the PID now appears as expected.
Flow on how to test this or QA Tickets related to this use-case: [APP-2890](https://aptoide.atlassian.net/browse/APP-2890)
Tickets related to this pull-request: [APP-2890](https://aptoide.atlassian.net/browse/APP-2890)
[APP-2890]: https://aptoide.atlassian.net/browse/APP-2890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …

[APP-2890] - Add PID to DeviceInfoViewModel

---

app/src/main/java/cm/aptoide/pt/notification/SystemNotificationShower.java

No
Open app check that you dont get the permission prompt unless you really need it (have a permission to show).
Before, we would be showing it always.
We think this is happening because this permission is mandatory above android 13. But our target is 12, which means we dont have a way to request it, so we think the system itself is handling the permission request when we create the notification channels. If we commented the notification channel creation, it would not show the permission dialog.
**What are the …

[APP-2877] Fix notifications permission

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AppGamesPurchaseInfo.kt

Makes every purchase info in AG have 2 decimal places
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2893](https://aptoide.atlassian.net/browse/APP-2893)
Tickets related to this pull-request: [APP-2893](https://aptoide.atlassian.net/browse/APP-2893)
[APP-2893]: https://aptoide.atlassian.net/browse/APP-2893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2893]: https://aptoide.atlassian.net/browse/APP-2893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-2893] - Force 2 Decimals in AG Purchase Info

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
extensions/src/main/java/cm/aptoide/pt/extensions/IntExtensions.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt

This PR aims to add the download numbers to the app view screen
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2643](https://aptoide.atlassian.net/browse/APP-2643)
Tickets related to this pull-request: [APP-2643](https://aptoide.atlassian.net/browse/APP-2643)
**Questions:**
[APP-2643]: https://aptoide.atlassian.net/browse/APP-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2643]: https://aptoide.atlassian.net/browse/APP-2643?atlOrigin=eyJpIjoiNWRkNTljN …

[APP-2643] Add download numbers to app view

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/AppIconWProgress.kt

- Changes the LaunchedEffect that controls the anamitation for indeterminate progresses to be triggered based on the download state object type and not the object itself. Since the progress in the Installing state is constantly being updated, the object reference changes and the LaunchedEffect is triggered each time.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2905](https://aptoide.atlassian.net/browse/APP-2905)
Tickets related to this pull-request: [APP-2905](https://aptoide.atlassian.net/browse/APP-2905)
[APP-2905]: https://aptoide.atlassian.net/browse/APP-2905?atlOrigin=eyJpI …

[APP-2905] Control icon progress based on state class type

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
extensions/src/main/java/cm/aptoide/pt/extensions/StringExtensions.kt

It implements a new function extractVideoId in StringExtensions to support different youtube url formats. It also assures that the video is only played if it reaches the supposed state to play, otherwise it shows the FG.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2904](https://aptoide.atlassian.net/browse/APP-2904)
Tickets related to this pull-request: [APP-2904](https://aptoide.atlassian.net/browse/APP-2904)
[APP-2904]: https://aptoide.atlassian.net/browse/APP-2904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2904]: …

[APP-2904] - Fix YoutubePlayer video errors

---

app-games/build.gradle.kts

- Adds support for different store names and signatures in the build process through environment variables.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2965](https://aptoide.atlassian.net/browse/APP-2965)
Tickets related to this pull-request: [APP-2965](https://aptoide.atlassian.net/browse/APP-2965)
[APP-2965]: https://aptoide.atlassian.net/browse/APP-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2965]: https://aptoide.atlassian.net/browse/APP-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

[APP-2965] Add support for different store names and signatures

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreView.kt

This PR aims to fix the bonus string format so it highlights the words in every language
The strings.xml isn't merged yet
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2957](https://aptoide.atlassian.net/browse/APP-2957)
Tickets related to this pull-request: [APP-2957](https://aptoide.atlassian.net/browse/APP-2957)
**Questions:**
[APP-2957]: https://aptoide.atlassian.net/browse/APP-2957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2957]: …

[APP-2957] Fix bonus string format

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideIdsRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/IdsRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/di/RepositoryModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/AptoideMMPCampaign.kt

This PR aims at implementing the Guest UID usage on the mmp calls.
No
Open app and check that the mmp calls have the guest uid. Dont forget it is only attributed on the apkfy flow, so you might need to clear cache and call the mmp /download to setup a fake apkfy.
Tickets related to this pull-request: [APP-2874](https://aptoide.atlassian.net/browse/APP-2874)
**Questions:**
[APP-2874]: https://aptoide.atlassian.net/browse/APP-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-2874] Guest ID

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
aptoide-installer/src/main/AndroidManifest.xml
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstallManager.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstaller.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/ObbService.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/InstallPermissions.kt
extensions/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt

- Fixes the issue of not being able to move OBB files to the obb folder on the first session that the user allows the necessary permissions to install apps.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3028](https://aptoide.atlassian.net/browse/APP-3028)
- Install an app with OBBs on the first session when the install permissions (unknown sources and external storage, if necessary) are accepted and check if the app installs successfully and the OBB files are moved to the device's storage Android/obb folder.
- Check for the following versions: < 11; 11; 12; 13; 14 …

[APP-3028] 1st installation permissions session and obbs

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt

- Adds the Indicative user property 'utm_package_name', which is the package name that comes in the Apkfy flow.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3022](https://aptoide.atlassian.net/browse/APP-3022)
- Start APKFY and check if the property is set and sent to indicative.
Tickets related to this pull-request: [APP-3022](https://aptoide.atlassian.net/browse/APP-3022)
[APP-3022]: https://aptoide.atlassian.net/browse/APP-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3022]: …

[APP-3022] Add utm_package_name as an Indicative user property

---

app-games/src/main/java/com/aptoide/android/aptoidegames/design_system/AptoideGamesSwitch.kt
buildSrc/src/main/kotlin/LibraryDependency.kt

Aims to fix the crash that occurs when changing perspective (portrait/landscape) returning negative values for width/height.
This seems to be related to an [issue](https://issuetracker.google.com/issues/314008560) fixed on a [later version of compose](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-beta01) , so I updated the compose version to the latest one (1.7.3) and replaced `rememberRipple` with `ripple` since the first didn't work on this new compose version
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2991](https://aptoide.atlassian.net/browse/APP-2991)
Tickets …

[APP-2991] - Upgrade Compose version and replace ripple

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/FakeInstallerNotificationsManager.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/InstallerNotificationsBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/InstallerNotificationsManager.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/RealInstallerNotificationsManager.kt

It implements the Ready To Install notification for when AG is downloading on background. 
It also changes the copy of the installing notification from "Installing" to "Preparing".
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3008](https://aptoide.atlassian.net/browse/APP-3008)
Tickets related to this pull-request: [APP-3008](https://aptoide.atlassian.net/browse/APP-3008)
[APP-3008]: https://aptoide.atlassian.net/browse/APP-3008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3008]: …

[APP-3008] - Ready To Install Notification

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/network/DownloaderRepository.kt

Adds sending HTTP error code for failed downloads Indicative events. 
Had to recreate a HttpException mapping to pass down the code.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3048](https://aptoide.atlassian.net/browse/APP-3048)
Tickets related to this pull-request: [APP-3048](https://aptoide.atlassian.net/browse/APP-3048)
[APP-3048]: https://aptoide.atlassian.net/browse/APP-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3048]: https://aptoide.atlassian.net/browse/APP-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

[APP-3048] Add sending HTTP error code for failed downloads

---

app-games/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml
aptoide-installer/src/main/AndroidManifest.xml
aptoide-network/src/main/AndroidManifest.xml
download-view/src/main/AndroidManifest.xml
environment-info/src/main/AndroidManifest.xml
extensions/src/main/AndroidManifest.xml
feature-appcoins/src/main/AndroidManifest.xml
feature-home/src/main/AndroidManifest.xml
feature-profile/src/main/AndroidManifest.xml
feature-settings/src/main/AndroidManifest.xml
feature_apps/src/main/AndroidManifest.xml
feature_editorial/src/main/AndroidManifest.xml
feature_search/src/main/AndroidManifest.xml
feature_updates/src/main/AndroidManifest.xml
install-manager/src/main/AndroidManifest.xml

It sets all the manifests' backup flags to false.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3057](https://aptoide.atlassian.net/browse/APP-3057)
Tickets related to this pull-request: [APP-3057](https://aptoide.atlassian.net/browse/APP-3057)
[APP-3057]: https://aptoide.atlassian.net/browse/APP-3057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3057]: https://aptoide.atlassian.net/browse/APP-3057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[APP-3057] - Set manifest backup flags to false

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt

It adds a new user property to indicative called android_language, that's the device language ISO code (ex.: pt-BR)
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3073](https://aptoide.atlassian.net/browse/APP-3073)
Tickets related to this pull-request: [APP-3073](https://aptoide.atlassian.net/browse/APP-3073)
[APP-3073]: https://aptoide.atlassian.net/browse/APP-3073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3073]: https://aptoide.atlassian.net/browse/APP-3073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

[APP-3073] - Add android_language Indicative User Property

---

app-games/src/main/java/com/aptoide/android/aptoidegames/UrlView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/PaymentsErrorView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

It replaces the occurrences CircularProgressIndicator with IndeterminateCircularLoading, our custom loading icon
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2997](https://aptoide.atlassian.net/browse/APP-2997)
Tickets related to this pull-request: [APP-2997](https://aptoide.atlassian.net/browse/APP-2997)
[APP-2997]: https://aptoide.atlassian.net/browse/APP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2997]: https://aptoide.atlassian.net/browse/APP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

[APP-2997] - Change native Loading Animation to custom one

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt

- Fixes issues with the parameter helper functions in both Indicative and Firebase analytics. The extension functions on nullable objects that hold analytics information were not returning the correct fallbacks.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3091](https://aptoide.atlassian.net/browse/APP-3091)
Tickets related to this pull-request: [APP-3091](https://aptoide.atlassian.net/browse/APP-3091)
[APP-3091]: https://aptoide.atlassian.net/browse/APP-3091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-3091]: …

[APP-3091] Fix parameter helper functions in analytics

---

app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt

- Improves the end of an app view video, by moving the video back to the beginning when the video ends, instead of showing the related content section.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2911](https://aptoide.atlassian.net/browse/APP-2911)
Tickets related to this pull-request: [APP-2911](https://aptoide.atlassian.net/browse/APP-2911)
[APP-2911]: https://aptoide.atlassian.net/browse/APP-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2911]: https://aptoide.atlassian.net/browse/APP-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

[APP-2911] Improve end of app view video

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt

- Extracts  common code in BI install analytics
- Adds new BI download event with cancel status
- Adds new BI click_on_install event with retry action, for when the user click on a retry button of an app
No
Flow on how to test this or QA Tickets related to this use-case: [APP-3083](https://aptoide.atlassian.net/browse/APP-3083)
Tickets related to this pull-request: [APP-3083](https://aptoide.atlassian.net/browse/APP-3083)

[APP-3083] Add new BI events related to installs

---

feature-bonus/src/main/java/cm/aptoide/pt/feature_bonus/data/BonusData.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/AptoideUrlsCacheInitializer.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt

This PR aims to fix the appc badge in case the API doesn't provide the banner
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2816](https://aptoide.atlassian.net/browse/APP-2816)
Tickets related to this pull-request: [APP-2816](https://aptoide.atlassian.net/browse/APP-2816)
**Questions:**
[APP-2816]: https://aptoide.atlassian.net/browse/APP-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2816]: …

[APP-2816] appc badge

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/DeviceInfoViewModel.kt

No
Flow on how to test this or QA Tickets related to this use-case: [AND-51](https://aptoide.atlassian.net/browse/AND-51)
Tickets related to this pull-request: [AND-51](https://aptoide.atlassian.net/browse/AND-51)
[AND-51]: https://aptoide.atlassian.net/browse/AND-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-51]: https://aptoide.atlassian.net/browse/AND-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-51] - support different store names multiple apks

---

feature-oos/src/main/java/cm/aptoide/pt/feature_oos/presentation/AvailableSpaceViewModel.kt

This PR addresses an issue with the OOS required space calculation. The miscalculation occurs because there is a slight delay in the system's update process; as a result, when checking the device storage after an uninstall, the system has not yet reflected the freed space.
Please fell free to discuss alternative solutions in this case I used the same solution as vanilla
No
Flow on how to test this or QA Tickets related to this use-case: [AND-25](https://aptoide.atlassian.net/browse/AND-25)
Tickets related to this pull-request: [AND-25](https://aptoide.atlassian.net/browse/AND-25)
**Questions:**
Does this add new dependencies which …

[AND-25] Fix OOS dialog

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/InstallPermissions.kt

It changes the name of the "Not Allowed" message when we get it from an AbortException by not accepting a permission to [name of the permission] permission not allowed. It also creates a new function to send a downloadAbortEvent to indicative, as stated in the ticket.
No
Try different ways of cancelling/not accepting the install permissions and see if the events are sent correctly.
Flow on how to test this or QA Tickets related to this use-case: [AND-81](https://aptoide.atlassian.net/browse/AND-81)
Tickets related to this pull-request: [AND-81](https://aptoide.atlassian.net/browse/AND-81)
[AND-81]: …

[AND-81] - Add indicative not allowed permissions download error

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/network/DownloaderRepository.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt

- Refactors the downloads logic to separate downloads of different apps by directories. Each app has its downloaded files inside a specific directory which name is the app's package name.
- Removes explicit file names from aab splits, making the splits file names fallback to the md5.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-97](https://aptoide.atlassian.net/browse/AND-97)
Tickets related to this pull-request: [AND-97](https://aptoide.atlassian.net/browse/AND-97)
[AND-97]: https://aptoide.atlassian.net/browse/AND-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

[AND-97] AAB splits partial download issue

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt

It applies the design changes made on home review 2.0 related to the My Games Bundle, namely the arrow color for the see all, the square icons, the DarkGrey background and the bottom padding for the apps.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-105](https://aptoide.atlassian.net/browse/AND-105)
Tickets related to this pull-request: [AND-105](https://aptoide.atlassian.net/browse/AND-105)
[AND-105]: https://aptoide.atlassian.net/browse/AND-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-105]: …

[AND-105] - Apply My Games changes in Home Review 2.0

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/InstalledApps.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MyGamesBundleView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/SeeAllMyGamesScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_oos/OutOfSpaceAppItem.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/AppGamesPurchaseInfo.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
extensions/src/main/java/cm/aptoide/pt/extensions/PackageManagerExtensions.kt

- Adds error catching when loading installed app icon drawables.
- Handles nullability in sections and screens that fetch installed app icon drawables.
- Moves and reuses function that fetches installed app icon drawables.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-113](https://aptoide.atlassian.net/browse/AND-113)
Tickets related to this pull-request: [AND-113](https://aptoide.atlassian.net/browse/AND-113)
[AND-113]: https://aptoide.atlassian.net/browse/AND-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-113]: …

[AND-113] Fix my games drawable crashes

---

aptoide-task-info/schemas/cm.aptoide.pt.task_info.database.TaskInfoDatabase/4.json
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/AptoideTaskInfoRepository.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/InstallationFileDao.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/TaskInfoDao.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/TaskInfoDatabase.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/model/InstallationFileData.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/model/TaskInfoData.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/database/model/TaskInfoWithFiles.kt
aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/di/TaskInfoModule.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/App.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealApp.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealInstallManager.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/repository/TaskInfoRepository.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/InstallManagerTest.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TestData.kt

- Adds logic to the install manager that, when trying to restore installation tasks for apps, checks if the apps meanwhile have already been installed or updated. For each app that is already installed/updated, its installation task is removed and not restored.
- Extracts a package info extension function that checks if an app Is outdated, by comparing it with a provided version code.
Yes
**INSTRUCTIONS FOR HOW TO TEST THIS ARE PROVIDED IN THE TICKET'S COMMENTS.**
Flow on how to test this or QA Tickets related to this use-case: [AND-98](https://aptoide.atlassian.net/browse/AND-98) …

[AND-98] Fix infinite installation loop for ag itself

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/Download.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt

~**IN DRAFT WHILE THE REQUIRED STRINGS ARE NOT ADDED**~
- Adds a bottom navigation item for the updates
- Creates the skeleton screen for the updates.
- Fixes an issue in the bottom bar items alignment, that started after updating the compose version.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-82](https://aptoide.atlassian.net/browse/AND-82)
Tickets related to this pull-request: [AND-82](https://aptoide.atlassian.net/browse/AND-82)
[AND-82]: https://aptoide.atlassian.net/browse/AND-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-82] Implement bottom navigation entry for updates

---

app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/NoUpdates.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
app/src/main/java/cm/aptoide/pt/updates/UpdatesView.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesUiState.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesViewModel.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/ViewModelProvider.kt

It implements a mock View Model and the UiState for updates, as well as the Empty and Loading views for the updates section for Aptoide Games
No
Flow on how to test this or QA Tickets related to this use-case: [AND-83](https://aptoide.atlassian.net/browse/AND-83)
Tickets related to this pull-request: [AND-83](https://aptoide.atlassian.net/browse/AND-83)
[AND-83]: https://aptoide.atlassian.net/browse/AND-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-83]: https://aptoide.atlassian.net/browse/AND-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[AND-83] - implement empty and loading states for updates

---

app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt

It adds navigation to the app item present in EditorialViewScreen
No
Flow on how to test this or QA Tickets related to this use-case: [AND-128](https://aptoide.atlassian.net/browse/AND-128)
Tickets related to this pull-request: [AND-128](https://aptoide.atlassian.net/browse/AND-128)
[AND-128]: https://aptoide.atlassian.net/browse/AND-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-128]: https://aptoide.atlassian.net/browse/AND-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-128] - Support Editorial to App view Navigation

---

app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesNotificationBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/di/RepositoryModule.kt
app-games/src/main/res/drawable/app_icon.xml
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesNotificationProvider.kt

This PR aims at implementing the updates notification.
Note 1. this was based on the PR https://github.com/Aptoide/aptoide-client-v8/pull/2052 so it shouldnt be merged before it.
This also means it has the commits from that branch. To review this pr, check by commit, my only single commit.
Note 2. This has strings hardcoded as they are not available yet.
Note 3. That this is hardcoded to send the notification up on app startup. This should obviosuly be removed and integrated on the https://aptoide.atlassian.net/browse/AND-85 ticket.
No
Open app, it will show a notification. …

[AND-86] updates notification

---

extensions/src/main/java/cm/aptoide/pt/extensions/IntExtensions.kt

Only adds + sign when we round it down
No
Flow on how to test this or QA Tickets related to this use-case: [AND-96](https://aptoide.atlassian.net/browse/AND-96)
Tickets related to this pull-request: [AND-96](https://aptoide.atlassian.net/browse/AND-96)
**Questions:**
[AND-96]: https://aptoide.atlassian.net/browse/AND-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-96]: https://aptoide.atlassian.net/browse/AND-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

[AND-96] Remove the + when we don't round it down

---

aptoide-task-info/src/main/java/cm/aptoide/pt/task_info/di/TaskInfoModule.kt

- Fixes the TaskInfo DB fallback to destructive migration, by removing the unecessary call to fallbackToDestructiveMigrationOnDowngrade, since it was removing the fallback on upgrades.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-132](https://aptoide.atlassian.net/browse/AND-132)
Tickets related to this pull-request: [AND-132](https://aptoide.atlassian.net/browse/AND-132)
**Questions:**
[AND-132]: https://aptoide.atlassian.net/browse/AND-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

[AND-132] Fix TaskInfo DB fallback to destructive migration

---

app-games/src/main/java/com/aptoide/android/aptoidegames/search/analytics/SearchAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt

(On draft until some questions are answered when Ana comes back) - It adds a search_result_click event sent when the search results come out empty.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-100](https://aptoide.atlassian.net/browse/AND-100)
Tickets related to this pull-request: [AND-100](https://aptoide.atlassian.net/browse/AND-100)
[AND-100]: https://aptoide.atlassian.net/browse/AND-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-100]: https://aptoide.atlassian.net/browse/AND-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

[AND-100] - Add indicative empty search_result_click

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt

- Reduces the bundleIcon size to 40x40px
- Makes the icon optional
- If have icon the title style is InputsL, otherwise it stays Title as it was before this change.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-104](https://aptoide.atlassian.net/browse/AND-104)
Tickets related to this pull-request: [AND-104](https://aptoide.atlassian.net/browse/AND-104)
[AND-104]: https://aptoide.atlassian.net/browse/AND-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-104]: https://aptoide.atlassian.net/browse/AND-104?atlOrigin=eyJpIjoiNWRkNTlj …

[AND-104] - Update PTO Header UI

---

app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/Bundles.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt

Refactors the empty search screen to also show the trending bundle, changing also the UI paddings for the error image and text.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-137](https://aptoide.atlassian.net/browse/AND-137)
Tickets related to this pull-request: [AND-137](https://aptoide.atlassian.net/browse/AND-137)
[AND-137]: https://aptoide.atlassian.net/browse/AND-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-137]: https://aptoide.atlassian.net/browse/AND-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

[AND-137] - Add Trending Bundle to Empty Search Screen

---

app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesNotificationBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesNotificationProvider.kt

It shows a custom string both on notifications and updates view when the only outdated app is AG
No
Flow on how to test this or QA Tickets related to this use-case: [AND-150](https://aptoide.atlassian.net/browse/AND-150)
Tickets related to this pull-request: [AND-150](https://aptoide.atlassian.net/browse/AND-150)
[AND-150]: https://aptoide.atlassian.net/browse/AND-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-150]: https://aptoide.atlassian.net/browse/AND-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-150] - Change updates' strings when the only app is AG

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/di/ViewModelProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesPreferencesViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt

This PR aims at implementing the auto update switch on the empty state of the updates.
Also took the oportunity to refactor the update flag view model.
No
Open the section (with no updates -> or simply change the idle state to show the no updates screen as well) with auto update off, check if you see the toggle. Then turn on, reopen the view and check if you have the simple version of the empty screen
Tickets related to this pull-request: [AND-148](https://aptoide.atlassian.net/browse/AND-148)
**Questions:**
[AND-148]: …

[AND-148] auto update in empty state

---

app-games/build.gradle.kts
app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/PostCacheInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/data/AptoideCategoriesRepository.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/di/RepositoryModule.kt

This PR aims at avoid having ws75-cache POST calls  . Since for some requests, we wanted to have a different dev url, we separated the retrofit instance. For the others, the chosen solution was to create an interceptor which will check if it is a post  and check the base url to remove the cache.
No
Open app, check if all requests are ok. Confirm there are no POST calls with ws75-cache.
Tickets related to this pull-request: [AND-129](https://aptoide.atlassian.net/browse/AND-129)
**Questions:**
[AND-129]: …

[AND-129] ws75 post requests

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt

It changes the order of settings to General, Support, Payments, Legal
No
Flow on how to test this or QA Tickets related to this use-case: [AND-157](https://aptoide.atlassian.net/browse/AND-157)
Tickets related to this pull-request: [AND-157](https://aptoide.atlassian.net/browse/AND-157)
[AND-157]: https://aptoide.atlassian.net/browse/AND-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-157]: https://aptoide.atlassian.net/browse/AND-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-157] - Switch Payments and Support order on Settings

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideAsyncImage.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app/src/main/java/cm/aptoide/pt/appview/AppViewScreen.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/Mappers.kt

It fixes the screenshots being cropped on the appview by changing the contentScale to Fit, applying the same density mapping to the screenshots urls that vanilla has, and changing the screenshots list to also contain their width and height, in order to scale the content having only a fixed height.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-158](https://aptoide.atlassian.net/browse/AND-158)
Tickets related to this pull-request: [AND-158](https://aptoide.atlassian.net/browse/AND-158)
[AND-158]: https://aptoide.atlassian.net/browse/AND-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

[AND-158] - Fix Cropped Screenshots

---

app-games/src/main/AndroidManifest.xml
app-games/src/main/java/com/aptoide/android/aptoidegames/LaunchIntentExtensions.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialViewScreen.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/domain/usecase/ArticleUseCase.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/EditorialViewModel.kt
feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/presentation/ViewModelProvider.kt

This PR aims to support app links so when the web user clicks on an App or downloads it gets redirected to Aptoide Games
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2709](https://aptoide.atlassian.net/browse/APP-2709)
Tickets related to this pull-request: [APP-2709](https://aptoide.atlassian.net/browse/APP-2709)
**Questions:**
[APP-2709]: https://aptoide.atlassian.net/browse/APP-2709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2709]: …

[APP-2709] Add app links support

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/AptoideMMPCampaign.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt

It adds the MMP logic coming from applinks to appview as described in the ticket -> Send the utms when the deeplink comes with utm_source (check the ticked for a more detailed description)
No
Flow on how to test this or QA Tickets related to this use-case: [AND-93](https://aptoide.atlassian.net/browse/AND-93)
Tickets related to this pull-request: [AND-93](https://aptoide.atlassian.net/browse/AND-93)
[AND-93]: https://aptoide.atlassian.net/browse/AND-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-93]: …

[AND-93] - Add AptoideMMP support to AppView AppLinks

---

app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt

This PR addresses the issue of the last item on the list being cut off. While this solution resolves the visibility issue of the last item, it does not yet address the problem of the scroll jump.
No
Flow on how to test this or QA Tickets related to this use-case: [APP-2910](https://aptoide.atlassian.net/browse/APP-2910)
Tickets related to this pull-request: [APP-2910](https://aptoide.atlassian.net/browse/APP-2910)
**Questions:**
[APP-2910]: https://aptoide.atlassian.net/browse/APP-2910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

[APP-2910] Refactor padding logic on screens with Bottom bar

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt

- Makes the currently selected tab reset to zero whenever the tab list size changes.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-130](https://aptoide.atlassian.net/browse/AND-130)
Tickets related to this pull-request: [AND-130](https://aptoide.atlassian.net/browse/AND-130)
[AND-130]: https://aptoide.atlassian.net/browse/AND-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-130]: https://aptoide.atlassian.net/browse/AND-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-130] Fix selected tab issues in AppView on process restart

---

download-view/src/main/java/cm/aptoide/pt/download_view/presentation/InstalledAppOpener.kt

There were some times that the app was crashing when users tried to open a game, due to the intent being null. Added a null check so that doesn't happen.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-183](https://aptoide.atlassian.net/browse/AND-183)
Tickets related to this pull-request: [AND-183](https://aptoide.atlassian.net/browse/AND-183)
[AND-183]: https://aptoide.atlassian.net/browse/AND-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-183]: https://aptoide.atlassian.net/browse/AND-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

[AND-183] - Add null check on openInstalledApp activity

---

app-games/src/main/java/com/aptoide/android/aptoidegames/di/RepositoryModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideQueryLangInterceptor.kt
app/src/main/java/cm/aptoide/pt/di/RepositoryModule.kt
app/src/main/java/cm/aptoide/pt/network/AptoideQueryLangInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/data/network/QueryLangInterceptor.kt
aptoide-network/src/main/java/cm/aptoide/pt/aptoide_network/di/NetworkModule.kt

Adds the lang parameter to baseOkHttpRequests, following Vanilla's logic 
No
Flow on how to test this or QA Tickets related to this use-case: [AND-180](https://aptoide.atlassian.net/browse/AND-180)
Tickets related to this pull-request: [AND-180](https://aptoide.atlassian.net/browse/AND-180)
[AND-180]: https://aptoide.atlassian.net/browse/AND-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-180]: https://aptoide.atlassian.net/browse/AND-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-180] - Add lang parameter to requests

---

app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/domain/ChatInteraction.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieUIState.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageBubble.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt

Fixes crash when token takes too long to be retrieved from the API.
Maintains game preview history from previous assistant answers.
No
Manually add a shorter timeout to responses to test crash.
Make several questions and check if the preview is maintained
Tickets related to this pull-request: [AND-118](https://aptoide.atlassian.net/browse/AND-118)
[AND-185](https://aptoide.atlassian.net/browse/AND-185)
**Questions:**
[AND-118]: https://aptoide.atlassian.net/browse/AND-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

[AND-118/185] GameGenie crash and history

---

app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieFeatureProvider.kt

This PR aims at implementing game genie feature flag. Should show only in Japan and Portugal.
No
Open the app and check if you have the game genie.
Tickets related to this pull-request: [AND-168](https://aptoide.atlassian.net/browse/AND-168)
**Questions:**
[AND-168]: https://aptoide.atlassian.net/browse/AND-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-168] Game Genie only in PT and JP

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt

It adds the app size in MB by segments like it's described in the documentation
No
Flow on how to test this or QA Tickets related to this use-case: [AND-195](https://aptoide.atlassian.net/browse/AND-195)
Tickets related to this pull-request: [AND-195](https://aptoide.atlassian.net/browse/AND-195)
[AND-195]: https://aptoide.atlassian.net/browse/AND-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-195]: https://aptoide.atlassian.net/browse/AND-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-195] - Add app size to download analytics

---

app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenuHandler.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt

It makes every bottom navigation menu not reload if it's clicked but we are already in that view. Then in Home, Search (on the results only), Updates and Categories it scrolls to the top of the list/page
No
Flow on how to test this or QA Tickets related to this use-case: [AND-201](https://aptoide.atlassian.net/browse/AND-201)
Tickets related to this pull-request: [AND-201](https://aptoide.atlassian.net/browse/AND-201)
[AND-201]: https://aptoide.atlassian.net/browse/AND-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-201]: …

[AND-201] Handle Bottom Navigation clicks on the same menu

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/FirebaseAnalyticsSender.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/IndicativeAnalyticsSender.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/DownloaderSelector.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/ScheduledDownloadsListener.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/ff/Extensions.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewShort.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
app/src/main/java/cm/aptoide/pt/appview/DownloadView.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideDownloader.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/ViewModelProvider.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/di/RepositoryModule.kt
feature-flags/src/main/java/cm/aptoide/pt/feature_flags/domain/FeatureFlags.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/workers/PackageDownloader.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/workers/PackageInstaller.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TasksTest.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TestData.kt

Adds package downloader selector by feature flag and user property for the current AB test variant. 
Had to refactor workers cancellation in order to support runtime suspended switch of the downloader implementation.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-213](https://aptoide.atlassian.net/browse/AND-213)
Tickets related to this pull-request: [AND-213](https://aptoide.atlassian.net/browse/AND-213)
[AND-213]: https://aptoide.atlassian.net/browse/AND-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-213]: …

[AND-213] Add package downloader implementation change with the feature flag

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/analytics/AnalyticsProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/analytics/PaymentAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/credit_card/AdyenCreditCardScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/di/PaymentsModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/MainPaymentsView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/paypal/PaypalScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/transaction/TransactionScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstallationScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/wallet/WalletInstalledScreen.kt

It moves all `iap` analytics events to their own PaymentAnalytics class and adds all the Indicative events correspondent to the Firebase ones with the naming changes noted in the ticket
No
Test payment methods' and their success/failure to see if events are being sent and sent correctly.
Flow on how to test this or QA Tickets related to this use-case: [AND-217](https://aptoide.atlassian.net/browse/AND-217)
Tickets related to this pull-request: [AND-217](https://aptoide.atlassian.net/browse/AND-217)
[AND-217]: https://aptoide.atlassian.net/browse/AND-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

[AND-217] Add Analytics class and Indicative events for Payments

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/DownloaderSelector.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/ScheduledDownloadsListener.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/InstallerNotificationsBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/RealInstallerNotificationsManager.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideDownloader.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchDownloader.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/network/DownloaderRepository.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/DownloadInfo.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealInstallManager.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/Task.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/workers/PackageDownloader.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/AppTest.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TasksTest.kt
install-manager/src/test/java/cm/aptoide/pt/install_manager/TestData.kt

- Refactor Task State to include task progress
- Changes the PackageDownloader interface and implementations so that it can emit more complex download info. It now returns not only the progress, but also the total number of downloaded bytes.
- Adds the new download speed parameter to download analytics events.
No
See by commit.
Flow on how to test this or QA Tickets related to this use-case: [AND-196](https://aptoide.atlassian.net/browse/AND-196)
Tickets related to this pull-request: [AND-196](https://aptoide.atlassian.net/browse/AND-196)
[AND-196]: …

[AND-196] Add download speed to download analytics events

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchDownloader.kt

- Fixes a bug where the progress is stuck and there is no error when the network fails, while using the Fetch package downloader.
- Fixes the returned exception types, so that the errors can be correctly propagated and shown at UI level.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-215](https://aptoide.atlassian.net/browse/AND-215)
Tickets related to this pull-request: [AND-215](https://aptoide.atlassian.net/browse/AND-215)
[AND-215]: https://aptoide.atlassian.net/browse/AND-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-215] Fix stuck download with Fetch on connection failed

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/DownloadException.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/fetch/FetchDownloader.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/network/DownloaderRepository.kt

- Adds the error url parameter for download fail analytics event.
- Adds a new DownloadException that is used to wrap exceptions coming from PackageDownloader implementations.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-182](https://aptoide.atlassian.net/browse/AND-182)
Tickets related to this pull-request: [AND-182](https://aptoide.atlassian.net/browse/AND-182)
[AND-182]: https://aptoide.atlassian.net/browse/AND-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-182]: …

[AND-182] Add error url for download fail analytics event

---

app-games/schemas/com.aptoide.android.aptoidegames.gamegenie.data.database.GameGenieDatabase/1.json
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieApiService.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieDatabase.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieHistoryDao.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/model/ChatInteractionEntity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/model/Converters.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/model/GameGenieHistoryEntity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/di/GameGenieModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/domain/GameGenieChat.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieUIState.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt

Implement chat history saving in Room. The idea of this is to present the past conversations with GameGenie, but for now we are only aiming to save the conversations, not to present them to the user.
Yes
Flow on how to test this or QA Tickets related to this use-case: [AND-186](https://aptoide.atlassian.net/browse/AND-186)
Tickets related to this pull-request: [AND-186](https://aptoide.atlassian.net/browse/AND-186)
**Questions:**
[AND-186]: https://aptoide.atlassian.net/browse/AND-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

[AND-186] Implement GameGenie chat history saving

---

app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/analytics/AnalyticsProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/analytics/PromoCodeAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/di/PromoCodesModule.kt

- Adds new analytics to the promo code bottom sheet. Specifically, an analytics event to know when the bottom sheet is shown and to know when the user clicks on the button to use the promo code.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-245](https://aptoide.atlassian.net/browse/AND-245)
Tickets related to this pull-request: [AND-245](https://aptoide.atlassian.net/browse/AND-245)
[AND-245]: https://aptoide.atlassian.net/browse/AND-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-245]: …

[AND-245] Add promo code bottom sheet analytics

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt

This PR aims to adds download_queue_entry and download_queue_exit events
No
Flow on how to test this or QA Tickets related to this use-case: [AND-280](https://aptoide.atlassian.net/browse/AND-280)
Tickets related to this pull-request: [AND-280](https://aptoide.atlassian.net/browse/AND-280)
**Questions:**
[AND-280]: https://aptoide.atlassian.net/browse/AND-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-280]: https://aptoide.atlassian.net/browse/AND-280?atlOrigin=eyJpIjoiNWRkNTlj …

[AND-280] Add download_queue_entry and download_queue_exit event

---

app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

This PR aims at implementing a filter where the "apps-group-hmd-controller" bundle is only shown for users that have an hmd phone and the fusion model.
PS: The values for the manufacturer and model are still pending confirmation with hmd.
No
Open the app in your phone and check that the bundles doesnt show. To check showing, either you fake the function on the code or we wait for an hmd device.
Tickets related to this pull-request: [AND-242](https://aptoide.atlassian.net/browse/AND-242)
**Questions:**
[AND-242]: …

[AND-242] Filter bundle for hmd devices that are not fusion

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/dto/AnalyticsData.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsData.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/AnalyticsInstallPackageInfoMapper.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt

Adds `action` parameter to the `download` and `install` Indicative events. 
Had to refactor a bit to save the action value in the install package info payload.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-278](https://aptoide.atlassian.net/browse/AND-278)
Tickets related to this pull-request: [AND-278](https://aptoide.atlassian.net/browse/AND-278)
[AND-278]: https://aptoide.atlassian.net/browse/AND-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-278]: https://aptoide.atlassian.net/browse/AND-278?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

[AND-278] Add `action` parameter to the `download` and `install` events

---

app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt

Fix the order of GameGenie suggestion ids. Since the layout is reversed, the suggestion ids became inverted.
No
Open the app and check the logs game genie_suggests_click position
Tickets related to this pull-request: [AND-228](https://aptoide.atlassian.net/browse/AND-228)
**Questions:**
[AND-228]: https://aptoide.atlassian.net/browse/AND-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-228] Reverse suggestion ids for GameGenie

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AutoScrollViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/PublisherTakeOverBundle.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeVideoStateProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/network/presentation/NetworkStateProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/Mappers.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/model/AppJSON.kt

- Adds video support for auto carousel app items.
- Adds all the necessary logic to fetch the feature flag regarding the editor's choice video A/B testing.
- Fixes an issue with offset item scaling in the auto carousel.
No
- **To test, simply install AG and check if the videos appear and work correctly in case the A/B testing variant is the second one. The flag can be checked through a proxy service, for example.**
- **Check if the video only runs on unmetered connections (as it is intended) and that it stops correctly and shows only the feature graphics on metered connections.**
Flow on how to test this or QA Tickets related to this use-case: …

[AND-230] Editor's Choice video A/B testing

---

aptoide-installer/src/main/AndroidManifest.xml
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/di/AptoideInstallerModule.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/UninstallEvents.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/UninstallResult.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt

- Changes uninstalls to use android's PackageInstaller, replacing the ACTION_DELETE system intent previously used for uninstalls.
- Makes the migrate action rely on the uninstall task state, in order to start the installation only when the uninstall task is completed.
No
- this can be tested through the migration test flow, as described in PR #2171 
Flow on how to test this or QA Tickets related to this use-case: [AND-288](https://aptoide.atlassian.net/browse/AND-288)
Tickets related to this pull-request: [AND-288](https://aptoide.atlassian.net/browse/AND-288)
[AND-288]: …

[AND-288] Change uninstalls to use android's PackageInstaller

---

app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Bundle.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/BundlesUseCase.kt
feature-home/src/main/java/cm/aptoide/pt/feature_home/domain/Widget.kt

This PR aims at implementing the initial mapping for promotional cards.
No
Use the rewrite and check it. Currently it is mapping to Unit on the UI, but soon those will be implemented with the respective viewmodels.
Tickets related to this pull-request: [AND-261](https://aptoide.atlassian.net/browse/AND-261)
**Questions:**
[AND-261]: https://aptoide.atlassian.net/browse/AND-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-261] Map Promotionals

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/task_info/AptoideTaskInfoProbe.kt

- Creates an analytics wrapper for the TaskInfoRepository.
- Changes the download queue entry analytics event to be sent whenever a task is added to the TaskInfoRepository, instead of sending it inside the install view states. This guarantees that the event is sent even if there is no user interaction, which is the case of auto updates.
No
- Test the auto update flow to guarantee that 
Flow on how to test this or QA Tickets related to this use-case: [AND-289](https://aptoide.atlassian.net/browse/AND-289)
Tickets related to this pull-request: [AND-289](https://aptoide.atlassian.net/browse/AND-289) …

[AND-289] Firebase download queue entry analytics on auto-update

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt

- Fixes a reported crash when getting the user installed packages, which throwed either a DeadObjectException or a BadParcelableException, by catching the exceptions and returning an empty list of installed packages instead.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-303](https://aptoide.atlassian.net/browse/AND-303)
Tickets related to this pull-request: [AND-303](https://aptoide.atlassian.net/browse/AND-303)
[AND-303]: https://aptoide.atlassian.net/browse/AND-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-303]: …

[AND-303] Add exception handling when getting installed packages

---

app-games/src/main/java/com/aptoide/android/aptoidegames/LaunchIntentExtensions.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt

This Pr aims to add support for notifications for external pages
No
Flow on how to test this or QA Tickets related to this use-case: [AND-304](https://aptoide.atlassian.net/browse/AND-304)
Tickets related to this pull-request: [AND-304](https://aptoide.atlassian.net/browse/AND-304)
**Questions:**
[AND-304]: https://aptoide.atlassian.net/browse/AND-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-304]: https://aptoide.atlassian.net/browse/AND-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

[AND-304] add support for survey via firebase notification

---

app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/di/RepositoryModule.kt
feature-apkfy/src/main/java/cm/aptoide/pt/feature_apkfy/domain/ApkfyModel.kt

- Extracts the method that sets the apkfy UTM properties to a class responsible for handling APKFY related analytics.
- Adds a new event to collect info about the apkfy calls.
- Adds retry logic to repeat the apkfy call in case it fails.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-295](https://aptoide.atlassian.net/browse/AND-295)
Tickets related to this pull-request: [AND-295](https://aptoide.atlassian.net/browse/AND-295)
[AND-295]: https://aptoide.atlassian.net/browse/AND-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-295] Add APKFY analytics and retry logic

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt

- Adds the apkfy guest uid as indicative user property, regardless if the guest uid is fetched from the apkfy or from the shared preferences.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-301](https://aptoide.atlassian.net/browse/AND-301)
Tickets related to this pull-request: [AND-301](https://aptoide.atlassian.net/browse/AND-301)
[AND-301]: https://aptoide.atlassian.net/browse/AND-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-301]: https://aptoide.atlassian.net/browse/AND-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

[AND-301] Add apkfy guest uid as indicative user property

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AutoScrollViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/videos/presentation/YoutubePlayer.kt

- Adds a method to change the speed of a carousel in the AutoScrollViewModel and makes the AutoScrollViewModel provider automatically react to changes in the speed received.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-230](https://aptoide.atlassian.net/browse/AND-230)
Tickets related to this pull-request: [AND-230](https://aptoide.atlassian.net/browse/AND-230)
[AND-230]: https://aptoide.atlassian.net/browse/AND-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-230]: https://aptoide.atlassian.net/browse/AND-230?atlOrigin=eyJpIjo …

[AND-230] Fix scroll speed and replay in editor choice carousel videos

---

feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt

- Makes auto updates call the respective map download events for each app being updated.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-305](https://aptoide.atlassian.net/browse/AND-305)
Tickets related to this pull-request: [AND-305](https://aptoide.atlassian.net/browse/AND-305)
[AND-305]: https://aptoide.atlassian.net/browse/AND-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-305]: https://aptoide.atlassian.net/browse/AND-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-305] Call mmp download events on auto updates

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/IndicativeAnalyticsSender.kt

- Adds the removal of Indicative properties with null values. Whenever setting Indicative properties, if any of the properties were to be replaced with a null value, it removes the property instead so that it shows correctly as not defined on Indicative.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-329](https://aptoide.atlassian.net/browse/AND-329)
Tickets related to this pull-request: [AND-329](https://aptoide.atlassian.net/browse/AND-329)
[AND-329]: https://aptoide.atlassian.net/browse/AND-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

[AND-329] Add removal of Indicative properties with null values

---

app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/GameGenieRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieHistoryDao.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/model/Converters.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/di/GameGenieModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/domain/ConversationInfo.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ChatbotViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ConversationHistoryUIState.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ConversationHistoryViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/ViewModelProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/ConversationHistoryBox.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/ConversationsDrawer.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/DrawerContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/res/drawable/more.xml

This PR aims to add the conversation history to GameGenie
Past conversation stored on the phone should be shown.
Implemented chat deletion.
No
See commit.
Open GameGenie and check if chat history is correct. If you already had chats with GameGenie from the previous version it should be shown. 
Test sliding and clicking the open drawer button. 
Test deleting chat.
Tickets related to this pull-request: [AND-188](https://aptoide.atlassian.net/browse/AND-188)
**Questions:**
[AND-188]: …

[AND-188] Add conversation history to GameGenie

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/AppComingSoonViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/domain/AppComingSoonManager.kt
feauture_app_coming_soon/src/main/java/cm/aptoide/pt/appcomingsoon/repository/AptoideAppComingSoonPromotionalRepository.kt

This PR aims at fixing error mapping in the AppComingSoon card. If there was an error during the mapping of the card, it would be out of the flow meaning it wouldn't be caught by the .catch{} block from kotlin flow.
No
See by commit
Put a rewrite for an AppComingSoon widget from getWidgets but don't add the rewrite for the card content, meaning we will have an empty card (current error we have in the api) and the mapping will emit an exception, which was not being caught correctly.
Tickets related to this pull-request: [AND-279](https://aptoide.atlassian.net/browse/AND-279)
**Questions:**
Does this add new dependencies which need …

[HOTFIX/AND-279] App coming soon error mapping fix

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyAnalytics.kt

- Adds direct but no utm value on apkfy utm Indicative properties, for then the package name from apkfy is equal to AG's package name.
- Adds UTM OEMID from apkfy as an Indicative user property.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-330](https://aptoide.atlassian.net/browse/AND-330)
Tickets related to this pull-request: [AND-330](https://aptoide.atlassian.net/browse/AND-330)
[AND-330]: https://aptoide.atlassian.net/browse/AND-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-330]: …

[AND-330] Expand apkfy tracking

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/GenericAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/AllCategoriesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/editorial/EditorialMoreScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/GamesScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRow.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/HomeTabRowStateProvider.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/AllCategoriesUiState.kt
feature_categories/src/main/java/cm/aptoide/pt/feature_categories/presentation/AllCategoriesViewModel.kt

- Adds horizontal scrollable tab row to AG's home screen.
- Refactors some screen for convenience, so that some of those screen views can be reused as views shown in Home Screen tabs.
- Adds fetching of firebase feature flags that control the visibility on the tab row.
- Adds fetching of firebase feature flags that control the content and order of the tabs in the tab row.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-299](https://aptoide.atlassian.net/browse/AND-299)
Tickets related to this pull-request: [AND-299](https://aptoide.atlassian.net/browse/AND-299)
[AND-299]: …

[AND-299] Add horizontal tabs on Home Screen

---

feature_editorial/src/main/java/cm/aptoide/pt/feature_editorial/data/AptoideEditorialRepository.kt

- Removes aptoide_uid usage from editorial endpoints.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-36](https://aptoide.atlassian.net/browse/AND-36)
Tickets related to this pull-request: [AND-36](https://aptoide.atlassian.net/browse/AND-36)
[AND-36]: https://aptoide.atlassian.net/browse/AND-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-36]: https://aptoide.atlassian.net/browse/AND-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-36] Remove aptoide_uid usage from editorial endpoints

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/dto/AnalyticsData.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/NewAppPromotionalView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewShort.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promotions/domain/CompatiblePromotionsUseCase.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadUiState.kt
download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/App.kt

- Adds the option to migrate alias package names in ahab promotion dialogs.
No
- Uninstall an alias package name of an app that has ahab/promotions through another store. The app must have a different package name.
- Launch AG and check if the dialog appears and the migration works as intended.
Flow on how to test this or QA Tickets related to this use-case: [AND-315](https://aptoide.atlassian.net/browse/AND-315)
Tickets related to this pull-request: [AND-315](https://aptoide.atlassian.net/browse/AND-315)
[AND-315]: https://aptoide.atlassian.net/browse/AND-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

[AND-315] Add app migrate for ahab v2

---

app-games/src/main/java/com/aptoide/android/aptoidegames/search/analytics/SearchAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt

- Fixes null safety in search analytics for the search meta instances used in the search view, in order to avoid possible NullPointerExceptions.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-341](https://aptoide.atlassian.net/browse/AND-341)
Tickets related to this pull-request: [AND-341](https://aptoide.atlassian.net/browse/AND-341)
[AND-341]: https://aptoide.atlassian.net/browse/AND-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-341]: https://aptoide.atlassian.net/browse/AND-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

[AND-341] Fix search meta null safety in search analytics

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/AppComingSoonPromotionalView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/repository/AppComingSoonPromotionalWorker.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationsPermissionRequester.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/permissions/notifications/NotificationsPermissionViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/toolbar/AppGamesToolBar.kt

- Improves the notifications permission requester by adding result handling and returning.
- Refactors the app coming soon card notify button to only change state depending on the notification permissions result.
- Removes the notifications permissions check from the app coming soon worker.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-335](https://aptoide.atlassian.net/browse/AND-335)
Tickets related to this pull-request: [AND-335](https://aptoide.atlassian.net/browse/AND-335)
[AND-335]: https://aptoide.atlassian.net/browse/AND-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

[AND-335] Add notification permissions result handling

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt

- Improves the url domain in download analytics, by using regex to also include domains that might not have the ".apk" part.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-283](https://aptoide.atlassian.net/browse/AND-283)
Tickets related to this pull-request: [AND-283](https://aptoide.atlassian.net/browse/AND-283)
[AND-283]: https://aptoide.atlassian.net/browse/AND-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-283]: https://aptoide.atlassian.net/browse/AND-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

[AND-283] Use regex to get url domain in download analytics

---

app-games/src/main/java/com/aptoide/android/aptoidegames/appview/CustomScrollableTabRow.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/TopChartsView.kt

- Fixes the top charts view list padding.
- Add bottom padding to home horizontal tab row to match design.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-299](https://aptoide.atlassian.net/browse/AND-299)
Tickets related to this pull-request: [AND-299](https://aptoide.atlassian.net/browse/AND-299)
[AND-299]: https://aptoide.atlassian.net/browse/AND-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-299]: https://aptoide.atlassian.net/browse/AND-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

[AND-299] Fix home tab row paddings

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/repository/UpdatesPreferencesRepository.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/repository/AppInfoRepositoryImpl.kt

This PR aims at making auto updates only for devices with API above or equal to 31.
No
Test the auto updates flow
Tickets related to this pull-request: [AND-346](https://aptoide.atlassian.net/browse/AND-346)
**Questions:**
[AND-346]: https://aptoide.atlassian.net/browse/AND-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-346] Auto Updates for devices above or equal to API 31

---

app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/di/ViewModelProvider.kt

This PR aims at refactoring the auto updates viewmodel provider to put the API version rule inside the provider instead of every usage
No
Test the flow of changing the autoupdates flag. Check also the empty state of the updates
Tickets related to this pull-request: [AND-346](https://aptoide.atlassian.net/browse/AND-346)
**Questions:**
[AND-346]: https://aptoide.atlassian.net/browse/AND-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-346] remove auto updates for sdk30

---

feature_updates/src/main/AndroidManifest.xml
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/data/AutoUpdateWorker.kt

This PR aims at implementing internet availability checks before performing the auto updates. 
We had the Worker restriction for the unmetered connection, but this was not enough as it only detects if it is on wifi, not if that wifi has a stable connection and we detected several internet errors on the the auto update flow.
No
Change the code for the initial delay to be in 5 minutes so you have time to do the next step.
Run the app, install through adb with app id an older version of for example mobile legends. 
Check if the autoupdate ran correctly.
Test all cases, where the ping fails, so it needs to do a retry and confirm that it only does one retry.
**What are …

[AND-347] Check internet connection before AutoUpdates

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/AdViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/MintegralAd.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/ViewModelProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/CarouselAppView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/obb/OBBInstallManager.kt
extension/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt

- Fixes crashes caused by clicks in mintegral ads after configuration changes.
- Also fixes an issue with the carousel auto scroll after its list was changed.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-291](https://aptoide.atlassian.net/browse/AND-291)
Tickets related to this pull-request: [AND-291](https://aptoide.atlassian.net/browse/AND-291)
[AND-291]: https://aptoide.atlassian.net/browse/AND-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-291]: https://aptoide.atlassian.net/browse/AND-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

[AND-291] Fix mintegral ad clicks on config changes

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallProbe.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideDownloader.kt

This PR aims at moving the unknown sources to the end of the download.
No
Run the app without the install from unknown sources permission and try canceling on the rationale dialog, canceling by pressing back on the settings and check that the events are correct ("abort" now on the install event and not on the download one)
Tickets related to this pull-request: [AND-387](https://aptoide.atlassian.net/browse/AND-387)
**Questions:**
[AND-387]: https://aptoide.atlassian.net/browse/AND-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

[AND-387] Align unknown sources to the end of vanilla

---

app-games/src/main/AndroidManifest.xml
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/InstallerSelector.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/di/InstallerModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/RealInstallerNotificationsManager.kt
app-games/src/main/res/xml/paths.xml
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/InstallerUtils.kt
aptoide-installer/src/main/java/cm/aptoide/pt/installer/LegacyInstaller.kt
extension/src/main/java/cm/aptoide/pt/extensions/PlatformUtils.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/dto/InstallPackageInfo.kt

- Extracts some package installer functions for convenience.
- Adds the apk file type to downloaded apk files, to avoid issues with package install intents.
- Adds functions to check for MIUI devices and MIUI optimizations state.
- Adds a legacy installer, that relies on ACTION_INSTALL_PACKAGE intents instead of android's PackageInstaller API.
- Adds a package installer selector to AG.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-378](https://aptoide.atlassian.net/browse/AND-378)
- To correctly test the legacy installer and the checks for MIUI devices, a MIUI device with an API <= 30 is required.
Tickets …

[AND-378] Use legacy installer for Xiaomi devices below or equal to API 30

---

feature_updates/src/main/java/cm/aptoide/pt/feature_updates/di/ViewModelProvider.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesPreferencesViewModel.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/repository/UpdatesPreferencesRepository.kt

- Prevents silent updates on MIUI devices that have MIUI optimizations turned on.
No
- To correctly test this, a MIUI device with API >= 31 (API levels from which silent updates are allowed) is required and the MIUI optimizations must be turned on.
Flow on how to test this or QA Tickets related to this use-case: [AND-381](https://aptoide.atlassian.net/browse/AND-381)
Tickets related to this pull-request: [AND-381](https://aptoide.atlassian.net/browse/AND-381)
[AND-381]: https://aptoide.atlassian.net/browse/AND-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-381] Disable silent updates on MIUI devices with optimizations on

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstaller.kt

- Sets the install location in the PackageInstaller session params to INSTALL_LOCATINO_AUTO, so that the device automatically handles and decides the package install location, instead of it always defaulting to the internal storage.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-356](https://aptoide.atlassian.net/browse/AND-356)
Tickets related to this pull-request: [AND-356](https://aptoide.atlassian.net/browse/AND-356)
[AND-356]: https://aptoide.atlassian.net/browse/AND-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-356]: …

[AND-356] Use auto install location in PackageInstaller sessions

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/InstallerQueueHandler.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/InstallAnalyticsImpl.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt

- Adds an installer queue handler that allows to cancel/clear the entire download queue after a single pending download is cancelled by the user.
- Adds an alternative of the download analytics event with status equal to 'cancel_queue', that is sent for each package download that is automatically canceled and removed from the queue.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-388](https://aptoide.atlassian.net/browse/AND-388)
Tickets related to this pull-request: [AND-388](https://aptoide.atlassian.net/browse/AND-388)
[AND-388]: …

[AND-388] Download Queue Handling on Cancel Action

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/analytics/NotificationsAnalytics.kt

This PR aims to modify the notification permission flow. On the first launch, the app requests the native notification permission. If the user declines, a custom dialog is presented on the second launch, and on the third launch, the Ahab is activated as before.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-380](https://aptoide.atlassian.net/browse/AND-380)
Tickets related to this pull-request: [AND-380](https://aptoide.atlassian.net/browse/AND-380)
**Questions:**
[AND-380]: …

[AND-380] Change the notification permission order

---

app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/data/database/GameGenieDatabase.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/di/GameGenieModule.kt

This PR aims at fixing the database migration error. This error was happening because the title was not defined as not null. Since we are clearing the database on this migration anyways, we just dropped the table and recreated it instead of deleting, as deleting would only remove the records and not fix the structure.
Yes 
Install version 1.8.0. Make some GG queries to have entries on the DB. Then install this version and check if GG works correctly.
Tickets related to this pull-request: [AND-399](https://aptoide.atlassian.net/browse/AND-399)
**Questions:** …

[AND-399] game genie DB migration

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/platform/UserActionHandler.kt

- Prevents emission of abandoned install session intents, by removing flow replay in the UserActionHandler, which is responsible for emitting the session intents to the UI.
No
- Check ticket for steps on how to reproduce and test this flow.
Flow on how to test this or QA Tickets related to this use-case: [AND-406](https://aptoide.atlassian.net/browse/AND-406)
Tickets related to this pull-request: [AND-406](https://aptoide.atlassian.net/browse/AND-406)
[AND-406]: https://aptoide.atlassian.net/browse/AND-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-406] Prevent emission of abandoned install session intents

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/analytics/DownloadProbe.kt

- Prevents unreadable error types in download analytics events, caused by obfuscation of HttpExceptions in package download fails.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-413](https://aptoide.atlassian.net/browse/AND-413)
Tickets related to this pull-request: [AND-413](https://aptoide.atlassian.net/browse/AND-413)
[AND-413]: https://aptoide.atlassian.net/browse/AND-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-413]: https://aptoide.atlassian.net/browse/AND-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

[AND-413] Prevent obfuscated error types in download analytics events

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCode.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeSheetUiState.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeSheetViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/ViewModelProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/analytics/PromoCodeAnalytics.kt
extension/src/main/java/cm/aptoide/pt/extensions/ContextExtensions.kt

- Creates a promo code bottom sheet UI state to centralize its dependencies.
- Refactors the promo code bottom sheet for convenience and better readability.
- Improves promo codes analytics events, by renaming the parameters and adding a status for the impression event.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-417](https://aptoide.atlassian.net/browse/AND-417)
Tickets related to this pull-request: [AND-417](https://aptoide.atlassian.net/browse/AND-417)
[AND-417]: https://aptoide.atlassian.net/browse/AND-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

[AND-417] Improve promo codes analytics events

---

app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/analytics/PromoCodeAnalytics.kt

- Adds the package name parameter to promo codes analytics events, in order to identify the app to which the promo code belongs.
No
- Test the normal promo code flow and check if the related analytics events send the package name parameter.
Flow on how to test this or QA Tickets related to this use-case: [AND-403](https://aptoide.atlassian.net/browse/AND-403)
Tickets related to this pull-request: [AND-403](https://aptoide.atlassian.net/browse/AND-403)
[AND-403]: https://aptoide.atlassian.net/browse/AND-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-403] Add package name parameter to promo codes analytics events

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCode.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/promo_codes/PromoCodeBottomSheetContent.kt

- Overrides the analytics context to be "promo_code" in download and install events that start from the promo codes bottom sheet.
- Makes the promotion value configurable in the promo codes deep link, in order to avoid showing a hardcoded value.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-411](https://aptoide.atlassian.net/browse/AND-411)
Tickets related to this pull-request: [AND-411](https://aptoide.atlassian.net/browse/AND-411)
[AND-411]: https://aptoide.atlassian.net/browse/AND-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[AND-411] Promo codes improvements

---

app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/InstallerNotificationsBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/notifications/RealInstallerNotificationsManager.kt

- Prevents installer notifications from loading the app icon multiple times.
- Sets installer notifications to belong to the same notification group, which prevents the notification expand glitch from happening.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-398](https://aptoide.atlassian.net/browse/AND-398)
Tickets related to this pull-request: [AND-398](https://aptoide.atlassian.net/browse/AND-398)
[AND-398]: https://aptoide.atlassian.net/browse/AND-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-398]: …

[AND-398] Fix installer notification glitch while downloading

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/Platform.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/Mintegral.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_ad/di/AdsModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BundlesView.kt

- Extracts a Mintegral interface to allow having different implementations or instances of anonymous objects.
- Creates a DI provider for Mintegral, that decides which implementation to use. The DI provider will return an empty Mintegral implementation that as no initialization, through an anonymous object.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-416](https://aptoide.atlassian.net/browse/AND-416)
Tickets related to this pull-request: [AND-416](https://aptoide.atlassian.net/browse/AND-416)
[AND-416]: https://aptoide.atlassian.net/browse/AND-416?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

[AND-416] Prevent Mintegral initialization in HMD builds

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt

- Adds a check for the API level in MainActivity, to prevent requesting the POST_NOTIFICATIONS request on devices with API level below 33, since this permission is only supported on API levels above 33.
- Adds exception catching on the permission launcher, to prevent possible unnecessary crashes on the first launch.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-422](https://aptoide.atlassian.net/browse/AND-422)
Tickets related to this pull-request: [AND-422](https://aptoide.atlassian.net/browse/AND-422)
[AND-422]: https://aptoide.atlassian.net/browse/AND-422?atlOrigin=eyJpIjoiNWRk …

[AND-422] Stop post notifications permission request on API levels below 33

---

app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/MMPLinkerCampaign.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt

- Saves the provided OEM id in mmp-linker campaigns, for direct usage in its download events.
- Makes the app auto updates send mmp-linker campaign events, if present.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-444](https://aptoide.atlassian.net/browse/AND-444)
Tickets related to this pull-request: [AND-444](https://aptoide.atlassian.net/browse/AND-444)
[AND-444]: https://aptoide.atlassian.net/browse/AND-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-444]: https://aptoide.atlassian.net/browse/AND-444?atlOrigin=eyJpIjoiNWRkN …

[AND-444] Send mmp linker events on auto updates

---

aptoide-installer/src/main/java/cm/aptoide/pt/installer/AptoideInstallPackageInfoMapper.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/dto/InstallationFile.kt

- Fixes obb file extension issues in installation files, by ensuring that the correct file extension types are appended if required.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-458](https://aptoide.atlassian.net/browse/AND-458)
Tickets related to this pull-request: [AND-458](https://aptoide.atlassian.net/browse/AND-458)
[AND-458]: https://aptoide.atlassian.net/browse/AND-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-458]: https://aptoide.atlassian.net/browse/AND-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

[AND-458] Fix obb file extension issues in installation files

---

feature-oos/src/main/java/cm/aptoide/pt/feature_oos/domain/InstalledAppsUseCase.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Extensions.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
install-manager/src/main/java/cm/aptoide/pt/install_manager/repository/AppInfoRepositoryImpl.kt

This PR aims at changing the filter of system apps to the updates level instead of the installed apps query.
No
See by commit.
Tickets related to this pull-request: [AND-441](https://aptoide.atlassian.net/browse/AND-441)
**Questions:**
[AND-441]: https://aptoide.atlassian.net/browse/AND-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-441] System apps not being detected installed

---

app-games/src/main/java/com/aptoide/android/aptoidegames/developer/AGDeveloperOptionsViewModel.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/developer/AGDeveloperPreferencesRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/developer/ViewModelProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/developer/di/RepositoryModule.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/firebase/FirebaseToken.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/settings/analytics/SettingsAnalytics.kt
extension/src/main/java/cm/aptoide/pt/extensions/ModifierExtensions.kt

- Adds extra options on the Settings screen.
- Refactors the paddings in the Settings screen to match the design.
No
Flow on how to test this or QA Tickets related to this use-case: [AND-457](https://aptoide.atlassian.net/browse/AND-457)
Tickets related to this pull-request: [AND-457](https://aptoide.atlassian.net/browse/AND-457)
[AND-457]: https://aptoide.atlassian.net/browse/AND-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-457]: https://aptoide.atlassian.net/browse/AND-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

[AND-457] Add extra options in settings screen

---

app-games/src/main/java/com/aptoide/android/aptoidegames/bottom_bar/AppGamesBottomBar.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GameGenieFeatureProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/GenieSearchView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/BottomBarMenus.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt

This PR creates support for GameGenie AB Test using booleans instead of the 3 variants. The search screen is fully substituted by the GameGenie chat screen
No
See commit
Check various times if the search opens the search view or GameGenie view
Tickets related to this pull-request: [AND-465](https://aptoide.atlassian.net/browse/AND-465)
**Questions:**
[AND-465]: https://aptoide.atlassian.net/browse/AND-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-465] Create support for new GameGenie search AB test using Booleans

---

app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/presentation/RTBSectionMoreView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/presentation/RTBSectionView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/AptoideRTBRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/GamesScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt

This PR aims at implementing some fixes on the rtb and bonus appc bundle views. 
Fixes the title, adds see more to the rtb bundle and fixes a bug where if the bundle failed to load, the header of the bundle would stay visible.
No
See by commit
Using rewrites check if both bundles are ok (both rtb and bonus).
Tickets related to this pull-request: [AND-501](https://aptoide.atlassian.net/browse/AND-501)
**Questions:**
[AND-501]: https://aptoide.atlassian.net/browse/AND-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

[AND-501] fix bonus banner

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/analytics/NotificationsAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/presentation/AnalyticsProvider.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/domain/UpdatesNotificationAnalyticsManager.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesNotificationBuilder.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/AutoUpdateGameInstallObserver.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/NotificationTypes.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/domain/Updates.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesNotificationProvider.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/presentation/UpdatesNotificationsVisibilityManager.kt
feature_updates/src/main/java/cm/aptoide/pt/feature_updates/repository/UpdatesPreferencesRepository.kt

This PR aims at implementing the experiment 7 regarding updates where some users will see only certain types of updates notifications.
No
Test all variants, left steps on slack.
Tickets related to this pull-request: [AND-505](https://aptoide.atlassian.net/browse/AND-505)
**Questions:**
[AND-505]: https://aptoide.atlassian.net/browse/AND-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-505] experiement 7: Updates notification

---

app-games/src/main/java/com/aptoide/android/aptoidegames/MainActivity.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_companion_apps_notification/CompanionAppsNotificationBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_editors_choice_recommendation/EditorsChoiceAppsRecommendationNotificationBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_promotional/AppComingSoonNotificationBuilder.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/analytics/NotificationsAnalytics.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/domain/UpdatesNotificationAnalyticsManager.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesNotificationBuilder.kt

This PR aims at applying some fixes to the experiment 7. 
Separating the notification event into two based on its action.
Renaming the user property due to the max characters.
No
See by commit
Run the app and attempt to simulate all possible combinations.
Tickets related to this pull-request: [AND-515](https://aptoide.atlassian.net/browse/AND-515)
**Questions:**
[AND-515]: https://aptoide.atlassian.net/browse/AND-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AND-515] Fix experiment7

---

app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/AppGridView.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusBundleMoreScreen.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/feature_rtb/repository/AptoideRTBRepository.kt
app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/AptoideMMPCampaign.kt
feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt

This PR aims at implementing campaign id usage in the RTB bundle. We also had to pass it to the the appview in order to convert the download urls. 
No
See by commit
Click and make the downloads in the rtb bundle both from home and see more view.
Note that the downloads done specifically in the see more view, using that button, instead of the the appview, won't have the campaign id because we are currently not receiving the download mmp urls in the rtb response. This was already aligned with the Apptech team and will be done in the future.
Tickets related to this pull-request: [AND-514](https://aptoide.atlassian.net/browse/AND-514) …

[AND-514] Use campaign id in rtb
